### ISSUE TITLE
Error in Powershell terminal

### ISSUE THREAD

**Issue by tomer-ds** [PowerShell/PSReadLine#1004]
```
PS> $response.RawContent -split "`n" | Select-String 'Location' | Where-Object {$_ -match "https:.*"}
```
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
```

### Environment
PSReadLine: 2.0.0-beta4
PowerShell: 2019.5.0
OS: Microsoft Windows 10.0.18362
Last 200 Keys
```
 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace [ ] LeftArrow 0 Enter
 UpArrow LeftArrow Backspace 1 ` 3 Backspace Backspace 3 Enter
 UpArrow Backspace Backspace Backspace Backspace Spacebar | Spacebar g m Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow . G e t t Tab ) Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace s p l i t Backspace Backspace Backspace Backspace Backspace Backspace Spacebar - s p l i t Spacebar " ` n " Spacebar | Spacebar S e l e c t - S t r i n g Spacebar ' ' LeftArrow L o c a t i o n Enter
 UpArrow Spacebar | Spacebar W h e r e - O b j e c t Spacebar { } LeftArrow $ _ . m a Backspace Backspace Backspace Spacebar m a t c h LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow - RightArrow RightArrow RightArrow RightArrow RightArrow Spacebar " " LeftArrow h t t p s : \ . Backspace Backspace . * Enter

```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 35.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by IanKemp** [comment]
Same issue with PS Core 7 preview 3 **running in [Windows Terminal](https://github.com/microsoft/terminal) 0.3.2171.0**:

### Environment
PSReadLine: 2.0.0-beta4
PowerShell: 7.0.0-preview.3
OS: Microsoft Windows 10.0.18362

<last 200 keys elided as contains sensitive info>

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 28.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

Amusingly, if I try to paste the snippet supplied in the "New issue" template, I get a similar explosion (in attached logfile). However, **that exception only occurs in `pwsh.exe` running under Windows Terminal** - if I post the "New issue" snippet directly into a standalone `pwsh.exe` console window and run it, no problem.

[psreadline-explosion.log](https://github.com/PowerShell/PSReadLine/files/3533495/psreadline-explosion.log)
