### ISSUE TITLE
Starting Spring Boot Application via intergrated terminal

### ISSUE THREAD

**Issue by KevinLeeMiguel** [PowerShell/PSReadLine#1008]
This happens when i edit my vsCode .settings file and change console to be intergratedTerminal 

Environment data
----------------

 provide the output of the following:
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 i t o r y \ o r g \ s p r i n g f r a m e w o r k \ s p r i n g - c o r e \ 4 . 3 . 1 3 . R E L E A S E \ s p r i n g - c o r e - 4 . 3 . 1 3 . R E L E A S E . j a r ; C : \ U s e r s \ K e v i n L e e M i g u e l \ . m 2 \ r e p o s i t o r y \ o r g \ j s o n \ j s o n \ 2 0 1 8 0 8 1 3 \ j s o n - 2 0 1 8 0 8 1 3 . j a r ' Space ' c o m . h e x a k o m b . b f w . B f w A p p l i c a t i o n ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

Steps to reproduce or exception report
--------------------------------------

**Comment by ShadowDrone** [comment]
same here with Maven only. Switched to "externalTerminal"
