### ISSUE TITLE
Error when using unicode characters (e.g. 👍)

### ISSUE THREAD

**Issue by autoantwort** [PowerShell/PSReadLine#1009]
I entered `echo "👍"` and get the error:
```powershell
Last 9 Keys:
 e c h o Space " � " Enter


Exception:
System.Text.EncoderFallbackException: Unable to translate Unicode character \uD83D at index 6 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(Char ch, Char*& chars)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass81_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```
I copied the emoji from [here](https://unicode-table.com/de/1F44D/) and pasted it in the powershell.

Environment data
----------------
PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.290 (WinBuild.160101.0800)
PS file version: 10.0.18362.290 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 3000

**Comment by autoantwort** [comment]
Sorry its a duplicate of  #949.
