### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below.

### ISSUE THREAD

**Issue by Willsms** [PowerShell/PSReadLine#1033]
-----------------------------------------------------------------------
Last 200 Keys:
 . 0 \ s i m p l e c l i e n t _ h t t p s e r v e r - 0 . 6 . 0 . j a r ; C : \ U s e r s \ d 2 6 \ . m 2 \ r e p o s i t o r y \ i o \ p r o m e t h e u s \ s i m p l e c l i e n t _ p u s h g a t e w a y \ 0 . 6 . 0 \ s i m p l e c l i e n t _ p u s h g a t e w a y - 0 . 6 . 0 . j a r ' Space ' c o m . c r a w l e r . m o n i t o r . c r a w l e r m o n i t o r . D e m o A p p l i c a t i o n ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -15.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by ryanrain2016** [comment]
same problem met,execept 'Actual value was -31'.
version as below:
版本: 1.38.1 (user setup)
提交: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
日期: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
