### ISSUE TITLE
Visual Studio Code crashing in the console endlessly

### ISSUE THREAD

**Issue by atee86** [PowerShell/PSReadLine#1055]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0-beta4
PowerShell: 2019.5.0
OS: Microsoft Windows 10.0.18362
Last 0 Keys
```

```

### Exception
```
System.Management.Automation.Runspaces.InvalidRunspaceStateException: Cannot invoke the pipeline because the runspace is not in the Opened state. Current state of the runspace is 'Closing'.
   at System.Management.Automation.Runspaces.RunspaceBase.AddToRunningPipelineList(PipelineBase pipeline)
   at System.Management.Automation.Runspaces.RunspaceBase.DoConcurrentCheckAndAddToRunningPipelines(PipelineBase pipeline, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(IEnumerable input, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

PS>

Steps to reproduce or exception report
--------------------------------------

Click on the Format document and the error is throwing itself endlessly into the console.

**Comment by msftrncs** [comment]
This is actually an error occurring in PowerShell from the VSCode-PowerShell extension.  PSReadLine picks it up, because it happens in background processing, and PSReadLine is the only (or first) exception handler that is found to handle the error.    Be sure to check the https://github.com/PowerShell/vscode-powershell repository for a possible solution.

While I do not think PSReadLine is responsible for the error, keep in mind that the VSCode-PowerShell extension is responsible for implementing PSReadLine in to their Integrated PowerShell Console, so it could be part of that implementation interacting with the background task the extension is performing (such as formatting requests).

**Comment by daxian-dbw** [comment]
> **Click on the Format document**

@atee86 Can you please elaborate the repro steps more? What does _Click on Format document_ mean here?
/cc @TylerLeonhardt @rjmholt

**Comment by rjmholt** [comment]
An update to the PowerShell extension was released this week and include some bug fixes as well as a more recent release of PSReadLine, so please try that out. If the issue continues, you should definitely open an issue at https://github.com/PowerShell/vscode-PowerShell where we can follow up for more information and solve the problem.

**Comment by atee86** [comment]
> > **Click on the Format document**
> 
> @atee86 Can you please elaborate the repro steps more? What does _Click on Format document_ means here?
> /cc @TylerLeonhardt @rjmholt

I'm not quite sure, it kinda happens randomly. When i right click in a powershell document and click on the Format document the issue happens. Sometimes. Not always.
Today i just tried to execute a script in the terminal inside vscode (. scriptpath) and the same issue happened again. It strikes quite randomly.

**Comment by daxian-dbw** [comment]
@atee86 Can you please upgrade to the latest PowerShell VSCode extension and see if the issue still happens with it?

**Comment by daxian-dbw** [comment]
@atee86 I will close this issue. Please try out the latest PowerShell VSCode extension.
If you still run into the same problem, please open an issue in the [PowerShellEditorServices repo](https://github.com/PowerShell/PowerShellEditorServices).
