### ISSUE TITLE
Error Pasting Long Text Functions in VisualStudio Code's PowerShell window.

### ISSUE THREAD

**Issue by LazaroOnline** [PowerShell/PSReadLine#1056]
```
SYSTEM:
PSReadline version: 2.0.0-beta2
os: 10.0.18362.356 (WinBuild.160101.0800)
PS file version: 10.0.18362.356 (WinBuild.160101.0800)
BufferWidth: 117
BufferHeight: 26
```
```
Visual Studio Code Version:
Version: 1.38.1 (system setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

Not sure if this is a bug in PowerShell or VisualStudio Code, but since both are from Microsoft in GitHub and the error log ask the user to submit it here then here it goes.
It only occurs within VisualStudio Code, I don't reproduce it in Windows Terminal App nor the classic PowerShell console.

How to reproduce:
Open Visual Studio Code, go to the PowerShell console (1: PowerShell)
with `Control + '`
Make sure it is selected `1: PowerShell` and not `2: Powershell Integrated Console`

Copy the following code and paste it `Control + v` in the console:
The code text must be a function declaration long enough to make it fail. In my machine it works if I remove a few lines from this example, but breaks when there is too many text, around 2000 chars but not always the same number.
To ensure you can reproduce it, add more lines to the function until copying and pasting breaks the console.
When reproduced, it shows the error once or multiple times, it seems to do a "retry" strategy until it finally works, with long functions (400 lines, 25000 characters) it can spend around a minute of successive errors spamming the output.
```
function test() {
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
write-host "test test test test test test test test test"
}
```

When pasted, instead of all at once instantly, it takes some time and you can see it is adding each character individually with a time delay between each new character 😢.
Then while it is still adding characters it will break with the following exception:

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 e s t Space t e s t Space t e s t Space t e s t Space t e s t " Enter
 w r i t e - h o s t Space " t e s t Space t e s t Space t e s t Space t e s t Space t e s t Space t e s t Space t e 
s t Space t e s t Space t e s t " Enter
 w r i t e - h o s t Space " t e s t Space t e s t Space t e s t Space t e s t Space t e s t Space t e s t Space t e 
s t Space t e s t Space t e s t " Enter
 w r i t e - h o s t Space " t e s t Space t e s t Space t e s t Space t e s t Space t e s t Space t e s t Space t e 
s t Space t e s t Space t e s t " Enter
 }

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -9.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by daxian-dbw** [comment]
@LazaroOnline This issue has been fixed in the latest prelease `2.0.0-beta5`. Please upgrade your PSReadLine module and give it a try.
