### ISSUE TITLE
Bug in Anaconda3 Powershell Prompt

### ISSUE THREAD

**Issue by rtreu1** [PowerShell/PSReadLine#1066]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
(base) PS C:\WINDOWS\system32>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 16 Keys:
 ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` Shift+Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
> Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

This URL indicates that you are using the `2.0.0-beta3` or prior versions of PSReadLine. The issue should be fixed in `2.0.0-beta5`. Please get the latest version from PowerShellGallery and try it out.
