### ISSUE TITLE
System.ArgumentOutOfRangeException after horizontal resize + UpArrow

### ISSUE THREAD

**Issue by vschweitzer** [PowerShell/PSReadLine#1117]
Environment data
----------------
PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 190
BufferHeight: 3000

Steps to reproduce or exception report
--------------------------------------
### Reproduce 
* Open Powershell by shift+right-clicking in Explorer and choosing "Open PowerShell window here" or open Powershell from the start menu
* Resize the window (first time the issue appeared was after setting it to full-screen). Issue seems to only appear after horizontal resize, vertical only has no effect.
* Hit the "UpArrow" key (so far, no other key seems to have any negative effect)

### Exception Report

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
UpArrow
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
at System.Console.SetCursorPosition(Int32 left, Int32 top)
at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Additional info
This issue seems to be related to resizing the window, but as #292 is closed at the moment of writing, and as the exception reports don't match, I thought this should get its own issue.

**Comment by vschweitzer** [comment]
PSReadLine 2.0.0-beta5 does indeed seem to fix it, as stated in [msftrncs's answer](https://github.com/PowerShell/PSReadLine/issues/1112#issuecomment-544745396).
