### ISSUE TITLE
ArgumentOutOfRangeException when pasting multiple lines at the bottom of Windows Terminal (0.6.2951.0)

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PSReadLine#1129]
I can't find a duplicate for this exact one, but that might be poor searching on my part 

### Environment
PSReadLine: 2.0.0-beta5
PowerShell: 7.0.0-preview.5
OS: Microsoft Windows 10.0.18362
Last 200 Keys - cut down because the there were many [enters] to take the input to the last row of the screen. 
```
 Enter    
 Enter
 Escape F i l t e r Spacebar Spacebar p i p e t e s t Spacebar { Enter
 Ctrl+Enter Enter
 Ctrl+Enter " C a l l e d " Enter
 Ctrl+Enter $ i n p u t Enter
 Ctrl+Enter } Enter
 F i l t e r Spacebar Spacebar p i p e t e s t Spacebar { Enter
 Ctrl+Enter Enter
 Ctrl+Enter " C a l l e d " Enter
 Ctrl+Enter $ i n p u t Enter
 Ctrl+Enter }
```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 59.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.MoveCursor(Int32 newCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.MoveToLine(Int32 lineOffset)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InsertLineAbove(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

Notice also that texted pasted from the Windows PowerShell ISE puts ctrl-enter in where enter might be expected.

**Comment by msftrncs** [comment]
#1081.  😄   If you past with CTRL-V, all is fine.   Its not PS ISE that's causing the CTRL-ENTER, its Windows Terminal failing to remove the LF.

**Comment by jhoneill** [comment]
Thought it might be a search failure. -)   Will close this one

And I think Windows terminal has taken to swapping  cr/lf to ctrl-enter as a way not to get duplicate enters in the current version.
Interestingly I had ctrl-c and ctrl-v set as a explicit options in my terminal settings. Ctrl-V only works properly now I have taken those out.
