### ISSUE TITLE
Powershell "Something went wrong" 

### ISSUE THREAD

**Issue by uditrana** [PowerShell/PSReadLine#1130]
Environment data
----------------
PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 124
BufferHeight: 31

Steps to reproduce or exception report
--------------------------------------
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 158 Keys:
 & Space C : / U s e r s / m e o w / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o n 3 7 / p y t h o n . e x e Space " c : / U s e r s / m e o w / O n e D r i v e / C o l l e g e / C a r n e g i e _ M e l l o n / 1 5 - 1 1 2 Space T e a c h i n g Space A s s i s t a n t / F a l l Space 2 0 1 9 / F O O . p y " Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size 
in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by msftrncs** [comment]
@uditrana, there is a new version of PSReadline (2.0.0-beta5) available from PowerShellGallery, and it should resolve this and many other issues.   Give it a try.
