### ISSUE TITLE
System.ArgumentOutOfRangeException: The value must be greater than or...

### ISSUE THREAD

**Issue by JonasGao** [PowerShell/PSReadLine#1131]
Environment data
----------------

```none
PS version: 6.2.2
PSReadline version: 2.0.0-beta3
os: 10.0.18362.418 (WinBuild.160101.0800)
PS file version: 6.2.2.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 166
BufferHeight: 49
```

I got the following error message
=======================================

![批注 2019-10-26 224745](https://user-images.githubusercontent.com/4549584/67621492-a9b12680-f842-11e9-9df9-7ba66f7fb71f.png)

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
```
 RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow LeftArrow - Enter
 c d Space . \ s p Tab b o Tab Space Backspace l Backspace ; Space g i t Tab Space r e m o Tab Space s h o Tab Space o r i Tab g i n Space Backspace l Backspace ; Space c d Space . . \ s p r i n g Tab - f r a Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace s p r i n Tab f r a Tab LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow . RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow ; Space g i t Space r e m o t e Space s h o w Space o r i g i n ; Space c d Space . . Enter
 l s Space . . Enter
 l s Space / . Backspace Backspace . . \ g i Tab . c o m Tab Enter
 m v Space s p Tab Tab
```

Exception:
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 49.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------

**Comment by JonasGao** [comment]
duplicated #1115 #1112

**Comment by msftrncs** [comment]
@JonasGao, your exception is different, its being caused in DrawMenu, but I am sure it is fixed in 2.0.0-beta5.

**Comment by JonasGao** [comment]
@msftrncs Thank you for your reply, I will update it.

**Comment by Mewida0101** [comment]
I have the same problem but I can't fix it
could you explain for me how to fix it? please
