### ISSUE TITLE
Error Report - Unknown error "16389"

### ISSUE THREAD

**Issue by CXwudi** [PowerShell/PSReadLine#1132]
Environment data
----------------
PS version: 5.1.17763.771
PSReadline version: 2.0.0-beta2
os: 10.0.17763.1 (WinBuild.160101.0800)
PS file version: 10.0.17763.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 3000

Steps to reproduce or exception report
--------------------------------------
`PS D:\11134\Videos\gpac> bash

MINGW64 /d/11134/Videos/gpac (master)
$

MINGW64 /d/11134/Videos/gpac (master)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

MINGW64 /d/11134/Videos/gpac (master)
$ ./configure --static-mp4box --use-zlib=no

MINGW64 /d/11134/Videos/gpac (master)
$ make -j4

MINGW64 /d/11134/Videos/gpac (master)
$ exit
exit
PS D:\11134\Videos\gpac> cd ..
PS D:\11134\Videos> .\MP4Box.exe -add 【蒼姫ラピス】ワンダードライブ _ アリスと蔵六OP【歌わせてみた】.aac 【蒼姫ラピス】ワンダードライブ _ アリスと蔵六OP【歌わせてみた】.m4a
Error - 2 input names specified, please check usage
PS D:\11134\Videos>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 43 Keys:
 b a s h Enter
 m p 4 Tab Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace c d Space . . Enter
 m p 4 Tab Space Ctrl+v Space Ctrl+v Space Ctrl+v Backspace Backspace Backspace m 4 a Enter
 UpArrow

Exception:
System.IO.IOException: Unknown error "16389".
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__ConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at System.IO.TextWriter.SyncTextWriter.Write(String value)
   at System.Console.Write(String value)
   at Microsoft.PowerShell.Internal.VirtualTerminal.Write(String value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

PS D:\11134\Videos>
PS D:\11134\Videos>`

**Comment by msftrncs** [comment]
I don't think I have seen this error before.   Can you reproduce this easily?   Can you try PSReadLine 2.0.0-beta5?  I am guessing it might have something to do with encoding of the console stream.

**Comment by CXwudi** [comment]
I can not install  PSReadLine 2.0.0-beta5 as it mentioned the invalid parameter on "-AllowPrerelease".
The issue is easily reproducible, here is the video of how I reproduced it 
https://drive.google.com/open?id=1RsMaE8cOU2v4W8bAEQvAzXkB46FimKS1

**Comment by msftrncs** [comment]
You will need to also install an update to the PowerShellGet module.   Windows PowerShell is still deployed with a pretty old version, and then that might require an update of the PackageManagement module as well.  This usually requires a `install-module modulename -force` in administrator mode.

**Comment by CXwudi** [comment]
The issue is verified fixed in PSReadLine 2.0.0-beta5
