### ISSUE TITLE
Ctrl+l exception

### ISSUE THREAD

**Issue by vingo555** [PowerShell/PSReadLine#1135]
The issue is very easy to reproduce.
1. Open powershell terminal.
2. Press "Ctrl" + mouse wheel to adjust the font size
3. Using "Ctrl+l" to clear the screen.

The exception stack is :

`Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 19 Keys:
 Enter
 Ctrl+l ` Ctrl+l Ctrl+l l s Enter
 Ctrl+l Ctrl+l Ctrl+l c l e a r Enter
 Ctrl+l Ctrl+l

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ClearScreen(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------`

**Comment by msftrncs** [comment]
Have you tried PSReadline 2.0.0-beta5?  It more than likely remedies this.  If it doesn't, be sure to include your environment data

**Comment by daxian-dbw** [comment]
I cannot reproduce this using pwsh 7.0.0-preview.5, which has `2.0.0-beta5` PSReadLine.
