### ISSUE TITLE
something went wrong when i press 6 keys in the same time 

### ISSUE THREAD

**Issue by thearrival** [PowerShell/PSReadLine#1138]
hello my name is Ismail i have found this issues in power shell when 
i press 6 digits one by one its appear for me this message blow .
_____________________________________________________
Last 6 Keys:
 d f Backspace Backspace Backspace Enter

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

_________________________________________________________________________

**Comment by daxian-dbw** [comment]
Hi @thearrival, you didn't provide the environment data. The issue template has the script to help get you the environment data, please run it and paste the output in your post.
Also, if the environment data states that you are using `PSReadline` less than `2.0.0-beta5`, you may want to upgrade and give it a try.

**Comment by daxian-dbw** [comment]
Close the issue due to the lack of information.
