### ISSUE TITLE
Script for PowerShell Gallery

### ISSUE THREAD

**Issue by sah6149** [PowerShell/PSReadLine#1153]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by sah6149** [comment]
Last 200 Keys:
```
 r y Space { Enter
 Space Space Space Space Space Space U n i n s t a l l - M o d u l e Space - N a m e Space $ m o d u l e . n a m e Space - R e q u i r e d V e r s i o n Space $ m o d u l e . v e r s i o n Space - F o r c e : $ F o r c e Space - E r r o r A c t i o n Space S t o p Space - W h a t I f : $ W h a t I f Enter
 Space Space Space Space } Space c a t c h Space { Enter
 Space Space Space Space Space Space W r i t e - H o s t Space ( " ` t " Space + Space $ _ . E x c e p t i o n . M e s s a g e ) Enter
 Space Space Space Space } Enter
 Space Space } Enter
 }
```

Exception:
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -16.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)

**Comment by msftrncs** [comment]
@sah6149, if you could provide the environment data, using the script in the New Issue template, it would indicate the version of PSReadLine and the console information.   

This looks a lot like a known issue and should be fixed in beta5.

**Comment by daxian-dbw** [comment]
Please try out `2.0.0-beta5` of PSReadLine from PowerShellGallery.
