### ISSUE TITLE
issue in powershell 5.1, it maybe due to PSReadline

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#1166]
Environment data
----------------

```
PS version: 5.1.18362.145
Split-Path : Cannot bind argument to parameter 'Path' because it is null.
At line:16 char:44
+ ... et-Content "$(Split-Path -Parent (Get-Module PSReadLine).Path)\PSRead ...
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.Sp
   litPathCommand

Get-Content : Cannot find path 'C:\PSReadLine.psd1' because it does not exist.
At line:16 char:10
+     $m = Get-Content "$(Split-Path -Parent (Get-Module PSReadLine).Pa ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\PSReadLine.psd1:String) [Get-Content], ItemNotFoundExceptio
   n
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

PSReadline version:
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 111
BufferHeight: 3000
```

Steps to reproduce or exception report
--------------------------------------

reproducibility-> 5/5

---

steps- 

go to a long path, like `C:\Users\rosco\Downloads\vscode insiders\1.40.0-insider\3f6ed25939b8ef157a7a41e0dc43b517898d4005`<br>
snap powershell window to right half. <br>
paste text. <br>
output by powershell-

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Enter
 Enter
 $ c a l c _ h a s h Space = Space ( G e t - F i l e H a s h Space . \ V S C o d e - w i n 3 2 - i a 3 2 - 1 . 4 0 . 0 - i n s i d e r . z i p ) . H a s h . T o L o w e r ( ) Enter
 $ h a s h Space = Space g c Space . \ V S C o d e - w i n 3 2 - i a 3 2 - 1 . 4 0 . 0 - i n s i d e r . S H A 2 5 6 . t x t Enter
 Enter
 e c h o Space $ h a s h Enter
 # s e l e c t Space a n d Space p a s t e Space t h e Space o u t p u t Space o f Space h a s h Enter
 $ h a s h Space = Space " Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

Powershell info-
```$PSVersionTable.PSVersion
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  145
```
Os info-
On `Microsoft Windows [Version 10.0.18362.418]`

----

regards ratatoeey

**Comment by ghost** [comment]
never mind, its not happening anymore.

----

regards ratatoeey

**Comment by ghost** [comment]
this was the text that was pasted.

```
#in powershell 5.1

$calc_hash = (Get-FileHash .\VSCode-win32-ia32-1.40.0-insider.zip).Hash.ToLower()
$hash = gc .\VSCode-win32-ia32-1.40.0-insider.SHA256.txt

echo $hash
#select and paste the output of hash
$hash = "
```

---

I suspect it was present only with `Microsoft Windows [Version 10.0.18362.418]`
and not the latest version of 1903. 
----

regards ratatoeey
