### ISSUE TITLE
VSC running more than 2 instances getting error

### ISSUE THREAD

**Issue by ravishankar54** [PowerShell/PSReadLine#1169]
Last 200 Keys:
 a \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 1 9 . 1 0 . 4 4 1 0 4 \ p y t h o n F i l e s \ p t v s d _ l a u n c h e r . p y ' Space ' - - d e f a u l t ' Space ' - - n o d e b u g ' Space ' - - c l i e n t ' Space ' - - h o s t ' Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 5 2 3 7 0 ' Space ' c : \ U s e r s \ r a b o y i n a \ D o w n l o a d s \ P r o p 5 T e s t . p y ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size 
in that dimension.
Parameter name: top
Actual value was -22.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by msftrncs** [comment]
@ravishankar54, can you confirm your environment using the script in the issue template, and what was the last thing you did just before the exception?

This exception report looks like one that should already be fixed in PSReadLine 2.0.0-beta5.

**Comment by ravishankar54** [comment]
Hi Carl,

I am running 3 python scripts with three instances of VSC. And i got this
exception.

Please let me know anything else you require from me.

Thanks and Regards,
Ravi.

**Comment by daxian-dbw** [comment]
@ravishankar54 Please try out the `2.0.0-beta5` version of `PSReadLine` from PowerShellGallery. This issue should be fixed in that version.
Also, please include the environment data in your future issue reports. The issue template has the script to collect the environment data for you.
