### ISSUE TITLE
Ctrl+v throws a System.ArgumentOutOfRangeException exception

### ISSUE THREAD

**Issue by RadicalTeapot** [PowerShell/PSReadLine#1193]
Encountered an exception pasting the line following line in a new instance of the Windows Terminal:
```
$newCommand = "SetDisplaySliceIndicator"; $base = "Template"; Get-ChildItem "*$base*" | %{New-Item -Path ($_.name.Replace($base, $newCommand)) -Force | Set-Content -Value (Get-Content $_.name).Replace($base, $newCommand) -Path {$_.name}}

```
Environment data
----------------
PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 39

Steps to reproduce or exception report
--------------------------------------
Last 1 Keys:
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by msftrncs** [comment]
@RadicalTeapot, PSReadLine 2.0.0-beta6 from PowerShellGallery should help.

**Comment by RadicalTeapot** [comment]
I've updated to the beta6 and I can't reproduce the issue anymore. I'll close this issue for now.
