### ISSUE TITLE
[Vi Mode] Shift+W at start of prompt in "command mode" always causes an exception

### ISSUE THREAD

**Issue by rjmholt** [PowerShell/PSReadLine#1195]
### Environment
PSReadLine: 2.0.0-beta5
PowerShell: 7.0.0-preview.5
OS: Microsoft Windows 10.0.19023
Last 87 Keys
```
 LeftWindows LeftWindows LeftWindows g c i Spacebar - p a t h Spacebar : Shift+Backspace C : \ p r o Tab Enter RightArrow Spacebar - r e Tab Spacebar | Shift+Spacebar G e t - F i l Tab Enter Enter LeftWindows G e t - E r r o r Enter UpArrow UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter UpArrow UpArrow Enter Escape W
```

### Exception
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at Microsoft.PowerShell.PSConsoleReadLine.ConvertOffsetToPoint(Int32 offset)
   at Microsoft.PowerShell.PSConsoleReadLine.MoveCursor(Int32 newCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.ViNextGlob(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken)

```

### Steps to reproduce:

```powershell
Set-PSReadLineOption -EditMode Vi
```

<kbd>Enter</kbd>

<kbd>Esc</kbd>

<kbd>Shift</kbd>+<kbd>W</kbd>

**Comment by msftrncs** [comment]
https://github.com/PowerShell/PSReadLine/blob/e7f28ff8acaa5f188909b8ce39ccb2a272cc0068/PSReadLine/Movement.vi.cs#L97

`i` = 0, `_buffer`'s `Length` = 0, `Math.Min()` of 0 and -1 results in -1.  Cursor cannot be set to -1.
