### ISSUE TITLE
ViRegister crashing Powershell on `dd` command

### ISSUE THREAD

**Issue by msftrncs** [PowerShell/PSReadLine#1197]
Environment data
----------------

PowerShell 7 preview 5 on Windows 10 (Insiders 19025) with PSReadLine 2.0.0-beta6 (might be debug build)

Steps to reproduce or exception report
--------------------------------------

Enable VI mode `Set-PSReadLineOption -EditMode vi`

Press <kbd>ESC</kbd>, then <kbd>d</kbd><kbd>d</kbd>, and each time I get a major crash that closes the PowerShell window (or process).  This is a brand new console with a blank command line, minus the previous command to switch to VI mode.

### Exception report:
```
Process terminated. Assertion failed.
   at Microsoft.PowerShell.PSConsoleReadLine.ViRegister.Record(StringBuilder buffer, Int32 offset, Int32 count)
   at Microsoft.PowerShell.PSConsoleReadLine.ViRegister.Record(StringBuilder buffer)
   at Microsoft.PowerShell.PSConsoleReadLine.DeleteLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ViChord(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at CallSite.Target(Closure , CallSite , Type , Object , Object )
   at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.DlrScriptCommandProcessor.Complete()
   at System.Management.Automation.CommandProcessorBase.DoComplete()
   at System.Management.Automation.Internal.PipelineProcessor.DoCompleteCore(CommandProcessorBase commandRequestingUpstreamCommandsToStop)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProcImpersonate()
   at System.Management.Automation.Runspaces.PipelineThread.WorkerProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

cc @springcomp

**Comment by springcomp** [comment]
I can definitely reproduce this bug, sorry about that.
Let me work on a fix.

**Comment by springcomp** [comment]
Fortunately, this was due to an incorrect condition in an `Assert` and does not have any effect on Release builds.

**Comment by msftrncs** [comment]
No problems …  I only found it because I really don't know what I am doing in VI mode, so I was just pressing keys until things crashed.  😄
