### ISSUE TITLE
System.ArgumentOutOfRangeException when using Powershell in Windows Terminal

### ISSUE THREAD

**Issue by acnvrk** [PowerShell/PSReadLine#1201]
Environment data
----------------
PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost (Windows Terminal) (Version: 0.6.2951.0)
BufferWidth: 120
BufferHeight: 28

Steps to reproduce or exception report
--------------------------------------
1. Was pressing the up-arrow keys to cycle through the recent commands, and the following crash dump appeared on the terminal.

Crash log on the terminal:
-------------------------
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 200 Keys:
 e s Backspace r s i o n 7 0 Enter
 g i t Space b r a n c h Space - D Space j o b c a r d p i e c e s t a b l e Enter
 UpArrow Shift+Ctrl+LeftArrow Shift+Ctrl+LeftArrow Backspace Backspace Backspace Enter
 UpArrow UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Lef Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 g i t Space m e r g e Space R e a Backspace f a c Tab Enter
 g i t Space l o g Enter
 g i t Space s v n Space d c o m m i t Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow

Exception:
-----------
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -92.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by msftrncs** [comment]
@acnvrk, give PSReadLine 2.0.0-beta6 a try from PowerShellGallery, and all should be well.
