### ISSUE TITLE
Unknown issue? PS requested I report

### ISSUE THREAD

**Issue by XavierEmeralds** [PowerShell/PSReadLine#1211]
Environment data
----------------
PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 3000

Steps to reproduce or exception report
--------------------------------------
-----------------------------------------------------------------------
Last 120 Keys:
 a b d Space s h e l l Enter
 a d b Space s h e l l Enter
 . Space \ a d b Enter
 . \ \ a d b Enter
 . \ \ a d b Space s h e ; Backspace l l Enter
 . \ \ a b d Space d e v i c e s Enter
 UpArrow UpArrow Enter
 r u n Enter
 g t Backspace r t Backspace Backspace e t - h e l p Enter
 . \ \ Space a b d Space s Backspace Backspace Backspace Backspace Backspace Backspace a b d Space s h e l l Enter
 a b d Enter
 a d b Backspace Backspace

Exception:
System.IO.IOException: Insufficient quota to complete the requested service.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.set_CursorVisible(Boolean value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by msftrncs** [comment]
@XavierEmeralds, you might find this fixed in PSReadLine 2.0.0-beta6, available from PowerShellGallery.  Remotely, this might be an error in the .Net system, as this is a pretty unusual error.  Please report if it still happens with beta6.
