### ISSUE TITLE
Problem initializing server and client in python vs code

### ISSUE THREAD

**Issue by nfragav** [PowerShell/PSReadLine#1224]
Last 168 Keys:
 C : / U s e r s / n i c o l / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o n 3 7 / p y t h o n . e x e Space " c : \ U s e r s \ n i c o l \ r e p o \ P r o g r a m a c i o n Space A v a n z a d a \ n f r a g a v - i i c 2 2 3 3 - 2 0 1 9 - 2 \ T a r e a s \ T 0 3 \ s e r v e r \ s e r v e r _ n e t w o r k . p y " Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by msftrncs** [comment]
@nfragav, you didn't report your environment information, but this is probably under an older version.  You should give PSReadLine 2.0.0-beta6 a try from PowerShellGallery.
