### ISSUE TITLE
Error number 200

### ISSUE THREAD

**Issue by Zhanra** [PowerShell/PSReadLine#1237]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

PS version: 7.0.0-preview.1
PSReadline version: 2.0.0-beta4
os: 10.0.18362.356 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 59

This is the error report:
--------------------------------------

[192.168.3.144]: PS C:\>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0-beta4
PowerShell: 7.0.0-preview.1
OS: Microsoft Windows 10.0.18363
Last 200 Keys
```
 Enter
 UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace UpArrow DownArrow UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Home Shift+Ctrl+RightArrow Shift+Ctrl+RightArrow Shift+Ctrl+LeftArrow Delete Enter
 UpArrow UpArrow Spacebar - f Tab Backspace r Tab e Tab Backspace Backspace Backspace Backspace UpArrow UpArrow DownArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow Spacebar | Spacebar g e t - p r i n t j Tab Spacebar | Spacebar r e m o v e - p r i n Tab Tab Tab Tab Enter     UpArrow UpArrow UpArrow Enter
 g e t - p r i n t e r Tab Spacebar - p r i n Tab t Escape UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 r e s t a r t - s e r v Tab Spacebar s p o Tab Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 Enter

```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 58.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

--------------------------------------

**Comment by daxian-dbw** [comment]
This issue has been fixed by #1182, and the fix is included in 2.0.0-beta6. Please try out the 2.0.0-beta6 from PowerShell Gallery.
