### ISSUE TITLE
Running Python program in VSCode with Cyrillic keyboard fails

### ISSUE THREAD

**Issue by amitrovic** [PowerShell/PSReadLine#1268]
Environment data
I've got this message:
----------------
Last 1 Keys:
 &

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.     
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)   
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

Steps to reproduce or exception report
--------------------------------------
1. Run Python file in terminal (VSCode with Python extension)
2. Exception is raised
Note: My keyboard was preset to Cyrillic, when I switched it to the US English it worked without any problem.

**Comment by msftrncs** [comment]
@amitrovic, this looks like an issue that was fixed a while ago, but you didn't mention your environment data.  Give PSReadLine 2.0.0-rc1 a try from PowerShellGallery.  Report back if you still have issues with the Cyrillic keyboard setup.
