### ISSUE TITLE
Windows Shell Java Debug Buffer Problem

### ISSUE THREAD

**Issue by Longengie** [PowerShell/PSReadLine#1270]
When I run the Java Program on Visual Code, there are some change that I meet the error code bellow in PowerShell. After that error code, the program still run normally and work correctly. The code was simulate Stack Data Structure.
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS E:\JAVA\JavaApplication4> & 'C:\Users\User\.vscode\extensions\vscjava.vscode-java-debug-0.24.0\scripts\launcher.bat' 'C:\Program Files\Java\jdk-13.0.1\bin\java' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:60976' '--enable-preview' '-Dfile.encoding=UTF-8' '-cp' 'C:\Users\User\AppData\Roaming\Code\User\workspaceStorage\e60d432cbb3f4f49e1697cb026cc0db3\redhat.java\jdt_ws\JavaApplication4_afd0aa99\bin' 'javaapplication4.JavaAppli
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' 
C : \ U s e r s \ U s e r \ A p p D a t a \ R o a m i n g \ C o d e \ U s e r \ w o r k s p a c e S t o r a g 
e \ e 6 0 d 4 3 2 c b b 3 f 4 f 4 9 e 1 6 9 7 c b 0 2 6 c c 0 d b 3 \ r e d h a t . j a v a \ j d t _ w s \ J 
a v a A p p l i c a t i o n 4 _ a f d 0 a a 9 9 \ b i n ' Space ' j a v a a p p l i c a t i o n 4 . J a v a A 
p p l i c a t i o n 4 ' Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)   
------------------
```
Sorry, bellow is the Output of my code and I can't show for some reason.

**Comment by msftrncs** [comment]
@Longengie, you're using an older version of PSReadLine.  Give 2.0.0-rc1 a try from PowerShellGallery.  This issue should be resolved now.
