### ISSUE TITLE
System.ArgumentOutOfRangeException inside VS Code

### ISSUE THREAD

**Issue by vincentmathis** [PowerShell/PSReadLine#1273]
I get this error when using Powershell inside VS Code.
I could not reproduce it with a normal Powershell Window.

```
> & {
>>     $hostName = $Host.Name
>>     if ($hostName -eq "ConsoleHost" -and (Get-Command Get-CimInstance -ErrorAction SilentlyContinue)) {
>>         $id = $PID
>>         $inWindowsTerminal = $false
>>         while ($true) {
>>             $p = Get-CimInstance -ClassName Win32_Process -Filter "ProcessId Like $id"
>>             if (!$p -or !$p.Name) { break }
>>             if ($p.Name -eq "WindowsTerminal.exe") { $inWindowsTerminal = $true; break }
>>             $id = $p.ParentProcessId
>>         }
>>         if ($inWindowsTerminal) { $hostName += " (Windows Terminal)" }
>>     }
>>
>>     "`nPS version: $($PSVersionTable.PSVersion)"
>>     $v = (Get-Module PSReadline).Version
>>     $m = Get-Content "$(Split-Path -Parent (Get-Module PSReadLine).Path)\PSReadLine.psd1" | Select-String "Prerelease = '(.*)'"
>>     if ($m) {
>>         $v = "$v-" + $m.Matches[0].Groups[1].Value
>>     }
>>     "PSReadline version: $v"
>>     if ($IsLinux -or $IsMacOS) {
>>         "os: $(uname -a)"
>>     } else {
>>         "os: $((dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion)"
>>     }
>>     "PS file version: $($name = if ($PSVersionTable.PSEdition -eq "Core") { "pwsh.dll" } else { "powershell.exe" }; (dir $pshome\$name).VersionInfo.FileVersion)"
>>     "HostName: $hostName"
>>     "BufferWidth: $([console]::BufferWidth)"
>>     "BufferHeight: $([console]::BufferHeight)`n"
>> }--
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Space e l s e Space Ctrl+Alt+{ Space " p o w e r s h e l l . e x e " Space Ctrl+Alt+} ; Space ( d i r Space $ p s h o m e Ctrl+Alt+\ $ n a m e ) . V e r s i o n I n f o . F i l e V e r s i o n ) " Enter
 Space Space Space Space " H o s t N a m e : Space $ h o s t N a m e " Enter
 Space Space Space Space " B u f f e r W i d t h : Space $ ( Ctrl+Alt+[ c o n s o l e Ctrl+Alt+] : : B u f f e r W i d t h ) " Enter       
 Space Space Space Space " B u f f e r H e i g h t : Space $ ( Ctrl+Alt+[ c o n s o l e Ctrl+Alt+] : : B u f f e r H e i g h t ) ` n " Enter
 Ctrl+Alt+} Enter
 Enter
 - - >

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -24.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

Environment data
----------------

PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.356 (WinBuild.160101.0800)
PS file version: 10.0.18362.356 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 139
BufferHeight: 8

Steps to reproduce or exception report
--------------------------------------

I first encountered this error when using MenuComplete with posh-git trying to set some posh-git settings with `$GitPromptSettings.` followed by `Tab`.
Then I tried opening this issue pasting the evironment data script  from above resulted in this error too.

I think it might be related to `BufferHeight` since this is only 8 inside VS Code but in a normal Powershell window its 1000.

**Comment by vincentmathis** [comment]
I just realized myself that this is a duplicate that I didn't find before and which is supposed to be fixed.
I installed `2.0.0-beta6` and it works now.

Sorry for that.
