### ISSUE TITLE
InvalidOperationException thrown when typing `cffcc` in command mode

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PSReadLine#1281]
Environment data
----------------

```
PS version: 7.0.0-rc.1
PSReadline version: 2.0.0-rc1
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost
BufferWidth: 145
BufferHeight: 9001
```

Steps to reproduce or exception report
--------------------------------------

1. run `Set-PSReadLineOption -EditMode Vi`
2. type `abc`
3. type <kbd>Esc</kbd>
4. type `cffcc`, exception will be thrown

### Exception
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.PowerShell.PSConsoleReadLine.StartEditGroup()
   at Microsoft.PowerShell.PSConsoleReadLine.GroupUndoHelper.StartGroup(Action`2 instigator, Object instigatorArg)
   at Microsoft.PowerShell.PSConsoleReadLine.ViReplaceLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ViChord(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by daxian-dbw** [comment]
```
<c,f>            ViReplaceToChar                  Deletes until the to be given character.
<c,c>            ViReplaceLine                    Repace the current line with the next set of characters typed.
```
`cff` asks PSReadLine to delete until the character `f` while `abcd` doesn't contain the letter `f`. The method `ViReplaceToChar` calls `StartGroup` which sets `_editGroupStart` but PSReadLine doesn't get to the insert mode because `f` is not found, and then the subsequent `cc` calls `StartGroup` again which expects `_editGroupStart` to be `-1` and throw the exception because `_editGroupStart` is not reset from the `cff` operation.

It might be a simple fix in `ViReplaceToChar` that we add a `else` block and call `EndGroup()`. But it's possible a more general issue that PSReadLine just didn't reset `_editGroupStart` properly in some of its operations in VI mode.
https://github.com/PowerShell/PSReadLine/blob/4fe166e000d0ed1b28a9db865c900f485b5ed027/PSReadLine/Replace.vi.cs#L251-L268
