### ISSUE TITLE
PS preview 1

### ISSUE THREAD

**Issue by Zhanra** [PowerShell/PSReadLine#1286]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

PS version: 7.0.0-preview.1
PSReadline version: 2.0.0-beta4
os: 10.0.18362.356 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 59

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0-beta4
PowerShell: 7.0.0-preview.1
OS: Microsoft Windows 10.0.18363
Last 192 Keys
```
 $ w k F8 Enter
 e n t e r F8 Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Delete Delete Delete Delete Delete R I S S A Enter         D A T E Escape c m d Enter
 d a t e Enter
 UpArrow Spacebar 1 2 / 2 7 / 2 0 1 9 Enter
 UpArrow UpArrow : Enter
 UpArrow Escape c d \ Enter
 g e t - n e t f F8 Enter
 s e t - n e t f F8 F8 F8 Escape n e w - n e t f F8 F8 F8 F8 F8 F8 Enter
 n e w - n e t f F8 F8 Enter
 n e w - n e t f F8 F8 F8 F8 F8 F8 F8 F8 Enter
 n e w - n e t f F8 F8 F8 F8 F8 F8 F8 Enter
 n e w - n e t f F8 F8 F8 F8 F8 F8 F8 Enter
 n e w - n e t f F8 F8 F8 F8 F8 F8 F8 Enter
 n e w - n e t f F8 F8 F8 F8 F8 F8 F8 Enter
 Enter

```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 58.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by daxian-dbw** [comment]
@Zhanra this issue should be solved in PSReadLine 2.0.0-rc1, available from PowerShellGallery. Give it a try.
