### ISSUE TITLE
Bug occurred when I tried creating a resource group using power shell in Azure portal

### ISSUE THREAD

**Issue by ootoo1992** [PowerShell/PSReadLine#1297]
Environment data
----------------
Azure portal using cloud shell

-----------------------------------------------------------------------
Last 200 Keys:
```
 l " Space } Space e l s e Space { Space " p o w e r s h e l l . e x e " Space } ; Space ( d i r Space $ p s h o m e \ $ n a m e ) . V e r s i o n I n f o . F i l e V e r s i o n ) " Enter
 Space Space Space Space " H o s t N a m e : Space $ h o s t N a m e " Enter
 Space Space Space Space " B u f f e r W i d t h : Space $ ( [ c o n s o l e ] : : B u f f e r W i d t h ) " Enter
 Space Space Space Space " B u f f e r H e i g h t : Space $ ( [ c o n s o l e ] : : B u f f e r H e i g h t ) ` n " Enter
 } Enter

```

Exception:
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -32.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------

Steps to reproduce or exception report
--------------------------------------
1. Login to Azure portal.
2. Open Azure's cloud-shell.
3.  Make a resource group using this powershell script (I forgot to close the } after the if:

Get-AzureRmResourceGroup -Name new-gr -ErrorVariable notPresent -ErrorAction SilentlyContinue
 if ($notPresent)
 {
New-AzureRmResourceGroup -Name new-gr -Location westeurope -Force

else
 {

 }

**Comment by daxian-dbw** [comment]
@ootoo1992 This has been fixed in recent versions of PSReadLine and the most recent version is `2.0.0-rc2`, but the PowerShell Cloud Shell is using pwsh 6.2.3 with the version `2.0.0-beta3` of PSReadLine. PowerShell 7 with the most latest PSReadLine will be released soon (early next month) and Cloud Shell will rev the PowerShell version after that, so you will get the fix by that time.
