### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below.

### ISSUE THREAD

**Issue by joe6727** [PowerShell/PSReadLine#1299]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 d d r e s s = l o c a l h o s t : 4 9 8 3 5 ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s 
\ J o e \ A p p D a t a \ R o a m i n g \ C o d e \ U s e r \ w o r k s p a c e S t o r a g e \ 3 e f 3 d d c 4 0 f 5 4 9 1 6 6 7 7 8 2 9 9 6 9 6 9 e 2 3 7 c 8 \ r e d h a t . j a v a \ j d t _ w s \ 1 Space G r a n u l a r _ 4 4 7 b c 4 7 5 \ b i n ' Space ' g r a n u l a r ' 
Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS D:\Users\Joe\Documents\1 Granular> & 'C:\Users\Joe\.vscode\extensions\vscjava.vscode-java-debug-0.24.0\scripts\launcher.bat' 'C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.232-3\bin\java' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:49835' '-Dfanular_447bc475\bin' 'granular'

Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by daxian-dbw** [comment]
@joe6727 This issue has been fixed in recent versions of PSReadLine. Please try out the `2.0.0-rc2` from PowerShell Gallery.
