### ISSUE TITLE
I pasted something into a fresh seasson and It told me to come here and make an issue for you

### ISSUE THREAD

**Issue by oziphantom** [PowerShell/PSReadLine#1310]
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -3.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS D:\GitHub\ForOzi\tactics\Master> D:\pathstuff\64tass.exe -a master.mla -o master.prg  --no-caret-diag --dump-labels -l master.tass @D:\pathstuff\tassargs.arg  -L master.list --verbose-list --line-numbers
```

**Comment by daxian-dbw** [comment]
This issue were fixed in recent versions of PSReadLine. Please try out the `2.0.0-rc2` from PowerShell Gallery.
