### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below.

### ISSUE THREAD

**Issue by raiden-e** [PowerShell/PSReadLine#1316]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 70 Keys:
 l s Space - r e c u r s e ) . c o u n t Home ( Enter
 c d Space r e n Ü * Backspace Backspace * Enter
 l s Enter
 l s Space Backspace Backspace Backspace Backspace ( k Backspace l s ) . c o u n t Enter
 c l k c Backspace Backspace s Enter
 Enter
 c l s Enter
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/58954125/73093029-01ad0700-3ede-11ea-95d5-38cadd224985.png)

**Comment by raiden-e** [comment]
PowerShell pasted the clipboards contents after this message normally (without me pressing ctrl + v again)

**Comment by daxian-dbw** [comment]
This was fixed. Please see the pinned issue and try out the latest version of `PSReadLine` from PowerShell Gallery.
