### ISSUE TITLE
Powershell command crash "Oops, something went wrong"

### ISSUE THREAD

**Issue by fguitton** [PowerShell/PSReadLine#1317]
Hello, the lovely PowerShell requested if I could please report de following :
Thank you for the wonderful work !

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 173 Keys:
 c d Space / / Backspace r Backspace R e Tab Tab s f Tab Enter
 n c u Space - u a Enter
 UpArrow Backspace c Enter
 UpArrow Backspace Ctrl+c Ctrl+c UpArrow Backspace Enter
 c d Space p a c Tab Tab Tab Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 c d Space . . / . . / Enter
 y a r n Space i n s t a l l Space - - f o r c e Enter
 y a r n Space s t a Backspace Backspace Backspace s t Backspace Backspace s t u r o Backspace y Backspace Backspace Backspace o r y b o o k Enter
 Ctrl+c Ctrl+c UpArrow Enter
 Ctrl+c Ctrl+c C Ctrl+c Ctrl+c Ctrl+c Ctrl+c UpArrow UpArrow UpArrow DownArrow DownArrow Enter
 Ctrl+c Ctrl+c Ctrl+c c l e a r Enter
 c d Space p a c k Tab Tab Tab Enter
 UpArrow UpArrow UpArrow Enter
 Ctrl+c Ctrl+c Ctrl+c c d Space . . Enter
 c d Space . . Enter
 UpArrow UpArrow Ctrl+l

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by daxian-dbw** [comment]
Error when pressing `Ctrl+l` has been fixed in recent versions. Please take a look at the pinned issue #1315
