### ISSUE TITLE
Some emoji, eg '😃' don't work, whereas others like '⏰' do

### ISSUE THREAD

**Issue by mikemaccana** [PowerShell/PSReadLine#1329]
Moved from https://github.com/microsoft/terminal/issues/1606

Using app store preview build of Windows Terminal, with <kbd>win+.</kbd> to send 😃 and then ⏰:

![image](https://user-images.githubusercontent.com/172594/60107029-149c0500-975e-11e9-81ab-a5475b746ac6.png)

@DHowett-MSFT mentioned it's likely not a Windows Terminal issue:

> Powershell has trouble with high unicode input ... and there's not much we can do to help that.

```

Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by lzybkr** [comment]
@iSazonov - see https://github.com/PowerShell/PSReadLine/issues/1045

**Comment by iSazonov** [comment]
I opened https://github.com/dotnet/runtime/issues/800, maybe not entirely correct, but the presence of these features in Core seems desirable.

**Comment by daxian-dbw** [comment]
@DHowett-MSFT You mentioned in microsoft/terminal#1606 that:
> Powershell has trouble with high unicode input ... and there's not much we can do to help that.

For all high unicode emoji input, such as 😀 (surrogates: `D83D, DE04`), `Console.Readkey()` seems to only return a high surrogates character, like `ConsoleKeyInfo { Key = 18, KeyChar = '\ud83d', Modifiers = 0 }`, but not the low surrogates. Could you please provide me some pointers on how to correctly read all surrogates? An in general, can you please provide me some pointers on how should a readline library handle emojis?

**Comment by SeeminglyScience** [comment]
@daxian-dbw it's sent as two separate keys.  If you do this you'll see both

```powershell
while ($true) {
    '0x{0:X4}' -f [int][Console]::ReadKey($true).KeyChar
}
```

**Comment by SeeminglyScience** [comment]
Also, I think escape sequences are being written between the surrogates:

```powershell
[Console]::WriteLine("`u{D83D}`u{DE00}")
# Shows emoji

[Console]::WriteLine("`u{D83D}`e[30m`u{DE00}")
# Shows two separate question mark characters
```

**Comment by daxian-dbw** [comment]
`[Console]::WriteLine("`u{D83D}`u{DE00}")` shows 2 question mark character for me in both Windows terminal and legacy console host:

![image](https://user-images.githubusercontent.com/127450/82387236-59223600-99eb-11ea-88d7-35ab42567868.png)

**Comment by SeeminglyScience** [comment]
Yeah you gotta change output encoding first:

```powershell
[Console]::OutputEncoding = [Text.Encoding]::Unicode
```

**Comment by iSazonov** [comment]
Oh, is it a time to change [Console]::OutputEncoding to Utf8 for PowerShell?

**Comment by SeeminglyScience** [comment]
Also `Delete` should delete two characters if the target is a high surrogate.  @daxian-dbw let me know if you want a new issue for that.

**Comment by daxian-dbw** [comment]
@SeeminglyScience Yes, please open a new issue for `Delete`. Thanks!

**Comment by daxian-dbw** [comment]
For me later: https://github.com/microsoft/terminal/issues/1503#issuecomment-605311026

**Comment by nu8** [comment]
As a workaround, I found that NuShell with Windows Terminal works as expected:

>![1329](https://user-images.githubusercontent.com/61808913/91104299-18ae0600-e633-11ea-8127-92cb1e24ce43.png)

https://github.com/nushell/nushell

**Comment by rayphi** [comment]
I've got also an Exception for a 💄in my commit message.

Exception:
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83D at index 10 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass81_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Func`2 fileOpener)
   at Microsoft.PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by chenshuai2144** [comment]
I have same  error
![image](https://user-images.githubusercontent.com/8186664/91842965-85ef1600-ec87-11ea-90d3-1668247ca598.png)

**Comment by ninmonkey** [comment]
This caused by `PSReadLine` itself

# Error Case: 

1. Create a filename that requires surrogate pairs, include a `🖥️` or `😀` 
1. copy a path to your clipboard
1. type `gi '` then paste the path

File not found

I verified `gi (get-clipboard)` **does** have the right path.

# Working Case: Remove-Module

1. run `Remove-Module PSReadLine`
2. Paste like the first test

Get-Item **does** find the file

![image](https://user-images.githubusercontent.com/3892031/116796059-450e0200-aa9f-11eb-86bd-1a07702b0938.png)

# Notes:

It doesn't seem to matter whether the 3 encodings are set to `utf16le` vs `utf8`
`[console]::InputEncoding, [console]::OutputEncoding, $OutputEncoding`

Even though the terminal didn't render the runes correctly, the paste still was the valid path
![image](https://user-images.githubusercontent.com/3892031/116796069-5b1bc280-aa9f-11eb-895b-75f0d1086cd6.png)

**Comment by StevenBucher98** [comment]
Revisiting this issue, I dont seem to get any errors copying and pasting large sets of emojis in Windows Terminal with PowerShell 7.3.1 and PSReadLine 2.2.6

![image](https://user-images.githubusercontent.com/20605456/210612099-ea7ed799-dc41-4779-a8c6-6b7fecd604a5.png)

Without windows Terminal it seems to be _okay_ but has little different rendering and a few ??

![image](https://user-images.githubusercontent.com/20605456/210612155-b7c88141-0a34-4056-8ec4-8967183b4953.png)

With Mac it gets a little messy with more than like 2 emojis, see screen recording 

Uploading Screen Recording 2023-01-04 at 9.14.48 AM.mov…

**Comment by UsmanTariq2** [comment]
Has this issue been fixed?
Whenever i enter a emoji like 🤑the windows terminal shows � � instead of rendering the proper emoji in the terminal when inputting an emoji
The information provided here is confusing me that is why asking.
