### ISSUE TITLE
error on tab completion

### ISSUE THREAD

**Issue by eidellev** [PowerShell/PSReadLine#1339]
-----------------------------------------------------------------------
Last 70 Keys:
```
 c d Space j o u Tab m a Tab Enter
 l l Enter
 Enter
 Enter
 l l Enter
 s c o o p Space u p Tab Enter
 Enter
 Enter
 Enter
 Enter
 ' ' Backspace Backspace Enter
 u p d a t e - m u Tab Backspace y Tab Enter
 l l Enter
 l l Enter
 y n u p Backspace Backspace Backspace Space u p Tab Tab
```

Exception:
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 41.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.Complete(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
This issue will be closed because you didn't follow the bug report template to provide **environment data** and **repro steps**.

At any rate, the reported issue is very likely fixed in recent versions of PSReadLine.
So, please try out the latest version of PSReadLine from PowerShell Gallery. If you still run into this, please update your issue description and re-open the issue afterwards.
