### ISSUE TITLE
System.IO.IOException: The parameter is incorrect.

### ISSUE THREAD

**Issue by sranesushant1988** [PowerShell/PSReadLine#1344]
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.Console.set_CursorVisible(Boolean value)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorVisible(Boolean value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for the reported exception, it's thrown from the Win32 API `SetConsoleCursorInfo`. I've reviewed that API and it seems like an impossible to thrown unless there is some random corruption in conhost.
https://github.com/dotnet/runtime/blob/fddce702c2ff94c6ca05e401cfb0eb1944083767/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L557-L566

Sorry I can't do anything about it, but thanks for reporting it.
