### ISSUE TITLE
Pasting long function

### ISSUE THREAD

**Issue by wonderplayer** [PowerShell/PSReadLine#1353]
Got the following error when pasting long function to terminal window in VS Code

Last 200 Keys:
 " Enter
 Space Space Space Space } Enter
 Tab e l s e Enter
 Tab { Enter
 Tab Tab # Space A d d Space a Space + 1 Space h o u r Space t i m e s t a m p Space t o Space t h e Space O A u t h 2 Space t o k e n Space r e s p o n s e : Enter
 Tab Tab $ s c r i p t : g r a p h A P I A u t h R e s u l t Space | Space A d d - M e m b e r Space - N o t e P r o p e r t y N a m e Space e x p i r a t i o n _ t i m e Space - N o t e P r o p e r t y V a l u e Space ( ( G e t - D a t e ) . A d d H o u r s ( 1 ) ) Enter
 Tab } Enter
 } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -35.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
@wonderplayer Please use Issue template to report:
> The maintainer may close your issue without further explanation or engagement if:
>- You delete this entire template and go your own path;

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for the exception you report here, check out the pinned issue #1306
