### ISSUE TITLE
Error when pressing tab to navigate to other folders.

### ISSUE THREAD

**Issue by andersonn-roberto** [PowerShell/PSReadLine#1355]
-----------------------------------------------------------------------
Last 200 Keys:
```
 Enter
 c d Space s t a r Tab . i n Tab Enter
 c d Space . . Enter
 d o t n e t Space s n Backspace l n Space a d d Space t o Backspace Backspace s t a r Tab Tab d o Tab Enter
 UpArrow Backspace Backspace End Backspace Backspace Backspace Backspace i n f Tab Enter
 d o t n e t Space b u i l d Enter
 c d Space s t a r Tab Tab Tab Tab Tab Tab Tab Tab Space Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace . a Tab Enter
 d o t n e t Space a d d Space r e f e r e n c e Space . . \ s t Tab D o Tab Tab
```

Exception:
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.      Parameter name: top
Actual value was 32.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.Complete(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)       at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)    ```
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for the exception you report here, check out the pinned issue #1306
