### ISSUE TITLE
Error when I  put a lotof line as argument

### ISSUE THREAD

**Issue by jrcarreiro** [PowerShell/PSReadLine#1356]
Last 200 Keys:
```
 o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O p a S o p a O
```

Exception:
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -75.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by iSazonov** [comment]
@f0rgetful Please use Issue template to pull an issue.
> The maintainer may close your issue without further explanation or engagement if:
> - You delete this entire template and go your own path;
> - You file an issue that has many duplicates;
> - You file an issue completely blank in the body.

**Comment by daxian-dbw** [comment]
@f0rgetful Check out the pinned issue #1306
