### ISSUE TITLE
In VS Code getting this System.OutOfMemoryException: Array dimensions exceeded supported range.

### ISSUE THREAD

**Issue by mukund720** [PowerShell/PSReadLine#1360]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:

Exception:
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at Microsoft.PowerShell.PSConsoleReadLine.<ReadHistoryFile>b__67_0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by mukund720** [comment]
please check image for ref.

**Comment by mukund720** [comment]
![image](https://user-images.githubusercontent.com/11161480/74810171-db2f8f80-5314-11ea-9c2d-f44d4ba438e8.png)

**Comment by iSazonov** [comment]
Do you use 2.0 version?

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for the reported issue, I believe it's a real bug. PSReadLine calls `File.ReadAllLines(Options.HistorySavePath)` to get back all content of the file, and this issue is bound to happen when the file is too large.
