### ISSUE TITLE
The red Text Compels me . . .

### ISSUE THREAD

**Issue by clarkkd** [PowerShell/PSReadLine#1374]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 / k u r t i / D e s k t o p / R e s e a r c h / R 
a t e M y P r o f e s s o r / t e s t i n g . p y Enter
 & & & & & & & & & & & & & & & & & & & & Space C : 
/ U s e r s / k u r t i / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o n 3 8 
- 3 2 / p y t h o n . e x e Space c : / U s e r s / k u r t i / D e s k t o p / R e s e a r c h / R a 
t e M y P r o f e s s o r / t e s t i n g . p y Enter
 &

Exception:
System.ArgumentOutOfRangeException: The value must 
be greater than or equal to zero and less than the 
console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, 
Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor) 
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
See the pinned issue #1306
