### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by mokasini** [PowerShell/PSReadLine#1378]
Last 6 Keys:
 & Space C : / U

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and 
less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String 
defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)     
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS Microsoft.PowerShell.Core\FileSystem::\\uni.au.dk\Users\au643925\Documents\Pythondir> sers/au643925/AppData/Local/Programs/Python/Python38/python.exe -m pip install -U mypy 
--user
sers/au643925/AppData/Local/Programs/Python/Python38/python.exe : The term 'sers/au6439
25/AppData/Local/Programs/Python/Python38/python.exe' is not recognized as the name of  
a cmdlet, function, script file, or operable program. Check the spelling of the name, o 
r if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ sers/au643925/AppData/Local/Programs/Python/Python38/python.exe -m pi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (sers/au643925/A...on38/python.exe:Strin  
   g) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by iSazonov** [comment]
Do you see https://github.com/PowerShell/PSReadLine/issues/1306?
