### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by scottnm** [PowerShell/PSReadLine#1386]
Last 66 Keys:
c d Space z : \ b Backspace o s 3 \ s r Tab Enter
$ e n v : s d Tab x Tab r Tab Enter
t s h e l l Enter
d i r Tab Tab Enter
x b c p Space z : | t m Tab Backspace Backspace \ Backspace Backspace \ t m Tab Tab Tab Tab Tab

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -15.
at System.Console.SetCursorPosition(Int32 left, Int32 top)
at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount) at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect) at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
@daxian-dbw It seems having a script to auto close such issues saves a lot of your time :-)
