### ISSUE TITLE
PSReadline in Windows PowerShell crashes when I type or paste the following: @{3e800

### ISSUE THREAD

**Issue by exchange12rocks** [PowerShell/PSReadLine#1391]
## Environment

```none
PS version: 5.1.18362.628
PSReadline version: 2.0.0
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 130
BufferHeight: 3000
```

## Exception report

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0
PowerShell: 5.1.18362.628
OS: Microsoft Windows 10.0.18363
Last 7 Keys
```
 @ { 3 e 8 0 0
```

### Exception
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Management.Automation.Language.SemanticChecks.VisitHashtable(HashtableAst hashtableAst)
   at System.Management.Automation.Language.HashtableAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.CommandExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.PipelineAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.StatementBlockAst.InternalVisit(AstVisitor visitor, ReadOnlyCollection`1 traps, ReadOnlyCollection`1 statements, AstVisitAction action)
   at System.Management.Automation.Language.NamedBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ScriptBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.SemanticChecks.CheckAst(Parser parser, ScriptBlockAst ast)
   at System.Management.Automation.Language.ScriptBlockAst.PerformPostParseChecks(Parser parser)
   at System.Management.Automation.Language.Parser.ParseTask(String fileName, String input, List`1 tokenList, Boolean recursed, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.Parse(String fileName, String input, List`1 tokenList, ParseError[]& errors, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.ParseInput(String input, String fileName, Token[]& tokens, ParseError[]& errors)
```

## Steps to reproduce

1. Open Windows PowerShell window.
2. Paste or type the following string into the window: @{3e800
(last two characters can be any digits)

Does not reproduce on PowerShell 7.

## Expected behavior

Nothing happens.

## Actual behavior

PSReadline crashes.

**Comment by daxian-dbw** [comment]
Thanks for the reporting!
It's a bug in Windows PowerShell, which I believe is fixed in PowerShell 7. Here is the repro without `PSReadLine` involved:
```powershell
try {
    [System.Management.Automation.Language.Parser]::ParseInput("@{3e800", [ref]$null, [ref]$null)
} catch {
    $e = $_
}

$e.Exception.InnerException.InnerException | fl * -Force
```
This is the result:
```none
Message        : Object reference not set to an instance of an object.
Data           : {}
InnerException :
TargetSite     : System.Management.Automation.Language.AstVisitAction
                 VisitHashtable(System.Management.Automation.Language.HashtableAst)
StackTrace     :    at System.Management.Automation.Language.SemanticChecks.VisitHashtable(HashtableAst hashtableAst)
                    at System.Management.Automation.Language.HashtableAst.InternalVisit(AstVisitor visitor)
                    at System.Management.Automation.Language.CommandExpressionAst.InternalVisit(AstVisitor visitor)
                    at System.Management.Automation.Language.PipelineAst.InternalVisit(AstVisitor visitor)
                    at System.Management.Automation.Language.StatementBlockAst.InternalVisit(AstVisitor visitor,
                 ReadOnlyCollection`1 traps, ReadOnlyCollection`1 statements, AstVisitAction action)
                    at System.Management.Automation.Language.NamedBlockAst.InternalVisit(AstVisitor visitor)
                    at System.Management.Automation.Language.ScriptBlockAst.InternalVisit(AstVisitor visitor)
                    at System.Management.Automation.Language.SemanticChecks.CheckAst(Parser parser, ScriptBlockAst ast)
                    at System.Management.Automation.Language.ScriptBlockAst.PerformPostParseChecks(Parser parser)
                    at System.Management.Automation.Language.Parser.ParseTask(String fileName, String input, List`1
                 tokenList, Boolean recursed, ParseMode parseMode)
                    at System.Management.Automation.Language.Parser.Parse(String fileName, String input, List`1
                 tokenList, ParseError[]& errors, ParseMode parseMode)
                    at System.Management.Automation.Language.Parser.ParseInput(String input, String fileName, Token[]&
                 tokens, ParseError[]& errors)
HelpLink       :
Source         : System.Management.Automation
HResult        : -2147467261
```
I will resolve this issue as external.
BTW, Windows PowerShell is in maintenance mode and I'm afraid the fix for this issue will not meet the bar. But feel free to open an issue in [PowerShell repo](https://github.com/powershell/powershell) to ask the question.
