### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below.

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#1392]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0
PowerShell: 5.1.18362.628
OS: Microsoft Windows 10.0.18363
Last 48 Keys
```
 w g e t . Tab Tab Tab Spacebar - - h t t p s - o n l y Spacebar Shift+Insert " Home Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow " End Enter
 s t i Backspace Backspace i t e _ u r l = " " PageUp
```

### Exception
```
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

------

next is
```
PS C:\Users\username> site_url="" 
```

**Comment by ghost** [comment]
this is normally ignored, but just this once. goodbye.

**Comment by daxian-dbw** [comment]
Thanks for the reporting! From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for the reported exception, see https://github.com/PowerShell/PSReadLine/issues/551#issuecomment-341856386. Quoted below:

> I've reviewed PSReadLine and the .Net api that is used and this seems like an impossible condition. The .Net api Console.SetWindowsPosition validates the parameters before calling the Win32 api, yet it's the Win32 api reporting the error.
>
> As this was not reproducible, I'll chalk this up to some random corruption in conhost - it wouldn't be the first transient error like this that I've seen.
>
>Sorry I can't do anything about it, but thanks for reporting it.
