### ISSUE TITLE
PSReadLine error in VS Code 

### ISSUE THREAD

**Issue by gbargsley** [PowerShell/PSReadLine#1397]
This occurs after installing PowerShell 7 per VS Code recommendation.  Does not occur outside of VS Code in a normal Powershell command.

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Enter
 ( Space Space Space ' ' A C C T D M D S S Q L D 0 2 ' ' , Enter
 Space Space Space Space ' ' A z u r e ' ' , Enter
 Space Space Space Space ' ' A z u r e Space S o u t h Space C e n t r a l ' ' , Enter
 Tab ' ' A C C T D ' ' , Enter
 Tab ' ' I n f r a s t r u c t u r e ' ' , Enter
 Space Space Space Space ' ' G a r r y Space B a r g s l e y ' ' , Enter
 Tab ' ' D E V ' ' , Enter
 Space Space Space Space ' ' Y ' ' , Enter
 Space Space Space Space ' ' T E X P A C ' ' , Enter
 Space Space Space Space ' ' Y ' ' , Enter
 Tab ' ' S Q L Space S e r v e r s Space - Space D e v ' ' Enter
 ) ' Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in 
that dimension.
Parameter name: top
Actual value was -18.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by iSazonov** [comment]
See https://github.com/PowerShell/PSReadLine/issues/1306

**Comment by gbargsley** [comment]
@iSazonov How do I determine what fixed the issue and what to install?

**Comment by iSazonov** [comment]
You should use a script from Bug Issue template.

**Comment by gbargsley** [comment]
I cannot find anything on any of the issues or fixes for how to get past this? @iSazonov

**Comment by gbargsley** [comment]
I really need to get some traction on this.  I cannot use VS Code anymore because of this issue.  Does anyone have an workarounds.

**Comment by rkeithhill** [comment]
@gbargsley What is the version number of your PSReadLine? Run `Get-Module PSReadLine`

**Comment by daxian-dbw** [comment]
>  Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

This Url from your reported exception indicates it's a fairly old version of PSReadLine (<= 2.0.0-beta3).
I don't know how come you get the PS 7 but have an old version of PSReadLine in play because PS 7 ships the 2.0.0 GA version of PSReadLine. So check out the PSReadLine version you are using and upgrade it to the latest GA version. The issue has been fixed in the GA version.
