### ISSUE TITLE
Testing API Call on PaloALto using Python

### ISSUE THREAD

**Issue by Fennec78** [PowerShell/PSReadLine#1410]
Oops, something went wrong.  Please report this bug with the details below.
-----------------------------------------------------------------------
Last 200 Keys:
 n . e x e ' Space ' c : \ U s e r s \ r a b i h a n n a \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h 
o n - 2 0 2 0 . 2 . 6 4 3 9 7 \ p y t h o n F i l e s \ p t v s d _ l a u n c h e r . p y ' Space ' - - d e f a u l t ' Space ' - - c l i e n t ' Space ' - - h o s t ' Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 5 2 0 4 5 ' Space ' d : 
\ C o d e \ P a l o a l t o - a p i \ m a i n . p y ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by iSazonov** [comment]
See #1306

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro steps** the next time.

As for this issue, please see #1306 for details.
