### ISSUE TITLE
 Version 6.13.4

### ISSUE THREAD

**Issue by aflahaayub** [PowerShell/PSReadLine#1429]
Last 54 Keys:
 n p m Space - - v e r s i o n Enter
 Delete Backspace n p m Space i n i t Space - y Enter
 Ctrl+l n p m Space i n s t a l l Space n o d e - s a a Backspace s s Enter 
 Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal 
to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -3.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)        
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
See #1306

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro step** the next time.

Issues related to `Ctrl+l` has been fixed by avoid using `SetCursorPosition`, see #1315.
