### ISSUE TITLE
Exception: System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Tusharcoder18** [PowerShell/PSReadLine#1430]
Whenever I am trying to run a minimal python code which uses the yield keyword, I am certainly getting this error during execution. According to my observation, maybe I am getting this due to the yield keyword of Python. After restart it gives a prompt that Python tool crashed 5 times during previous session.

-----------------------------------------------------------------------
Last 194 Keys:
 p y t h o n Space - u Space " d : \ P y t h o n Space 3 Space J o s e Space P o r t i l l a \ P y t h o n Space 3 Space J o s e Space P o r t i l l a \ P y P r a c t i c e \ I t e r a t o r s Space a n d Space G e n e r a t o r s \ r a n d o m _ n u m . p y " Enter
 p y t h o n Space - u Space " d : \ P y t h o n Space 3 Space J o s e Space P o r t i l l a \ P y t h o n Space 3 Space J o s e Space P o r t i l l a \ P y P r a c t i c e \ I t e r a t o r s Space a n

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and
less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String
defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
See #1306
