### ISSUE TITLE
"Last 138 Keys:" error

### ISSUE THREAD

**Issue by thomasortonbrady** [PowerShell/PSReadLine#1436]
Last 138 Keys:
 d a t Backspace Backspace Backspace l s Enter
 d a t a e r Backspace Backspace s e r v i c e c Tab F9 F8 LeftArrow Ctrl+Backspace Ctrl+Backspace Ctrl+v Ctrl+z Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+LeftArrow UpArrow Escape D a t a S E r v i Backspace Backspace Backspace Ctrl+Backspace D a t a S E r Ctrl+Backspace D A t a Backspace Backspace Backspace Backspace Backspace D a t a S e r v i c e C l F8 Tab F8 F8 F8 F8 F8 LeftArrow Ctrl+Backspace Ctrl+Backspace Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+Delete Ctrl+v End LeftArrow t r i n d e v - 6 4 3 6 RightArrow Enter
 UpArrow Enter
 UpArrow Enter
 LeftWindows LeftArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was 108.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.SetCursorPosition(Int32 cursor)
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
See #1306

**Comment by thomasortonbrady** [comment]
I was just reporting this because the error advised me to do so. Closing this.
