### ISSUE TITLE
Exception when pressing Ctrl+L

### ISSUE THREAD

**Issue by anthonyvdotbe** [PowerShell/PSReadLine#1437]
This occured in a standard PowerShell window inside VS Code's Terminal view, upon pressing Ctrl+L. Pressing it again worked as expected.

PSVersion = 5.1.18362.628

````
-----------------------------------------------------------------------
Last 200 Keys:
 e r c e p t o r Enter
 c d Space i a m Enter
 r g Space - Backspace m a s t e r Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow - s Space Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Delete M Enter
 UpArrow UpArrow Home RightArrow RightArrow RightArrow Delete Delete Delete Enter
 UpArrow UpArrow UpArrow DownArrow Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Delete n Backspace m Enter
 UpArrow Home RightArrow RightArrow . e x e Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Enter
 c d Space . . Enter
 UpArrow UpArrow Enter
 c d Space i a m Enter
 UpArrow UpArrow Enter
 c d Space . . Enter
 Ctrl+l c d Space s o c Tab Enter
 r g Space m a s t e r Enter
 UpArrow UpArrow DownArrow Shift+Ctrl+LeftArrow Ctrl+c Ctrl+c c d Space . . Enter
 r g Space - s Space R e m o t e M a i l i n g S e r v i c e Enter
 UpArrow Shift+Ctrl+LeftArrow c r e a t e M a i l i n g Enter
 \ Backspace Backspace Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
````

**Comment by iSazonov** [comment]
See #1306

**Comment by anthonyvdotbe** [comment]
Thanks for the reference. My particular stack trace isn't in there though, so I'll leave this open for now

**Comment by daxian-dbw** [comment]
From the bug report template:
```
The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
```
So, please follow the bug report template to provide **environment data** and **repro step** the next time.

Issues related to `Ctrl+l` has been fixed by avoid using `SetCursorPosition`, see #1315.

**Comment by anthonyvdotbe** [comment]
@daxian-dbw when I received the error in PowerShell, I used the [provided link](https://github.com/PowerShell/PSReadLine/blob/09300c0990b1f1d4a62434c2ac1bba22cfc0a6bd/PSReadLine/PSReadLineResources.resx#L393) which opens [this page](https://github.com/PowerShell/PSReadLine/issues/new). So I didn't "go my own path", since I never saw a template to begin with.
I opened #1440 and submitted https://github.com/PowerShell/PSReadLine/pull/1441

**Comment by daxian-dbw** [comment]
@anthonyvdotbe This is a good feedback, thanks for submitting the PR!
