### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below.

### ISSUE THREAD

**Issue by codaamok** [PowerShell/PSReadLine#1443]
```
-----------------------------------------------------------------------
Last 200 Keys:
 Space = Space G e t - C o m m a n d Space - N a m e Space $ N a m e Enter
 Space Space Space Space Space Space Space Space } Enter
 Space Space Space Space } Enter
 Enter
 Space Space Space Space i f Space ( $ C o m m a n d I n f o Space - i s Space [ S y s t e m . M a n a g e m e n t . A u t o m a t i o n . A l i
a s I n f o ] ) Space { Enter
 Space Space Space Space Space Space Space Space $ C o m m a n d I n f o Space = Space $ C o m m a n d I n f o . R e s o l v e d C o m m a n d En
ter
 Space Space Space Space } Enter
 Enter
 Space Space Space Space r e t u r n Space $ C o m m a n d I n f o Enter
 } Enter
 UpArrow UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

It was triggered by pasting something in to my console. I tried pasting it again in a fresh window but no exception was caught. What I tried pasting was:

```powershell
function Get-CommandInfo {
    <#
    .SYNOPSIS
        Get-Command helper.
    .DESCRIPTION
        Get-Command helper.
    #>

    [CmdletBinding()]
    param (
        # The name of a command.
        [Parameter(Mandatory, ParameterSetName = 'ByName')]
        [String]$Name,

        # A CommandInfo object.
        [Parameter(Mandatory, ParameterSetName = 'FromCommandInfo')]
        [System.Management.Automation.CommandInfo]$CommandInfo,

        # If a module name is specified the private / internal scope of the module will be searched.
        [String]$ModuleName,

        # Claims and discards any other supplied arguments.
        [Parameter(ValueFromRemainingArguments, DontShow)]
        $EaterOfArgs
    )

    if ($Name) {
        if ($ModuleName) {
            try {
                if (-not ($moduleInfo = Get-Module $ModuleName)) {
                    $moduleInfo = Import-Module $ModuleName -Global -PassThru
                }
                $CommandInfo = & $moduleInfo ([ScriptBlock]::Create('Get-Command {0}' -f $Name))
            }
            catch {
                $pscmdlet.ThrowTerminatingError($_)
            }
        }
        else {
            $CommandInfo = Get-Command -Name $Name
        }
    }

    if ($CommandInfo -is [System.Management.Automation.AliasInfo]) {
        $CommandInfo = $CommandInfo.ResolvedCommand
    }

    return $CommandInfo
}
```

**Comment by iSazonov** [comment]
See #1306
