### ISSUE TITLE
bck-i-search: apply_ | Ctrl+r | System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. Parameter name: top Actual value was -9.

### ISSUE THREAD

**Issue by python640** [PowerShell/PSReadLine#1444]
bck-i-search: apply_
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 UpArrow UpArrow UpArrow Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Enter
 Enter
 Enter
 t e r r a f o r m Space i n i t Space m o d Tab Tab Tab Backspace Backspace Backspace m o d u l e s / a u r o r a _ p o s t g r e s q l Enter
 c d Space s Tab a Tab Tab Tab Ctrl+c Ctrl+c c d Space . . Enter
 c d Space s s Tab Backspace Tab Tab Enter
 UpArrow UpArrow UpArrow Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace p l a n Enter
 Enter
 Enter
 Enter
 UpArrow UpArrow DownArrow Enter
 Ctrl+c Ctrl+l Enter
 Enter
 Enter
 UpArrow UpArrow DownArrow Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace a p p l Ctrl+c Ctrl+c Ctrl+r a p p 
l y Ctrl+r Ctrl+r

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -9.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.UpdateHistoryDuringInteractiveSearch(String toMatch, Int32 direction, Int32& searchFromPoint)
   at Microsoft.PowerShell.PSConsoleReadLine.InteractiveHistorySearchLoop(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.InteractiveHistorySearch(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
See #1306
