### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by cixa** [PowerShell/PSReadLine#1457]
Last 200 Keys:
 a \ j d k - 1 3 . 0 . 2 \ b i n \ j a v a . e x e ' Space ' - D f i l e . e n c
o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s \ c a i t l \ A p p D a t a \ R o a m i n g \ C o d e \ U s e r \ w o r k s p a c e S t o r a g e
\ b f 3 b f 6 0 8 c 8 0 b 6 8 5 1 f c b 3 7 d 4 4 6 a 2 f 8 c a 2 \ r e d h a t . j a v a \ j d t _ w s \ P r a c t i s e _ 1 1 3 7 3 8 5 7 \ b i n ' Space ' T e
s t 2 ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData,
String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
See #1306

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
