### ISSUE TITLE
node crash after yargs installation

### ISSUE THREAD

**Issue by Abstrath** [PowerShell/PSReadLine#1458]
Was following a curriculum and was told to install yargs version "^12.0.2" and then received the following issue when trying to add options...

 node app.js add --title=
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 i s Space m y Space t i t l e " Enter
 UpArrow Enter
 Ctrl+c n p m Space o i Backspace Backspace o Backspace i Space y a r g s @ 1 2 . 0 . 2 Enter
 n p m Backspace Backspace o d e Space a p p . j s Enter
 UpArrow Space a d d Space - - t i t l e Space Backspace =
" n o d e Space a p p . j s Space a d d Space - - t i t l e = " n o d e Space a d d . j s Enter
 Ctrl+c Enter
 Enter
 LeftArrow n p m Space o Backspace i o Backspace Enter
 n p m Backspace Backspace o d e Space a p p . j s Space a
d d Space - - t i t l e = " UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace n
o d e Space a p p . j s Enter
 n o d e Space a p p . j s Space a d d Space - - t i t l e
= '

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
See #1306

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
