### ISSUE TITLE
vscode told me to report

### ISSUE THREAD

**Issue by Judimax** [PowerShell/PSReadLine#1461]
Last 200 Keys:
 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace - - l i s t Enter
 c l e a r Enter
 UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow l i s t Enter
 UpArrow Backspace Backspace Backspace Backspace i n s t a l l Space p y
r e b a s e Enter
 c d Space . . Enter
 c d Space s Backspace Backspace Backspace Backspace Backspace c Space d
. . Enter
 c d Space . . Enter
 c d Space s Tab Tab t Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 l s Enter
 p y t h o n 3 9 Backspace 8 Tab Space s u Tab Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace v a l u Tab Enter
 c l e a r Enter
 c d Space . . / Enter
 l s Enter
 c d Space a n Tab C o Tab Enter
 c d Space b Tab Enter
 c d Space p Tab Enter
 b Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32
value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace,
EngineIntrinsics engineIntrinsics)

**Comment by iSazonov** [comment]
See #1306

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
