### ISSUE TITLE
Powershell in Mac OS Catalina 10.15.3 Error

### ISSUE THREAD

**Issue by mustaqsyed445** [PowerShell/PSReadLine#1474]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:
```

```

Exception:
```
System.IO.IOException: The system cannot open the device or file specified : 'PSReadLineHistoryFile_-753757225'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------

**Comment by iSazonov** [comment]
Dup #833 #857

**Comment by daxian-dbw** [comment]
@mustaqsyed445 The mutex name was fixed to be consistent across powershell sessions in #1061. It's likely resolve this issue. Can you please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery? See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.

I will close this issue. If you run into the same with the 2.0.1 version of PSReadLine, please reopen it.
