### ISSUE TITLE
System.IO.IOException: The parameter is incorrect.

### ISSUE THREAD

**Issue by iamshital** [PowerShell/PSReadLine#1494]
Putting the logs as it is - 

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 D : \ U s e r s \ s h s a v e k a . R E D M O N D \ O n e D r i v e Space - Space M i c r o s o f t \ T a s k s \ A u t o T r i a g e \ G e t - B V T E x c e p t i o n s . p s 1 " Enter
 Ctrl+c UpArrow Enter
 Ctrl+c Ctrl+c Ctrl+c UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c c l e a r Enter
 D : \ U s e r s \ s h s a v e k a . R E D M O N D \ O n e D r i v e Space - Space M i c r o s o f t \ T a s k s \ A u t o T r i a g e \ G e t - B V T E x c e p t i o n s . p s 1 Home " End " PageUp

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by iSazonov** [comment]
Please use issue template to report and a script from the template to share information about your environment.

**Comment by iamshital** [comment]
Okay.
