### ISSUE TITLE
  VS code C++ file Debgugging Error  Exception: System.ArgumentOutOfRangeException:

### ISSUE THREAD

**Issue by asmat-wecan** [PowerShell/PSReadLine#1499]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Loading personal and system profiles took 859ms.
(base) PS E:\CPP>  & 'c:\Users\khan003\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ti00cslc.rvy' '--stdout=Microsoft-MIEngine-Out-wmy3ximr.cgc' '--stderr=Microsoft-MIEngine-Error-52jsqszh.xx4' '--pid=Microsoft-MIEngine-Pid-221pkfno.0mt' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpr
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 l c . r v y ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - w m y 3 x i m r . 
c g c ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - 5 2 j s q s z h . x x 4 ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - 2 2 1 p k f n o . 0 m t ' Space ' 
- - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)    
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
(base) PS E:\CPP>  & 'c:\Users\khan003\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ti00cslc.rvy' '--stdout=Microsoft-MIEngine-Out-wmy3ximr.cgc' '--stderr=Microsoft-MIEngine-Error-52jsqszh.xx4' '--pid=Microsoft-MIEngine-Pid-221pkfno.0mt' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpre
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 l c . r v y ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - w m y 3 x i m r . 
c g c ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - 5 2 j s q s z h . x x 4 ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - 2 2 1 p k f n o . 0 m t ' Space ' 
- - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)    
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
(base) PS E:\CPP>  & 'c:\Users\khan003\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ti00cslc.rvy' '--stdout=Microsoft-MIEngine-Out-wmy3ximr.cgc' '--stderr=Microsoft-MIEngine-Error-52jsqszh.xx4' '--pid=Microsoft-MIEngine-Pid-221pkfno.0mt' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpret
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 l c . r v y ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - w m y 3 x i m r . 
c g c ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - 5 2 j s q s z h . x x 4 ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - 2 2 1 p k f n o . 0 m t ' Space ' 
- - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)    
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
(base) PS E:\CPP>  & 'c:\Users\khan003\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ti00cslc.rvy' '--stdout=Microsoft-MIEngine-Out-wmy3ximr.cgc' '--stderr=Microsoft-MIEngine-Error-52jsqszh.xx4' '--pid=Microsoft-MIEngine-Pid-221pkfno.0mt' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interprete
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 l c . r v y ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - w m y 3 x i m r . 
c g c ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - 5 2 j s q s z h . x x 4 ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - 2 2 1 p k f n o . 0 m t ' Space ' 
- - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)    
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
(base) PS E:\CPP>  & 'c:\Users\khan003\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ti00cslc.rvy' '--stdout=Microsoft-MIEngine-Out-wmy3ximr.cgc' '--stderr=Microsoft-MIEngine-Error-52jsqszh.xx4' '--pid=Microsoft-MIEngine-Pid-221pkfno.0mt' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 l c . r v y ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - w m y 3 x i m r . 
c g c ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - 5 2 j s q s z h . x x 4 ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - 2 2 1 p k f n o . 0 m t ' Space ' 
- - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)    
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
(base) PS E:\CPP>  & 'c:\Users\khan003\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ti00cslc.rvy' '--stdout=Microsoft-MIEngine-Out-wmy3ximr.cgc' '--stderr=Microsoft-MIEngine-Error-52jsqszh.xx4' '--pid=Microsoft-MIEngine-Pid-221pkfno.0mt' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter=
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 l c . r v y ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - w m y 3 x i m r . 
c g c ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - 5 2 j s q s z h . x x 4 ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - 2 2 1 p k f n o . 0 m t ' Space ' 
- - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)    
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
(base) PS E:\CPP>  & 'c:\Users\khan003\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ti00cslc.rvy' '--stdout=Microsoft-MIEngine-Out-wmy3ximr.cgc' '--stderr=Microsoft-MIEngine-Error-52jsqszh.xx4' '--pid=Microsoft-MIEngine-Pid-221pkfno.0mt' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter=m
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 l c . r v y ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - w m y 3 x i m r . 
c g c ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - 5 2 j s q s z h . x x 4 ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - 2 2 1 p k f n o . 0 m t ' Space ' 
- - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)    
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
(base) PS E:\CPP>  & 'c:\Users\khan003\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ti00cslc.rvy' '--stdout=Microsoft-MIEngine-Out-wmy3ximr.cgc' '--stderr=Microsoft-MIEngine-Error-52jsqszh.xx4' '--pid=Microsoft-MIEngine-Pid-221pkfno.0mt' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter=mi
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 l c . r v y ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - w m y 3 x i m r . 
c g c ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - 5 2 j s q s z h . x x 4 ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - 2 2 1 p k f n o . 0 m t ' Space ' 
- - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)    
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
(base) PS E:\CPP>  & 'c:\Users\khan003\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ti00cslc.rvy' '--stdout=Microsoft-MIEngine-Out-wmy3ximr.cgc' '--stderr=Microsoft-MIEngine-Error-52jsqszh.xx4' '--pid=Microsoft-MIEngine-Pid-221pkfno.0mt' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter=mi'
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 l c . r v y ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - w m y 3 x i m r . 
c g c ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - 5 2 j s q s z h . x x 4 ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - 2 2 1 p k f n o . 0 m t ' Space ' 
- - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)    
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
(base) PS E:\CPP>  & 'c:\Users\khan003\.vscode\extensions\ms-vscode.cpptools-0.28.0-insiders2\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-ti00cslc.rvy' '--stdout=Microsoft-MIEngineo.0mt' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter=mi'
(base) PS E:\CPP>

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
