### ISSUE TITLE
PowerShell got stuck with an unknown internal error

### ISSUE THREAD

**Issue by sharathchandrapotla** [PowerShell/PSReadLine#1502]
Details of the bug:
-----------------------------------------------------------------------
Last 55 Keys:
 ` ` ` UpArrow UpArrow Shift+Ctrl+LeftArrow Shift+Ctrl+LeftArrow Shift+Ctrl+LeftArrow Shift+Ctrl+LeftArrow Shift+Ctrl+RightArrow Backspace w i n 3 2 _ c o m p Backspace Backspace Backspace Backspace p r o d u c t Enter
 ` UpArrow Shift+Ctrl+LeftArrow Backspace Ctrl+v Enter
 ` UpArrow Shift+Ctrl+LeftArrow Ctrl+v Enter
 ` ` UpArrow Enter
 ` Enter
 Enter
 c l s Enter

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
@sharathchandrapotla I recommend you to use the latest 2.0.1 version of PSReadLine (https://www.powershellgallery.com/packages/PSReadLine/2.0.1).

As for the reported exception, see https://github.com/PowerShell/PSReadLine/issues/551#issuecomment-341856386. Quoted below:

> I've reviewed PSReadLine and the .Net api that is used and this seems like an impossible condition. The .Net api `Console.SetWindowsPosition` validates the parameters before calling the Win32 api, yet it's the Win32 api reporting the error.
>
> As this was not reproducible, I'll chalk this up to some random corruption in conhost - it wouldn't be the first transient error like this that I've seen.
>
>Sorry I can't do anything about it, but thanks for reporting it.
