### ISSUE TITLE
Windows 10 debloater bug

### ISSUE THREAD

**Issue by Cr7xbox321** [PowerShell/PSReadLine#1503]
i was trying to make my pc better with the windows 10 debloater and when i copied and pasted it on to my windows power shell i noticed that it wasn't exactly the same compared to the guy who's video i was watching so i tried to undo it and copy and paste it again and it glitched out saying there's a bug and that to report this and im not sure if this is what im supposed to put report but here it is
Last 1 Keys:
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1404.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by Cr7xbox321** [comment]
sorry if this didn't make any sense,im not good at explaining things

**Comment by daxian-dbw** [comment]
The exception reported in your issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
