### ISSUE TITLE
System.IndexOutOfRangeException in 2.1.0-beta1

### ISSUE THREAD

**Issue by asmat-wecan** [PowerShell/PSReadLine#1507]
vscode c++ Debugging exception

## Environment
PSReadLine: 2.1.0-beta1
PowerShell: 5.1.18362.752
OS: Microsoft Windows 10.0.18363
Last 200 Keys
```
 ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - 1 i d u p i y q . s v 2 ' Spacebar ' - - s t 
d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - l j q h g d 1 v . q x x ' Spacebar ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - 3 n d r u n l n . w 2 r ' Spacebar ' - - d b g E x e = C : \ M i n G 
W \ b i n \ g d b . e x e ' Spacebar ' - - i n t e r p r e t e r = m i ' Spacebar Enter
 Spacebar & Spacebar ' c : \ U
```

## Exception report
 ```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at Microsoft.PowerShell.PSConsoleReadLine.ConvertOffsetToPoint(Int32 offset)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by iSazonov** [comment]
Could you please add repo steps? What is terminal you use?

**Comment by daxian-dbw** [comment]
@Asmat87 Could you please add repro steps? That would be very helpful to investigate this issue.
