### ISSUE TITLE
_editGroupStart is not properly set when go back to history

### ISSUE THREAD

**Issue by isti115** [PowerShell/PSReadLine#1518]
I am so used to moving word by word in PowerShell under windows, that I keep pressing Ctrl+Left and Ctrl+Right under linux as well, which at some point resulted in the following message asking me to report this here:

### Environment
PSReadLine: 2.0.0
PowerShell: 7.0.0
OS: Linux 5.6.8-arch1-1 #1 SMP PREEMPT Wed, 29 Apr 2020 16:22:56 +0000
Last 200 Keys
```
 Enter
 v i m Spacebar Backspace Backspace Backspace Backspace Backspace v i m Spacebar . Backspace Backspace Backspace Backspace Backspace Backspace v i m Spacebar Backspace Backspace Backspace Backspace c p Spacebar c o Tab B Tab Spacebar c o Tab B Tab Backspace Backspace Backspace Backspace l a g d a Enter
 v i m Spacebar c o Tab B Tab Backspace Backspace Backspace Backspace l Tab Enter
 v i m Spacebar - s Spacebar t e x t Backspace Backspace s t . v i m Spacebar - c Spacebar " " LeftArrow w g Backspace q RightArrow LeftArrow LeftArrow LeftArrow : RightArrow End Spacebar c o Tab B Tab Backspace Backspace Backspace Backspace l a g d a Enter
 v i m UpArrow UpArrow Enter
 UpArrow LeftArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow Backspace Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow UpArrow Home RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Backspace Backspace Backspace Delete Spacebar _ Backspace " Escape 1 ; 5 C UpArrow UpArrow DownArrow UpArrow Home RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Escape
```

### Exception
```
System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.Collections.Generic.List`1.GetRange(Int32 index, Int32 count)
   at Microsoft.PowerShell.PSConsoleReadLine.EndEditGroup(Action`2 instigator, Object instigatorArg)
   at Microsoft.PowerShell.PSConsoleReadLine.GroupUndoHelper.EndGroup()
   at Microsoft.PowerShell.PSConsoleReadLine.ViCommandMode(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by daxian-dbw** [comment]
Here is the repro:
1. Make sure you are in VI edit mode.
1. Type `cls` and then press <kbd>Enter</kbd>
1. Type `ok` and then press <kbd>Enter</kbd>
1. Type `abcdef` and then press <kbd>Escape</kbd> to switch to Command mode
1. Press <kbd>Shift+c</kbd> which will delete the character `f`
1. Press <kbd>UpArrow</kbd> to get to the history entry `ok`
1. Press <kbd>Escape</kbd> to switch to Command mode.

the root cause is `_editGroupStart` is not reset when switching to a history item.
