### ISSUE TITLE
Reporting PSReadLine exception encountered

### ISSUE THREAD

**Issue by ThirdDeviation** [PowerShell/PSReadLine#1519]
Working in VS Code 1.45.0, Python extension 2020.5.78807
Win 10 Pro, build 18363.778

Started debugger after several previous debugging runs (normal stuff) and ran into the following error:

```
Last 200 Keys:
 r i p t s \ p y t h o n . e x e ' Space ' c : \ U s e r s \ B r a n d o n \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 2 0 . 4 . 7 6 1 8 6 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e b u g p y \ w h e e l s \ d e b u g p y \ l a u n c h e r ' Space ' c : \ U s e r s \ B r a n d o n \ D e s k t o p \ M e n u A p p \ C I Space S c r a p i n g Space S a n d b o x . p y ' Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

I also noticed that the text in the console above the point where the exception was thrown had become garbled at some point:

```
1INSTRUCTIONSPound chicken to uniform thickness as needed.
Cut each breast diagonally into thirds, then cut each piece into thirds.
Dissolve 3 tablespoons salt and sugar in 2 quarts cold water in large
container. Add chicken, cover, and let sit for 15 minutes.

2Meanwhile, toss panko with oil in bowl until
evenly coated. Microwave, stirring frequently, until light golden brown, about
5 minutes. Transfer to shallow dish and let cool slightly. Whisk eggs, flour,
onion powder, garlic -powder, 1 teaspoon salt, and 1/4 teaspoon pepper together
, and cook hallow dish.
for 6 minutes. Transfeack in rimmed baking sheet. Remover nuggets tm brine and pat dry with paper towels. Working with several chickeno clean bow time, dredge in egg mixture, letting excess drip off, then coatl          mixture, pressing gently to adhere; transfer to prepared rack.
and gently l firm, about 4 hours. (Frozen nuggets can be transferred to
toss to red bag and stored in freezer for up to 1 month.)istribute. 
Return nuggggets: Lightly spray base ofets to air asket with vegetable oil spray. Place up to 18 nuggets
fryer and c basket. Place basket in air fryer, set temperature toook until  , and cook for 6 minutes. Transfer nuggets to clean bowl
chicken is toss to redistribute. Return nuggets to air fryer and cook until
crisp and rcrisp and registers 160 degrees, 6 to 10 minutes.egisters 160 degrees, 
6 to 10 minv) PS C:\Users\Brandon\Desktop\MenuApp> utes.      
Serve.    
```

It actually should have looked more like this:

```
INSTRUCTIONS1Pound chicken to uniform thickness as needed.
Cut each breast diagonally into thirds, then cut each piece into thirds.
Dissolve 3 tablespoons salt and sugar in 2 quarts cold water in large
container. Add chicken, cover, and let sit for 15 minutes.

2Meanwhile, toss panko with oil in bowl until
evenly coated. Microwave, stirring frequently, until light golden brown, about
5 minutes. Transfer to shallow dish and let cool slightly. Whisk eggs, flour,
onion powder, garlic -powder, 1 teaspoon salt, and 1/4 teaspoon pepper together
in second shallow dish.

3Set wire rack in rimmed baking sheet. Remove
chicken from brine and pat dry with paper towels. Working with several chicken
pieces at a time, dredge in egg mixture, letting excess drip off, then coat
with panko mixture, pressing gently to adhere; transfer to prepared rack.
Freeze until firm, about 4 hours. (Frozen nuggets can be transferred to
zipper-lock bag and stored in freezer for up to 1 month.)

4To Cook Nuggets: Lightly spray base of
air-fryer basket with vegetable oil spray. Place up to 18 nuggets
in prepared basket. Place basket in air fryer, set temperature to
400 degrees, and cook for 6 minutes. Transfer nuggets to clean bowl
and gently toss to redistribute. Return nuggets to air fryer and cook until
chicken is crisp and registers 160 degrees, 6 to 10 minutes.
Serve.
```

Everything has been working fine since the error occurred, so I don't need any follow-up or otherwise.  That said, if there's anything else I can provide that would be helpful, don't hesitate to let me know.

Thanks.

**Comment by daxian-dbw** [comment]
You didn't paste the environment data that was displayed along with the exception. But it's likely that you are using an old version of PSReadLine and this issue was fixed (see #1306)
Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery and give it a go. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.

**Comment by rkeithhill** [comment]
@daxian-dbw Why can't PSRL dump its version info and environment info like the PS version, OS version, etc along with the exception msg/callstack?  It would make it easier for folks to submit all the environment info you need.

**Comment by daxian-dbw** [comment]
@rkeithhill The exception report does include the environment information like versions of OS, PowerShell and PSReadLine, as well as the buffer size. But many users don't include them in the issue report.

https://github.com/PowerShell/PSReadLine/blob/24636202f8d636d0c8e0de5b5e5bc3e7a68a4433/PSReadLine/PSReadLineResources.resx#L395-L410

**Comment by rkeithhill** [comment]
>  many users don't include them in the issue report.

That's a bummer.  :-(  Good news is that it is getting rarer that I get these in PSRL.

**Comment by rkeithhill** [comment]
@daxian-dbw I wonder if it would help to change this?
```
### Environment 
```
to 
```
### Environment - please include this information when reporting an issue
```

**Comment by lzybkr** [comment]
Ideally you could auto-populate a new bug after asking for permission.
