### ISSUE TITLE
Resizing Window Doesn't Realign Text In Window

### ISSUE THREAD

**Issue by RedFox134** [PowerShell/PSReadLine#1525]
I tried to resize the power shell window after it opened.  It was just a blank blue screen, so I tried to type in cls.  I was then able to see text in the window and received this error: 

```
Last 4 Keys:
 c l s Enter


Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

![opened original](https://user-images.githubusercontent.com/1450461/81970599-67d0ad80-95e5-11ea-92dd-bdc498ecaf47.png)
![blank powershell window](https://user-images.githubusercontent.com/1450461/81970601-68694400-95e5-11ea-8916-ca57cd6de97e.png)
![Powershell error](https://user-images.githubusercontent.com/1450461/81970602-68694400-95e5-11ea-8258-dc441f616bb0.png)

**Comment by daxian-dbw** [comment]
@RedFox134 The issue was fixed by #1182. Please upgrade to the `2.0.1` version of PSReadLine from PowerShell Gallery and give it a try.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
