### ISSUE TITLE
found bug while executing python file

### ISSUE THREAD

**Issue by Surya742** [PowerShell/PSReadLine#1543]
Last 200 Keys:
 " c : \ U s e r s \ L o t u s \ D e s k t o p \ U n i v e r s i t y Space o f Space Space M i c h e g e n \ s q l L i t e . p y " Enter
 p y t h o n Space - u Space " c : \ U s e r s \ L o t u s \ D e s k t o p \ U n i v e r s i t y Space o f Space Space M i c h e g e n \ s q l L i t e . p y " Enter
 p y t h o n Space - u Space " c : \ U s e r s \ L o t u s \ D e s k t o p \ U n i v e r s i t y Space o f Space Space M i c h e g e n \ s q l L i t e . p y " Enter

Exception:
Parameter name: top
Actual value was 31.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
