### ISSUE TITLE
Error using 'run and debug' for Java

### ISSUE THREAD

**Issue by KensiHa** [PowerShell/PSReadLine#1556]
Last 200 Keys:
 l i b : j d w p = t r a n s p o r t = d t _ s o c k e t , s e r v e r = n , s u s p e n d = y , a d d r e s s = l o c a l h o s t : 5 8 7 6 8 ' Space ' - D f i l e . en 
 c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s \ u s e r 1 \ A p p D a t a \ L o c a l \ T e m p \ v s c o d e s w s _ f 8 a a 8 \ j d t _ w s \ j d t . l s - j a v a - p r o j e c t \ b i n ' Space ' Q S t a c k T e s t ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the 
console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor) 
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
