### ISSUE TITLE
Bug (System.ArgumentOutOfRangeException) when trying to enter git commit message

### ISSUE THREAD

**Issue by dsaavedr** [PowerShell/PSReadLine#1563]
It always appears the first time adding the quotations. After error message appears, command runs normally.

Last 200 Keys:
 s t Space . Enter
 g s Space Backspace Backspace Space s Enter
 g Space c m Space Backspace Backspace Backspace a d d Space c s Tab Enter
 g Space c m Space - m Backspace Backspace - m Space " g l Backspace Backspace Backspace g Space s Enter
 g Space a d d Space Backspace Backspace Backspace Backspace c m Space - a Space - m Space " g Space s Enter
 g Space c o n f i g Enter
 g Space c o n f i g Space - l Enter
 ` c l s s Enter
 g Space s Enter
 g Space s Enter
 g Space a d d Space . Enter
 g Space c m Space - m Space " g Space c m Space - m Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace g Space s Enter
 g Space c m Space - Backspace Backspace Backspace Backspace Backspace Enter
 g Space Backspace Backspace c l s s Enter
 g Space s Enter
 g Space c m Space - m Backspace Backspace a Backspace Backspace Backspace Backspace a d d Space . Enter
 g Space c m Space - m Space "

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
