### ISSUE TITLE
bug in running java program

### ISSUE THREAD

**Issue by harshvinayak0809** [PowerShell/PSReadLine#1567]
Last 200 Keys:
 a v a c Space S t r i n g B u i l d e r D e m o . j a v a Space } Space ; Space i f Space ( $ ? ) Space { Space j a v a Space S t r i n g B u i l d e r D e m o Space } Enter
 c d Space " c : \ U s e r s \ H A R S H Space V I N A Y A K \ D e s k t o p \ v s c o d e \ j a v a \ c o m \ " Space ; Space i f Space ( $ ? ) Space { Space j a v a c Space S t r i n g B u i l d e r D e m o . j a v a Space } Space ; Space i f Space ( $ ? ) Space { Space j a v a Space S t r i n g B u i l d e r D e m o Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.        
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)      
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
