### ISSUE TITLE
Problem with python scrapping website using requests and bs4

### ISSUE THREAD

**Issue by gazananda** [PowerShell/PSReadLine#1571]
Last 200 Keys:
 P y t h o n / m a i l s Space f o r Space c o l l e g e / f o r Space c o l l e g e / e x t r a c t n a m e s . p y " Enter
 & Space " C : / P r o g r a m Space F i l e s Space ( x 8 6 ) / P y t h o n 3 8 - 3 2 / p y t h o n . e x e " Space e : / P y t h o n / c h e c k / s c r a p e 2 . p y Enter
 & Space " C : / P r o g r a m Space F i l e s Space ( x 8 6 ) / P y t h o n 3 8 - 3 2 / p y t h o n . e x e " Space " e : / P y t h o n / m a i l s Space f o

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 10.
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
