### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by PaddyMack** [PowerShell/PSReadLine#1573]
PS HKU:\S-1-5-21-4080282891-2210617260-1132012767-1001\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer\Run\> Get-ItemProperty .

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 i d e r Space R e g i s t r y Space - R o o t Space H K E Y _ U S E R S Enter
 Ctrl+v Enter
 $ A g e n t S I U D Space = Space ( G e t - L o c a l U s e r Space - N a m e Space a g e n t ) . s i d . v a l u e Home Ctrl+RightArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Enter
 $ a g e n t Tab Enter
 d i o r Backspace Backspace i r Backspace Backspace r Enter
 c d Space $ a g e n t s Tab Enter
 c d Ctrl+Alt+| Enter
 Ctrl+c c d . . Enter
 UpArrow UpArrow \ s Tab m i Tab w i n Tab c u Tab p o Tab e Tab r Tab Enter
 d i r Enter
 g e t - i t e m p Tab Space . Ctrl+Alt+| UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow UpArrow UpArrow DownArrow DownArrow DownArrow Enter
 g e t - i t e m p Tab Space . Ctrl+Alt+|

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
