### ISSUE TITLE
Bug when editing multiline statements

### ISSUE THREAD

**Issue by viniciusvillas** [PowerShell/PSReadLine#1584]
As requested by the software itself, here are the details. It happened when editing a multiline statement (~35 lines). The editor behavior for multiline statements was messy before this (the scrollbar went crazy going up and down).
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
 e s t T i m e s t a m p ] ) Space = Space c a l . [ Y e a r ] Enter
 G R O U P Space B Y Space c a l . [ M o n t h ] , Space c a l . [ Y e a r ] Enter
 O R D E R Space B Y Space [ Y e a r ] , Space [ M o n t h ] ; Enter
 ' Enter
 W H E R E Space Q u e r y N a m e Space = Space ' 3 - M o n t h Space R e q u e s t Space C o u n t Space A v e r a g e ' Shift+Home Shift+UpArrow Shift+UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 " @ ; LeftArrow ) Ctrl+Home

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -11.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.1 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
