### ISSUE TITLE
Exception: System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.  

### ISSUE THREAD

**Issue by dupinderdhiman** [PowerShell/PSReadLine#1609]
-----------------------------------------------------------------------
Last 193 Keys:
 Space & Space ' c : \ U s e r s \ D u p i n d e r D h i m a n \ . v s c o d e \ e x t e n s i o n s \ v s c j a v a . v s c o d e - j a v a - d e b u g - 0 . 2 6 . 0 \ s c r i p t s \ l a u n c h e r . b a t ' Space ' E : \ O p e n _ J D K \ o p e n j d k - 1 1 . 0 . 2 _ w i n d o w s - x 6 4 _ b i n \ j d k - 1 1 . 0 . 2 \ b i n \ j a v a . e x e ' Space ' - a g e n t l i b : j d w p = t r a n s p

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.        
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
