### ISSUE TITLE
Dynamic Distribution Group in Bulk - powershell 

### ISSUE THREAD

**Issue by brunoalbuquerque91** [PowerShell/PSReadLine#1612]
Last 200 Keys:
 Space I t Space i s Space " b a d Space f o r m " Space t o Space w r i t e Space o u t p u t Space u n l e s s Space e n t i r e 
l y Space n e c e s s a r y Enter
 Space Space Space Space W r i t e - O u t p u t Space " $ N a m e , Space $ A l i a s , Space $ P r i m a r y S m t p A d d r e s 
s , Space $ I n c l u d e d R e c i p i e n t s , Space $ C o n d i t i o n a l S t a t e O r P r o v i n c e , Space $ A c c e p t M e s s a g e s O n l y F r o m D L M e m b e r s " Space Enter
 Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -5.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
