### ISSUE TITLE
Cannot find module 'worker_threads' scrape-yt

### ISSUE THREAD

**Issue by Sanusihassan** [PowerShell/PSReadLine#1619]
I've installed scrape-yt and included the files as shown in the documentation [here](https://www.npmjs.com/package/scrape-yt).

when im running the script, i get this error:

```bash
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Sanusi\Desktop\Portfolio\save-tube-bad\node_modules\scrape-yt\dist\index.js:55:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
PS C:\Users\Sanusi\Desktop\Portfolio\save-tube-bad>
```

**Comment by vexx32** [comment]
This is not a PowerShell nor PSReadLine error.

I'd advise you take that one up with the maintainers of the appropriate project. Thanks! 🙂
