### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below.

### ISSUE THREAD

**Issue by 7-904-001-67-28** [PowerShell/PSReadLine#1627]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
### Environment
PSReadLine: 2.0.2
PowerShell: 2020.6.0
OS: Microsoft Windows 10.0.19041
Last 1 Keys
```
 DownArrow
```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 12.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken 
cancellationToken)
```<!--

Before submitting your bug report ...
- Please make sure you are able to reproduce the issue with the latest version of PSReadLine.
- Please check for duplicates. +1 the duplicate if you find one and add additional details if you have any.

The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
- You file an issue that has many duplicates;
- You file an issue completely blank in the body.

-->

## Environment

```none
[run the script below and paste the output here]
```

**Comment by daxian-dbw** [comment]
@7-904-001-67-28 Can you run the following script as instructed in the bug report template and paste the result? 
Also, what is the history item when you type `DownArrow` that caused the exception? Can you share the text of that history command?

```powershell
& {
    $hostName = $Host.Name
    if ($hostName -eq "ConsoleHost" -and (Get-Command Get-CimInstance -ErrorAction SilentlyContinue)) {
        $id = $PID
        $inWindowsTerminal = $false
        while ($true) {
            $p = Get-CimInstance -ClassName Win32_Process -Filter "ProcessId Like $id"
            if (!$p -or !$p.Name) { break }
            if ($p.Name -eq "WindowsTerminal.exe") { $inWindowsTerminal = $true; break }
            $id = $p.ParentProcessId
        }
        if ($inWindowsTerminal) { $hostName += " (Windows Terminal)" }
    }

    "`nPS version: $($PSVersionTable.PSVersion)"
    $m = Get-Module PSReadline
    $v = $m.Version; $pre = $m.PrivateData.PSData.Prerelease
    if ($pre) { $v = "$v-$pre" }
    "PSReadline version: $v"
    if ($IsLinux -or $IsMacOS) {
        "os: $(uname -a)"
    } else {
        "os: $((dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion)"
    }
    "PS file version: $($name = if ($PSVersionTable.PSEdition -eq "Core") { "pwsh.dll" } else { "powershell.exe" }; (dir $pshome\$name).VersionInfo.FileVersion)"
    "HostName: $hostName"
    "BufferWidth: $([console]::BufferWidth)"
    "BufferHeight: $([console]::BufferHeight)`n"
}
```

**Comment by daxian-dbw** [comment]
Also, the reported stack trace doesn't look right, `ForceRender()` is not called from `Initialize`.

```
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, Cancellati
```

Due to the lack of accurate information in this bug report, I will close it for now.
But you are welcome to fill out all the missing information from the bug report template and provide the text of that history command that caused the problem. Then we can reopen this bug.

**Comment by 7-904-001-67-28** [comment]
Я сделал ровно то, о чём меня попросила программа.  Разбираться в Вашей бредятине я не собираюсь, даже не мечтайте.
А будете так хамить, в следующий раз вообще ничего делать не стану, просто проигнорирую сообщение об ошибке.  Я за отладку денег не получаю и никому ничем не обязан.

**Comment by daxian-dbw** [comment]
I'm sorry that you feel that way. Just want to get the necessary information needed for investigation. The script is for gathering environment data, which is part of the bug template.

**Comment by 7-904-001-67-28** [comment]
Original at Russian
Я не отказываюсь помогать вам, но надрываться и лезть из кожи вон не собираюсь.  Сделайте процесс удобным и для меня тоже, а не только для вас.

Translation by computer
I do not refuse to help you, but I am not going to get over and out of my skin. Make the process convenient for me too, not just for you.
