### ISSUE TITLE
Getting this exception when running a simple beginners script that I ran several times prior. Was prompted to submit the below information to Github

### ISSUE THREAD

**Issue by johnnytriple3** [PowerShell/PSReadLine#1637]
Last 200 Keys:
 c o d e / P r a c t i c e / t e s t . p y Enter
 & Space " C : / P r o g r a m Space F i l e s / P y t h o n 3 8 / p y t h o n . e x e " Space c : / U s e r s / j o n a t / D e s k t o p / . v s c o d e / P r a c t i c e / t e s t . p y Enter
 & Space " C : / P r o g r a m Space F i l e s / P y t h o n 3 8 / p y t h o n . e x e " Space c : / U s e r s / j o n a t / D e s k t o p / . v s c o d e / P r a c t i c e / t e s t . p y Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -11.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
