### ISSUE TITLE
random error when run selected powershell command

### ISSUE THREAD

**Issue by smartpcr** [PowerShell/PSReadLine#1651]
## Environment

```none
[run the script below and paste the output here]
```

the script throws error at:
```
$v = $m.Version; $pre = $m.PrivateData.PSData.Prerelease
```
```
ParentContainsErrorRecordException: The property 'PSData' cannot be found on this object. Verify that the property exists.
```
### Environment
PSReadLine: 2.0.2
PowerShell: 2020.6.0
OS: Microsoft Windows 10.0.19635
Last 0 Keys
```

```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')Actual value was 11.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.CalculateWhereAndWhatToRender(Boolean cursorMovedToInitialPos, RenderData renderData, LineInfoForRendering& lineInfoForRendering)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by daxian-dbw** [comment]
@smartpcr Thanks for the issue report.
Did you run the env-data-collecting script in the strict mode (called `Set-StrictMode -Version xxx` before running the script)? That error should not happen when the strict mode is off. Can you please turn off the strict mode and try again?

Also, can you please share the command line that caused the exception? If you were looping through history commands using `UpArrow` or `DownArrow`, it would be great if you can share the command line text of the particular history item that caused the exception. Thank you in advance!
