### ISSUE TITLE
Issue on full screen 

### ISSUE THREAD

**Issue by imohitarora** [PowerShell/PSReadLine#1661]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 94 Keys:
 l s Enter
 c l e a r Enter
 p w d Enter
 c l e a r Enter
 g i t Space c l o n e Space Ctrl+v Enter
 c d Space h a Tab Enter
 l s Enter
 c l e a r Enter
 l s Enter
 n Backspace Backspace m v n Space o Backspace i n s t a ; ; Backspace Backspace l l Enter
 c l e a r Enter
 l s Enter
 e x i t Backspace Backspace Backspace Backspace Backspace ` UpArrow UpArrow Enter
 Enter

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions.
