### ISSUE TITLE
Reporting error

### ISSUE THREAD

**Issue by OI-nikhilkenvetil** [PowerShell/PSReadLine#1667]
I've been asked to report this error. I don't know what this means TBH.

### Environment
PSReadLine: 2.0.2
PowerShell: 2020.6.0
OS: Microsoft Windows 10.0.18362
Last 0 Keys
```

```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 6.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)

**Comment by daxian-dbw** [comment]
@OI-nikhilkenvetil Thanks for reporting this issue.

Where did you run into this issue? VS Code terminal?
Can you please run the following script in the same terminal where you ran into the issue and paste the result here? This script collects the environment data such as the host you are using, the windows/buffer size of your terminal. Thanks!

```powershell
& {
    Set-StrictMode -Off
    $hostName = $Host.Name
    if ($hostName -eq "ConsoleHost" -and (Get-Command Get-CimInstance -ErrorAction SilentlyContinue)) {
        $id = $PID
        $inWindowsTerminal = $false
        while ($true) {
            $p = Get-CimInstance -ClassName Win32_Process -Filter "ProcessId Like $id"
            if (!$p -or !$p.Name) { break }
            if ($p.Name -eq "WindowsTerminal.exe") { $inWindowsTerminal = $true; break }
            $id = $p.ParentProcessId
        }
        if ($inWindowsTerminal) { $hostName += " (Windows Terminal)" }
    }

    "`nPS version: $($PSVersionTable.PSVersion)"
    $m = Get-Module PSReadline
    $v = $m.Version; $pre = $m.PrivateData.PSData.Prerelease
    if ($pre) { $v = "$v-$pre" }
    "PSReadline version: $v"
    if ($IsLinux -or $IsMacOS) {
        "os: $(uname -a)"
    } else {
        "os: $((dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion)"
    }
    "PS file version: $($name = if ($PSVersionTable.PSEdition -eq "Core") { "pwsh.dll" } else { "powershell.exe" }; (dir $pshome\$name).VersionInfo.FileVersion)"
    "HostName: $hostName"
    "BufferWidth: $([console]::BufferWidth)"
    "BufferHeight: $([console]::BufferHeight)`n"
}
```

**Comment by daxian-dbw** [comment]
Also, do you still remember what you typed in the terminal that caused this exception? A repro would be extremely useful for us to investigate.

**Comment by OI-nikhilkenvetil** [comment]
Damn.. Sorry I missed this. I guess it's too late now. If it happens again, I'd open a new one.
