### ISSUE TITLE
issues with exercise 03_05_begin

### ISSUE THREAD

**Issue by lwatson8** [PowerShell/PSReadLine#1678]
Last 184 Keys:
 & Space C : / U s e r s / l w a t s o n 8 / A p p D a t a / L o c a l / P r o g r a m s / P y t 
h o n / P y t h o n 3 8 - 3 2 / p y t h o n . e x e Space " c : / U s e r s / l w a t s o n 8 / D e s k t o p / E x _ F i l e s _ P r o g r a m m i n g _ F o u n d a t i o n s _ F u n d a m e n 
t a l s / E x e r c i s e Space F i l e s / C h a p 0 3 / 0 3 _ 0 5 _ b e g i n . p y " Enter    

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by vexx32** [comment]
See: https://github.com/PowerShell/PSReadLine/issues/1306

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.2 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
