### ISSUE TITLE
bug with function

### ISSUE THREAD

**Issue by SilverDiligent** [PowerShell/PSReadLine#1681]
Last 200 Keys:
 S S e s s i o n Space - C o n f i g u r a t i o n N a m e Space M i c r o s o f t . E x c h a n g e Space - C o n n e c t i o n U r i Space h t t p : / / server.FQDN.com/ P o w e r S h e l l / Space - A u t h e n t i c a t i o n Space K e r b e r o s Space - C r e d e n t i a l Space $ c r e d sEnter
 Space Space Space Space I m p o r t - P S S e s s i o n Space - S e s s i o n Space $ s Enter
 Enter
 } Space # F u n c t i o n Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 33.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.3 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
