### ISSUE TITLE
Borked clone of https://github.com/paulirotta/Quicksilver.git

### ISSUE THREAD

**Issue by paulirotta** [PowerShell/PSReadLine#1685]
Windows 10-64bit, Intel i7, all updates, latest Git installed and re-installed

Can not clone a git repo

The problem appeared within a day of applying Windows Feature update, 2004

I have until recently not had trouble with this repo (but was using an older fork)

-------------- example 1 ------------- (include the library master branch as a Rust dependency using https:// ..)
error: failed to get `quicksilver` as a dependency of package `vibration-explorer v0.1.0 (C:\Users\pauli\github\vibration-explorer)`
Caused by:
  failed to load source for dependency `quicksilver`
Caused by:
  Unable to update https://github.com/paulirotta/quicksilver.git?branch=master
Caused by:
  cannot checkout to invalid path 'Quicksilver/Resources/wildcard.*'; class=Checkout (20)
PS C:\Users\pauli\github\vibration-explorer>

---------------- example 2 ----------------- (clone the repo in Powershell using git@ )

PS C:\Users\pauli\github> git clone git@github.com:ryanisaacg/quicksilver.git
Cloning into 'quicksilver'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 5280 (delta 3), reused 3 (delta 0), pack-reused 5270
Receiving objects: 100% (5280/5280), 9.96 MiB | 105.00 KiB/s, done.
Resolving deltas: 100% (3780/3780), done.
PS C:\Users\pauli\github>

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 80 Keys:
 ` ` c d Space g i t Tab v i Tab Enter
 c a r g o Space u p d a t e Enter
 ` v f Space . . Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c d Space . . Enter
 ` l s Enter
 m v Space q u Tab Space q u Tab Backspace 2 Enter
 g i t Space c l o n e Space Ctrl+v Enter
 ` Enter

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by paulirotta** [comment]
These seems to have been some odd temporary problem with github that eventually was sorted on that end.

It was giving a capital "Quicksilver" in the repository URL but is not (properly?) using "quicksilver". Local attempts at non-capitalized clone did not work either at that time, but now it just kind of works. .net world..
