### ISSUE TITLE
Bug in VSCode while bebugging c++ file

### ISSUE THREAD

**Issue by RashimNarayanTiku** [PowerShell/PSReadLine#1711]
Last 200 Keys:
 i c r o s o f t - M I E n g i n e - E r r o r - x u i s k p u k . f q a ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - n 4 b k f g r b . v q z ' Space ' - - d b g E x e = C : \ P r o g r a m Space F i l e s Space ( x 8 6 ) \ m i n g w - w 6 4 \ i 6 8 6 - 8 . 1 . 0 - w i n 3 2 - d w a r f - r t _ v 6 - r e v 0 \ m i n g w 3 2 \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()   
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)  
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()     
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
