### ISSUE TITLE
Bugs that I found when using the Powershell terminal from VS Code.

### ISSUE THREAD

**Issue by Iamanowner** [PowerShell/PSReadLine#1717]
-
Last 125 Keys:
 & Space D : / P y t h o n / P y t h o n 3 8 / p y t h o n . e x e Space " d : / M y Space t h i n g s / P y t h o n / C M D . p y " Enter  
 & Space D : / P y t h o n / P y t h o n 3 8 / p y t h o n . e x e Space " d : / M y Space t h i n g s / P y t h o n / m a g i c 8 . p y " Enter

Exception:
equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was 80.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Comment by economyshutdown** [comment]
thx.
