### ISSUE TITLE
Ryntime error (Py)

### ISSUE THREAD

**Issue by CanadianLegend** [PowerShell/PSReadLine#1723]
Last 11 Keys:
 & Space C : / U s e r s /

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to 
zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object 
arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, 
Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------        
PS C:\Users\ehabj\Desktop\Dev Stuff\Learner Project Full\Python Learning Stuff> ehabj/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/ehabj/Desktop/Dev Stuff/Learner Project Full/Python Learning Stuff/Start.py"
ehabj/AppData/Local/Programs/Python/Python38-32/python.exe : The term 
'ehabj/AppData/Local/Programs/Python/Python38-32/python.exe' is not 
recognized as the name of a cmdlet, function, script file, or operable         
program. Check the spelling of the name, or if a path was included, verify     
that the path is correct and try again.
At line:1 char:1
+ ehabj/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/ ...    
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ehabj/AppData/L...8-32/python. 
   exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by CanadianLegend** [comment]
This issue occurs whenever I attempt to import from one py file to another. Simply using the `from (file) import (class)` - or any variant manages to generate this error & fails to print as desired. I can verify it is not an issue with code as this came code executes without issue in another IDE. I have attempted a reinstall and this has not resolved the issue.

**Comment by CanadianLegend** [comment]
Upgrading Py seems to have resolved the issue - as such, I will close this issue.
