### ISSUE TITLE
$host.Name -eq 'ConsoleHost'  AND System.IO.IOException: The handle is invalid. with NSClient++

### ISSUE THREAD

**Issue by tabacha** [PowerShell/PSReadLine#1734]
## Environment

```PS version: 5.1.14409.1018
PSReadline version: 1.2
os: 6.3.9600.16384 (winblue_rtm.130821-1623)
PS file version: 10.0.14409.1005 (rs1_srvoob.161208-1155)
HostName: ConsoleHost
The handle is invalid.
At C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1:36 char:18
+ "BufferWidth: $([console]::BufferWidth)"
+ ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : OperationStopped: (:) [], IOException
+ FullyQualifiedErrorId : System.IO.IOException

BufferWidth:
The handle is invalid.
At C:\Windows\System32\WindowsPowerShell\v1.0\profile.ps1:37 char:19
+ "BufferHeight: $([console]::BufferHeight)`n"
+ ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : OperationStopped: (:) [], IOException
+ FullyQualifiedErrorId : System.IO.IOException

BufferHeight: 
```

## Exception report

```
Oops, something went wrong. Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.IO.IOException: The handle is invalid.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
at Microsoft.PowerShell.Internal.ConhostConsole.get_CursorLeft()
at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

## Steps to reproduce

We use Nagios Windows NSClient++ for monitoring. All are deployed the same, on the most machines everything looks okay, but on some machines (10-20%) we got the stack trace above when we call a powerShell Script via NSclient++ (not on console)

Our Powershell profile ( C:\Windows\System32\WindowsPowerShell\v1.0\Profile.ps1) looks like this:

```
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol,[Net.SecurityProtocolType]::Tls12

try {
if ($host.Name -eq 'ConsoleHost') {
	Set-PSReadlineKeyHandler -Key Tab -Function Complete
}
}
catch {
	Write-Host "Fehler beim laden von PSReadLineKeyHandler"
}
```
and this is the place where psReadLine is called. It does not matter what powershell script we start wir nsclient++

The Environment (above) was called with nsclient++. On an intractive session it looks like this: 
```
PS version: 5.1.14409.1018
PSReadline version: 1.2
os: 6.3.9600.16384 (winblue_rtm.130821-1623)
PS file version: 10.0.14409.1005 (rs1_srvoob.161208-1155)
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 3000
```

## Expected behavior

No Stack-Trace, No Output

## Actual behavior

Stack-Trace

**Comment by iSazonov** [comment]
You have no need to load PSRL and profile in the scenario - you should run Windows PowerShell with NoInteractive and NoProfile parameters.

**Comment by tabacha** [comment]
> You have no need to load PSRL and profile in the scenario - you should run Windows PowerShell with NoInteractive and NoProfile parameters.

Yes, this works
