### ISSUE TITLE
SetWindowPosition WinIOError

### ISSUE THREAD

**Issue by jeffythedragonslayer** [PowerShell/PSReadLine#1738]
Got this stacktrace shortly after maximizing the powershell window and increasing the font size, then continuing typing:

```
-----------------------------------------------------------------------
Last 200 Keys:
 Enter
 l s Enter
 d i r Enter
 X c p y Space Backspace Backspace Backspace o p y Space S t e a m Tab Space S t e a m Tab Backspace - c a f e o l d Space / H Backspace E Space / H Enter
 c d Space S Backspace c a f Tab Tab Tab Ctrl+c c d Space S t e a Tab Tab Enter
 Ctrl+l d i r Enter
 g i t Space s t a t u s Enter
 g i t Space l o g Enter
 ` g i t Space s t a t u s Backspace Backspace Backspace Backspace Backspace Backspace c h e c k o u t Space 4 f 7 0 3 f 5 2 e 3 c b 0 3 6 0 4 8 c b 3 7 7 1 6 7 f 1 0 0 0 a 3 b 3 5 f 8 8 c Enter
 c d Space . . Enter
 c d Space S t e Tab Enter
 d i r Enter
 Ctrl+l g i t Space s t a t u s Enter
 Ctrl+l g i t Space Ctrl+l

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by vexx32** [comment]
Can you verify which PSReadLine version you're using, and give an update a try if you're not currently on the latest?

**Comment by jeffythedragonslayer** [comment]
Is that found in the $PSVersionTable?

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by vexx32** [comment]
No, you'll need to check the module version and whether it's prerelease or not. Something like this?

```ps1
 gmo psreadline | select name, version, @{n="PreRelease";e={$_.PrivateData.PSData.Prerelease}}
```

**Comment by jeffythedragonslayer** [comment]
Yup:

```
Name       Version PreRelease
----       ------- ----------
PSReadline 2.0.0   beta2
```

**Comment by vexx32** [comment]
Yeah, that's a fairly old version. Definitely worth upgrading with either `Update-Module PSReadLine` or (if that doesn't work) you can also use `Install-Module PSReadLine -Force`

Quite a few of these issues were fixed already, so it's possible you just need to upgrade. 🙂

**Comment by jeffythedragonslayer** [comment]
`Install-Module PSReadLine -Force` completed, but only in a powershell launched with admin privileges.
