### ISSUE TITLE
Ctrl+Space

### ISSUE THREAD

**Issue by GSysAdmin** [PowerShell/PSReadLine#1748]
Last 200 Keys:
 l e Space M i c r o s o f t . G r a p h . I n t u n e Space - Ctrl+Space DownArrow UpArrow RightArrow DownArrow LeftArrow Enter
 Space G e t Enter
 G e t - D e v i c e M a n a g e m e n t S c r i p t s Enter
 Enter
 Enter
 UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+Space - - Ctrl+Space DownArrow DownArrow Enter
 Space * ' Backspace * LeftArrow S c r i p t s Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace s Enter
 UpArrow Backspace LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Enter
 G e t - D e v i c e M a n a g e m e n t S c r i p t s Enter
 UpArrow Tab Backspace Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Tab Tab Tab Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+Space Backspace t Ctrl+Space

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -10.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

Using this https://github.com/microsoft/Intune-PowerShell-SDK
Have imported Module -Name Microsoft.Graph.Intune
And this module https://github.com/Microsoft/Intune-PowerShell-SDK/releases

**Comment by GSysAdmin** [comment]
Using this https://github.com/microsoft/Intune-PowerShell-SDK
Have imported Module -Name Microsoft.Graph.Intune
And this module https://github.com/Microsoft/Intune-PowerShell-SDK/releases

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
