### ISSUE TITLE
Issue Occured while using Python with VSCode with powershell as default terminal

### ISSUE THREAD

**Issue by udistructor** [PowerShell/PSReadLine#1766]
-----------------------------------------------------------------------
Last 200 Keys:
 t h o n \ P y t h o n 3 8 \ p y t h o n . e x e ' Space ' c : \ U s e r s \ u n i v e \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 2 0 . 8 . 1 0 3 6 0 4 \ p y t h o n F i l e s \ l i b \ p y 
t h o n \ d e b u g p y \ l a u n c h e r ' Space ' 5 0 2 0 2 ' Space ' - - ' Space ' e : \ P r o j e c t s \ D a t a S c i e n c e Space P r o j e c t s \ C o d e E x e c \ e x e q t . p y ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
