### ISSUE TITLE
Vscode error

### ISSUE THREAD

**Issue by Yoplayer-1** [PowerShell/PSReadLine#1767]
Hi I found an error it gave a link so I clicked it and I found this page 

The code I entered (Python)
from math import*
print(10 + 10)

The error : 
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights 
reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\-------\Desktop\NOTEPAD ++\PYTHON>
Oops, something went wrong.  Please report this 
bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 &

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.  
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\-------\Desktop\NOTEPAD ++\PYTHON>  C:/Users/YOPLAYER1/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/YOPLAYER1/Desktop/NOTEPAD ++/PYTHON/Project.py"
20
PS C:\Users\-------\Desktop\NOTEPAD ++\PYTHON>

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
