### ISSUE TITLE
error while compiling c++ code using vscode, terminal is set to powershell

### ISSUE THREAD

**Issue by Nick-infinity** [PowerShell/PSReadLine#1768]
Last 200 Keys:
 F i l e . c p p Space - o Space t e m p C o d e R u n n e r F i l e Space } Space ; Space i f Space ( $ ? ) Space { Space . \ t e m p C o d e R u n n e r F i l e Space } Enter        
 c d Space " c : \ U s e r s \ N i k h i l Space G u p t a \ D o c u m e n t s \ V S C o d e \ c p p \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space m a x _ d e p t h _ r e c . c p p Space - o Space m a x _ d e p t h _ r e c Space } Space ; Space i f Space ( $ ? ) Space { Space . \ m a x _ d e p t h _ r e c Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value 
must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 
dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by Nick-infinity** [comment]
**vs code info**

Version: 1.48.1 (user setup)
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:12:13.244Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Nick-infinity** [comment]
solution is here #1306 
Update PSReadline Module
