### ISSUE TITLE
VS Code error when running Python Code

### ISSUE THREAD

**Issue by Rv607x** [PowerShell/PSReadLine#1769]
Last 200 Keys:
 : / P y t h o n / p y t h o n . e x e Space " c : / U s e r s / J r o b a h ' s Space C o v e / D e s k t o p / c e l l o . p y " Enter
 & Space C : / P y t h o n / p y t h o n . e x e Space " c : / U s e r s / J r o b a h ' s Space C o v e / D e s k t o p / c e l l o . p y " Enter   
 3 _ d i g i t s & Space C : / P y t h o n / p y t h o n . e x e Space " c : / U s e r s / J r o b a h ' s Space C o v e / D e s k t o p / c e l l o 
. p y " Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.       
Actual value was 30.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)     
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\Jrobah's Cove> 3_digits& C:/Python/python.exe "c:/Users/Jrobah's Cove/Desktop/cello.py"
At line:1 char:9
+ 3_digits& C:/Python/python.exe "c:/Users/Jrobah's Cove/Desktop/cello. ...
+         ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it  
as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
