### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#1774]
Oops, something went wrong.  Please report this bug 
with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 0 C _ 2 . c p p Space - o Space 1 4 0 0 C _ 2 Space } Space ; Space i f Space ( $ ? ) Space { Space . \ 1 4 0 0 C _ 2 Space } Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 Enter
 c d Space " c : \ U s e r s \ S H A S H A N K Space M I S H R A \ D e s k t o p \ c + + \ c o d e f o r e c e s \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space 1 4 0 0 C _ 2 . c p p Space - o Space 1 4 0 0 C _ 2 Space } Space ; Space i f Space ( $ ? ) Space { Space . \ 1 4 0 0 C _ 2 Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)   
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\SHASHANK MISHRA\Desktop\c++\codeforeces>

**Comment by vexx32** [comment]
See #1306 🙂

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
