### ISSUE TITLE
Oops, something went wrong.

### ISSUE THREAD

**Issue by williamgriffiths** [PowerShell/PSReadLine#1779]
Last 200 Keys:
 T o D e c i m a l . j a v a Space } Space ; Space i f Space ( $ ? ) Space { Space j a v a Space O c t a l T o D e c i m a l Space } Enter      
 c d Space " c : \ U s e r s \ w g r i f \ D e s k t o p \ 1 5 0 Space B a s i c Space J a v a Space E x e r c i s e s \ 2 5 . Space O c t a l Space t o Space D e c i m a l \ " Space ; Space i f Space ( $ ? ) Space { Space j a v a c Space O c t a l T o D e c i m a l . j a v a Space } Space ; Space i f Space ( $ ? ) Space { Space j a v a Space O c t a l T o D e c i m a l Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.  
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, 
Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

=========================================================
Code:

import java.util.Scanner;

class OctalToDecimal {
    
    public static void main(String[] args) {
        
        Scanner s = new Scanner(System.in);
        System.out.print("Enter octal number: ");
        int i = s.nextInt();
        s.close();
        System.out.println("Decimal: " + Integer.parseInt(Integer.toString(i),8));

    }

}

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
