### ISSUE TITLE
visual studio does not run how can i fix it?

### ISSUE THREAD

**Issue by Bjarmi99** [PowerShell/PSReadLine#1790]
Last 200 Keys:
 h o n Ctrl+Alt+\ P y t h o n 3 8 - 3 2 Ctrl+Alt+\ p y t h o n . e x e ' Space ' c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ L e n o v o Ctrl+Alt+\ . v s c o d e Ctrl+Alt+\ e x t e n s i o n s Ctrl+Alt+\ m s - p y t h o n . p y t h o n - 2 0 2 0 . 8 . 1 0 5 3 6 9 Ctrl+Alt+\ p y t h o n F i l e s Ctrl+Alt+\ l i b Ctrl+Alt+\ p y t h o n Ctrl+Alt+\ d e b u g p y Ctrl+Alt+\ l a u n c h e r ' Space ' 6 1 6 7 6 ' Space ' - - ' Space ' c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ L e n o v o Ctrl+Alt+\ D 
o c u m e n t s Ctrl+Alt+\ P y t h o n Ctrl+Alt+\ c a r _ r e n t a l . p y ' Space Enter
 Space

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -19.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
