### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by BryanZambranoAroca** [PowerShell/PSReadLine#1798]
Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de 
consola en dicha dimensión.
PS C:\Users\bryan\Music\ANPR-master\Licence_plate_recognition\USA_plates> & C:/Python38/python.exe c:/Users/bryan/Music/ANPR-master/Licence_plate_recognition/USA_plates/train.py
2020-09-10 09:49:03.547890: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-09-10 09:49:03.548324: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "c:/Users/bryan/Music/ANPR-master/Licence_plate_recognition/USA_plates/train.py", line 45, in <module>    
    ohe = OneHotEncoder(handle_unknown='ignore', categorical_features=None)
  File "C:\Python38\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'categorical_features'

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
