### ISSUE TITLE
System.IO.IOException: The parameter is incorrect

### ISSUE THREAD

**Issue by igaurab** [PowerShell/PSReadLine#1802]
Log: 

```
Last 56 Keys:
 Ctrl+l Ctrl+l l a s d Enter
 Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l l n v i m Enter
 n v i m Enter
 a s d Ctrl+l Ctrl+l Backspace Backspace Backspace d a s l Backspace Backspace Backspace Backspace l Backspace Ctrl+l Ctrl+l Ctrl+l Ctrl+l n v i m Enter
 a s d l ; Ctrl+l

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1315). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
