### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by seamecob** [PowerShell/PSReadLine#1803]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 x c e p t i o n M e s s a g e s ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s \ B o k a m o s o Space S e a m e c o \ A p p D a t a \ R o a m i n g \ C o d e \ U s e r \ w o r k s p a c e S t o r a g e \ c 7 0 e 7 a d 8 3 a b 6 a 4 e 7 d 2 7 5 3 b 9 b 5 b 3 9 c e b 0 \ r e d h a t . j a v a \ j d t _ w s \ n e w C o d e _ e 2 e b 7 4 f e \ b i n ' Space ' F l o w ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and 
less than the console's buffer size in that 
dimension.
Parameter name: top
Actual value was -10.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String 
defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)     
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
