### ISSUE TITLE
Getting this error every time I run/debug a java file in VS Code

### ISSUE THREAD

**Issue by Abir-Tx** [PowerShell/PSReadLine#1805]
Last 200 Keys:
 w C o d e D e t a i l s I n E x c e p t i o n M e s s a g e s ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s \ A b i r _ \ A p p D a t a \ R o a m i n g \ C o d e \ U s e r \ w o r k s p a c e S t o r a g e \ 8 f 3 6 8 5 4 9 d 8 4 1 a d 2 b 5 f f b c 3 c 4 9 a c 2 8 4 c b \ r e d h a t . j a v a \ j d t _ w s \ H A C C _ 2 1 f d d d d c \ b i n ' Space ' A p p 
' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

![image](https://user-images.githubusercontent.com/28858998/93009414-9dd96a80-f5a2-11ea-8828-efc1f1e22ff5.png)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Comment by Abir-Tx** [comment]
Thanks, I have fixed it. Thanks a lot
