### ISSUE TITLE
VSCode: System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by WilfSilver** [PowerShell/PSReadLine#1807]
Hi, I have just had this error while VSCode was trying to debug a program.
Powershell version: 5.1.18362.752
Windows Build: 18363.1082
Windows Version: 1909
This only happened once, I tried to debug again and it was fine.

Last 200 Keys:
 = C : \ S t r a w b e r r y \ c \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter
 Space & Space ' c : \ U s e r s \ X X X X X \ . v s c o d e \ e x t e n s i o n s \ m s - v s c o d e . c p p t o o l s - 0 . 3 0 . 0 - i n s i d e r s 5 \ d e b u g A d a p t e r s \ b i n \ W i n d o w s D e b u g L a u n c h e r . e x e ' Space ' - - s t d i n = M i c r o s o f t - M I E n g i n e - I n - r

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 98.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable\`1 key, Object arg)   
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary\`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
