### ISSUE TITLE
Something went wrong after using "."

### ISSUE THREAD

**Issue by tester346** [PowerShell/PSReadLine#1811]
Hi!

I opened PowerShell from shift+right click inside folder menu on Windows 10 - 2004 v19041.508

Used button "."

and it happened

	Oops, something went wrong.  Please report this bug with the details below.
	Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
	-----------------------------------------------------------------------
	Last 1 Keys:
	 .

	Exception:
	System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console buffer size in this dimension.
	Parameter name: left
	Real value is -1.
	   at System.Console.SetCursorPosition(Int32 left, Int32 top)
	   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
	   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
	   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
	   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
	   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
	   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
	   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
	   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
	-----------------------------------------------------------------------
	PS _PATH_> $PSVersionTable.PSVersion

	Major  Minor  Build  Revision
	-----  -----  -----  --------
	5      1      19041  1

The path where I opened PowerShell instance is 120~ character long.

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
