### ISSUE TITLE
Last 200 Keys

### ISSUE THREAD

**Issue by FirowMD** [PowerShell/PSReadLine#1813]
-----------------------------------------------------------------------
Last 200 Keys:
 o t e c t o r Space v i c t i m . c Space - o Space v i c t i m . e x e Enter
 c l e a r Enter
 g d b Space - q Space e x p l o t i Backspace Backspace i t . e x e Enter
 c l e s Backspace Backspace s Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace . \ e x o Backspace p l o Tab Backspace Backspace . e x e Space v i c t i m . e x e Enter
 Enter
 UpArrow UpArrow UpArrow DownArrow UpArrow Backspace Backspace Backspace Backspace c l s Enter
 . \ e x p l o i t . e x e Space Backspace c Backspace Space v i c t i m . e x e Enter
 Enter
 UpArrow Enter
 g Backspace Backspace Backspace UpArrow Enter
 UpArrow Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
