### ISSUE TITLE
Bug in python

### ISSUE THREAD

**Issue by hanifk-ai** [PowerShell/PSReadLine#1816]
Last 200 Keys:
 p y t h o n Space t e s t . p y Enter
 c l e a r Enter
 & Space " C : / U s e r s / H a n i f Space K a m i l . D E S K T O P 
- P I S 7 G 8 D / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o n 3 8 - 3 2 / p y t h o n . e x e " Space " c : / U s 
e r s / H a n i f Space K a m i l . D E S K T O P - P I S 7 G 8 D / D o c u m e n t s / T u t o r i a l Space P y t h o n / 0 0 - T e m p l a 
t e / M a i n . p y " Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
