### ISSUE TITLE
Terminal error Visual studio code

### ISSUE THREAD

**Issue by Matts-Training-Hub** [PowerShell/PSReadLine#1820]
Oops, something went wrong.  Please report this bug with the details below.  
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------      
Last 164 Keys:
 & Space C : / U s e r s / M a t t / A p p D a t a / L o c a l / P r o g r a 
m s / P y t h o n / P y t h o n 3 8 - 3 2 / p y t h o n . e x e Space " c : / U s e r s / M a t t / O n e D r i v e Space - Space U n i v e r s i t y Space o f Space S o u t h a m p t o n / M i c r o s o f t Space L e a r n Space P y t h o n / f o r m a t _ e x e r c i s e . p y " Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
