### ISSUE TITLE
I am trying to convert ubuntu wsl1 version to wsl2 this error is found

### ISSUE THREAD

**Issue by hanzlahabib** [PowerShell/PSReadLine#1823]
Last 173 Keys:
 w s l Space - l Space - v Enter
 w s l Space - - s e t - d e f a u l t - v e r s i o n Space 2 Enter
 Ctrl+j Ctrl+x Enter
 UpArrow Enter
 UpArrow Enter
 w s l Space - v Space - l Enter
 w s l Space - l Space - v Enter
 UpArrow UpArrow UpArrow Enter
 w s l . e x e Space - - s e t - v e r s i o n Space U b u n t u Space 2 Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow RightArrow = Backspace * Enter
 UpArrow LeftArrow LeftArrow Backspace - 2 0 - Backspace . 0 4 Enter
 Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -16.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.InsertLineAbove(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
