### ISSUE TITLE
make monitor issue

### ISSUE THREAD

**Issue by mererose-sc** [PowerShell/PSReadLine#1827]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 1 \ e s p - i d f \ t o o l s \ i d f . p y Space - p Space C O M 3 Space m o n i t o r Enter
 s e t Space I D F _ P A T H = d : \ S m a r t C l e a n 1 \ e s p - i d f Enter
 C : \ U s e r s \ m e r e r \ . e s p r e s s i f \ p y t h o n _ e n v \ i d f 4 . 0 _ p y 3 . 8 _ e n v \ S c r i p t s \ p y t h o n . e x e Space d : \ S m a r t C l e a n 1 \ e s p - i d f 
\ t o o l s \ i d f . p y Space - p Space C O M 3 Space m o n i t o r Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 33.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
