### ISSUE TITLE
Failed to install IPyKernel extension on Visual Studio

### ISSUE THREAD

**Issue by DebmalyaDas1841111** [PowerShell/PSReadLine#1834]
Last 200 Keys:
 / U s e r s / D e b m a l y a Space D a s / . v s c o d e / e x t e n s i o n s / m s - p y t h o n . p y t h o n - 2 0 2 0 . 9 . 1 1 1 4 0 7 / p y t h o n F i l e s / p y v s c - r u n - i s o l a t e d . p y " Space p i p Space i n s t a l l Space - U Space i p y k e r n e l Space - - u s e r Space C : / U s e r s / D E B M A L ~ 1 / A p p D a t a / L o c a l / T e m p / t m p - 1 5 0 6 0 b d R 1 b Z g h U Q y c . l o g Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object 
arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
