### ISSUE TITLE
VS Code told me to inform Github of my problem..

### ISSUE THREAD

**Issue by Glass69** [PowerShell/PSReadLine#1838]
I am following a python turtorial on youtube where we create a module to read emails from my inbox.
I have also recently (yesterday and today) installed VS Code extensions 'C++' and 'Binary'. Maybe this could be the reason why my code is getting errors..??
The code and error are below:  

>>> import imaplib
>>> import email
>>> 
>>> host = 'imap@gmail.com'
>>> username = 'WebDevAK51@gmail.com'
>>> password = 'Dribbling'
>>>
>>> mail = imaplib.IMAP4_SSL(host)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\imaplib.py", line 1297, in __init__
    IMAP4.__init__(self, host, port)
PS C:\Python_Projects\30_Days_Of_Python\Day_9>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 22 Keys:
 c d Space D a y _ 9 Enter
 p y t h o n Enter
 Enter
 c l s Enter
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.  
Parameter name: top
Actual value was -11.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Python_Projects\30_Days_Of_Python\Day_9> import imaplib
>> import email
>>
>> host = 'imap@gmail.com'
>> username = 'WebDevAK51@gmail.com'
>> password = 'Dribbling'
>> 
>> mail = imaplib.IMAP4_SSL(host)
>> mail.login(username, password)
>> mail.select('inbox')
>>
>> _, search_data = mail.search(None, 'UNSEEN')

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
