### ISSUE TITLE
`MenuComplete` results in `ArgumentOutOfRangeException`

### ISSUE THREAD

**Issue by daxian-dbw** [PowerShell/PSReadLine#1851]
## Environment

```none
PS C:\Users\username\Desktop\7> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Exception report

```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 300.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.UpdateMenuSelection(Int32 selectedItem, Boolean select, Boolean showTooltips, String toolTipColor)
   at Microsoft.PowerShell.PSConsoleReadLine.MenuCompleteImpl(Menu menu, CommandCompletion completions)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.MenuComplete(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

prerequisites
server 2012 r2, RDP to the server, PS7 was copied to the desktop of the server as a standalone copy taken from a machine where it was previously installaed via downloaded installation.

The issue is reproduciable constantly. Steps:
type gci c:\ -(then type ctrl+space) and immediatelly the issue pops up as on the screenshot.

https://user-images.githubusercontent.com/29511875/94073525-4fc53200-fe00-11ea-9350-e0cee160dd1b.png
![image](https://user-images.githubusercontent.com/127450/95115500-6f126800-06fa-11eb-8849-b76224894388.png)

**Comment by daxian-dbw** [comment]
@antondubinkin Can you please confirm 2 things:
1. This issue happens on `server 2012 r2`, but not on your latest Windows 10 machine, right?
2. Does this issue also depends on the window/buffer size you are using? If so, can you please share the window/buffer size when you are able to reproduce the issue?
