### ISSUE TITLE
Exception when Pasting multiline ps cmd in Windows Terminal + Windows Powershell 

### ISSUE THREAD

**Issue by thakkar-vishal** [PowerShell/PSReadLine#1858]
Am running windows powershell in Windows Terminal (not pscore v6). When I paste a multiline (with tabs) ps cmd edited in notepad into the window, I get the following error. 

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------

Last 200 Keys:
 Tab t h u m b n a i l H a s h Space = Space $ _ . t h u m b n a i l H a s h ; Enter
 Tab Tab Tab t h u m b n a i l W i d t h Space = Space $ _ . t h u m b n a i l W i d t h ; Enter
 Tab Tab Tab t h u m b n a i l H e i g h t Space = Space $ _ . t h u m b n a i l H e i g h t ; Enter
 Tab Tab Tab m e d i a U r l Space = Space $ _ . m e d i a U r l ; Enter
 Tab Tab } Enter
 Tab Tab $ q Enter
 Tab } ; Enter
 Tab } Enter
 } Space | Space % Space { Space $ _ Space | Space C o n v e r t T o - J s o n Space - C o m p r e s s Space } Enter
 UpArrow UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
