### ISSUE TITLE
Exception after using Ctrl+C to cancel DigitArgument

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PSReadLine#188]
Repro:
a Alt+1 Ctrl+C
Stack:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at PSConsoleUtilities.PSConsoleReadLine.ConvertOffsetToCoordinates(Int32 offset) in PSReadLine\PSReadLine\Render.cs:line 517
   at PSConsoleUtilities.PSConsoleReadLine.PlaceCursor() in PSReadLine\PSReadLine\Render.cs:line 503
   at PSConsoleUtilities.PSConsoleReadLine.ReallyRender() in PSReadLine\PSReadLine\Render.cs:line 270
   at PSConsoleUtilities.PSConsoleReadLine.Render() in PSReadLine\PSReadLine\Render.cs:line 70
   at PSConsoleUtilities.PSConsoleReadLine.ClearStatusMessage(Boolean render) in PSReadLine\PSReadLine\Render.cs:line 53
   at PSConsoleUtilities.PSConsoleReadLine.DigitArgument(Nullable`1 key, Object arg) in PSReadLine\PSReadLine\ReadLine.cs:line 725
   at PSConsoleUtilities.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg) in PSReadLine\PSReadLine\ReadLine.cs:line 434

**Comment by lzybkr** [comment]
Dupe of #184.
