### ISSUE TITLE
vs code g++ debugger bug

### ISSUE THREAD

**Issue by irfan-hossain-bhuiyan** [PowerShell/PSReadLine#1883]
the input is not working in debugger.I reinstall c++ extension several time.even restart my pc.but I can't use input in g++ debugger.Other debugger isnot working too.

the error shows:

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Belayet Hossain\Documents\vs code project\c project>  & 'c:\Users\Belayet Hossain\.vscode\extensions\ms-vscode.cpptools-1.0.1\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-13dlvr32.yxf' '--stdout=Microsoft-MIEngine-Out-lsfqhokl.itw' '--stderr=Microsoft-MIEngine-Error-b44ayxa0.0xm' '--pid=Microsoft-MIEngine-Pid-qazlpk3o.jwl' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpr
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 3 2 . y x f ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - l s f q h o 
k l . i t w ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - b 4 4 a y x a 0 . 0 x m ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - q a z l p k 3 o 
. j w l ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\Belayet Hossain\Documents\vs code project\c project>  & 'c:\Users\Belayet Hossain\.vscode\extensions\ms-vscode.cpptools-1.0.1\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-13dlvr32.yxf' '--stdout=Microsoft-MIEngine-Out-lsfqhokl.itw' '--stderr=Microsoft-MIEngine-Error-b44ayxa0.0xm' '--pid=Microsoft-MIEngine-Pid-qazlpk3o.jwl' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpre
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 3 2 . y x f ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - l s f q h o 
k l . i t w ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - b 4 4 a y x a 0 . 0 x m ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - q a z l p k 3 o 
. j w l ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\Belayet Hossain\Documents\vs code project\c project>  & 'c:\Users\Belayet Hossain\.vscode\extensions\ms-vscode.cpptools-1.0.1\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-13dlvr32.yxf' '--stdout=Microsoft-MIEngine-Out-lsfqhokl.itw' '--stderr=Microsoft-MIEngine-Error-b44ayxa0.0xm' '--pid=Microsoft-MIEngine-Pid-qazlpk3o.jwl' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpret
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 3 2 . y x f ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - l s f q h o 
k l . i t w ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - b 4 4 a y x a 0 . 0 x m ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - q a z l p k 3 o 
. j w l ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\Belayet Hossain\Documents\vs code project\c project>  & 'c:\Users\Belayet Hossain\.vscode\extensions\ms-vscode.cpptools-1.0.1\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-13dlvr32.yxf' '--stdout=Microsoft-MIEngine-Out-lsfqhokl.itw' '--stderr=Microsoft-MIEngine-Error-b44ayxa0.0xm' '--pid=Microsoft-MIEngine-Pid-qazlpk3o.jwl' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interprete
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 3 2 . y x f ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - l s f q h o 
k l . i t w ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - b 4 4 a y x a 0 . 0 x m ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - q a z l p k 3 o 
. j w l ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\Belayet Hossain\Documents\vs code project\c project>  & 'c:\Users\Belayet Hossain\.vscode\extensions\ms-vscode.cpptools-1.0.1\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-13dlvr32.yxf' '--stdout=Microsoft-MIEngine-Out-lsfqhokl.itw' '--stderr=Microsoft-MIEngine-Error-b44ayxa0.0xm' '--pid=Microsoft-MIEngine-Pid-qazlpk3o.jwl' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 3 2 . y x f ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - l s f q h o 
k l . i t w ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - b 4 4 a y x a 0 . 0 x m ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - q a z l p k 3 o 
. j w l ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\Belayet Hossain\Documents\vs code project\c project>  & 'c:\Users\Belayet Hossain\.vscode\extensions\ms-vscode.cpptools-1.0.1\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-13dlvr32.yxf' '--stdout=Microsoft-MIEngine-Out-lsfqhokl.itw' '--stderr=Microsoft-MIEngine-Error-b44ayxa0.0xm' '--pid=Microsoft-MIEngine-Pid-qazlpk3o.jwl' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter=
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 3 2 . y x f ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - l s f q h o 
k l . i t w ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - b 4 4 a y x a 0 . 0 x m ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - q a z l p k 3 o 
. j w l ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\Belayet Hossain\Documents\vs code project\c project>  & 'c:\Users\Belayet Hossain\.vscode\extensions\ms-vscode.cpptools-1.0.1\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-13dlvr32.yxf' '--stdout=Microsoft-MIEngine-Out-lsfqhokl.itw' '--stderr=Microsoft-MIEngine-Error-b44ayxa0.0xm' '--pid=Microsoft-MIEngine-Pid-qazlpk3o.jwl' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter=m
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 3 2 . y x f ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - l s f q h o 
k l . i t w ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - b 4 4 a y x a 0 . 0 x m ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - q a z l p k 3 o 
. j w l ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\Belayet Hossain\Documents\vs code project\c project>  & 'c:\Users\Belayet Hossain\.vscode\extensions\ms-vscode.cpptools-1.0.1\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-13dlvr32.yxf' '--stdout=Microsoft-MIEngine-Out-lsfqhokl.itw' '--stderr=Microsoft-MIEngine-Error-b44ayxa0.0xm' '--pid=Microsoft-MIEngine-Pid-qazlpk3o.jwl' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter=mi
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 3 2 . y x f ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - l s f q h o 
k l . i t w ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - b 4 4 a y x a 0 . 0 x m ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - q a z l p k 3 o 
. j w l ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\Belayet Hossain\Documents\vs code project\c project>  & 'c:\Users\Belayet Hossain\.vscode\extensions\ms-vscode.cpptools-1.0.1\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-13dlvr32.yxf' '--stdout=Microsoft-MIEngine-Out-lsfqhokl.itw' '--stderr=Microsoft-MIEngine-Error-b44ayxa0.0xm' '--pid=Microsoft-MIEngine-Pid-qazlpk3o.jwl' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter=mi'
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 3 2 . y x f ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - l s f q h o 
k l . i t w ' Space ' - - s t d e r r = M i c r o s o f t - M I E n g i n e - E r r o r - b 4 4 a y x a 0 . 0 x m ' Space ' - - p i d = M i c r o s o f t - M I E n g i n e - P i d - q a z l p k 3 o 
. j w l ' Space ' - - d b g E x e = C : \ M i n G W \ b i n \ g d b . e x e ' Space ' - - i n t e r p r e t e r = m i ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\Belayet Hossain\Documents\vs code project\c project>  & 'c:\Users\Belayet Hossain\.vscode\extensions\ms-vscode.cpptools-1.0.1\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsongine-Error-b44ayxa0.0xm' '--pid=Microsoft-MIEngine-Pid-qazlpk3o.jwl' '--dbgExe=C:\MinGW\bin\gdb.exe' '--interpreter=mi'

**Comment by daxian-dbw** [comment]
This issue was fixed (see #1306). Please upgrade to the 2.0.4 version of PSReadLine from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
