### ISSUE TITLE
Resizing windows before `Escape` results in ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by markSmurphy** [PowerShell/PSReadLine#1884]
### Environment
PSReadLine: 2.0.2
PowerShell: 7.0.3
OS: Microsoft Windows 10.0.19041
Last 200 Keys
```
 LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow RightArrow RightArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace g e t Enter
 UpArrow Escape
```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 29.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.RevertLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

```none
PS version: 7.0.3
PSReadline version: 2.0.2
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.0.3.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 131
BufferHeight: 29
```

## Exception report

```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 29.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.RevertLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

I was using Powershell to issue a few HTTPie commands, which involved recalling the last command and using `left` and/or `ctrl`+`left` to go back over the last command to slightly edit it. I resized the window (for the purposes of a screen shot) and this issue occured.

[Edited] This issue happens only when you resize the window after `UpArrow` and before `Escape`.

## Expected behavior

No error message

## Actual behavior

The error 
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
```
Along with the details above

**Comment by daxian-dbw** [comment]
@markSmurphy Thanks for reporting this issue. We have been receiving some reports about this exception stack on PSReadLine 2.0.x versions but couldn't get a repro to investigate the problem.

> I was using Powershell to issue a few HTTPie commands, which involved recalling the last command and using `left` and/or `ctrl`+`left` to go back over the last command to slightly edit it. I resized the window (for the purposes of a screen shot) and this issue occured.

Looking at the the `Last 200 Keys`, when did you resize the window? For example, did you resize the window after the `UpArrow` and before `Escape`?
How did you resize the window? Shrink/increase both the width and height? Shrink/increase only the width or height?

Information about those questions would be very helpful to our investigation. Thank you in advance!

**Comment by daxian-dbw** [comment]
Also, if possible, can you please share a screenshot of the terminal content that is shown right above the exception message?

**Comment by markSmurphy** [comment]
Here's the screen shot you asked for. 
In case it's relevant, the pwsh.exe process has been active for 17 days, so there's quite a build up of command history.

I can't reproduce this at will.

You can make out (in the screen shot below) the HTTPie command at the top of the screen "http get https://...." - the previous command was "http options https://..." and you can see in the "Last 200 keys" me navigating back over the line, deleting the seven characters in " O P T I O N S" and replacing it with "get" before executing it.
![image](https://user-images.githubusercontent.com/9842107/96287233-85150800-0fd9-11eb-9b0d-43d9bae8a317.png)

**Comment by daxian-dbw** [comment]
@markSmurphy Appreciate your reply and the screenshot. I think I can reproduce the exception now. Will investigate further. Thanks.

**Comment by daxian-dbw** [comment]
@ckruegerkpmg I doubt you are facing the same issue. This issue happens only when you resize the window after `UpArrow` and before `Escape`.

If you see the same exception stack, it's likely already fixed (see #1306). Please upgrade to the [2.1.0-rc1 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0-rc1) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Comment by taketakeyyy** [comment]
@daxian-dbw

I encountered an error that I think is related to this error.

I was using powershell on VSCode. With the screen size of "The input cursor is just barely on the right side of the screen", I got an error when I pressed a `.` or `,` key. 

![10](https://user-images.githubusercontent.com/6479780/98464121-f8d6b900-2203-11eb-9f0b-4fc27aba69e9.PNG)

```
C:\Users\takey\Desktop\myspace\workspace\Algorithm>
問題が発生しました。このバグを以下の詳細と共に報告して
ください。
GitHub で報告: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
直前 200 個のキー:
 LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow g + + Space Enter  
 . . . . Enter
 . . Backspace Backspace Enter
 . Backspace Backspace g + + Space P r i m e Tab s e g m e n t Tab Enter
 . / a Enter
 Enter
 . Backspace . . Backspace Backspace Backspace UpArrow UpArrow Enter
 . / a Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 Enter
 Enter
 UpArrow Enter
 Enter
 Enter
 UpArrow Enter
 . / a Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow UpArrow Enter
 Enter
 UpArrow UpArrow Enter
 . / a Enter
 Enter
 Enter
 . . Backspace Backspace Backspace Backspace . Backspace Enter
 . Backspace Enter
 Enter
 . Backspace . Backspace UpArrow UpArrow Enter        
 . Enter
 . . Backspace Backspace Enter
 . Backspace Enter
 Enter
 , Backspace . Backspace Enter
 Enter
 . Enter
 . Backspace Backspace Enter
 . Backspace . . Backspace Enter
 . Backspace . Backspace Enter
 . . a a Enter
 Backspace , ,

例外:
System.ArgumentOutOfRangeException: 値には 0 以上で、 
コンソールの次元のバッファー サイズ未満を指定しなけれ 
ばなりません。
パラメーター名:left
実際の値は -1 です。
   場所 System.Console.SetCursorPosition(Int32 left, Int32 top)
   場所 Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)     
   場所 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   場所 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   場所 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

After resizing the screen size, the error no longer occurs :).

![11](https://user-images.githubusercontent.com/6479780/98464213-ba8dc980-2204-11eb-9624-5289a6c9f766.PNG)

**Comment by daxian-dbw** [comment]
@taketakeyyy You are using a very old version of PSReadLine, maybe 2.0.0-beta1 or prior. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please file a new issue if you run into the same issue with the latest version.

**Comment by maettu-this** [comment]
Potentially the same issue here:
```
PS C:\_ABC\Workspaces\ProjectA\All\02-Product\Trunk\05-Source\ProjectA\XY\XY.ProjectA.Core.Test.Files\LocalUserSettings>
Leider ist ein Fehler aufgetreten. Geben Sie mit diesem Fehler folgende Details an.
Bericht auf GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Letzte 1 Tasten:
 .

Ausnahme:
System.ArgumentOutOfRangeException: Der Wert muss größer als oder gleich 0 (null) sein und geringer als die Puffergröße der Konsole in dieser Dimension.
Parametername: left
Der tatsächliche Wert war -1.
   bei System.Console.SetCursorPosition(Int32 left, Int32 top)
   bei Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   bei Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   bei Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   bei Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   bei Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   bei Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   bei Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   bei Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\_ABC\Workspaces\ProjectA\All\02-Product\Trunk\05-Source\ProjectA\XY\XY.ProjectA.Core.Test.Files\LocalUserSettings>
```
The issue seems to occur when the width of the console is exactly the width of the prompt. The issue does not occur when shortening the path to:
```
PS C:\_ABC\Workspaces\ProjectA\All\02-Product\Trunk\05-Source\ProjectA\XY\XY.ProjectA.Core.Test.Files\LUSettings>
```

**Comment by maettu-this** [comment]
```
Name                           Value
----                           -----
PSVersion                      5.1.18362.1171
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1171
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
