### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by deepan-py** [PowerShell/PSReadLine#1905]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new  
-----------------------------------------------------------------------
Last 200 Keys:
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  

Exception:
System.ArgumentOutOfRangeException: The value must be greater than 
or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -41.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)      
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)        
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 
key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

While calculating first 3000 value of pi and copying it and double taping on the terminal it continuously pasting them in the terminal cause error.

**Comment by deepan-py** [comment]
![image](https://user-images.githubusercontent.com/60477808/97400828-c5e41980-1915-11eb-83f3-6e6ccbb4bff1.png)
