### ISSUE TITLE
Tab menu completion crashes on Windows Terminal

### ISSUE THREAD

**Issue by jmmv** [PowerShell/PSReadLine#1908]
I reconfigured my PowerShell to enable menu completion, like this:

```powershell
Set-PSReadlineKeyHandler -Key Tab -Function MenuComplete
```

To test this out, I typed `Set-` followed by tab, which asked me if I wanted to display the more than 600+ options. When confirming with `y`, I was greeted with this error:

```
-----------------------------------------------------------------------
Last 14 Keys:
 S e t - E Tab Ctrl+c Ctrl+c S e t - Tab y

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -642.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

I'm able to reproduce this consistently, but I've found out that this is only happening when running a PowerShell session from within Windows Terminal (version 1.3.2651.0). Running these same steps from a "regular" PowerShell window doesn't expose the problem.

Some more useful details:

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.546
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.546
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by daxian-dbw** [comment]
> PSReadline version: 2.0.0-beta2

This is a very old version, so the issue you saw was already fixed. Please give a try to the 2.1.0-rc1 version of PSReadLine.
