### ISSUE TITLE
Pasting piece of PS-code in VS Code/powershell console returns error

### ISSUE THREAD

**Issue by Kipjr** [PowerShell/PSReadLine#1914]
Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

I'm not allowed to share the Pasted code due to company policy 

My code piece of code was a function which I wanted to test.
- 64 lines (4comments, 8 newlines, rest is code)
- average line length 71 characters
- Max line length 528 characters (comment of raw input of code)

```

Last 200 Keys:
 m e Space o n N o t i f i c a t i o n T y p e Space - V a l u e Space Space $ n o t i f i c a t i o n A r r a y [ 1 ] . A l l Enter
 Space Space Space Space $ o b j Space | Space A d d - M e m b e r Space - M e m b e r T y p e Space N o t e P r o p e r t y Space - N a m e Space o f f N o t i f i c a t i o n T y p e 
Space - V a l u e Space Space $ n o t i f i c a t i o n A r r a y [ 2 ] . A l l Enter
 Space Space Space Space Enter
 Space Space Space Space r e t u r n Space $ o b j Enter
 } Space # Space e n d Space f u n c t i o n

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -24.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by Kipjr** [comment]
Additional info:

- CTRL + V  --> WORKS 
- Right mouse button --> Behaviour above
