### ISSUE TITLE
Received an error message when running python asking to report the bug to github for VS Code. I'm unable to run any python code and I've tried uninstalling/reinstalling python directly from python.org

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#1924]
Bug message in VS code terminal - 

```
Last 200 Keys:
 i n g / E x e r c i s e Space F i l e s / C h 0 7 / 0 7 _ 0 6 / b e g i n " Enter      
 & Space c : / U s e r s / e r i c j / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o n 3 9 / p y t h o n . e x e Space " c : / U s e r s / e r i c j / D o c u m e n t s / P r o g r a m m i n g / P y t h o n / T r a i n i n g / E x e r c i s e Space F i l e s / C h 0 7 / 0 7 _ 0 6 / b e g i n / p l a n t . p y " Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and 
less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String 
defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)     
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by daxian-dbw** [comment]
@ericj10 You didn't provide PSReadLine version information so it's not clear whether this is a new issue. Most likely, this issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
