### ISSUE TITLE
There is a bug when i am doing object oriented programming

### ISSUE THREAD

**Issue by MirzaAlbab** [PowerShell/PSReadLine#1929]
Last 200 Keys:
 . 7 \ b i n \ j a v a . e x e ' Space ' - D f i l e . e 
n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s \ L E N O V O \ A p p D a t a \ R o a m i n g 
\ C o d e \ U s e r \ w o r k s p a c e S t o r a g e \ 9 d d 2 1 e a f 1 d 0 3 c 4 9 5 a b c c a 2 4 c f 8 0 6 1 
5 8 7 \ r e d h a t . j a v a \ j d t _ w s \ 0 0 9 Space - Space U T S Space P B O Space P R A K _ 9 1 b a 5 b f 
f \ b i n ' Space ' M a i n ' Space Enter
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 
top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char 
c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop() 
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)       
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
