### ISSUE TITLE
I was using webdriver to build insta bot but while running it i faced this error

### ISSUE THREAD

**Issue by Rachit-Pandey-2004** [PowerShell/PSReadLine#1937]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 p y t h o n . e x e Space " c : / U s e r s / h p / D e s k t o p / D e s t o p Space d a t a / I n s t a g r a m Space b o t / n e w _ m e t h o d . p y " Enter
 & Space C : / U s e r s / h p / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o n 3 9 / p y t h o n . e x e Space " c : / U s e r s / h p / D e s k t o p / D e s t o p Space d a t a / I n s t a g r a m Space b o t / n e w _ m e t h o d . p y " Enter
 &

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.        
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfI   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatch   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
