### ISSUE TITLE
Visual Studio Code - Terminal python code execution error message 11-12-2020 11:14AM

### ISSUE THREAD

**Issue by RonyHobby** [PowerShell/PSReadLine#1948]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 \ l i b \ p y t h o n \ d e b u g p y \ l a u n c h e r ' Space ' 5 0 6 9 8 ' Space ' - - ' Space ' c : \ U s e r s \ j e a n r \ D o c u m e n t s \ P R O G R A M M I N G - S O F T W A R E - F I R M W A R E \ P y t h o n \ P y t h o n _ C o u r s e s \ A u t o m a t i o n - W e b _ S c r a p i n g \ W e b _ S c r a p i n g \ W e b _ S c r a p i n g _ 1 0 1 _ C o u r s e \ P r a c t i c e \ a p p . p y ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
