### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below. Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

### ISSUE THREAD

**Issue by raffg** [PowerShell/PSReadLine#1950]
Last 200 Keys:
 m e - S e r i e s - D a t a - w i t h - F a c e b o o k - P r o p h e t . g i t Enter
 g i t Space s t a t u s Enter
 g i t Space a d Space . Backspace Backspace d Space . Enter
 g i t Space c o m m i t Space - m Space " a d d i n g Space P a c k t Space s u b m o d u l e " Enter
 g i t Space p u s h Enter
 g i t Space s t a t u s Enter
 g i t Space s t a t u s Enter
 g i t Space a d d Space . Enter
 g i t Space s t a t u s Enter
 c d Space F o Tab Enter
 g i t Space s t a t u s Enter
 g i t Space a d d Space . Enter
 g i t Space c o m m i t Space - m Space "

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
