### ISSUE TITLE
Instructed to report by PowerShell

### ISSUE THREAD

**Issue by Aaryan-M** [PowerShell/PSReadLine#1956]
Here are the details I was instructed to provide
---

Last 200 Keys:
 Ctrl+Space Ctrl+Space m Ctrl+Space - Ctrl+Space t Ctrl+Space Ctrl+Space y p e Space f l e Backspace Backspace Ctrl+Space Ctrl+z i l e Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace - i t e m Ctrl+Space Space f i l e Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow RightArrow Ctrl+Space LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Ctrl+Space Enter
 End Space - v Ctrl+Space Space i p Backspace p Backspace Backspace " I m p o Backspace Backspace Backspace Backspace i m p o r t Space s u b p r o c e s s " Enter
 UpArrow Space - p Ctrl+Space Space . Enter
 UpArrow Backspace Backspace Space $ p r o g r m m Backspace Backspace a m i Backspace m i n g / P y t h o n / Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow P r o j e c t s Space i n Space P r o g r e s s Enter
 UpArrow " Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow " Backspace Ctrl+RightArrow Ctrl+RightArrow " Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow RightArrow Ctrl+Backspace Ctrl+Backspace C : / U s e r s ? Backspace Ctrl+Delete Ctrl+Delete Ctrl+Delete Delete / Space Backspace Ctrl+Space Enter
 Ctrl+Space Ctrl+Space

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -31.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
