### ISSUE TITLE
Last 0 Keys: Exception: System.IO.IOException: The handle is invalid.

### ISSUE THREAD

**Issue by npoliquin** [PowerShell/PSReadLine#1958]
My command is executed (Created new deploy), but I got this error:

```
Last 0 Keys:
Exception:
System.IO.IOException: The handle is invalid.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.Internal.VirtualTerminal.get_BufferWidth()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
Created new deploy unnamed for 'production'
```
Any idea why?

**Comment by npoliquin** [comment]
I used appveyor for deployment. I changed the build configuration from **cmd** to **PS Core** and it's fixed the issue.
