### ISSUE TITLE
Errors in Visual Studio Code terminal

### ISSUE THREAD

**Issue by grantcv1** [PowerShell/PSReadLine#1961]
I upgraded to PowerShell V7.1.0 yesterday after being prompted to within Visual Studio Code. There were numerous problems with this upgrade as the Preview version seemed to hang around and then conflict with the new release. I installed and uninstalled both the Powershell  application (including the preview version) and the preview PowerShell extension several times before the terminal would work at all.

Now, when I run the debugger, the integrated terminal shows '2: Node Debug Console'. When the application stops,  the terminal often, but not always, will show:

Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
PS C:\Users\grantcv1\Documents\Projects\LegisPro3>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 a 2 " } ' ; Space & Space ' C : \ U s e r s \ g r a n t c v 1 \ D o c u m e n t s \ P r o j e c t s \ L e g i s P r o 3 / W o r k s p a c e / n o d e _ m o d u l e s / . b i n / e l e c t r o n . C M D ' Space ' C : \ U s e r s \ g r a n t c v 1 \ D o c u m e n t s \ P r o j e c t s \ L e g i s P r o 3 / W o r k s p a c e / s c r i p t s / M a i n . j s ' Space Enter
 Space c d Space ' C : \ U s e r s \ g r a n t c v 1 \ D o

Exception:
Parameter name: top
Actual value was 30.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
