### ISSUE TITLE
ArgumentOutOfRangeException when pasting PowerShell function

### ISSUE THREAD

**Issue by BioTurboNick** [PowerShell/PSReadLine#1962]
Pasting this into PS prompt and hitting Enter resulted in an error. It worked a while ago. Pressing enter again seems to work?

```
function Archive-Directory
{
    param(
        [string]$dir,
        [string]$currentPath = ""
    )

    write ("Checking " + $dir)
    
    $contents = @(Get-ChildItem $dir | where {$_.Name -ne $archiveLinkName})
    
    # Archive all old files in this directory and traverse each child directory to do the same.
    foreach ($item in $contents)
    {
        $isDirectory = $item.Attributes -match "Directory"
        $isOld = $item.LastWriteTime.Year -lt $yearLimit
    
        if ($isDirectory)
        {
            $nextPath = $currentPath + "\" + $item.Name
            
            Archive-Directory $item.FullName $nextPath
        }
        elseif ($isOld)
        {
            Archive-File $item.FullName $currentPath
        }
    }
    
    $newCount = @(Get-ChildItem $dir | where {$_.Name -ne $archiveLinkName}).Count
    
    if ($newCount -lt $contents.Count)
    {
        # Some files or folders were archived
    
        if ($newCount -eq 0)
        {
            # Archiving moved all files and folders, so this directory may also be removed.
            Remove-Item $dir -Recurse -Force
        }
        else
        {
            # Files and folders were archived but some remain, place a link to the archive location here for convenience.
            Create-ArchiveShortcut $currentPath
        }
    }
    elseif ($newCount -eq 0)
    {
        # Folder started empty. If folder is old, remove it.
        $isOld = (Get-Item $dir).LastWriteTime.Year -lt $yearLimit
        if ($isOld)
        {
            Remove-Item $dir -Recurse -Force
        }
    }
}
```

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 r t e d Space e m p t y . Space I f Space f o l d e r Space i s Space o l d , Space r e m o v e Space i t . Enter
 Space Space Space Space Space Space Space Space $ i s O l d Space = Space ( G e t - I t e m Space $ d i r ) . L a s t W r i t e T i m e . Y e a r Space - l t Space $ y e a r L i m i t Enter
 Space Space Space Space Space Space Space Space i f Space ( $ i s O l d ) Enter
 Space Space Space Space Space Space Space Space { Enter
 Space Space Space Space Space Space Space Space Space Space Space Space R e m o v e - I t e m Space $ d i r Space - R e c u r s e Space - F o r c e Enter
 Space Space Space Space Space Space Space Space } Enter
 Space Space Space Space } Enter
 }

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -27.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
