### ISSUE TITLE
possible bug in powershell 7 for trying to pull folder permissions and exporting to a csv file. 

### ISSUE THREAD

**Issue by sysadminpowerbi** [PowerShell/PSReadLine#1963]
Last 200 Keys:
 Enter
 # Space o l d Space c o d e Space b e l o w . Space Enter
 # Space G e t - C h i l d I t e m Space ' F O L D E R N A M E ' Space - R e c u r s e Space | Space W h e r e - O b j e c t Space { ( G e t - A c l Space $ _ . F u l l N a m e ) . A c c e s s Space | Space W h e r e - O b j e c t Space { $ _ . I d e n t i t y R e f e r e n c e Space - e q Space ' D O M A I N U S E R N A M E ' } Space } Enter
 # Space E x p o r t - C s v Space $ r e p o r t p a t h Space - N o C l o b b e r Shift+LeftArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -22.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.VisualSelectionCommon(Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by sysadminpowerbi** [comment]
screenshot

![image](https://user-images.githubusercontent.com/74629765/99460686-c7817b80-28dc-11eb-9cd0-e65aa023b912.png)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
