### ISSUE TITLE
PSReadline error in VSCode when running PowerShell code selection

### ISSUE THREAD

**Issue by vojtech-kasny** [PowerShell/PSReadLine#1965]
There is strange error generated, when running PowerShell code selection (F8).
This error is not generated for full script execution (F5).
This error occurs only in VSCode.
Tested in Microsoft Terminal, and the error is not thrown here.
**PSReadline module version 2.0.0**

```powershell
$CommandArgs = @{
>>     Before = @{
>>         @(
>>             @{Name='test_b1';Id='b1'}, 
>>             @{Name='test_b2';Id='b2'}, 
>>             @{Name='test_b3';Id='b3'}  
>>         )
>>     }
>>     After = @{
>>         @(
>>             @{Name='test_b1';Id='b1'}, 
>>             @{Name='test_b2';Id='b2'}, 
>>             @{Name='test_b3';Id='b3'}, 
>>             @{Name='test_a1';Id='a1'}  
>>         )
>>     }
>> }
>>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Space Space Space Space A f t e r Space = Space @ { Enter
 Space Space Space Space Space Space Space Space @ ( Enter
 Space Space Space Space Space Space Space Space Space Space Space Space @ { N a m e = ' t e s t _ b 1 ' ; I d = ' b 1 ' } , Enter
 Space Space Space Space Space Space Space Space Space Space Space Space @ { N a m e = ' t e s t _ b 2 ' ; I d = ' b 2 ' } , Enter
 Space Space Space Space Space Space Space Space Space Space Space Space @ { N a m e = ' t e s t _ b 3 ' ; I d = ' b 3 ' } , Enter
 Space Space Space Space Space Space Space Space Space Space Space Space @ { N a m e = ' t e s t _ a 1 ' ; I d = ' a 1 ' } Enter
 Space Space Space Space Space Space Space Space ) Enter
 Space Space Space Space } Enter
 } Enter
 Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by daxian-dbw** [comment]
> Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

@vojtech-kasny The bug-reporting URL shown in the error message indicates you were using a very old version of PSReadLine (2.0.0-beta2 or prior). This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
