### ISSUE TITLE
Powershell gave an error upon pressing the "Up arrow" - tried viewing old history

### ISSUE THREAD

**Issue by Viktova** [PowerShell/PSReadLine#1966]
## is it reproduce-able / did you check with the latest version?
No and I don't want to.

## Environment

```
PS version: 5.1.19041.610
PSReadline version: 
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 10.0.19041.1 (WinBuild.160101.0800)
HostName: Windows PowerShell ISE Host
The handle is invalid.
At line:27 char:21
+     "BufferWidth: $([console]::BufferWidth)"
+                     ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], IOException
    + FullyQualifiedErrorId : System.IO.IOException
 
BufferWidth: 
The handle is invalid.
At line:28 char:22
+     "BufferHeight: $([console]::BufferHeight)`n"
+                      ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], IOException
    + FullyQualifiedErrorId : System.IO.IOException
 
BufferHeight: 
```

## Exception report

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

## Steps to reproduce

It didn't happen again so I couldn't reproduce :(

## Expected behavior

No error should show up inside the terminal when viewing or cycling through old command history.

## Actual behavior

`showed an error but i was still inside the terminal and could use it normally`

**Comment by Viktova** [comment]
Possible duplicate of: https://github.com/PowerShell/PSReadLine/issues/1954
closing.
