### ISSUE TITLE
Bug (System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.)

### ISSUE THREAD

**Issue by notIbrahim** [PowerShell/PSReadLine#1975]
-----------------------------------------------------------------------
Last 200 Keys:
 Space & Space ' c : \ U s e r s \ P e r f o r m a n c e \ . v s c o d e \ e x t e n s i o n s \ m s - v s c o d e . c p p t o o l s - 1 . 1 . 2 \ d e b u g A d a p t e r s \ b i n \ W i n d o w s D e b u g L a u n c h e r . e x e ' Space ' - - s t d i n = M i c r o s o f t - M I E n g i n e - I n - u z 0 r 5 e e 2 . a k w ' Space ' - - s t d o u t = M i c r o s o f t - M I E n g i n e - O u t - k 3 r k s h 3 u .    

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 16.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
