### ISSUE TITLE
powershell docker crashing

### ISSUE THREAD

**Issue by preddyp** [PowerShell/PSReadLine#2017]
## Environment

```none
[PS version: 7.0.3
PSReadline version: 2.0.2
os: Linux ljb000000 4.15.18+test #1 SMP Mon Oct 29 03:40:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PS file version: 7.0.3.0
HostName: ConsoleHost
BufferWidth: 256
BufferHeight: 83]
```

## Exception report

<!--PS /> ss terminated. The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
### Environment.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
PSReadLine: 2.0.2owerShell.ManagedPSEntry.Main(System.String[])
PowerShell: 7.0.3tOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
OS: Linux 4.15.18+test #1 SMP Mon Oct 29 03:40:39 UTC 2018
Last 1 Keysm.Console.SetCursorPosition(Int32 left, Int32 top)
```at System.Console.set_CursorLeft(Int32 value)
 P at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineFromConsole(Boolean endOnTab, String initialContent, Boolean calledFromPipeline, String& restOfLine, ReadLineResult& result)
```at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLine(Boolean endOnTab, String initialContent, ReadLineResult& result, Boolean calledFromPipeline, Boolean transcribeResult)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineWithTabCompletion(Executor exec)
### Exceptionft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
```at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
System.DivideByZeroException: Attempted to divide by zero.
   at Microsoft.PowerShell.PSConsoleReadLine.PhysicalLineCount(Int32 columns, Boolean isFirstLogicalLine, Int32& lenLastPhysicalLine)oolean staMode, String configurationName)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()Text, String helpText, String[] args)
   at Microsoft.PowerShell.PSConsoleReadLine.Render()SessionState initialSessionState, String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)Text, String helpText, String[] args)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)args, Int32 argc)PowerShell 7.0.3
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```e 'help' to get help.

PS /> 
;Process terminated. The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineFromConsole(Boolean endOnTab, String initialContent, Boolean calledFromPipeline, String& restOfLine, ReadLineResult& result)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLine(Boolean endOnTab, String initialContent, ReadLineResult& result, Boolean calledFromPipeline, Boolean transcribeResult)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineWithTabCompletion(Executor exec)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(InitialSessionState initialSessionState, String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.ConsoleShell.Start(String bannerText, String helpText, String[] args)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc)crystalnet@ljb000000:~/crystalnet/orchestrator$ 3;1R3;1R3;7R3;7R;1R;1R;7R;7R146R146R152R152R;1R;1R;7R;7R;1R;1RRRR;1R;1R;7R;7R;1R;1RRRR 
3: command not found -->

## Steps to reproduce

<!-- Installed docker on linux machine following https://docs.microsoft.com/en-us/powershell/scripting/install/powershell-in-docker?view=powershell-7
within couple minutes docker crashing consistenly -->

## Expected behavior

<!-- A description of what you're expecting, possibly containing screenshots or reference material. -->

## Actual behavior

<!-- What's actually happening? -->

**Comment by preddyp** [comment]
Hi Damian, what is the fix!?
Thanks
Prabhakar

**Comment by preddyp** [comment]
Hi @daxian-dbw ,
What is the fix!?

Thaank you
Prabhakar

**Comment by daxian-dbw** [comment]
@preddyp You provided no information except for the environment data. Did you miss anything? Feel free to reopen the issue after you fill in the needed information.
