### ISSUE TITLE
Starting PowerShell generated this error. How to resolve it

### ISSUE THREAD

**Issue by earnrice10** [PowerShell/PSReadLine#2018]
### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.1.0-preview.2
OS: Microsoft Windows 10.0.18363
BufferWidth: 120
BufferHeight: 30

Last 0 Keys
```

```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by daxian-dbw** [comment]
I recommend you to remove you PSReadLinue module folder and install it again from PowerShell Gallery. The 2.2.0-beta1 PSReadLine folder should be structured like this:
```
C:\PROGRAM FILES\POWERSHELL\7\MODULES\PSREADLINE\2.2.0
│   Changes.txt
│   License.txt
│   Microsoft.PowerShell.PSReadLine2.dll
│   PSReadLine.format.ps1xml
│   PSReadLine.psd1
│   PSReadLine.psm1
│   SamplePSReadLineProfile.ps1
│   System.Runtime.InteropServices.RuntimeInformation.dll
│
├───net461
│       Microsoft.PowerShell.PSReadLine.Polyfiller.dll
│
└───net5.0
        Microsoft.PowerShell.PSReadLine.Polyfiller.dll
```

**Comment by garyng** [comment]
Might need to remove it from `%userprofile%\Documents\PowerShell\Modules` as well.
