### ISSUE TITLE
Bug System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by sarahheavner** [PowerShell/PSReadLine#2020]
Last 200 Keys:
 Enter
 & Space " C : / U s e r s / S a r a h Space J r / a n a c o n d a 3 / p y t h o n . e x e " Space " c : / U s e r s / S a r a h Space J r / D e s k t o p / A s s i g n m e n t s / d u - d e n - d a t a - p t - 0 8 - 2 0 2 0 - u - c / 1 2 - W e b - S c r a p i n g - a n d - D o c u m e n t - D a t a b a s e s / 3 / A c t i v i t i e s / 0 2 - S t u _ R e n d e r _ S t r i n g / U n s o l v e d / a p p . p y " Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.        
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)      
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\Sarah Jr\Desktop\Assignments\du-den-data-pt-08-2020-u-c\12-Web-Scraping-and-Document-Databases\3\Activities\02-Stu_Render_String\Unsolved>

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
