### ISSUE TITLE
Can't type in a quotation mark

### ISSUE THREAD

**Issue by shelbykauth** [PowerShell/PSReadLine#2029]
So I was trying to run something in the vsCode built-in integrated terminal on Windows 10.

Previous somewhat successful commands had been
`npm run test:dev` (multiple times over)
`npm run test:dev -- --delay` (this didn't work as expected)
`npm run test:dev` (ran fine)
`npm run test:dev -- --grep Multiple DBs`
  - in the middle of typing this, I realized I forgot to use quotes
  - stick a quote at the end, and I get something close to the following error
  - try again, do a quote immediately after `-- grep `, get the following error
  - try again, same thing.
  - copy terminal, click on link, paste it over here.

- Go back to other terminal (same program, terminal was already open)
  - `Get-Host`
  - `npm run test:dev -- --grep "Multiple DBs"` no problem, runs as expected

- Leave it be for a while as I type up this, return to original terminal with bug
  - I can type it in no problem

# Error Information

```
> npm run test:dev -- --grep 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new     
-----------------------------------------------------------------------
Last 200 Keys:
 : Space Backspace [branch_name redacted] Space - f Enter
 n p m Space t e s t Enter
 Ctrl+c C : / U s e r s / s k a u t h / A p p D a t a / L o c a l / P 
r o g r a m s / G i t / m i n g w 6 4 / s h a r e / d o c / g i t - d 
o c / UpArrow DownArrow UpArrow Backspace Backspace Backspace Backspace r u n Space t e s t : d e v Enter
 Ctrl+c UpArrow Space - - Space - - d e l a y Enter
 Ctrl+c Ctrl+c UpArrow UpArrow Enter
 UpArrow UpArrow DownArrow UpArrow Backspace Backspace Backspace Backspace Backspace g r e p Space M u l t i p l e Space D B s " Ctrl+c Ctrl+c UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace g r e p Space " UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace g r e p Space "

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or 
equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object 
arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

# Version Information
```
[dir redacted]> Get-Host


Name             : ConsoleHost
Version          : 5.1.18362.1171
InstanceId       : [uuid redacted]
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace



```

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
