### ISSUE TITLE
Module initialization failed on busy system

### ISSUE THREAD

**Issue by FallenGameR** [PowerShell/PSReadLine#203]
I'm changing ownership for C:\automation\history and all of it's children recursively. There are lots of files in this folder. Plus I'm installing  windows update on hyper-V. The system feels less responsive but is working. But when a Powershell window is opened in C:\automation\history and PsReadline is being imported from profile I get this error:

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
Or email: jason@truewheels.net
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean e
xitContext)
   at PSConsoleUtilities.PSConsoleReadLine.ReadHistoryFile()
   at PSConsoleUtilities.PSConsoleReadLine.DelayedOneTimeInitialize()
   at PSConsoleUtilities.PSConsoleReadLine.Initialize(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)
   at PSConsoleUtilities.PSConsoleReadLine.ReadLine(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by FallenGameR** [comment]
Hm... after the ownership change finished and hyper-v machine was stopped and closed I still get the same error opening powershell in some folders.

Powershell in C:\ - open fine, PsReadLine is imported
Powershell in C:\Users\alexko - PsReadLine fail initialization with the same error

Trying out reboot...

**Comment by lzybkr** [comment]
Closing - I don't think this exception can leak anymore. If you see it using 2.0, feel free to reopen.
