### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below.

### ISSUE THREAD

**Issue by bikash1317** [PowerShell/PSReadLine#2030]
Last 200 Keys:
 I n E x c e p t i o n M e s s a g e s ' Space ' - D f i l e . e n c o d i n g = U T F 
- 8 ' Space ' - c p ' Space ' C : \ U s e r s \ B i k a s h 1 3 1 7 \ A p p D a t a \ R o a m i n g \ C o d e \ U s e r \ w o r k s p a c e S t o r a g e \ 5 8 6 e a 9 5 a 2 
9 1 d 4 b 9 f c 6 8 8 9 4 b 5 0 0 1 6 2 f b 5 \ r e d h a t . j a v a \ j d t _ w s \ P r o g r a m s _ 4 d 6 7 c a e b \ b i n ' Space ' D e m o 7 6 ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -3.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)    
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS D:\3RD - Semester\CWS-1\Programs>  & 'c:\Users\Bikash1317\.vscode\extensions\vscjava.vscode-java-debug-0.29.0\scripts\launcher.bat' 'C:\Program Files\java\jdk-14.0.2\bin\java.exe' '-XX:+ShowCodeDetailsInExceptionMessages' '-Dfile.encoding=UTF-8' '-cp' 'C:\Usfb5\redhat.java\jdt_ws\Programs_4d67caeb\bin' 'Demo76' 
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 

        at Demo76.main(Demo76.java:127)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
