### ISSUE TITLE
 something went wrong

### ISSUE THREAD

**Issue by boganLY** [PowerShell/PSReadLine#2034]
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.1.0-preview.6
OS: Microsoft Windows 10.0.18363
BufferWidth: 120
BufferHeight: 30

Last 0 Keys
```

```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by daxian-dbw** [comment]
@boganLY Could you please describe how this happened? Does it happen consistently? How did you install the 2.2.0-beta1 version of PSReadLine?

Can you please run share the folder structure of the 2.2.0-beta1 PSReadLine module folder? You can get the structure by running the following script:
```powershell
$path = gmo PSReadLine | % ModuleBase
tree /F $path
```

**Comment by daxian-dbw** [comment]
`2.2.0-beta1` version of PSReadLine doesn't work with 7.1 preview versions. Please upgrade to 7.1 GA.
