### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by godalming123** [PowerShell/PSReadLine#2039]
i have a bug in my github repo when i run __init__.py in the arrow folder
-------------------------------------------------------------------------------
github repo : https://github.com/godalming123/how-coding-should-work/tree/create-arrow-folder-as-impotable-module
i think the error message is in the for loop of arrow\textToList.py at line 28 as a got the same error several times
error message:
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 / a r r o w / _ _ i n i t _ _ . p y Enter
 & Space " C : / P r o g r a m Space F i l e s / W i n d o w s A p p s / P y t h o n S o f t w a r e F o u n d a t i o n . p y t h o n . 3 . 9 _ 3 . 9 . 2 4 0 . 0 _ x 6 4 _ _ q b z 5 n 2 k f r a 8 p 0 / p y t h o n 3 . 9 . e x e " Space c : / U s e r s /jamie/ s o u r c e / r e p o s / h o w - c o d i n g - s h o u l d - w o r k / a r r o w / _ _ i n i t _ _ . p y Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
