### ISSUE TITLE
Typing `git commit -m " ` causes System.ArgumentOutOfRangeException exception

### ISSUE THREAD

**Issue by rrmhearts** [PowerShell/PSReadLine#2040]
## Environment
Windows 10, 
Powershell
```
Get-Host | Select-Object Version  

Version       
-------
5.1.18362.1171
```
Not the whole thing but the script below causes the same error. I think PS is in a corrupted state.
```none
     "HostName: $hostName"
HostName: ConsoleHost
PS C:\Users\Admin\Documents\Gitea\flask-pytorch-backend\frontend>     "BufferWidth: $([console]::BufferWidth)"
BufferWidth: 65
PS C:\Users\Admin\Documents\Gitea\flask-pytorch-backend\frontend>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new-----------------------------------------------------------------------
Last 200 Keys:
 l l " Space } Space e l s e Space { Space " p o w e r s h e l l 
. e x e " Space } ; Space ( d i r Space $ p s h o m e \ $ n a m e ) . V e r s i o n I n f o . F i l e V e r s i o n ) " Enter
 Space Space Space Space " H o s t N a m e : Space $ h o s t N a 
m e " Enter
 Space Space Space Space " B u f f e r W i d t h : Space $ ( [ c 
o n s o l e ] : : B u f f e r W i d t h ) " Enter
 Space Space Space Space " B u f f e r H e i g h t : Space $ ( [ 
c o n s o l e ] : : B u f f e r H e i g h t ) ` n " Enter        
 }

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)    
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()       
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)      
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------```
```

## Exception report
```
PS C:\Users\Admin\Documents\Gitea\flask-pytorch-backend\frontend> git commit -m 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new-----------------------------------------------------------------------
Last 175 Keys:
 c d Space f r o n Tab Enter
 n p m Space s t a r t Enter
 n p m Space i Space - - s a v e Space r e a c t e r - r o u t e 
r - d o m Enter
 UpArrow Backspace Backspace Backspace Backspace - d o m LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow RightArrow RightArrow Backspace Backspace Enter     
 n p m Space a u d i t Space f i x Enter
 UpArrow UpArrow UpArrow UpArrow Enter
 g i t Space s t a t u s Enter
 g i t Space a d d Space . Space - u Enter
 g i t Space s t a t u s Enter
 g i t Space c o m m i t Space - m Space " g i t Space s t a t u 
s Enter
 g i t Space c o m m i t Space - m Space "

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()       
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)      
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```
-----------------------------------------------------------------------

## Steps to reproduce
git status
git commit -m "
**ERROR**

## Expected behavior
Expect PS to let me finish typing the command.

## Actual behavior
After typing `-m "`, the error report appears.

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
