### ISSUE TITLE
Oops, something went wrong.

### ISSUE THREAD

**Issue by Ohh2333** [PowerShell/PSReadLine#2043]
## Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.1.0-preview.3
OS: Microsoft Windows 10.0.18363
BufferWidth: 120
BufferHeight: 30
```none
[run the script below and paste the output here]
```

## Exception report
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by daxian-dbw** [comment]
The `2.2.0-beta1` version of PSReadLine doesn't work with 7.1 preview versions. Please upgrade to 7.1 GA version.
