### ISSUE TITLE
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.

### ISSUE THREAD

**Issue by Marc05** [PowerShell/PSReadLine#2058]
While going through the command history in the console, this happened:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Marc05> Function Get-DNSHostEntryAsync {
>>     <#
>>         .SYNOPSIS
>>             Performs a DNS Get Host asynchronously
>>         .DESCRIPTION
>>             Performs a DNS Get Host asynchronously
>>         .PARAMETER Computername
>>             List of computers to check Get Host against
>>         .NOTES
>>             Name: Get-DNSHostEntryAsync
>>             Author: Boe Prox
>>             Version History:
>>                 1.0 //Boe Prox - 12/24/2015
>>                     - Initial result
>>         .OUTPUT
>>             Net.AsyncGetHostResult
>>         .EXAMPLE
>>             Get-DNSHostEntryAsync -Computername google.com,prox-hyperv,bing.com, github.com, powershellgallery.com, powershell.org
>>             Computername          Result
>>             ------------          ------
>>             google.com            216.58.218.142
>>             prox-hyperv           192.168.1.116
>>             bing.com              204.79.197.200
>>             github.com            192.30.252.121
>>             powershellgallery.com 191.234.42.116
>>             powershell.org        {104.28.15.25, 104.28.14.25}
>>         .EXAMPLE
>>             Get-DNSHostEntryAsync -Computername 216.58.218.142
>>             Computername   Result
>>             ------------   ------
>>             216.58.218.142 dfw25s08-in-f142.1e100.net
>>     #>
>>     #Requires -Version 3.0
>>     [OutputType('Net.AsyncGetHostResult')]
>>     [cmdletbinding()]
>>     Param (
>>         [parameter(ValueFromPipeline=$True)]
>>         [string[]]$Computername
>>     )
>>     Begin {
>>         $Computerlist = New-Object System.Collections.ArrayList
>>         If ($PSBoundParameters.ContainsKey('Computername')) {
>>             [void]$Computerlist.AddRange($Computername)
>>         } Else {
>>             $IsPipeline = $True
>>         }
>>     }
>>     Process {
>>         If ($IsPipeline) {
>>             [void]$Computerlist.Add($Computername)
>>         }
>>     }
>>     End {
>>         $Task = ForEach ($Computer in $Computerlist) {
>>             If (([bool]($Computer -as [ipaddress]))) {
>>                 [pscustomobject] @{
>>                     Computername = $Computer
>>                     Task = [system.net.dns]::GetHostEntryAsync($Computer)
>>                 }
>>             } Else {
>>                 [pscustomobject] @{
>>                     Computername = $Computer
>>                     Task = [system.net.dns]::GetHostAddressesAsync($Computer)
>>                 }
>>             }
>>         }
>>         Try {
>>             [void][Threading.Tasks.Task]::WaitAll($Task.Task)
>>         } Catch {}
>>         $Task | ForEach {
>>             $Result = If ($_.Task.IsFaulted) {
>>                 $_.Task.Exception.InnerException.Message
>>             } Else {
>>                 If ($_.Task.Result.IPAddressToString) {
>>                     $_.Task.Result.IPAddressToString
>>                 } Else {
>>                     $_.Task.Result.HostName
>>                 }
>>             }
>>             $Object = [pscustomobject]@{
>>                 Computername = $_.Computername
>>                 Result = $Result
>>             }
>>             $Object.pstypenames.insert(0,'Net.AsyncGetHostResult')
>>             $Object
>>         }
>>     }
>> }
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 39 Keys:
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -59.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
