### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below. Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

### ISSUE THREAD

**Issue by AlbBoy** [PowerShell/PSReadLine#2061]
Last 200 Keys:
 ' c : \ U s e r s \ C R S \ . v s c o d e \ e x t e n s i o n s \ v s c j a v a . v s c o d e - j a v a - d e b u g - 0 . 3 0 . 0 \ s c r i p t s \ l a u n c h e r . b a t ' Space ' C : \ P r o g r a m Space F i l e s \ J a v a \ j d k - 1 5 . 0 . 1 \ b i n \ j a v a . e x e ' Space ' - - e n a b l e - p r e v i e w ' Space ' - X X : + S h o w C o d e D e t a i l s I n E x c e p t i o n M e s s a g e s ' Space ' - D

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
