### ISSUE TITLE
Incorrect parameter when trying to clear the terminal?

### ISSUE THREAD

**Issue by JBillson** [PowerShell/PSReadLine#2080]
-----------------------------------------------------------------------
Last 34 Keys:
 a d b Space s h e l l Enter
 a d b Space d Backspace s h e l l Enter
 a d b Space s h e l l Enter
 Ctrl+c Ctrl+l

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
