### ISSUE TITLE
I see this Oops, something went wrong.  Please report this bug with the details below.

### ISSUE THREAD

**Issue by khoy2589** [PowerShell/PSReadLine#2081]
PS D:\¹Java ٫Ԩ\JavaLerning> 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 . 0 . 1 \ b i n \ j a v a . e x e ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s \ U S E R \ A p p D a t a \ R o a m i n g \ C o d e \ U s e r \ w o r k s p a c e S t o r a g e 
\ c 2 e 6 4 0 5 3 a c c 3 e 3 8 f 5 c a e b e c c 6 d c f 0 1 4 a \ r e d h a t . j a v a \ j d t _ w s \ J a v a L e r n i n g _ 1 5 c 0 5 2 f a \ b i n ' Space ' H e l l o i n j a v a ' Space Enter

Exception:
System.IO.IOException: Unknown error "16389".
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__ConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at System.IO.TextWriter.SyncTextWriter.Write(String value)
   at System.Console.Write(String value)
   at Microsoft.PowerShell.Internal.VirtualTerminal.Write(String value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS D:\¹Java ٫Ԩ\JavaLerning>

**Comment by daxian-dbw** [comment]
@khoy2589 You were using a very old version of PSReadLine (2.0.0-beta2 or prior). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
