### ISSUE TITLE
Report Bug: System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by olddway** [PowerShell/PSReadLine#2093]
I'm in Visual Studio Code try to run Python codes I downloaded from Udemy.com and got the following messages:

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 y t h o n . p y t h o n - 2 0 2 0 . 1 2 . 4 2 4 4 5 2 5 6 1 \ p y t h o n F i l e s \ l i b \ p y t h o n 
\ d e b u g p y \ l a u n c h e r ' Space ' 4 9 8 7 1 ' Space ' - - ' Space ' e : \ G o o g l e Space D r i v e \ P y t h o n \ U d e m y \ 1 0 0 Space D a y s Space o f Space C o d e \ 0 1 6 Space - Space O b j e 
c t Space O r e n t e d Space P r o g r a m m i n g \ o o p - c o f f e e - m a c h i n e - s t a r t \ m a i n . p y ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)      
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, 
Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
