### ISSUE TITLE
エラーです

### ISSUE THREAD

**Issue by solitary-coffee** [PowerShell/PSReadLine#2094]
直前 200 個のキー:
 P r o g r a m s \ P y t h o n \ P y t h o n 3 8 \ p y t h o n . e x e ' Space ' c : \ U s e r s \ k a z u \ . v s c o d 
e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 2 0 . 1 2 . 4 2 4 4 5 2 5 6 1 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e b u g p y \ l a u n c h e r ' Space ' 6 3 6 2 8 ' Space ' - - ' Space ' c : \ U s e r s \ k a z 
u \ D e s k t o p \ B O T テ ス ト \ j s o n . p y ' Space Enter

例外:
System.ArgumentOutOfRangeException: 値には 0 以上で、コンソールの次元のバッファー サイズ未満を指定しなければなりません。 
パラメーター名:top
実際の値は -1 です。
   場所 System.Console.SetCursorPosition(Int32 left, Int32 top)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   場所 Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   場所 Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   場所 Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   場所 Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\kazu\Desktop\Di>  c:; cd 'c:\Users\kazu\Desktop\BOTテスト'; & 'C:\Users\kazu\AppData\Local\Programs\Python\Pyuncher' '63628' '--' 'c:\Users\kazu\Desktop\BOTテスト\json.py' 
Traceback (most recent call last):
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in send  
    resp = conn.urlopen(
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\kazu\Desktop\BOTテスト\json.py", line 4, in <module>
    import json
  File "c:\Users\kazu\Desktop\BOTテスト\json.py", line 9, in <module>
    requests.post(WEB_HOOK_URL, data =
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 119, in post       
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 655, in send  
    r = adapter.send(request, **kwargs)
  File "C:\Users\kazu\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 498, in send  
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
