### ISSUE TITLE
Exception report as requested

### ISSUE THREAD

**Issue by ahlstart** [PowerShell/PSReadLine#2096]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 l a i n e n Space m a a j u s s i . e i t ' Space Enter
 Space c : ; Space c d Space ' c : Ctrl+Alt+\ D A T A Ctrl+Alt+\ P y t h o n Ctrl+Alt+\ E 2 F i l e s 2 C S V ' ; Space & Space ' C : Ctrl+Alt+\ P r o g r a m Space F i l e s Space ( x 8 6 ) Ctrl+Alt+\ M i c r o s o f t Space V i s u a l Space S t u d i o Ctrl+Alt+\ S h a r e d Ctrl+Alt+\ P y t h o n 3 7 _ 6 4 
Ctrl+Alt+\ p y t h o n . e x e ' Space ' c : Ctrl+Alt+\ U s e r s Ctrl+Alt+\ A r t o Ctrl+Alt+\ . v s c o d e Ctrl+Alt+\ e x t e n s i o n s Ctrl+Alt+\ m s 
- p y t h o n . p y t h o n - 2 0 2 0 . 1 2 .

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 9.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
