### ISSUE TITLE
 https://github.com/lzybkr/PSReadLine/issues/new

### ISSUE THREAD

**Issue by abhijeetrawat111** [PowerShell/PSReadLine#2098]

**Comment by siddharthkt45** [comment]
Last 200 Keys:
 e c h n i q u e s \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space S o r t s . c p p Space - o Space S o r t s Space } Space ; Space i f Space ( $ ? ) Space { Space . \ S o r t s Space } 
Enter
 c d Space " c : \ U s e r s \ t i w a r \ O n e D r i v e \ D e s 
k t o p \ C P P Space P r a c t i c e \ S o r t i n g Space T e c h n i q u e s \ " Space ; Space i f Space ( $ ? ) Space { Space g + 
+ Space S o r t s . c p p Space - o Space S o r t s Space } Space ; Space i f Space ( $ ? ) Space { Space . \ S o r t s Space } Enter 


Exception:
System.ArgumentOutOfRangeException: The value must be greater than 
or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)      
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by siddharthkt45** [comment]
I found this bug after executing my program via coderunner extension

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
