### ISSUE TITLE
Program says  The value must be greater than or equal to zero and less than the console's buffer size in that dimension

### ISSUE THREAD

**Issue by AlienX2001** [PowerShell/PSReadLine#2105]
`Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 A A A A A Y b A A A A c V N 5 c 3 R l b S 5 D b 2 1 w Y X J p c 2 9 u Y D F b W 1 N 5 c 3 R l b S 5 T d H J p b m c s I G 1 z Y 2 9 y b G l i L C B W Z X J z a W 9 u P T Q u M C 4 w L j A s I E N 1 b H R 1 c m U 9 b m V 1 d H J h b C w g U H V i b G l j S 2 V 5 V G 9 r Z W 4 9 Y j c 3 Y T V j N T Y x O T M 0 Z T A 4 O V 1 d C Q w A A A A K C Q w A A A A J G A A A A A k W A A A A C g s = Enter
 UpArrow Enter
 UpArrow UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -6.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------`
![image](https://user-images.githubusercontent.com/64488123/103762806-ec71af80-503e-11eb-8add-0fea18cb44b3.png)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShellGallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
