### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below.

### ISSUE THREAD

**Issue by YuriySamorodov** [PowerShell/PSReadLine#2158]
## Environment

```none
PS version: 7.2.0-preview.2
PSReadline version: 2.1.0-beta1
os: 10.0.21296.1000 (WinBuild.160101.0800)
PS file version: 7.2.0.0
HostName: ConsoleHost
BufferWidth: 120
BufferHeight: 9001
```

## Exception report

```
Last 60 Keys                                                                                                            ```                                                                                                                      UpArrow Shift+Ctrl+LeftArrow Shift+Ctrl+LeftArrow Shift+Ctrl+LeftArrow Shift+Ctrl+LeftArrow s Backspace Backspace Backspace Enter
 UpArrow Spacebar | Spacebar s e l e c t Spacebar - l a s Tab Spacebar 1 Enter
 UpArrow Spacebar | Spacebar R e Backspace Backspace U n i n s t a l l - m o d Tab Spacebar - C Tab = Backspace Backspace LeftWindows Escape
```

### Exception

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Text.StringBuilder.Insert(Int32 index, String value)
   at Microsoft.PowerShell.PSConsoleReadLine.EditItemDelete.Undo()
   at Microsoft.PowerShell.PSConsoleReadLine.RevertLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce
Regular work on PowerShell

## Expected behavior
No errors

## Actual behavior
![image](https://user-images.githubusercontent.com/5260172/105928734-2be85600-6057-11eb-8866-6bd394d217b0.png)

**Comment by daxian-dbw** [comment]
@YuriySamorodov what you ran into was fixed in the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0). Please upgrade to that version  from PowerShell Gallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Comment by YuriySamorodov** [comment]
Thanks @daxian-dbw!

**Comment by YuriySamorodov** [comment]
@daxian-dbw , just curious, what is the point using `Install-Module` instead of `Update-Module`?
