### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by navneethvariar14** [PowerShell/PSReadLine#2193]
Last 200 Keys:
 g e Space W o r k s \ O O P \ T e s t C o 
d e s \ L a b Space T e s t \ " Space ; Space i f Space ( $ ? ) Space { Space j a v a 
c Space R a n d o m 2 . j a v a Space } Space ; Space i f Space ( $ ? ) Space { Space 
j a v a Space R a n d o m 2 Space } Enter  
 c d Space " e : \ C o l l e g e Space W o 
r k s \ O O P \ T e s t C o d e s \ L a b Space T e s t \ " Space ; Space i f Space ( 
$ ? ) Space { Space j a v a c Space R a n d o m 2 . j a v a Space } Space ; Space i f 
Space ( $ ? ) Space { Space j a v a Space R a n d o m 2 Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
at dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)       
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)   
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by saifali-dev** [comment]
### Duplicate of #2190
I think I was having the same issue. Check your PSReadLine version, using the below command.
![image](https://user-images.githubusercontent.com/54573967/107150185-67035700-697e-11eb-9cb9-b312d9e29cbf.png)

**If PSReadLine version is not 2.1.0 then update it using the following command.**
**`Install-Module PSReadLine -Force`**
