### ISSUE TITLE
I Don't Know What This Is

### ISSUE THREAD

**Issue by Don-Chuy** [PowerShell/PSReadLine#2197]
Last 200 Keys:
 g e n t l i b : j d w p = t r a n s p o r t = d t _ s o c k e t , s e r v e r = n , s u s p e n d = y , a d d r e s s = l o c a l h o s t : 4 9 6 8 9 ' Space ' - - e n a b l e - p r e v i e w ' Space ' - X X : + S h o w C o d e D e t a i l s I n E x c e p t i o n M e s s a g e s ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s \ J 0 8 m e \ A p p D a t a \ R o a m i n g \

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.    
Parameter name: top
Actual value was -1.
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)  
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
