### ISSUE TITLE
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.

### ISSUE THREAD

**Issue by chandramouleswaran** [PowerShell/PSReadLine#220]
Last 200 Keys:
 t i n u e Enter UpArrow Enter UpArrow UpArrow Enter UpArrow Enter g i t Spacebar t l o g Enter t l o g Enter g i t Spacebar t a s Backspace Backspace s t a t u s Enter g i t Spacebar p u l l Enter g i t Spacebar s t t Backspace a t u s Enter c l e a r Enter g i t Spacebar p u s h Enter g i t Spacebar p u l l Enter g i t Spacebar r e b a s e Spacebar - - a b o r t Enter g i t Spacebar s t a t u s Enter g Backspace g i t Spacebar t c o m m i t Enter Backspace Backspace c l e a r Enter c l e a r Enter g i t Spacebar p u s h Enter g i t Spacebar p u l l Enter g i t Spacebar c o m m i t Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c l e a r Enter LeftWindows Backspace Insert LeftWindows RightArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was 86.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at PSConsoleUtilities.PSConsoleReadLine.PlaceCursor(Int32 x, Int32& y)
   at PSConsoleUtilities.PSConsoleReadLine.SetCursorPosition(Int32 cursor)
   at PSConsoleUtilities.PSConsoleReadLine.ForwardChar(Nullable`1 key, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()

**Comment by lzybkr** [comment]
The stack trace is different, but #503 is very likely the same thing. At any rate, the code has been rewritten significantly and likely is fixed.
