### ISSUE TITLE
Vi Mode: '<tab><esc><tab>b' causes IndexOutOfRangeException

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#221]
Attempting to do a <tab> name completion with the `<tab><esc><tab>b` sequence causes
```
2006# ._gvimrcOops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 200 Keys:
 j k k k k k j Shift+Spacebar h h h j l l l h x b b c Spacebar i j j Backspace Backspace Backspace Escape u h d Spacebar
 Escape u h c Spacebar i d Escape u b d Spacebar i d h Escape b d Spacebar d Spacebar Escape Escape v Tab Spacebar b b $
 Tab b $ l l l Tab b Escape k k v Tab b Enter Escape k v b b b b b w w w w Tab E Tab b Ctrl+c i g e t - m o Tab Tab Shif
t+Tab Escape Tab b Escape Enter o n Tab Escape Tab b Enter UpArrow Home c a t Spacebar Enter UpArrow Escape Tab b Tab En
d Tab Backspace x x Tab RightArrow i RightArrow Tab Backspace Tab Tab Backspace Tab Ctrl+c Tab b Backspace Tab Escape Ta
b b k Tab S . \ Tab Tab Escape Tab b Backspace Ctrl+c _ g v x i _ Enter _ g v i Tab Escape Tab Backspace Backspace x x i
 Tab Escape Tab r b Ctrl+c _ g i g v i Tab Escape Tab 0 $ Tab b

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at PSConsoleUtilities.PSConsoleReadLine.ViFindPreviousWordPoint(Int32 i, String wordDelimiters)
   at PSConsoleUtilities.PSConsoleReadLine.ViBackwardWord(Nullable`1 key, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreI
fNoAction, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()
##    at PSConsoleUtilities.PSConsoleReadLine.ReadLine(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)
```

**Comment by lzybkr** [comment]
I can't reproduce this, I'm guessing it was fixed. If you can still reproduce with the latest sources, just reopen.
