### ISSUE TITLE
System.IO.IOException: The parameter is incorrect. Azure Powershell Error with PSReadLine 2.1.0

### ISSUE THREAD

**Issue by IsaacAsante** [PowerShell/PSReadLine#2216]
## Exception report

```
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.Console.set_CursorVisible(Boolean value)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorVisible(Boolean value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

Last 1 Keys
```
 d
```

When I open the Azure Powershell with Admin privileges and I type a key without even pressing enter, I immediately get the error described above. Just for extra info, I am using the following: 
- PSReadLine v2.1.0
- PowerShell v5.1.19041.610
- OS: Microsoft Windows 10.0.19041
- BufferWidth: 120
- BufferHeight: 3000

**Comment by daxian-dbw** [comment]
> When I open the Azure Powershell with Admin privileges ...

@IsaacAsante Can you please clarify what the "Azure PowerShell" is? Is it the regular powrshell.exe or something different (like the Azure Cloud Shell)?

**Comment by IsaacAsante** [comment]
> > When I open the Azure Powershell with Admin privileges ...
> 
> @IsaacAsante Can you please clarify what the "Azure PowerShell" is? Is it the regular powrshell.exe or something different (like the Azure Cloud Shell)?

I believe it was the cloud shell. But I changed my entire project approach, so I no longer need this now. Sorry. I guess I'll just close this issue.
