### ISSUE TITLE
Setting a shortcut for `exit`

### ISSUE THREAD

**Issue by cincuranet** [PowerShell/PSReadLine#222]
I'm trying to set `^D` to the `exit` function.

```
Set-PSReadlineKeyHandler -Key Ctrl+d `
                         -BriefDescription "Exit" `
                         -LongDescription "Exit" `
                         -ScriptBlock {
    param($key, $arg)

    exit
}
```

But when I set this up, it end up with exception:

```
Exception:
System.Management.Automation.ExitException: System error.
   at System.Management.Automation.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClassa.<InvokeWithPipe>b__8()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvoke(Object dollarUnder, Object input, Object[] args)
   at PSConsoleUtilities.PSConsoleReadLine.<>c__DisplayClass66.<ProcessOneKey>b__64()
   at PSConsoleUtilities.PSConsoleReadLine.<>c__DisplayClass62.<CalloutUsingDefaultConsoleMode>b__61()
   at PSConsoleUtilities.PSConsoleReadLine.CalloutUsingDefaultConsoleMode[T](Func`1 func)
   at PSConsoleUtilities.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()
   at PSConsoleUtilities.PSConsoleReadLine.ReadLine(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

Is there a way to do it other way? I, so far, resulted to calling `[Environment]::Exit(0)`, but that's dead slow.

**Comment by gwojan** [comment]
Try

``` PowerShell
Set-PSReadlineKeyHandler -Chord 'Ctrl+d' -Function DeleteCharOrExit
```

It works great for me...

**Comment by cincuranet** [comment]
I know about this one. I just don't like the deleting char part. :)

**Comment by lzybkr** [comment]
Yeah, it's a little weird - but some people expect it.

Try this:

```
Set-PSReadlineKeyHandler -Key Ctrl+d `
                         -BriefDescription "Exit" `
                         -LongDescription "Exit" `
                         -ScriptBlock {
    param($key, $arg)

    [PSConsoleUtilities.PSConsoleReadLine]::RevertLine()
    [PSConsoleUtilities.PSConsoleReadLine]::Insert('exit')
    [PSConsoleUtilities.PSConsoleReadLine]::AcceptLine()
}
```
