### ISSUE TITLE
PSConsoleReadLine.ReadLine() throws NullReferenceException

### ISSUE THREAD

**Issue by nightroman** [PowerShell/PSReadLine#223]
In a PowerShell console and in a custom host in a console application I tried to call `[PSConsoleUtilities.PSConsoleReadLine]::ReadLine()`. As a result in both cases I got:

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
Or email: jason@truewheels.net
-----------------------------------------------------------------------
Last 3 Keys:
 LeftWindows Ctrl+v Enter

Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PSConsoleUtilities.PSConsoleReadLine.ReadKey()
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()
   at PSConsoleUtilities.PSConsoleReadLine.ReadLine(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by nightroman** [comment]
I have realized that .psm1 exports the function `PSConsoleHostReadline` which works as expected. Perhaps `[PSConsoleUtilities.PSConsoleReadLine]::ReadLine()` is not designed for direct calls. So the issue is not a big deal and can be closed.

Still, some thoughts. `[PSConsoleUtilities.PSConsoleReadLine]::ReadLine()` is public and mentioned in _about_PSReadline.help.txt_. Its parameters all have default values, nulls. This creates an illusion that the function can be called and the parameters are optional.

If null parameters are not expected then checks for nulls and `ArgumentNullException` exceptions would make sense perhaps. Now it fails in a nested call in _ReadLine.cs_ at the line

```
var eventSubscribers = _singleton._engineIntrinsics.Events.Subscribers;
```

because `_engineIntrinsics` is null.

**Comment by nightroman** [comment]
It seems to be not an issue in the latest version, closing.
