### ISSUE TITLE
preview 3 issue 

### ISSUE THREAD

**Issue by pb5050** [PowerShell/PSReadLine#2231]
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.0-preview.3
OS: Microsoft Windows 10.0.21301
BufferWidth: 120
BufferHeight: 9001

Last 3 Keys
```
 Enter
 d Enter

```

### Exception
```
System.MissingMethodException: Method not found: 'Void System.Management.Automation.Subsystem.CommandPrediction.OnCommandLineAccepted(System.Collections.Generic.IReadOnlyList`1<System.String>)'.
   at Microsoft.PowerShell.PSConsoleReadLine.Microsoft.PowerShell.Internal.IPSConsoleReadLineMockableMethods.OnCommandLineAccepted(IReadOnlyList`1 history)
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.OnCommandLineAccepted(String commandLine)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

licate if you find one and add additional details if you have any.

The maintainer may close your issue without further explanation or engagement if:
- You delete this entire template and go your own path;
- You file an issue that has many duplicates;
- You file an issue completely blank in the body.

-->

## Environment

```none
[run the script below and paste the output here]
```

**Comment by msftrncs** [comment]
Already reported, duplicate #2221.
