### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by taooceros** [PowerShell/PSReadLine#2232]
### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.1.0-preview.3
OS: Microsoft Windows 10.0.19042
BufferWidth: 120
BufferHeight: 30

Last 0 Keys
```

```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Exception
Another exception, happens after command `Set-PSReadLineOption -PredictionSource HistoryAndPlugin`

```
System.MissingMethodException: Method not found: 'Void System.Management.Automation.Subsystem.CommandPrediction.OnCommandLineAccepted(System.Collections.Generic.IReadOnlyList`1<System.String>)'.
   at Microsoft.PowerShell.PSConsoleReadLine.Microsoft.PowerShell.Internal.IPSConsoleReadLineMockableMethods.OnCommandLineAccepted(IReadOnlyList`1 history)
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.OnCommandLineAccepted(String commandLine)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by msftrncs** [comment]
Already reported, duplicate to #2221.
