### ISSUE TITLE
Bug: Param issue.

### ISSUE THREAD

**Issue by mehoo2020** [PowerShell/PSReadLine#2235]
Last 200 Keys:
 4 a a - 9 9 7 8 - d 2 a 6 a 3 d 5 c d 7 1 Space | Space C o m p l e t e - T S T e n a n t P r o v i s i o n i n g Space - A w a i t Space | Space E n a b l e - T S T e n a n t Space - A w a i t Enter
 G e t - T S J o u r n a l R e c o r d Space - I t e m I d Space x f 5 P T f K 3 A U a 5 z E p j W b - 9 m W Q A D 2 o J Space - F r o m V e r s i o n Space 1 0 0 0 Space - T a r g e t M a c h i n e Space T o d o S i n g l e B o x _ I N _ 1 Enter
 ` Enter
 Enter
 Enter
 Enter

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
@mehoo2020 Thanks for opening the issue. However, it's missing important context information (version of PSReadLine, version of PowerShell, and etc.) that is necessary for investigation. If you ran into issues with PSReadLine, make sure upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery. The issue may have been fixed in the latest version.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
