### ISSUE TITLE
PSReadline fails in remoted vscode-insiders session when 'c' is entered by itself when using starship.rs

### ISSUE THREAD

**Issue by JustinGrote** [PowerShell/PSReadLine#2236]
## Environment

```none
PS version: 7.2.0-preview.3
PSReadline version: 2.1.0-rc1
os: Linux tinycloud.us.to 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
PS file version: 7.2.0.0
HostName: ConsoleHost
BufferWidth: 167
BufferHeight: 20
```

### Environment
PSReadLine: 2.1.0-rc1
PowerShell: 7.2.0-preview.3
OS: Linux 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020
BufferWidth: 167
BufferHeight: 20

Last 72 Keys
```
 p w s h Spacebar - n o p r o f i l e Enter
 Enter
 Enter
 Enter
 c Ctrl+c Enter
 Enter
 p w s h Spacebar - n o p r o f i l e Enter
 Enter
 Enter
 Enter
 Enter
 l s Enter
 c Enter
 Enter
 p s Backspace w h s Backspace Backspace s h Spacebar - n o p r o f i l e Enter
 c
```

### Exception
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at Microsoft.PowerShell.PSConsoleReadLine.ConvertOffsetToPoint(Int32 offset)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

1. Install latest vscode insiders
2. Initiate SSH remoting to a prompt that has starship.rs enabled
3. Press "c"
4. Triggers exception. Doesn't happen if anything is pressed before C

## Expected behavior
No exception :)
## Actual behavior
Exception :)

This is a bit of an esoteric one, may have something to do with how starship.rs positions the cursor or something?
- Doesn't happen in normal ssh
- Doesn't seem to happen in ssh in windows terminal
- Doesn't happen locally
- Only happens when using ssh remoting to a host with vscode and a custom prompt it seems.

What my starship prompt looks like 
![image](https://user-images.githubusercontent.com/15258962/108754908-6bda1600-74fb-11eb-86c8-a524020a7b8a.png)

**Comment by StevenBucher98** [comment]
Hmm @JustinGrote does this still happen with the latest version of PSReadLine or VSCode Insiders?

**Comment by JustinGrote** [comment]
Haven't used starship in a while, moved to `oh-my-posh` v3, so I'm not sure if it's still reproducible, I'll close the case for now and it can be re-opened if anyone else reports the same.
