### ISSUE TITLE
My Ctrl c is not working!!!

### ISSUE THREAD

**Issue by ZapiZa** [PowerShell/PSReadLine#2237]
When I using to Ctrl C in the power shell, It does not working. It say that, there are some bug.
Here is the Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
@ZapiZa Thanks for opening the issue. However, it's missing important context information (version of PSReadLine, version of PowerShell, and etc.) that is necessary for investigation. Make sure you upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery. The issue may have been fixed in the latest version.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
