### ISSUE TITLE
Windows 10 Preview crash

### ISSUE THREAD

**Issue by moswald** [PowerShell/PSReadLine#230]
This has been happening for the past couple of days. It seems fairly random, but it always happens quickly. After running a few commands, I get this:

``` posh
∞ cat .\SecureLinkIntegration\.nuget\packages.config
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 52 Keys:
 UpArrow LeftWindows Enter LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows c d Spacebar p r o j Tab w Tab e Tab m Tab Enter l s Enter c a t Spacebar Escape l s Spacebar s e Tab Enter c a t Spacebar s e Tab . Tab Enter UpArrow Tab Backspace

Exception:
System.Management.Automation.PSInvalidOperationException: There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was:

    param($ke...     }
    }

   at System.Management.Automation.ScriptBlock.GetContextFromTLS()
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvoke(Object dollarUnder, Object input, Object[] args)
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass66.<ProcessOneKey>b__64()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass62.<CalloutUsingDefaultConsoleMode>b__61()
   at Microsoft.PowerShell.PSConsoleReadLine.CalloutUsingDefaultConsoleMode[T](Func`1 func)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, Object reserved)
-----------------------------------------------------------------------
```

Here's the current version of Powershell.

``` posh
∞ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.0.10061.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.0
BuildVersion                   10.0.10061.0
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
```

**Comment by lzybkr** [comment]
Thanks for the report - as a workaround, from cmd.exe, you can run:

```
powershell -noprofile -command "Install-Module -Force PSReadline"
```

This will install PSReadline from the PowerShell gallery - that version doesn't have this problem and is effectively the same as the version installed with Windows 10.

**Comment by moswald** [comment]
Forgot I filed this issue. The Windows 10 version of PS doesn't have this issue, so I'll close.
