### ISSUE TITLE
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension

### ISSUE THREAD

**Issue by fenchu** [PowerShell/PSReadLine#2308]
## Environment
```
PS version: 5.1.19041.610
PSReadline version: 2.0.0-beta2
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 10.0.19041.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 252
BufferHeight: 43
```
## Exception report

```
(boots-fullstack-test) PS C:\dist\work\boots-fullstack-test>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -5.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
(boots-fullstack-test) PS C:\dist\work\boots-fullstack-test> $env:PATH="$($env:PATH);" + $pwd + "\win\"
>> $ENV:WEBDRIVER='Chrome'
>> $ENV:SCREENSHOT=1
>> $ENV:WEBDRIVER_OPEN=1
>> $ENV:WEBDRIVER_LANG='en'
>> $ENV:WEBHOST='test12'
(boots-fullstack-test) PS C:\dist\work\boots-fullstack-test>
```
## Steps to reproduce

start visual studio code, open a terminal (ctrl + j) and just cut and paste anything in, like the above which sets my environment settings

## Expected behavior

paste without any stacktrace
## Actual behavior

I get those stacktraces so often, never outside of vscode.

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
