### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by liew312** [PowerShell/PSReadLine#2317]
-----------------------------------------------------------------------
Last 200 Keys:
 t \ C Z 2 0 0 6 - S E \ C Z 2 0 0 6 - S E \ s r c \ p a g e s \ r a n d o m t e s t . j s " Enter
 n o d e Space " c : \ U s e r s \ l i e w z \ O n e D r i v e Space - Space N a n y a n g Space T e c h n o l o g i c a l Space U n i v e r s i t y \ D e s k t o p \ L i e w Space Z i Space P e n g \ C Z 2 0 0 6 \ C Z 2 0 0 6 Space p r o j e c t \ C Z 2 0 0 6 - S E \ C Z 2 0 0 6 - S E \ s r c \ p a g e s \ r a n d o m t e s t . j s " Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNooAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by anujjoshi63** [comment]
In my case, I am able to reproduce this error by running some commands in "split-pane" and then typing [ git commit -m " ].
The moment double inverted commas are types it throws an error:
```shell
Last 50 Keys:
 c d Space a Backspace e l Tab a m Tab Tab Enter
 g i t Space c o m m i t Space - m Space " Ctrl+c UpArrow UpArrow Backspace Ctrl+Backspace Ctrl+Backspace Ctrl+Backspace g i t Space c o m m i t Space - m Space "

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable\`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

The workaround to prevent this is to close one of the panes and keep only 1 pane.

**Comment by iSazonov** [comment]
Do use latest preview? This was seem fixed https://github.com/PowerShell/PSReadLine/issues/1306
