### ISSUE TITLE
Resizing a window followed by Ctrl-L

### ISSUE THREAD

**Issue by sep332** [PowerShell/PSReadLine#2324]
I was using a screen session via SSH. The SSH connection dropped. I resized the window and pressed Ctrl-L to clear it.

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 171 Keys:
 s s h Space b r i d g e r Enter
 s s h Space b r i d g e r Enter
 s s h Space b r i d g e r Enter
 Ctrl+l UpArrow Enter
 Ctrl+l s s h Space b r i d g e r Enter
 UpArrow Enter
 UpArrow DownArrow UpArrow Enter
 s c p Space b r i d g e r : s i m Tab p l i e Backspace Backspace e - t e s t - a b b M o d e m S w a p . p l Space . Enter
 m v Space s i m Tab Space D o c u Tab Enter
 s c r e e n Space Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace s s h Space b r i d g e r Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -6.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by sep332** [comment]
Thanks for the tip. I assumed this would be upgraded automatically over time.
