### ISSUE TITLE
System.ArgumentOutOfRangeException:

### ISSUE THREAD

**Issue by itfidele** [PowerShell/PSReadLine#2332]
Last 200 Keys:
Enter
Exception:

**System.ArgumentOutOfRangeException**: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 11.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
@fidele000 There is no environment data (version of PSReadLine and etc.) to help us triage the issue. If you were using a version of PSReadLine older than 2.1.0, then please upgrade to the 2.1.0 version of PSReadLine, and it's likely that the issue you ran into was fixed. See https://github.com/PowerShell/PSReadLine#upgrading for how to upgrade.
