### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ntdai95** [PowerShell/PSReadLine#2339]
### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 5.1.19041.868
OS: Microsoft Windows 10.0.19042
BufferWidth: 177
BufferHeight: 3

Last 1 Keys
```
 &
```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 5.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.RenderErrorPrompt(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by daxian-dbw** [comment]
@ntdai95-1565490 Can you please provide repro steps? If you have a custom prompt, it may play a role in this failure too.
