### ISSUE TITLE
Got this error while trying out PSReadLine Auto Completion

### ISSUE THREAD

**Issue by mutte-79** [PowerShell/PSReadLine#2360]
My setting for Terminal size is: 200 Col,  60Line
Command line for starting Terminal is: wt.exe -p "Terminal" ; split-pane -H -s 0.66 -p "PowerShell 7.2.0" mf down"

The error accured when I pressed TAB after typing "Get-"
The result where ~375
Afterwards I tried it with fewer hits and then it worked.

Love the program!!
-----------------------------------------------------------------------
Last 6 Keys:
 g e t - Tab y

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -70.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor(Int32 x, Int32 y)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.MenuComplete(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by mutte-79** [comment]
Ps. I'm using PowerShell 7.2.0 rev 4. So it might not be supported.

**Comment by daxian-dbw** [comment]
@mutte-79 what version of PSReadLine were you using when seeing this error? Can you run the following script to gather some environment data?

```powershell
& {
    $hostName = $Host.Name
    if ($hostName -eq "ConsoleHost" -and (Get-Command Get-CimInstance -ErrorAction SilentlyContinue)) {
        $id = $PID
        $inWindowsTerminal = $false
        while ($true) {
            $p = Get-CimInstance -ClassName Win32_Process -Filter "ProcessId Like $id"
            if (!$p -or !$p.Name) { break }
            if ($p.Name -eq "WindowsTerminal.exe") { $inWindowsTerminal = $true; break }
            $id = $p.ParentProcessId
        }
        if ($inWindowsTerminal) { $hostName += " (Windows Terminal)" }
    }

    "`nPS version: $($PSVersionTable.PSVersion)"
    $m = Get-Module PSReadline
    $v = $m.Version; $pre = $m.PrivateData.PSData.Prerelease
    if ($pre) { $v = "$v-$pre" }
    "PSReadline version: $v"
    if ($IsLinux -or $IsMacOS) {
        "os: $(uname -a)"
    } else {
        "os: $((dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion)"
    }
    "PS file version: $($name = if ($PSVersionTable.PSEdition -eq "Core") { "pwsh.dll" } else { "powershell.exe" }; (dir $pshome\$name).VersionInfo.FileVersion)"
    "HostName: $hostName"
    "BufferWidth: $([console]::BufferWidth)"
    "BufferHeight: $([console]::BufferHeight)`n"
}
```

**Comment by mutte-79** [comment]
Hi!

I’m sorry, I have reinstalled Windows on that computer. Something weird had happened to that PowerShell. Hardly any command worked at all and it complained it needed a later version of NuGet even though I JUST installed one.

Med vänliga hälsningar (With kind regards)
Mattias Högfjäll

**Comment by daxian-dbw** [comment]
@mutte-79 Thanks for your reply. Given that we don't have the necessary environment data to help further understand the issue, I will close this issue for now. If you run into something similar, please open a new issue, and follow the bug template to provide as much information as possible, thank you!
