### ISSUE TITLE
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.

### ISSUE THREAD

**Issue by Trueside** [PowerShell/PSReadLine#2385]
Last 200 Keys:
 \ t o o l s \ n o d e J s \ n o d e . e x e ' Space ' . \ n o d e _ m o d u l e s \ @ w d i o \ c l i \ b i n \ w d 
i o . j s ' Space ' . / e 2 e / w d i o . m m . c o n f . j s ' Space ' - - s p e c ' Space ' c : \ w o r k \ w w w w w w w w w w w w w w w w \ a n k r - p o r t a l \ e 2 e \ t e s t s \ c r y p t o - p a y m e n t s \ u s d t - a n 
k r - p a y m e n t s - b a s e - s u i t e . t e s t . j s ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by Trueside** [comment]
Hello. It's my first issue and I just follow the instructions from the terminal, so tell me please if you need something.  My platform is Windows 10.
