### ISSUE TITLE
Please report this bug with ALL the details below

### ISSUE THREAD

**Issue by PookyBeer** [PowerShell/PSReadLine#2394]
## Environment

```none
[run the script below and paste the output here]
```

## Exception report

PS D:\> Get-OrganizationConfig | Format-List DistributionGroupNamingPolicy
Creating a new Remote PowerShell session using Modern Authentication for implicit remoting of "Get-OrganizationConfig" command ...

DistributionGroupNamingPolicy : <GroupName>

PS D:\>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 5.1.14409.1018
OS: Microsoft Windows 6.1.7601 S
BufferWidth: 180
BufferHeight: 9999

Last 200 Keys
```
 - V a l u e Spacebar " G r o u p . U n i f i e d " Spacebar - E Q ) . i d Enter
 g e t - a z u r e a d Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Bac
kspace Backspace Backspace d i Tab Tab Tab Tab Home $ s e t t i n g s Spacebar = Spacebar End Enter
 UpArrow Home Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete End Spacebar - Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backs
pace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backs
pace Backspace Backspace Backspace Backspace Backspace Backspace Backspace G e t - O r g a n i z a t i o n C o n f i g Spacebar | Spacebar F o r m a t - L i s t Spacebar D i s t r
i b u t i o n G r o u p N a m i n g P o l i c y Enter

```

### Exception
```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at System.Management.Automation.Interpreter.LightCompiler.CompileTop(LambdaExpression node)
   at System.Management.Automation.Language.Compiler.CompileTree(Expression`1 lambda, CompileInterpretChoice compileInterpretChoice)
   at System.Management.Automation.Language.Compiler.Compile(CompiledScriptBlockData scriptBlock, Boolean optimize)
   at System.Management.Automation.CompiledScriptBlockData.ReallyCompile(Boolean optimize)
   at System.Management.Automation.CompiledScriptBlockData.CompileOptimized()
   at System.Management.Automation.CompiledScriptBlockData.Compile(Boolean optimized)
   at System.Management.Automation.DlrScriptCommandProcessor.Init()
   at System.Management.Automation.Runspaces.Command.CreateCommandProcessor(ExecutionContext executionContext, CommandFactory commandFactory, Boolean addToHistory, CommandOrigin or
igin)
   at System.Management.Automation.Runspaces.LocalPipeline.CreatePipelineProcessor()
```

**Comment by daxian-dbw** [comment]
@PookyBeer Thanks for reporting the issue.
It looks like your computer was under memory pressure when you saw this error. The `OutOfMemoryException` was thrown from the PowerShell engine (not PSReadLine), when expanding the size of a List object.

**Comment by PookyBeer** [comment]
Hi Dongbo,

That would make sense. The server has been crapping itself, and I'm actually just rebooting it now.

Wendy

----- Original message -----
