### ISSUE TITLE
using assembly crashes PSReadline

### ISSUE THREAD

**Issue by jcotton42** [PowerShell/PSReadLine#240]
Repro steps:
Install latest PS preview (April CTP)
type `using assembly` followed by any letter
An exception is thrown
Here is the output

```
Last 16 Keys:
 u s i n g Spacebar a s s e m b l y Spacebar a

Exception:
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Management.Automation.Language.SymbolResolver.VisitUsingStatement(UsingStatementAst usingStatementAst)
   at System.Management.Automation.Language.UsingStatementAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ScriptBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.SymbolResolver.ResolveSymbols(Parser parser, ScriptBlockAst scriptBlockAst)
   at System.Management.Automation.Language.Parser.ParseTask(String fileName, String input, List`1 tokenList, Boolean re
cursed)
   at System.Management.Automation.Language.Parser.Parse(String fileName, String input, List`1 tokenList, ParseError[]&
errors)
   at System.Management.Automation.Language.Parser.ParseInput(String input, String fileName, Token[]& tokens, ParseError
[]& errors)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment]
This is a bug in the PowerShell parser which has been fixed in more recent builds.
