### ISSUE TITLE
Oops, something went wrong.

### ISSUE THREAD

**Issue by kevpar** [PowerShell/PSReadLine#241]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 71 Keys:
 g c m Spacebar \* e v e n t \* Enter
 UpArrow Spacebar Spacebar Backspace | Spacebar ? Spacebar s o u r c e Spacebar - n e Spacebar N e t E v e n t P a c k e t C a p t u r e Enter
 g e t - e v e n t s u b Tab Escape Ctrl+u Ctrl+a Ctrl+u Ctrl+k

Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Microsoft.PowerShell.PSConsoleReadLine.Kill(Int32 start, Int32 length, Boolean prepend)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, Object reserved)

**Comment by MayaLuen** [comment]
getting the same almost - Last 58 keys etc

**Comment by lzybkr** [comment]
Fixed via #540
