### ISSUE TITLE
Error when clearing console

### ISSUE THREAD

**Issue by umuluto** [PowerShell/PSReadLine#2412]
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 g m Enter
 UpArrow UpArrow DownArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 $ f o o . Ctrl+Space g e t RightArrow Enter
 Tab Tab ) Enter
 UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace . g e t Tab Backspace t y Tab ) Enter
 f l u t t e r Space d e v i c e s Space - m Backspace - a c h Backspace Backspace Backspace m a c h i n e Enter
 f l u t t e r Space e m Tab Tab u l a t o r s Enter
 UpArrow Space - - l a u n c h Space P i x l Backspace e l _ 2 _ A P I _ 3 - Backspace 0 Enter
 UpArrow UpArrow DownArrow DownArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow UpArrow UpArrow Enter
 UpArrow Space | Space C o n v e r Tab Tab Tab Tab Tab Space | Space g m Enter
 DownArrow UpArrow Ctrl+l UpArrow DownArrow DownArrow f l u t t e r Space - - h e l p Enter
 DownArrow DownArrow DownArrow DownArrow DownArrow Ctrl+l Backspace Backspace Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
