### ISSUE TITLE
there is a random bug that occurred when I tried to run a java file with checkboxes in them with some image icons, nothing too severe the program ran just fine but the editor told me to report that bug the details are in the comment section   

### ISSUE THREAD

**Issue by omar-m-z-dotcom** [PowerShell/PSReadLine#2433]

**Comment by omar-m-z-dotcom** [comment]
----------------------------------------------------------------------- 
Last 200 Keys:
 \ P r o g r a m Space F i l e s \ J a v a \ j d k - 1 5 . 0 . 1 \ b i n \ j a v a . e x e ' Space ' - X X : + S h o w C o d e D e t a i l s I n E x c e p t i o n M e s s a g e s ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' @ C : \ U s e r s \ a s u s \ A p p D a t a \ L o c a l \ T e m p \ c p _ 8 q t s m 8 n t 8 c x y l 5 y t p c v 8 b d x e q . a r g f i l e ' Space ' C h e a k B o x M a i n ' Space Enter    


Exception:
System.ArgumentOutOfRangeException: 
The value must be greater than or equal to zero and less than the console's buffer size in that dimension.  
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)       
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, 
Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics) 
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
