### ISSUE TITLE
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

### ISSUE THREAD

**Issue by ChillCrunch37** [PowerShell/PSReadLine#2465]
Last 192 Keys:
 Space & Space ' C : \ P y t h o n \ p y t h o n . e x e ' Space ' c : \ U s e r s \ 
s p r e s \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 2 1 . 5 . 8 4 2 9 2 3 3 2 0 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e b 
u g p y \ l a u n c h e r ' Space ' 5 0 6 7 3 ' Space ' - - ' Space ' c : \ G D r i v e \ S c r a p e r \ T h r e a d s \ T W T a s y n c i o . p y ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by ChillCrunch37** [comment]
Magic self-healing code, or at least refreshing my mind with a night of sleep makes me forget about this issue.
