### ISSUE TITLE
Error when pressing backspace right after tabbing

### ISSUE THREAD

**Issue by etriebe** [PowerShell/PSReadLine#247]
Here is the exception details

---

Last 43 Keys:
 g e t - h e Tab Tab Backspace Ctrl+c g e t - h e l p Backspace c l s Enter
 g e t - h e Tab Tab Tab Tab Ctrl+c g e t - h e Tab Tab Backspace

Exception:
System.Management.Automation.RuntimeException: Unable to find type [PSConsoleUtilities.PSConsoleReadLine].
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exc
eption)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean crea
teLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Obj
ect dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClassa.<InvokeWithPipe>b__8()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandling
Behavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean p
ropagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvoke(Object dollarUnder, Object input, Object[] args)
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass67.<ProcessOneKey>b__65()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass63.<CalloutUsingDefaultConsoleMode>b__62()
   at Microsoft.PowerShell.PSConsoleReadLine.CalloutUsingDefaultConsoleMode[T](Func`1 func)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

**Comment by lzybkr** [comment]
You're using Win10 and have a custom key handler for Backspace.
The namespace has changed when this module was included by default.
Try using:
    [Microsoft.PowerShell.PSConsoleReadLine]
