### ISSUE TITLE
Exception while starting Node with debugger for Jest tests

### ISSUE THREAD

**Issue by amandalishus** [PowerShell/PSReadLine#2474]
This just started happening after the upgrade today... Every time I try to debug a test through the Test Explorer or Jest Test Runner extensions :(

Even worse, I'm having trouble figuring out how to (temporarily) switch to a bash shell with all the new terminal settings. Any help would be appreciated :)

> Oops, something went wrong.  Please report this bug with the details below.
> Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
> -----------------------------------------------------------------------
> Last 200 Keys:
>  o v e r a g e ' Space ' c : \ U s e r s \ a r o d e w a l d \ s o u r c e \ P r o j e c t s \ P r o v i d e r \ p r o v i d e r - f a c e t s - i n t e r f a c e - a p i \ s r c \ p r o v i d e r - s u f f i x \ r o w - p a r s e r . s e r v i c e . s p e c . t s ' Space ' - - t e s t N a m e P a t t e r n ' Space ' R o w P a r s e r Space s h o u l d Space h a n d l e Space i n v a l i d Space S 3 Space f i l e k e y \ . ' Space Enter
> 
> 
> Exception:
> System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.Parameter name: top
> Actual value was -1.
>    at System.Console.SetCursorPosition(Int32 left, Int32 top)
>    at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
>    at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
>    at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
>    at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
>    at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
>    at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
>    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by amandalishus** [comment]
Nm the help on changing the default terminal, I found it in settings.json :)

But please keep me posted on this one... I can bash when I must, but I'm really a PowerShell girl at heart <3

**Comment by amandalishus** [comment]
Thank you! Sorry for being a bother... Truly, I wasn't paying enough attention. The error started happening after a VSCode update and I incorrectly assumed this was an extension I had installed that was causing a problem. I was on deadline, just trying to get my unit tests done, and just posted the error and switched to bash without looking into the cause.

That makes me wonder though... Is there anything in PowerShell that should be letting me know when updates are available? I have to admit to being spoiled by the modern world... I only vageuely remember the whole "check for updates first" methodology of troubleshooting from my unhappy teen years ;)
