### ISSUE TITLE
Python Vscode error

### ISSUE THREAD

**Issue by Flamingsides** [PowerShell/PSReadLine#2475]
Hello, I'm a beginner programmer, learning python. I was trying to make an app using tkinter and tried to add an image as the background. I was trying to use "PhotoImage()" but I kept getting an error. (The error was: _tkinter.TclError: couldn't open "path to my image.png": no such file). 

This kept happening so I got frustrated and spammed the "run" button a couple of times (shouldn't have done that) and suddenly a lot of text started appearing in the terminal.  I'm not sure what it means or what went wrong but there was a line in there that said: 
> Oops, something went wrong.  Please report this bug with the details below. Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new 

The link brought me here and so I decided to write all this. I don't know what the error is but I just thought I'd report it as that line requested I do so, it said it was a bug so I thought it might be important.
It would first give me the error with my code which was `_tkinter.TclError: couldn't open "path to my image.png": no such file` and then it would print the path to my code a number of times, then print some other text that I'm not really sure I understand.

The error looked like this:

`Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
\-----------------------------------------------------------------------
Last 200 Keys:
 h Space e Space c Space k Space e Space r Space . Space p Space y Space " Space E n t e r Enter
 Space & Space S p a c e Space C Space : Space / Space U Space s Space e Space r Space s Space / Space s Space u Space h Space a Space Enter
 i Space b Space . Space z Space u Space b Space e Space r Space i Space 9 Space 1 Space _ Space s Space t Space u Space d Space / Space A Space p Space p Space D Space a Space t Space a Space / Space L Space o Space c Space a Space l Space / Space P Space r Space o Space g Space Enter
 r Space a Space m Space s Space / Space P Space y Space t Space h Space o Space n Space / Space P Space y Space t Space h Space o Space n Space 3 Space 9 Space / Space p Space y Space t Space h Space o Space n Space . Space e Space x Space e Space S p a c e`

`"Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary``2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
\-----------------------------------------------------------------------
PS C:\Users\suhaib.zuberi91_stud\Documents\Python Programs> _tkinter.TclError: couldn't open "C:/Users/suhaib.zuberi9>>
\>\> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Python39/python.exe 
"c:/Users/suhaib.zuberi91_stud/Documents/Python Programs/Personel Python Codes/gaming hours checker.py"
\>\> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Python39/python.exe "c:/Users/suhaib.zuberi91_stud/Documents/Python Programs/Personel Python Codes/gaming hours checker.py"
\>\> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Python39/python.exe "c:/Users/suhaib.zuberi91_stud/Documents/Python Programs/Personel Python Codes/gaming hours checker.py"
\>\> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Python39/python.exe "c:/Users/suhaib.zuberi91_stud/Documents/Python Programs/Personel Python Codes/gaming hours checker.py"
\>\> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Python39/python.exe "c:/Users/suhaib.zuberi91_stud/Documents/Python Programs/Personel Python Codes/gaming hours checker.py"
ocuments/Python Programs/Personel Python Codes/gaming hours checker.py"
\>\> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Python39/python.exe "c:/Users/suhaib.zuberi91_stud/Documents/Python Programs/Personel Python Codes/gaming hours checker.py"
\>\> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Python39/python.exe "c:/Users/suhaib.zuberi91_stud/Documents/Python Programs/Personel Python Codes/gaming hours checker.py"
\>\> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Python39/python.exe "c:/Users/suhaib.zuberi91_stud/Documents/Python Programs/Personel Python Codes/gaming hours checker.py"
\>\> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Python39/python.exe "c:/Users/suhaib.zuberi91_stud/Documents/Python Programs/Personel Python Codes/gaming hours checker.py"
\>\> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Python39/python.exe "c:/Users/suhaib.zuberi91_stud/D>> PS C:\Users\suhaib.zuberi91_stud\Documents\Python Programs> _tkinter.TclError: couldn't open "C:/Users/suhaib.zuberi91_stud/Documents/Python/milky_way.png": no such file or directory>>
_tkinter.TclError: : The term '_tkinter.TclError:' is not recognized as the name of a cmdlet, function, script       
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is        
correct and try again.
At line:1 char:1
\+ _tkinter.TclError: couldn't open "C:/Users/suhaib.zuberi91_stud/Docum ...
\+ ~~~~~~~~~~~~~~~~~~
    \+ CategoryInfo          : ObjectNotFound: (_tkinter.TclError::String) [], CommandNotFoundException
    \+ FullyQualifiedErrorId : CommandNotFoundException
PS C:\Users\suhaib.zuberi91_stud\Documents\Python Programs> >> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Python39/python.exe "c:/Users/suhaib.zuberi91_stud/Documents/Python Programs/Personel Python Codes/gaming hours checker.py"
At line:1 char:4
\+ \>\> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Pyth ...
\+    ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double   
quotation marks ("&") to pass it as part of a string.
    \+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    \+ FullyQualifiedErrorId : AmpersandNotAllowed
PS C:\Users\suhaib.zuberi91_stud\Documents\Python Programs> >> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Python39/python.exe "c:/Users/suhaib.zuberi91_stud/Documents/Python Programs/Personel Python Codes/gaming hours checker.py"`

There was more but a lot of it was just being repeated and it's included in the video below anyway
This wasn't the first error message that came which is why in the beginning, where it says "Last 200 Keys" it says a letter then space then another letter then space and so on, because it was the program typing that. Those keys were the program writing something earlier. Unfortunately, the first part of the text in the terminal is no longer present (I'm not sure why, it just disappeared and the text starts from somewhere in the middle) 

Here is a video of what was happening: 
https://user-images.githubusercontent.com/84507406/118970538-eef6f500-b9a0-11eb-9f8e-b71f787282ed.mp4
At the start of the video, I was scrolling through all the messages that appeared (I clicked it a few times and it kept printing)
towards the end, I was right clicking the terminal, and every time I do that, a lot of new text appears. 
Also, the text that appeared in the end was different and had different colours/formatting etc.

I'm not sure what happened towards the end, but looking at the lines in the first half of it, I feel like the issue had something to do with an "&" being in the wrong place (I haven't used that anywhere in my code).

In the video this is the part where the error messages change:
`PS C:\Users\suhaib.zuberi91_stud\Documents\Python Programs> >> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Python39/python.exe "c:/Users/suhaib.zuberi91_stud/Documents/Python Programs/Personel Python Codes/gaming hou
At line:1 char:4
\+ \>\> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programs/Python/Pyth ...
\+    ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double   
quotation marks ("&") to pass it as part of a string.
    \+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    \+ FullyQualifiedErrorId : AmpersandNotAllowed`
 
`PS C:\Users\suhaib.zuberi91_stud\Documents\Python Programs> >> & C:/Users/suhaib.zuberi91_stud/AppData/Local/Programsrs checker.
\>\> Oops, something went wrong.  Please report this bug with the details below.
\>\> Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
\>\> -----------------------------------------------------------------------
\>\> Last 200 Keys:
\>\>  s Space c h e c k e r . p y " Enter`

You can see that the terminal was printing a path in line 3 and then is was cut off at "hou" (it's supposed to be gaming hours checker) and it was continued in line 13 after "Python Programs" and then there's the message telling me to report this

Looking back, I feel like I might've accidently typed something in the terminal but there's no way of telling because the first part of the text in the terminal was cut off, I can't see it anymore. 

Any advice/support will be appreciated, thanks in advance!

Note: Apologies in advance if my writing style doesn't comply with GitHub standards, I honestly just created an account here to report this. I'm aware that I am terrible at explaining what happened, so I've attached the video, you can ask me any question you want.

**Comment by Flamingsides** [comment]
I'm not sure why my report is formatted so weirdly, sorry about that
