### ISSUE TITLE
PSReadline crashed on daily build

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/PSReadLine#2495]
### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.0-daily20210525.1
OS: Darwin 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64
BufferWidth: 125
BufferHeight: 41

Last 0 Keys
```

```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

start pwsh from the 7.2.0-daily20210525.1 build on macOS

## Expected behavior

pwsh should start

## Actual behavior

```
### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.0-daily20210525.1
OS: Darwin 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64
BufferWidth: 125
BufferHeight: 41

Last 0 Keys
```

```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```

## work around

launch with `pwsh-daily -noprofile -noninteractive`

**Comment by TravisEz13** [comment]
repros with beta 2 of psreadline as well

**Comment by daxian-dbw** [comment]
A breaking change to the command prediction experimental feature was merged on 5/20, and now changes to PSReadLine need to be done to work with the new interface. For now, I'm afraid you will have to switch to PSReadLine 2.1.0 temporarily, or you can use -noninteractive when working with the latest bits for the time being. The PSReadLine side changes are done, but the release of it will have to wait until after the next preview release of PowerShell because it depends on the NuGet packages.

**Comment by iSazonov** [comment]
Dup #2482

**Comment by HerbM** [comment]
7.2.0-preview.7 and PSReadLine 2.2.0  beta3 seem to be working on first examination.

(7.2.0-preview.5 and PSReadLine 2.2.0  beta3 did not work together.)
