### ISSUE TITLE
Error when running a python program

### ISSUE THREAD

**Issue by xphile1998** [PowerShell/PSReadLine#2520]
Last 197 Keys:
 & Space C : / U s e r s / x p h i l / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o n 3 9 / p y t h o n . e x e Space " c : / U s e r s / x p h i l / O n e D r i v e / D o c u m e n t s / O n e D r i v e / D o c u m e n t s / B Y U Space P a t h w a y Space W o r l d w i d e Space C o u r s e / T 3 Space - Space C S E P C 1 1 0 Space - Space P r o g r a m m i n g Space B a s i c s / t e s t i n g . p y " Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()  
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c) 
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()    
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by xphile1998** [comment]
This was the code running...

from PIL import Image
print("Installed correctly")
