### ISSUE TITLE
DMA Tool :: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.

### ISSUE THREAD

**Issue by francesco1119** [PowerShell/PSReadLine#2537]
I'm using the DMA Tool to Assess databases in bulk. 
I'm never assessing more than 10 server at the same time and I have 16GB of RAM in my machine freshly installed 4 weeks ago. 

Yesterday night I was running the DMA Tool and I went to bed as it was looking stuck. 
I was investigating just 1 server with less then 10 databases on it. 

```
PS C:\temp\DMACMD Assessment\ExpressVending.local>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

<img width="1035" alt="Screenshot 2021-06-02 101207" src="https://user-images.githubusercontent.com/3397477/120448196-9d307080-c38b-11eb-87a0-dd637c71b8ec.png">

**Comment by francesco1119** [comment]
I run the DMA Tool from the GUI. 
It now gives me the `protocol error 0x112f` when I connect through RDC to the machine. 
I believe the DMA tool is saturating the memory. 

This is so strange because I haven't experienced this assessing many more servers and databases

**Comment by francesco1119** [comment]
The problem is definitely the memory. 

Even after I closed the DMA Tool memory and CPU stay saturated making the OS eventually crash: 

![image](https://user-images.githubusercontent.com/3397477/120474773-e4792a00-c3a8-11eb-8839-0950eea2db08.png)

This is something that should be reported to the DMA Tool Team
