### ISSUE TITLE
These dialogues are shown on my terminal screen. Have a look on it.

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#2547]
Last 200 Keys:
 Space { Space g + + Space n . c p p Space - o Space n Space } Space ; Space i f Space ( $ ? ) Space { Space . \ n Space } Enter
 c d Space " c : \ G A M E S \ P r o j e c t s \ c o d e _ c h e f \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space n . c p p Space - o Space n Space } Space ; Space i f Space ( $ ? ) Space { Space . \ n Space } Enter
 c d Space " c : \ G A M E S \ P r o j e c t s \ c o d e _ c h e f \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space n . c p p Space - o Space n Space } Space ; Space i f Space ( $ ? ) Space { Space . \ n Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 11.
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
No environment data is provided to help the triage/investigation, please follow the bug template to provide needed information.

This issue is likely a dup of #1306, which was already fixed. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
