### ISSUE TITLE
System.UnauthorizedAccessException: Access to the path 'PSReadLineHistoryFile_1679151030' is denied.

### ISSUE THREAD

**Issue by animesh303** [PowerShell/PSReadLine#2586]
## Environment

```none
PS version: 5.1.17763.1971
PSReadline version:
os: 10.0.17763.1 (WinBuild.160101.0800)
PS file version: 10.0.17763.1 (WinBuild.160101.0800)
HostName: ConsoleHost
BufferWidth: 171
BufferHeight: 3000
```

## Exception report

```
System.UnauthorizedAccessException: Access to the path 'PSReadLineHistoryFile_1679151030' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNew, MutexSecurity mutexSecurity)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce
Launch a Powershell session and just press enter. 

## Expected behavior
Powershell prompt without any error. 

## Actual behavior
Powershell prompt with error. 

## Powershell version
```
### Environment
PSReadLine: 2.1.0
PowerShell: 5.1.17763.1971
OS: Microsoft Windows 10.0.17763
BufferWidth: 171
BufferHeight: 3000
```

**Comment by daxian-dbw** [comment]
Does this issue happen to you consistently? I cannot reproduce the issue.

**Comment by animesh303** [comment]
> Does this issue happen to you consistently? I cannot reproduce the issue.

Hello! Yes. It happens consistently. The only workaround to have a cleaner prompt is to remove this module for each Powershell session as below. But don't have any permanent fix. 

```
Add-Content -Value "`r`n Remove-Module PSReadline" -Path $PsHome\Profile.ps1
Add-Content -Value "`r`n Remove-Module PSReadline" -Path $PsHome\Microsoft.PowerShellISE_profile.ps1
```

**Comment by iSazonov** [comment]
Perhaps AV blocks the file temporary?

**Comment by animesh303** [comment]
> Perhaps AV blocks the file temporary?

There is no AV installed. Tried disabling the Windows defender service as well. Still, the problem persists.

**Comment by daxian-dbw** [comment]
`PSReadLineHistoryFile_1679151030` is the mutex name, not a file. I cannot reproduce the issue and have no idea why this would happen. @animesh303 Did you run PowerShell with 2 different user credentials?
