### ISSUE TITLE
issue? 

### ISSUE THREAD

**Issue by jhbooth** [PowerShell/PSReadLine#259]
I don't use any of the fancy package stuff, just an old-fashioned "git pull" to get the latest source, then rebuild in Visual Studio. I did a pull yesterday and am now getting this:

C:\Users\James > cd .\Documents\
C:\Users\James\Documents > cd .\Documents\
Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 10 Keys:
 c d Spacebar d o c Tab Enter
 UpArrow Backspace

Exception:
System.Management.Automation.RuntimeException: Unable to find type [PSConsoleUtilities.PSConsoleReadLine]. Make sure tha
t the assembly that contains this type is loaded.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exc
eption)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean crea
teLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Obj
ect dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClassa.<InvokeWithPipe>b__8()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, Dictionary`2 functionsToDefine, Lis
t`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis,
 Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvoke(Object dollarUnder, Object input, Object[] args)
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass67.<ProcessOneKey>b__65() in e:\src\PSReadLine\PSReadLine\
ReadLine.cs:line 460
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass63.<CalloutUsingDefaultConsoleMode>b__62() in e:\src\PSRea
dLine\PSReadLine\ReadLine.cs:line 440
   at Microsoft.PowerShell.PSConsoleReadLine.CalloutUsingDefaultConsoleMode[T](Func`1 func) in e:\src\PSReadLine\PSReadL
ine\ReadLine.cs:line 430
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg) in e:\src\PSReadLine\PSReadLine\ReadLine.cs:line 460
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop() in e:\src\PSReadLine\PSReadLine\ReadLine.cs:line 358
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics) in e:\src\PS
## ReadLine\PSReadLine\ReadLine.cs:line 287

C:\Users\James\Documents > cd .\Documents\

The UpArrow Backspace seems to do it every time.

jhb

**Comment by lzybkr** [comment]
It's an intentional breaking change, you need to change your custom key bindings, see c986e0eae5f075f7fed36f33ca38d78ebd08c05b

**Comment by jhbooth** [comment]
Excellent thanks, figured it had to be something like that. All fixed now.
jhb
