### ISSUE TITLE
Exception: System.ArgumentOutOfRangeException: 

### ISSUE THREAD

**Issue by venkateshkamath** [PowerShell/PSReadLine#2594]
My VS code terminal gives random last 64 keys action that literally says "
 UpArrow UpArrow Backspace Backspace Backspace Backspace ...........etc. And it crashes
 
More Details
 Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -3.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)        
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
Next time you see a similar error, please copy all relevant part to when opening an issue, including the "oops ..." part, the "last 200 keys:" part and the stack trace. Besides, please provide your environment data when opening an issue, by following the bug template.
