### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by kishan1495** [PowerShell/PSReadLine#2601]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new  
-----------------------------------------------------------------------
Last 188 Keys:
 & Space C : / U s e r s / U s e r / . v i r t u a l e n v s / e f 
f i n a n c e - 8 e 2 m - B Z d / S c r i p t s / A c t i v a t e . p s 1 Enter
 & Space C : / U s e r s / U s e r / . v i r t u a l e n v s / e f 
f i n a n c e - 8 e 2 m - B Z d / S c r i p t s / p y t h o n . e x e Space c : / U s e r s / U s e r / D e s k t o p / e f f i n a n 
c e / . v s c o d e / e f f i c e n t . p y Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than 
or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)      
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)        
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 
key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
