### ISSUE TITLE
Terminal told me to log an issue - 

### ISSUE THREAD

**Issue by warrmr** [PowerShell/PSReadLine#2613]
I pasted in a Powershell function that I have written, then pressed the up arrow twice to recall the last command, gave me the message below on the first up arrow then the second up arrow showed me the command as expected. 

I assume this is because the function I pasted in before (That the first up arrow tried to recall) was too large and threw this error. 

>> }
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
Last 200 Keys:
 $ u s e r n a m e Space - P a s s w o r d Space $ p a s s w o r d Enter
 Space Space Space Space $ r e t u r n Space = Space R e s e t - C r e s t r o n D e v i c e Space - D e v i c e Space $ d e v i c e I P Space - W a i t O n l y Space - S e c u r e Space - U s e r n a m e Space $ g l o b a l : u s e r n a m e Space - P a s s w o r d Space $ g l o b a l : p a s s w o r d Space - P o r t Space $ P o r t Enter
 Space Space Space Space W r i t e - V e r b o s e Space $ r e t u r n Enter
 } Enter
 Enter
 Enter
 Enter
 UpArrow UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -19.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\mattw> Set-CrestronAuthentication -deviceIP 192.168.101.145 -username "<<Some UserName>>" -password "<<Some Password>>"

**Comment by mwtrigg** [comment]
Just as a workaround - you can `remove-module PSReadline` and paste again.
