### ISSUE TITLE
Vi mode: IndexOutOfRangeException

### ISSUE THREAD

**Issue by gwojan** [PowerShell/PSReadLine#263]
Not sure how I never noticed this one before:

Type `Esc` to enter `Normal mode`, then `C` at an empty prompt. I'm guessing the 'correct' behavior would be to simply entry `Insert mode`.

`````` PowerShell
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 LeftWindows n e w - b l Tab Spacebar - Tab Tab Spacebar w o j a n g Enter UpArrow Enter l s Spacebar / Enter Escape k A
 * a u t o e x e c * Enter Escape k A Spacebar | Spacebar r m Enter h a Enter UpArrow UpArrow Ctrl+a Ctrl+c Ctrl+C Ctrl+
c PageDown PageDown PageDown PageDown PageDown PageDown PageUp PageDown ' A Spacebar s t r i n g Tab ' . t o Tab Tab Tab
 Tab Tab Tab Tab Tab Tab Tab Tab Tab Backspace Enter Escape k h h h h h h h h h h h h h C Tab Tab Tab Tab Tab Tab Tab Ta
b Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Shift+Tab Shift+Ta
b Shift+Tab Shift+Tab Shift+Tab Shift+Tab Shift+Tab Shift+Tab Shift+Tab Tab ) Enter $ a Backspace Backspace Backspace Es
cape k I $ a Spacebar = Spacebar Enter $ a Enter $ a . r e Tab Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspa
ce Backspace Backspace Backspace Backspace Backspace Ctrl+Spacebar Backspace Backspace Backspace Backspace Escape C

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at Microsoft.PowerShell.PSConsoleReadLine.ConvertOffsetToCoordinates(Int32 offset)
   at Microsoft.PowerShell.PSConsoleReadLine.ViReplaceToEnd(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```PowerShell
``````

**Comment by srdubya** [comment]
Fixed.  Thank you for finding and submitting this issue.  

You'll hear a Ding when doing this because I'm reusing the same delete-to-end code 'D' uses.  Please let me know whether this bothers you.

**Comment by gwojan** [comment]
I can probably live with that... :wink: I was just trying to be consistent with current behavior gVim and the other shells I'm using.

Any word on your pull request from PowerShell/PSReadLine? Eventually I'd like to attempt making some of these fixes myself but I'd like to only have to deal with one codebase.

**Comment by gwojan** [comment]
@srdubya I just tested the latest bits... I can definitely live with the new behavior because there is a ding and then it changes to `Insert Mode`.

Thanks you.

**Comment by srdubya** [comment]
I've completed all of the paper work, but haven't heard anything about my pull request except the automated messages.  As far as I can tell, vi-mode will be a straight forward merge.
