### ISSUE TITLE
Report Bug

### ISSUE THREAD

**Issue by ayushukla1** [PowerShell/PSReadLine#2651]
Hello, I am Ayush Shukla pursuing engineering in Electronics and Communication Engineering from Indian Institute of Information Technology, Nagpur, Maharashtra, India. I am practising code when some error occurred in runnning of program suggestion me to report this bug here with details which I am attaching here:

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 15 Keys:
 UpArrow UpArrow Enter
 UpArrow UpArrow DownArrow Enter
 DownArrow DownArrow DownArrow DownArrow UpArrow UpArrow UpArrow DownArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -7.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.NextHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

This is details of the bug.

Thanking You.

**Comment by dennisvanderpool** [comment]
I just had the same thing, see #2652

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
