### ISSUE TITLE
Oops error when first char is "

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#266]
$profile is SamplePSReadlineProfile.ps1
- OS: Windows 7 (x64 )
- PSVersionTable
  - PSVersion - 4.0
  - WSManStackVersion - 3.0
  - SerializationVersion - 1.1.0.1
  - CLRVersion - 4.0.30319.42000
  - BuildVersion - 6.3.9600.16406
  - PSCompatibleVersions - {1.0, 2.0, 3.0, 4.0}
  - PSRemotingProtocolVersion - 2.2

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
Or email: jason@truewheels.net
-----------------------------------------------------------------------
Last 1 Keys:
 "

Exception:
System.Management.Automation.RuntimeException: Unable to find type [Microsoft.PowerShell.PSConsoleReadLine]. Make sure that the assembly that contains this type is loaded.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClassa.<InvokeWithPipe>b__8()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvoke(Object dollarUnder, Object input, Object[] args)
   at PSConsoleUtilities.PSConsoleReadLine.<>c__DisplayClass66.<ProcessOneKey>b__64()
   at PSConsoleUtilities.PSConsoleReadLine.<>c__DisplayClass62.<CalloutUsingDefaultConsoleMode>b__61()
   at PSConsoleUtilities.PSConsoleReadLine.CalloutUsingDefaultConsoleMode[T](Func`1 func)
   at PSConsoleUtilities.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()
   at PSConsoleUtilities.PSConsoleReadLine.ReadLine(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment]
You are mixing versions.  The namespace PSConsoleUtilities was renamed to Microsoft.PowerShell.  You'll need to use PSConsoleUtilities in your profile, or else yourself the latest from the repo.
