### ISSUE TITLE
Error from latest

### ISSUE THREAD

**Issue by bdukes** [PowerShell/PSReadLine#267]
I updated to latest today, and got this error when trying to copy some text I was entering

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
Or email: jason@truewheels.net
-----------------------------------------------------------------------
Last 145 Keys:
 c d Spacebar $ w w w \ w q a Tab Enter t o u c h Spacebar w e b Tab w e b . c o n Tab Enter UpArrow Enter UpArrow Enter UpArrow Enter UpArrow Enter UpArrow Enter UpArrow Enter s u d o Spacebar i i s r e s t Backspace e t Enter l s Spacebar b Backspace w e Tab b i Tab Spacebar * . e x c l u d e Enter UpArrow Spacebar | Spacebar % Spacebar { } LeftArrow Spacebar LeftArrow Spacebar m v Spacebar $ _ . f u l l n a m e Spacebar " " LeftArrow $ { } LeftArrow $ _ . D i r e c t o r y RightArrow Ctrl+Shift+LeftArrow Ctrl+Shift+LeftArrow RightArrow \ Backspace Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+LeftArrow \ LeftArrow Ctrl+Shift+LeftArrow Ctrl+Shift+LeftArrow Ctrl+Shift+LeftArrow Shift+RightArrow Ctrl+c

Exception:
System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Windows.Clipboard.Flush()
   at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)
   at System.Windows.Clipboard.SetDataInternal(String format, Object data)
   at PSConsoleUtilities.PSConsoleReadLine.Copy(Nullable`1 key, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at PSConsoleUtilities.PSConsoleReadLine.InputLoop()
   at PSConsoleUtilities.PSConsoleReadLine.ReadLine(Runspace remoteRunspace, EngineIntrinsics engineIntrinsics)

-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment]
The clipboard code has been rewritten to not use winforms or wpf - and I think I'm not letting any exceptions out of the new code, so we'll call this fixed.
