### ISSUE TITLE
Error with PageUp in Full-Screen console.

### ISSUE THREAD

**Issue by rjfmachado** [PowerShell/PSReadLine#268]
set console to full screen with alt+enter, dir c:\windows and then page up.

Exception:
System.IO.IOException: The requested operation cannot be performed in full-screen mode.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

**Comment by lzybkr** [comment]
This is #232.
