### ISSUE TITLE
Command 'powershell -version 4.0' error

### ISSUE THREAD

**Issue by ecstatic-nobel** [PowerShell/PSReadLine#269]
Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment]
Do you have more details on how to repro?  Could this be #158?
