### ISSUE TITLE
CTRL+L after running the previous command intermittently results in an error

### ISSUE THREAD

**Issue by mj-crabtree** [PowerShell/PSReadLine#2722]
as per the title
- issue occurs inside the vscode integrated terminal
- ~~unable to recreate the issue in powershell via windows terminal preview~~
- issue exists in windows terminal
- unable to recreate the issue in powershell.exe
- i've redacted a few of the keystrokes but know that they were the title of a python script its argument.

if you need anything else from me then please, let me know!

thanks

```
-----------------------------------------------------------------------    
Last 54 Keys:
 p y Enter
 p y t h o n Tab Backspace Backspace Backspace Backspace Space * * * * * * * * Tab Space * * * * * Tab Enter
 UpArrow Enter
 Ctrl+l UpArrow Enter
 Ctrl+l UpArrow Enter
 UpArrow Enter
 UpArrow Ctrl+l Enter
 Ctrl+l UpArrow Escape Ctrl+l UpArrow Enter
 UpArrow Enter
 Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -5.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

UPDATE: issue exists when using powershell via windows terminal preview

```
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -8.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
