### ISSUE TITLE
right click bug in cpp

### ISSUE THREAD

**Issue by thapa35** [PowerShell/PSReadLine#2729]

**Comment by thapa35** [comment]
Last 200 Keys:
 Space Space Space Space Space Space Space Space i f Space ( i = = b ) { Enter
 Space Space Space Space Space Space Space Space Space Space Space Space c o n t i n u e ; Enter
 Space Space Space Space Space Space Space Space } Space Space Space Space Space Space Space Space i f Space ( i = = b ) { Enter
 Space Space Space Space Space Space Space Space Space Space Space Space c o n t i n u e ; Enter
 Space Space Space Space Space Space Space Space } Space Space Space Space Space Space Space Space i f Space ( i = = b ) { Enter
 Space Space Space Space Space Space Space Space Space Space Space Space c o n t i n u e ; Enter
 Space Space Space Space Space Space Space Space } Space Space Space Space Space Space Space Space i f Space ( i = = b ) { Enter
 Space Space Space Space Space Space Space Space Space Space Space Space c o n t i n u e ; Enter
 Space Space Space Space Space Space Space Space }

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -6.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)       
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
