### ISSUE TITLE
System.IO.IOException: The parameter is incorrect.

### ISSUE THREAD

**Issue by AndreiChirap** [PowerShell/PSReadLine#2754]
Last 133 Keys:
 p i p Space l i s t Enter
 c o n d a Space e v n Backspace Backspace n v Space l i s t Enter
 c o n d a Space a c t i v a t e Space D L Enter
 Ctrl+l l Backspace p w d Enter
 l s Enter
 c d Space D Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+l l l Enter
 l s Space - l Enter
 l s Space - l a Enter
 Ctrl+l d i r Space Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+l l Enter
 Ctrl+l l Enter
 Ctrl+l c d Space Backspace Backspace Backspace Backspace Ctrl+l Ctrl+l Ctrl+l

Exception:
System.IO.IOException: The parameter is incorrect.

  at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by AndreiChirap** [comment]
The error pops only when I zoom in and press ctrl+L to clear the shell, after I zoom out the error disappears. 

Edition	Windows 10 Pro
Version	21H1
Installed on	‎7/‎22/‎2021
OS build	19043.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0
