### ISSUE TITLE
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. Parameter name: left Actual value was -1.

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#2759]
just typed  (p y t h o n Space s q l i # 4 . p y Space ") this then the exception occured.

Last 18 Keys:
 p y t h o n Space s q l i # 4 . p y Space "

Exception:
System.ArgumentOutOfRangeException: The value must be greater than 
or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by ghost** [comment]
just restarted the visual studio code again and it works... lol

**Comment by guyrleech** [comment]
![image](https://user-images.githubusercontent.com/11651939/129952558-da814f94-462c-41cf-b0dc-4e667ac1da6d.png)

Just got a similar issue with PowerShell 5.1 on Win10 21H1 and PSReadLine 2.0.0 when demonstrating ctr r history searching
