### ISSUE TITLE
Error when pasting after resizing window

### ISSUE THREAD

**Issue by Hammerite** [PowerShell/PSReadLine#2816]
- open a powershell window
- resize it by dragging the corner handle
- paste something in

"Oops, something went wrong. Please report this bug with the details below..."

Last 1 Keys:
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -18.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by Hammerite** [comment]
sometimes it doesn't print an error but it looks weird

![image](https://user-images.githubusercontent.com/609347/132010426-ee9a5930-1765-4ad3-845c-c0b9428682f7.png)
