### ISSUE TITLE
Unhandled System.IO.IOException

### ISSUE THREAD

**Issue by zhiburt** [PowerShell/PSReadLine#2822]
Hey there, I am not sure if I should open the issue in first place but it was asked by your debug message so here I am 😄.

The issue appeared on AppVeyor

https://ci.appveyor.com/project/zhiburt/expectrl/builds/40658505/job/qra7ilb9m6wafjel

To bring more context.
My program uses `ConPTY` and it closes some `HANDLE`s when necessary.

## Exception report

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:
Exception:
System.IO.IOException: The handle is invalid.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.Internal.VirtualTerminal.get_BufferWidth()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
The Win32 internal error "No process is on the other end of the pipe" 0xE9 occurred while getting console output buffer information. Contact Microsoft Customer Support Services.
```

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:
Exception:
System.IO.IOException: The handle is invalid.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.Internal.VirtualTerminal.get_BufferWidth()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
----------------------------------------------------------------------
```

**Comment by daxian-dbw** [comment]
@zhiburt you were using a pretty old version of PSReadLine (2.0.0-beta2 or prior), and it's likely that the issue was fixed in a newer version. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

**Comment by zhiburt** [comment]
Thanks for the answer.
I'll close the issue as it was addressed.
