### ISSUE TITLE
It says Report the bug

### ISSUE THREAD

**Issue by Abhishekgaded** [PowerShell/PSReadLine#2823]
Last 186 Keys:
 c d Space " d : \ E \ P r o g r a m s \ c p p _ P r o g r a m s \ Q u e s t i o n s 
- S o l v e d - F r o m - t h e - W e b s i t e s \ L e e t _ C o d e _ Q u e s t io 
 n s \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space S i n g l y - L i 
n k e d - L i s t . c p p Space - o Space S i n g l y - L i n k e d - L i s t Space } Space ; Space i f Space ( $ ? ) Space { Space . \ S i n g l y - L i n k e d - L i s 
t Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)      
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by Abhishekgaded** [comment]
Is it serious to me or for you?
 I can't figure it out so please can somebody help it out.......!

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
