### ISSUE TITLE
error pop up tell me to report it here. 

### ISSUE THREAD

**Issue by StevePark85** [PowerShell/PSReadLine#2828]
Here is the error code:

Last 200 Keys:
 6 4 \ p y t h o n . e x e ' Space ' c : \ U s e r s \ s t e v e \ . v s c o d e \ e x t e n s i o n s \ m s - p y t h o n . p y t h o n - 2 0 2 1 . 9 . 1 1 9 1 0 1 6 5 8 8 \ p y t h o n F i l e s \ l i b \ p y t h o n \ d e b u g p y \ l a u n c h e r ' Space ' 4 9 6 3 6 ' Space ' - - ' Space ' c : \ U s e r s \ s t e v e \ D e s k t o p \ c o r e Space c l a s s Space d e v e l o p m e n t \ u n i t T e s t . p y ' Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size 
in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\steve\Desktop\core class development>  c:; cd 'c:\Users\steve\Desktop\core class development'; & 'C:\Program Fil
..E...............
======================================================================
ERROR: testCorrect (__main__.TestAcReport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\steve\Desktop\core class development\unitTest.py", line 212, in testCorrect
    r = AcReport()
  File "c:\Users\steve\Desktop\core class development\AC_report.py", line 27, in __init__
    self._constructAccounts()
  File "c:\Users\steve\Desktop\core class development\AC_report.py", line 149, in _constructAccounts
    self._constructAccount(accountID)
  File "c:\Users\steve\Desktop\core class development\AC_report.py", line 143, in _constructAccount
    account = Account(None, self.acReg.regDict[accountID], self.acReg)
  File "c:\Users\steve\Desktop\core class development\AC_account.py", line 78, in __init__
    self._readTransaction()
  File "c:\Users\steve\Desktop\core class development\AC_account.py", line 230, in _readTransaction
    self.transDict = json.loads(tempData) #json.loads convert string list/tuple back to dict
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 335 (char 334)

----------------------------------------------------------------------
Ran 18 tests in 0.523s

FAILED (errors=1)
PS C:\Users\steve\Desktop\core class development>  c:; cd 'c:\Users\steve\Desktop\core class development'; & 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe' 'c:\Users\steve\.vscode\extensions\ms-python.python-2021.9.1191016588\pythonFiles\lib\python\debugpy\launcher' '49640' '--' 'c:\Users\steve\Desktop\core class development\AC_report.py'

**Comment by StevePark85** [comment]
Hope this help.

**Comment by StevePark85** [comment]
After a debugging session, i found double '}}' on one of the output file created and output by json. Delete one of it remove exception on my program end. However, i don't have any idea on what causing json to output double '}}'. Most likely due to unhandled exception on my program GUI causing json to malfunction while writing to the file. It just my guess though.
