### ISSUE TITLE
CTRL + L shortcut crashed VS Code PowerShell

### ISSUE THREAD

**Issue by fahali** [PowerShell/PSReadLine#2831]
I was running tests with `mix` from an Elixir installation.

Here is the output of the crash:
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------    
Last 136 Keys:
 m i x Space t e s t Enter
 Ctrl+b Backspace i e x Space - S Space m i x Enter
 i e x b Backspace , b a t Space Backspace Backspace Backspace Backspace Backspace . b a t Space - S Space m i x Enter
 Ctrl+l m i x Space t e s t Enter
 m i x Space t e s t Enter
 m i x Space t e s t Enter
 m i x Space t e s t Enter
 Ctrl+r f o o RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Enter
 Ctrl+c Ctrl+c Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -6.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by sutt** [comment]
Look who comes crawling back to windows
