### ISSUE TITLE
something went wrong?

### ISSUE THREAD

**Issue by msatrioh** [PowerShell/PSReadLine#2838]
Last 200 Keys:
 p r e v i e w ' Space ' - X X : + S h o w C o d e D e t a i l s I n E x c e p t i o n M 
e s s a g e s ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' - c p ' Space ' C : \ U s e r s \ T o n y Space N u g r o h o \ A p p D a t a \ R o a m i n g \ C o d 
e \ U s e r \ w o r k s p a c e S t o r a g e \ 7 7 d 1 4 1 0 3 a b e a 0 f 5 0 f 0 0 1 b 8 e b f 2 3 4 c 1 e 3 \ r e d h a t . j a v a \ j d t _ w s \ T

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)      
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by msatrioh** [comment]
This happened when i tried to run a java file. I tried running the file through cmd and it worked normally.
