### ISSUE TITLE
Error when trying to run microsoft/iis

### ISSUE THREAD

**Issue by tcsatheesh** [PowerShell/PSReadLine#286]
C:\Users\domadm>docker run microsoft/iis
Unable to find image 'microsoft/iis:latest' locally
latest: Pulling from microsoft/iis
9aaec35b61af: Pull complete
Digest: sha256:d821828ee496a825794b51a8f30369cb32791d7aaa9c7a11cd2a94e9ba3c2e27
Status: Downloaded newer image for microsoft/iis:latest
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment]
Looks like #283
