### ISSUE TITLE
hardhat bug

### ISSUE THREAD

**Issue by vikingdev92** [PowerShell/PSReadLine#2871]
Last 200 Keys:
 b l e d : Space t r u e , Enter
 Space Space Space Space Space Space Space Space r u n s : Space 2 0 0 Enter
 Space Space Space Space Space Space } Enter
 Space Space Space Space } Enter
 Space Space } , Enter
 Space Space p a t h s : Space { Enter
 Space Space Space Space s o u r c e s : Space " . / c o n t r a c t s " , Enter
 Space Space Space Space t e s t s : Space " . / t e s t " , Enter
 Space Space Space Space c a c h e : Space " . / c a c h e " , Enter
 Space Space Space Space a r t i f a c t s : Space " . / a r t i f a c t s " Enter
 Space Space } , Enter
 Space Space m o c h a : Space { Enter
 Space Space Space Space t i m e o u t : Space 2 0 0 0 0 Enter
 Space Space } Enter
 }

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -20.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\34671\Desktop\MyAllNodeProjects\First_contract> C:\Users\34671\AppData\Roaming\npm-cache\_npx\13596\node_modules\hardhat\node_modules\keccak\prebuilds\win32-x64\node.napi.node'  
>> import('hardhat/config').HardhatUserConfig
>> module.exports = {
>>   defaultNetwork: "rinkeby",
>>   networks: {
>>     hardhat: {
>>     },
>>     rinkeby: {
>>       url: "https://eth-mainnet.alchemyapi.io/v2/123abc123abc123abc123abc123abcde",
>>       accounts: [privateKey1, privateKey2, ...]
>>     }
>>   },
>>   solidity: {
>>     version: "0.5.15",
>>     settings: {
>>       optimizer: {
>>         enabled: true,
>>         runs: 200
>>       }
>>     }
>>   },
>>   paths: {
>>     sources: "./contracts",
>>     tests: "./test",
>>     cache: "./cache",
>>     artifacts: "./artifacts"
>>   },
>>   mocha: {
>>     timeout: 20000
>>   }
>> 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

**Comment by vikingdev92** [comment]
For some reason it wont let me install the newest version, saying on not administrator to install it.

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\windows\system32> Install-Module

cmdlet Install-Module at command pipeline position 1
Supply values for the following parameters:
Name[0]: PSReadLine
Name[1]:

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
WARNING: Version '2.0.0' of module 'PSReadline' is already installed at 'C:\Program
Files\WindowsPowerShell\Modules\PSReadline\2.0.0'. To install version '2.1.0', run Install-Module and add the -Force
parameter, this command will install version '2.1.0' in side-by-side with version '2.0.0'.
PS C:\windows\system32> Install-Module

cmdlet Install-Module at command pipeline position 1
Supply values for the following parameters:
Name[0]: -Force
Name[1]:
PackageManagement\Install-Package : No match was found for the specified search criteria and module name '-Force'. Try
Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PS C:\windows\system32> Install-Module

cmdlet Install-Module at command pipeline position 1
Supply values for the following parameters:
Name[0]: PSReadLine
Name[1]: -AllowPrerelease
Name[2]: -Force
Name[3]:
PackageManagement\Install-Package : No match was found for the specified search criteria and module name
'-AllowPrerelease'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PackageManagement\Install-Package : No match was found for the specified search criteria and module name '-Force'. Try
Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
   ception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PS C:\windows\system32> -PSRepository
-PSRepository : The term '-PSRepository' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ -PSRepository
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (-PSRepository:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
