### ISSUE TITLE
repeatedly it is showing to report the bug 

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#2891]
-----------------------------------------------------------------------
Last 200 Keys:
 n e . I n p u t L o o p ( ) Space Space Space Space Space Space Enter
 Space Space Space a t Space M 
i c r o s o f t . P o w e r S h e l l . P S C o n s o l e R e 
a d L i n e . R e a d L i n e ( R u n s p a c e Space r u n s 
p a c e , Space E n g i n e I n t r i n s i c s Space e n g i 
n e I n t r i n s i c s ) Enter - - - - - - - - - - - - - - - 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
- - - - - - - - - - - - - - - - - - - - - - - - -

Exception:
System.ArgumentOutOfRangeException: The value must be greater 
than or equal to zero and less 
than the console's buffer size 
in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top) 
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()    
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)   
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()      
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
