### ISSUE TITLE
error encountered when using the [system.io] namespace in powershell

### ISSUE THREAD

**Issue by arch-daemon** [PowerShell/PSReadLine#2903]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 7.1.4
OS: Microsoft Windows 10.0.19043
BufferWidth: 120
BufferHeight: 30

Last 170 Keys

 u s i o n g Backspace Backspace Backspace n g Spacebar n a m e s p a c e Spacebar s y s t e m . f i o Backspace l e . i o Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow { Backspace [ RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow ] Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace [ s s y s t e m . Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace [ s UpArrow Spacebar LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c l s Enter
 a l s d f Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace [ ] LeftArrow s
```

### Exception
```
System.Management.Automation.PSArgumentException: Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.
   at System.Management.Automation.Language.TypeName..ctor(IScriptExtent extent, String name)
   at System.Management.Automation.Language.TypeResolver.ResolveTypeNameWithContext(TypeName typeName, Exception& exception, Assembly[] assemblies, TypeResolutionState typeResolutionState)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeName(TypeName typeName, Int32 genericArgumentCount, Boolean isAttribute)
   at System.Management.Automation.Language.SymbolResolver.DispatchTypeName(ITypeName type, Int32 genericArgumentCount, Boolean isAttribute)
   at System.Management.Automation.Language.SymbolResolver.VisitTypeExpression(TypeExpressionAst typeExpressionAst)
   at System.Management.Automation.Language.TypeExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.CommandExpressionAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.PipelineAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.StatementBlockAst.InternalVisit(AstVisitor visitor, ReadOnlyCollection`1 traps, ReadOnlyCollection`1 statements, AstVisitAction action)
   at System.Management.Automation.Language.NamedBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.ScriptBlockAst.InternalVisit(AstVisitor visitor)
   at System.Management.Automation.Language.Ast.Visit(AstVisitor astVisitor)
   at System.Management.Automation.Language.SymbolResolver.ResolveSymbols(Parser parser, ScriptBlockAst scriptBlockAst)
   at System.Management.Automation.Language.ScriptBlockAst.PerformPostParseChecks(Parser parser)
   at System.Management.Automation.Language.Parser.ParseTask(String fileName, String input, List`1 tokenList, Boolean recursed, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.Parse(String fileName, String input, List`1 tokenList, ParseError[]& errors, ParseMode parseMode)
   at System.Management.Automation.Language.Parser.ParseInput(String input, String fileName, Token[]& tokens, ParseError[]& errors)
```

### Screenshot

[error.zip](https://github.com/PowerShell/PSReadLine/files/7262478/error.zip)

### Environment data

```console
PS Version: 7.1.4
PS HostName: ConsoleHost
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 9001
```

### Steps to reproduce

Windows Terminal
Version: 1.10.2383.0

I'm running powershell in windows terminal. when keying in the system file namespace, powershell would display the error message.

### Expected behavior

invoking the namespace to pipe to get-member

### Actual behavior

receiving the message above

**Comment by daxian-dbw** [comment]
@arch-daemon Thanks for reporting the issue. This is an exception thrown from the PowerShell parser. Can you be more specific with your repro steps? I cannot reproduce the issue with what you put in the "Steps to reproduce" section.
