### ISSUE TITLE
"ls" command System.IO.Exception: "The parameter is incorrect"

### ISSUE THREAD

**Issue by paulneumeyer** [PowerShell/PSReadLine#2904]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
PS C:\my_pode\RBAC> ls

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 i p t s Space f r o m Space [ p Backspace Backspace p r o d u c t i o n Space d i r e c o r y Backspace Backspace Backspace t o r y , Space a s Space t h e y Space a r e Space n o t Space p r o d Space a n d Space w e Space a d d e d Space j u s t Space t o Space t e s t Space t h e Space p r o d Space b u i l d Space a n d Space d e s t r o y " Enter
 g i t Space p u s h Enter
 l s Space - l a Backspace Backspace Backspace Backspace Backspace Backspace Backspace g i t Space s t a t u s Enter
 g i t Space Backspace Backspace Backspace Backspace l s Space - l a Backspace Backspace Backspace Backspace Backspace Backspace Backspace m k a e Space Backspace Backspace Backspace Backspace a k e Space b u i l d - d e v Enter
 ` ` l s Space Enter


Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Environment data

```console
PS Version: 5.1.19041.1237
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 93
BufferHeight: 3000
```

### Steps to reproduce

None - one off. I'e tried to reproduce with the same "ls " command, also "ls".
Also the previous "make build-dev" then "ls " incase there was some interaction.   

### Expected behavior

the command "ls" has never failed before 

### Actual behavior

The reported error, as above.  When retrying "ls" it worked and listed the directory contents

**Comment by paulneumeyer** [comment]
I missed that the installed PSReadline Version was not the latest version.  I have updated PSReadLine from 2.0.0-beta2 to 2.1.0.
