### ISSUE TITLE
PowerShell 7.2.0 preview 10 Exception on first load after PS upgrade.

### ISSUE THREAD

**Issue by dembeck** [PowerShell/PSReadLine#2906]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Loading personal and system profiles took 673ms.
PS C:\>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.0-preview.10
OS: Microsoft Windows 10.0.22468
BufferWidth: 120
BufferHeight: 9001

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

![image](https://user-images.githubusercontent.com/9568447/135703083-bee9f35e-99c7-4ad8-bb3e-e93d6cefa248.png)


### Environment data

```console
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.0-preview.10
OS: Microsoft Windows 10.0.22468
BufferWidth: 120
BufferHeight: 9001

I can't run anything in PS 7.2.0-preview.10 but here is the info from PS 7.1.4 that uses the same profile.

PS Version: 7.1.4
PS HostName: ConsoleHost
PSReadLine Version: 2.2.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.22468.1000 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 9001
```

### Steps to reproduce

1. Download PS 7.2.0 Preview 10 x64 msi from GitHub
2. Upgrade PS 7.2.0 to Preview 10
3. Open PS 7.2.0 Preview 10 after upgrade

### Expected behavior

No errors or exceptions on load.

### Actual behavior

Was working fine before upgrading PS 7.2.0 to preview 10. On first load and every attempt after upgrading I receive the same error whether loaded as admin or not, or loaded with the -NoProfile switch or not.

**Comment by daxian-dbw** [comment]
This is a known issue and has been addressed in 2.2.0-beta3 release of PSReadLine. Please upgrade to use 2.2.0-beta3 with the latest 7.2.0-preview.9 PowerShell.
