### ISSUE TITLE
Container crashes running locally - div by zero error

### ISSUE THREAD

**Issue by dirtyrandy** [PowerShell/PSReadLine#2907]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.

Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.

Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md

Thank you!


### Environment

PSReadLine: 2.1.0

PowerShell: 7.1.4

OS: Linux 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021

BufferWidth: 0

BufferHeight: 0


Last 200 Keys



 8 Ctrl+n Ctrl+n ' 1 V @ @ Spacebar @ @ @ @ @ @ @ @ X � O f 7 R O 8 Ctrl+n Ctrl+n ' 1 V @ @ Ctrl+b @ @ @ @ @ @ @ � V Backspace a 9 Backspace @ @ � > \ " : Backspace @ @ � W � | 9 Backspace @ @ @ X � O f 7 R O @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ( + 6 � 9 Backspace @ @ X A d " : Backspace @ @ Spacebar X Backspace a 9 Backspace @ @ ! Ctrl+k  " : Backspace @ @ � U # @ @ @ @ @ X A d " : Backspace @ @ @ @ @ @ @ @ @ @ � V Backspace a 9 Backspace @ @ Spacebar W Backspace a 9 Backspace @ @ " Y  " : Backspace @ @ @ @ @ @ @ @ @ @ S � Ctrl+t � 9 Backspace @ @ � W Backspace a 9 Backspace @ @ � + < � 9 Backspace @ @

```

### Exception

```

System.DivideByZeroException: Attempted to divide by zero.

   at Microsoft.PowerShell.PSConsoleReadLine.PhysicalLineCount(Int32 columns, Boolean isFirstLogicalLine, Int32& lenLastPhysicalLine)

   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)

   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()

   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)

   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)

   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)

```

PS /> PS /> GProcess terminated. The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')

Actual value was -1.

   at System.Environment.FailFast(System.String, System.Exception)

   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)

   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')

Actual value was -1.

   at System.Console.SetCursorPosition(Int32 left, Int32 top)

   at System.Console.set_CursorLeft(Int32 value)

   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineFromConsole(Boolean endOnTab, String initialContent, Boolean calledFromPipeline, String& restOfLine, ReadLineResult& result) in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs:line 1796

   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLine(Boolean endOnTab, String initialContent, ReadLineResult& result, Boolean calledFromPipeline, Boolean transcribeResult) in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs:line 1431

   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineWithTabCompletion(Executor exec) in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs:line 1906

   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested) in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs:line 2476

   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested) in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs:line 2327

   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt() in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs:line 1027

   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName) in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs:line 1496

   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned) in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs:line 1463

   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText) in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs:line 250

   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc) in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ManagedEntrance.cs:line 99
```


### Screenshot

N/A

### Environment data

```console
N/A - host won't stay alive long enough to run
```

### Steps to reproduce

Literally just run the image, it'll crash soon enough.

### Expected behavior

Container does not crash on a whim.

### Actual behavior

Container crashes on a whim.

**Comment by daxian-dbw** [comment]
This is a duplicate of #2844 and #670, please see the comments https://github.com/PowerShell/PSReadLine/issues/2844#issuecomment-921047295, and https://github.com/PowerShell/PSReadLine/issues/670#issuecomment-921040014
