### ISSUE TITLE
An error occurs when trying to clear the screen using Ctrl+l

### ISSUE THREAD

**Issue by jvdon** [PowerShell/PSReadLine#2913]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Last 81 Keys:
 ` l s Enter
 l s Space - L a Enter
 Ctrl+l l s Space - N a m e Enter
 UpArrow Backspace Backspace Backspace Backspace D i r Enter
 c l s Enter
 c l s Enter
 c l s Enter
 c l s Enter
 c l Enter
 s c l s l Backspace Backspace Backspace Backspace Backspace c l s Enter
 Ctrl+l ` l s Enter
 c d Space 3 d Tab Backspace Tab Enter
 l s Enter
 Ctrl+l

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.1237
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 158
BufferHeight: 3000
```

### Steps to reproduce

Pressing Ctrl+l at any point to clear the screen.

### Expected behavior

This shortcut is supposed to clear the screen similar to Linux terminal behavior.

### Actual behavior

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by daxian-dbw** [comment]
This was already fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
