### ISSUE TITLE
Can't enter my documents folder

### ISSUE THREAD

**Issue by ksimple** [PowerShell/PSReadLine#294]
---

Last 11 Keys:
 c d Spacebar d o c Tab Enter
 d i r

Exception:
System.IO.IOException: The file or directory is corrupted and unreadable.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeReadHistoryFile()
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Func`2 fileOpener)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean readingHistoryFile, Boolean fromDifferentSession)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

**Comment by lzybkr** [comment]
Is it safe to say the exception was accurate?  Maybe I should just report IOException messages w/o all the extra stuff when reading/writing the history file.
