### ISSUE TITLE
Terminal Error 

### ISSUE THREAD

**Issue by JamesRobionyRogers** [PowerShell/PSReadLine#2943]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
-----------------------------------------------------------------------
Last 200 Keys:
 F i l e s \ J a v a \ j d k - 1 6 \ b i n \ j a v a . e x e ' Space ' - X X : + S h o w C o d e D e t a i l s I n E x c e p t i o n M e s s 
a g e s ' Space ' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' @ C : \ U s e r s \ J A M E S R ~ 1 \ A p p D a t a \ L o c a l \ T e m p \ c p _ k x l c 4 b x o 3 w g 1 1 7 0 y d l l 5 0 w 7 j 1 . a r g f i l e ' Space ' c o m . r o b i o n y r o g e r s . G U I ' Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -3.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.1237
PS HostName: ConsoleHost  
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 141
BufferHeight: 32
```

### Steps to reproduce

I was running some Java code through VS Code 

### Expected behavior

The intended Java project to run without any errors 

### Actual behavior

Java project ran, however the PowerShell error popped up in the terminal

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
