### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by snapdeus** [PowerShell/PSReadLine#2944]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 o d e Space p u Tab i n Backspace Backspace s Backspace l e Tab Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 Ctrl+l UpArrow Enter
 Ctrl+l UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 g i t Space a d d Space . Enter
 g i t Space c o m m i t Space - m Space ' l e t t e r s . j s Space a d d e d , Space d e s i g n s Space a d d , Space s Backspace Backspace Backspace Backspace d e d , Space w o r k i n g Space w i t h Space g e n e r a t i f e Space Backspace Backspace v Backspace Backspace v Space d e s i g n Space l i b r a r i e s Space a d d e d ' Enter
 g i t Space p u s h Enter
 Ctrl+l UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -12.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

![image](https://user-images.githubusercontent.com/44621390/140007470-8c57d9a7-df71-4ba9-bb10-96f0250f594a.png)

### Environment data

```console
PS Version: 5.1.19041.1237     
PS HostName: ConsoleHost       
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 284
BufferHeight: 52
```

### Steps to reproduce

hit ctrl+l and wish for the best

### Expected behavior

clear the screen

### Actual behavior

threw out of range exception

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1315). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
