### ISSUE TITLE
Invoking Powershell.exe as child process from 32 Bit application caused this issue

### ISSUE THREAD

**Issue by jaimin76** [PowerShell/PSReadLine#296]
Oops, something went wrong.  Please report this bug with the details below.

Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

---

Last 0 Keys:

Steps to reproduce  

1) On windows 10, From 32 Bit application invoke powrshell.exe 

Exception:

System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)

   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)

   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

---

**Comment by fsoikin** [comment]
Same here.

**Comment by lzybkr** [comment]
This looks like a dupe of #158.  If you think otherwise, I need more repro details.
