### ISSUE TITLE
System.IO.IOException: The handle is invalid

### ISSUE THREAD

**Issue by desrioux** [PowerShell/PSReadLine#297]
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment]
This looks like a dupe of #158
