### ISSUE TITLE
Bug when first running PowerShell 7.2

### ISSUE THREAD

**Issue by stephenjwalter** [PowerShell/PSReadLine#3027]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.0
OS: Microsoft Windows 10.0.19043
BufferWidth: 120
BufferHeight: 30

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

The above error happened the first time I ran PWSH 7.2 (which had automatically updated) within Windows Terminal. When the error happens, the PowerShell session is unusable, so I can't generate the environment data requested below.
Fortunately Powershell 7.1.n remains available from within Windows Terminal, so I've defaulted to that.



### Environment data

```console
PS Version: 7.1.4
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

1. Start PowerShell 7.2
2. That's all that's needed

### Expected behavior

Powershell to run without error

### Actual behavior

The above described error happens

**Comment by iSazonov** [comment]
Please update to latest Beta4 version.

**Comment by stephenjwalter** [comment]
Many thanks for the quick response.  I went with going to the beta-3 release. Works a treat.

**Comment by daxian-dbw** [comment]
@stephenjwalter it would be better to try out the beta4 release, which further improves the stability.
