### ISSUE TITLE
PowerShell fails to start

### ISSUE THREAD

**Issue by catleypa** [PowerShell/PSReadLine#3034]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.0
OS: Microsoft Windows 10.0.19043
BufferWidth: 138
BufferHeight: 70

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

![image](https://user-images.githubusercontent.com/50685649/141697551-d4f041be-31ce-497c-9068-9632ac8e788d.png)


### Environment data

```console
Cannot execute the script, pwsh is borked
```

### Steps to reproduce

Start Powershell 7.20

### Expected behavior

Would start without error

### Actual behavior

Fails to start and outputs exception

**Comment by pcopley** [comment]
Same error here ever since upgrade from `7.1.4` to `7.2.0`. `Set-PSReadLineOption -PredictionViewStyle ListView` in `C:\users\pcopley\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:652:1` is throwing the exception.
