### ISSUE TITLE
PSReadLine 2.2.0-beta2 error

### ISSUE THREAD

**Issue by psdarwin** [PowerShell/PSReadLine#3037]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.0
OS: Microsoft Windows 10.0.18363
BufferWidth: 120
BufferHeight: 9001

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

![image](https://user-images.githubusercontent.com/75449806/141804861-22c38afe-2b7d-46f9-834d-d590dd3f869b.png)


### Environment data

```console
PS Version: 7.2.0
PS HostName: ConsoleHost
PSReadLine Version: 2.2.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.18362.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 9001
```

### Steps to reproduce

This happens whenever I load PS7

### Expected behavior

No exception

### Actual behavior

The exception happens when PS7 loads, and for each cmdlet entered.

**Comment by psdarwin** [comment]
This might be a duplicate of https://github.com/PowerShell/PSReadLine/issues/2993.  Checking if the fix there works...

**Comment by psdarwin** [comment]
This worked:  
Install-Module PSReadLine -AllowPrerelease -Force
