### ISSUE TITLE
Error with Set-StrictMode in Profile

### ISSUE THREAD

**Issue by Bluecakes** [PowerShell/PSReadLine#304]
Hey,

Awesome tool, love it, recently decided i would use the Set-StrictMode cmdlet of powershell to force myself into better coding practices and i may have found a bug/error within PSReadLine.

Using the default SamplePSReadlineProfile.ps1 i was able to reproduce the issue by adding as the first line:

```
Set-StrictMode -Version Latest

...
PSReadLine setup here
...
```

```
PS E:\pshell> . "E:\pshell\modules\PSReadline\SamplePSReadlineProfile.ps1"
PS E:\pshell>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
Or email: jason@truewheels.net
-----------------------------------------------------------------------
Last 1 Keys:
 "

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CallSite.Target(Closure , CallSite , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
-----------------------------------------------------------------------
PS E:\pshell>
```

I'm using Windows 10 with PowerShell 5, i was also able to reproduce the error on Windows 8.1 with PowerShell 5 installed. Here is my Get-Host info for reference:

```
Name             : ConsoleHost
Version          : 5.0.10240.16384
InstanceId       : aa1431fe-d3ec-4d3c-8e56-65a572a5e59a
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-AU
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

**Comment by lzybkr** [comment]
The bug is in the sample profile, not in PSReadline proper.  I need to fix the sample, and also improve the error message to blame a custom handler and not suggest reporting a bug.
