### ISSUE TITLE
PowerShell 7.2.0 throws exception: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' on start up.

### ISSUE THREAD

**Issue by jghek** [PowerShell/PSReadLine#3044]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

![image](https://user-images.githubusercontent.com/48162144/142199664-70bce380-f32d-4878-a9eb-a443e546ea94.png)


### Environment data

```console
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.0
OS: Microsoft Windows 10.0.22000
BufferWidth: 120
BufferHeight: 30

Last 0 Keys


```
```


### Steps to reproduce

Start PowerShell in windows terminal, by clicking arrow down, PowerShell

### Expected behavior

Powershell to start and see prompt.

### Actual behavior

It throws an exception.

**Comment by jghek** [comment]
Smart bot... Issue was fixed. Thanks.
