### ISSUE TITLE
pwsh 7.2.0 only working with PSReadLine 2.2.0-beta3, not beta 4

### ISSUE THREAD

**Issue by JanRK** [PowerShell/PSReadLine#3066]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.0-beta4
PowerShell: 7.2.0
OS: Microsoft Windows 10.0.19043
BufferWidth: 250
BufferHeight: 9001

Last 0 Keys:



### Exception

System.InvalidCastException: Unable to cast object of type 'System.Management.Automation.Language.ErrorExpressionAst' to type 'System.Management.Automation.Language.CommandAst'.
   at Microsoft.PowerShell.PSConsoleReadLine.GetArgumentForParameter(CommandParameterAst param)
   at Microsoft.PowerShell.PSConsoleReadLine.GetDefaultAddToHistoryOption(String line)
   at Microsoft.PowerShell.PSConsoleReadLine.GetAddToHistoryOption(String line)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.UpdateHistoryFromFile(IEnumerable`1 historyLines, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.<ReadHistoryFile>b__102_0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadHistoryFile()
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![image](https://user-images.githubusercontent.com/14318004/143413301-e10adbb6-5eee-4b41-9b89-4a467d5c3e64.png)

### Environment data

```console
PS Version: 7.2.0
PS HostName: ConsoleHost
PSReadLine Version:
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 250
BufferHeight: 9001
```

### Steps to reproduce

Upgrading to pwsh 7.2.0 and running 
```
pwsh -noprofile -noninteractive -command "Install-Module -Name PSReadLine -AllowPrerelease -RequiredVersion 2.2.0-beta4 -Force -AllowClobber"
```

Installing beta3 makes pwsh work again
```
pwsh -noprofile -noninteractive -command "Install-Module -Name PSReadLine -AllowPrerelease -RequiredVersion 2.2.0-beta3 -Force -AllowClobber"
```

### Expected behavior

Working pwsh

### Actual behavior

Crashing pwsh.

**Comment by daxian-dbw** [comment]
@JanRK Can you please try out this private version of PSReadLine and see if it fixes problem you run into?
[PSReadLine.zip](https://github.com/PowerShell/PSReadLine/files/7621739/PSReadLine.zip)

**Comment by JanRK** [comment]
> @JanRK Can you please try out this private version of PSReadLine and see if it fixes problem you run into? [PSReadLine.zip](https://github.com/PowerShell/PSReadLine/files/7621739/PSReadLine.zip)

This appears to have solved it, thanks!

**Comment by daxian-dbw** [comment]
@JanRK Thanks for trying the fix! I'm having trouble to identity a test case for the issue you ran into, can you please do me a favor to try out the following private build again? This private build will print out the history entry that caused the parsing error and triggered the exception you saw. Could you please try it out and paste the history entry here, so that I can use it as a test case?

Thank you in advance!

[PSReadLine-print-culprit-history-entry.zip](https://github.com/PowerShell/PSReadLine/files/7627796/PSReadLine-print-culprit-history-entry.zip)

**Comment by JanRK** [comment]
I doesn't give me any output.

```
C:\Users\jan>pwsh -executionpolicy bypass -noprofile
PowerShell 7.2.0
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\jan> get-module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.2.0      beta4      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …

PS C:\Users\jan>
```

Btw this error occurs on multiple computers.

**Comment by daxian-dbw** [comment]
It will print out the culprit line only if the issue occurs. So, you didn't run into the same error again after using the `PSReadLine-print-culprit-history-entry.zip` package?

If you can still run into this issue on a computer, please replace the PSReadLine used on that computer with `PSReadLine-print-culprit-history-entry.zip` shared in https://github.com/PowerShell/PSReadLine/issues/3066#issuecomment-982882945, and then try triggering the same error. Once that error is triggered, the culprit line will be printed out.

**Comment by JanRK** [comment]
Here is the output, looks the same as beta4?

Beta3:
![Beta3-OK](https://user-images.githubusercontent.com/14318004/144289253-2cab9497-c49f-4736-863c-1586a68ec4bf.PNG)

Beta4:
![Beta4-Error](https://user-images.githubusercontent.com/14318004/144289284-9a8e2bbe-278d-472c-be6f-ed885afdf570.PNG)

PSReadLine-print-culprit-history-entry.zip:
<img width="1457" alt="print-culprit-Error" src="https://user-images.githubusercontent.com/14318004/144289332-fecc1b7e-218b-4756-846d-d569c203efd0.PNG">

**Comment by daxian-dbw** [comment]
I'm so sorry that I made a dumb mistake in that `PSReadLine-print-culprit-history-entry.zip` private build -- I made it print the string `line` instead of the variable `line` in my last change ...

![image](https://user-images.githubusercontent.com/127450/144292606-e03d3e22-c128-4413-af1d-2ad75aeb3040.png)

And thus, it only prints out `line` for you ...

![image](https://user-images.githubusercontent.com/127450/144292551-146bf545-5699-418d-a34b-901b98e88be7.png)

I have corrected it to print out the actual variable `line`, and here is the new private build:
[PSReadLine-print-culprit-NEW.zip](https://github.com/PowerShell/PSReadLine/files/7636371/PSReadLine-print-culprit-NEW.zip)

Could you please try again with this new build? It should print out the culprit history line this time. Thank you!

**Comment by JanRK** [comment]
Now I got a line:
![image](https://user-images.githubusercontent.com/14318004/144296619-deb15664-36a9-4bae-b4d8-72bc251c942f.png)

```
### Exception

System.InvalidCastException: Unable to cast object of type 'System.Management.Automation.Language.ErrorExpressionAst' to type 'System.Management.Automation.Language.CommandAst'.
   at Microsoft.PowerShell.PSConsoleReadLine.GetArgumentForParameter(CommandParameterAst param) in C:\arena\source\PSReadLine\PSReadLine\History.cs:line 535
   at Microsoft.PowerShell.PSConsoleReadLine.GetDefaultAddToHistoryOption(String line) in C:\arena\source\PSReadLine\PSReadLine\History.cs:line 623
   at Microsoft.PowerShell.PSConsoleReadLine.GetAddToHistoryOption(String line) in C:\arena\source\PSReadLine\PSReadLine\History.cs:line 162
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead) in C:\arena\source\PSReadLine\PSReadLine\History.cs:line 206
   at Microsoft.PowerShell.PSConsoleReadLine.UpdateHistoryFromFile(IEnumerable`1 historyLines, Boolean fromDifferentSession, Boolean fromInitialRead) in C:\arena\source\PSReadLine\PSReadLine\History.cs:line 487
   at Microsoft.PowerShell.PSConsoleReadLine.<ReadHistoryFile>b__102_0() in C:\arena\source\PSReadLine\PSReadLine\History.cs:line 459
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action) in C:\arena\source\PSReadLine\PSReadLine\History.cs:line 313
   at Microsoft.PowerShell.PSConsoleReadLine.ReadHistoryFile() in C:\arena\source\PSReadLine\PSReadLine\History.cs:line 456
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize() in C:\arena\source\PSReadLine\PSReadLine\ReadLine.cs:line 858
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics) in C:\arena\source\PSReadLine\PSReadLine\ReadLine.cs:line 708
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus) in C:\arena\source\PSReadLine\PSReadLine\ReadLine.cs:line 386



$environment -brand $brand -userBitWardenEmail $bwuser -userBitWardenPassword $bwpass
```

**Comment by daxian-dbw** [comment]
> `$environment -brand $brand -userBitWardenEmail $bwuser -userBitWardenPassword $bwpass`

Great! Now I'm able to reproduce the issue. That line will be my test case. Thank you!
