### ISSUE TITLE
An exception occurs when using git autocomplete commands

### ISSUE THREAD

**Issue by scaramushe** [PowerShell/PSReadLine#3068]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.1.0
PowerShell: 5.1.22000.282
OS: Microsoft Windows 10.0.22000
BufferWidth: 126
BufferHeight: 60

Last 200 Keys

 Spacebar o r i Tab H Backspace Spacebar H E A D : L Backspace s e r e Tab Ctrl+Backspace t e m p _ o v l 2 _ h w _ f e n c e _ w a Enter
 g i t Spacebar l o g Spacebar - 2 Enter
 b r a n c h e s Enter
 g i t Spacebar c h e c k Tab Spacebar d e v e Tab Enter
 g i t Spacebar l o g - 2 Enter
 UpArrow LeftArrow LeftArrow Spacebar Enter
 g i t Spacebar l o g Spacebar - 3 Enter
 UpArrow Ctrl+Backspace Ctrl+Backspace r e s e t Spacebar 0 Backspace - - h a r Tab Spacebar o r i Tab Ctrl+Backspace d e v e Tab Enter
 UpArrow UpArrow Enter
 g i t Spacebar d i f f Enter
 b u i l d Enter
 UpArrow Enter
 c d Spacebar s r c / G Tab Enter
 b u i l d Enter
 UpArrow Enter
 UpArrow UpArrow DownArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 g i t Spacebar p u s h Spacebar Backspace Backspace Backspace Backspace Backspace c Backspace l
```

### Exception
```
System.InvalidOperationException: Queue empty.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Dequeue()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![image](https://user-images.githubusercontent.com/72554978/143500814-0eda475c-2fcb-4a83-bf51-2324aee581dc.png)

### Environment data

```console
PS Version: 5.1.22000.282
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 126
BufferHeight: 60
```

### Steps to reproduce

use git with autocomplete - works fine
run msbuild
try using git with autocomplete - crash

seen once
The git itself is not in a good state - can't find the sha1 it is on so maybe it is related

### Expected behavior

Autocomplete works, no exception

### Actual behavior

The exception...

**Comment by daxian-dbw** [comment]
@scaramushe what is the git autocomplete tool you are using? Can you share a pointer?

**Comment by scaramushe** [comment]
posh-git is the autocomplete tool
