### ISSUE TITLE
Holding Ctrl+Enter in powershell(only when opened in windows terminal) raises a "System.ArgumentOutOfRangeException" after a few seconds

### ISSUE THREAD

**Issue by lev-blit** [PowerShell/PSReadLine#3069]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter Ctrl+Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -446.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.InsertLineAbove(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.1320
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

Open Windows Terminal
Open a PowerShell tab
Hold the keys Ctrl+Enter(which generate a new line with >> below where you are currently typing)
Hold until you see the exception text pop up, then you can scroll up and see the exception

### Expected behavior

No exception, just keep adding those new lines with >>. This is what happens when using PowerShell on it's own, outside of windows terminal.

### Actual behavior

If the keys are not let go, the exception is thrown multiple times throughout the process. The exception is only thrown after a few seconds of holding the keys, from the exception it seems that after 200 times of the new line being generated.

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
