### ISSUE TITLE
Problem loading PowerShell 7.2.1 on Windows Terminal

### ISSUE THREAD

**Issue by DNM1008** [PowerShell/PSReadLine#3124]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Exception

System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![image](https://user-images.githubusercontent.com/54259825/147399653-7efb3ac0-2475-4df5-8a40-7a579fdb6607.png)

### Environment data

```console
### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.1
OS: Microsoft Windows 10.0.19043
BufferWidth: 118
BufferHeight: 103

Last 0 Keys
```

### Steps to reproduce

Launching the program

### Expected behavior

No issue and PowerShell loads just fine

### Actual behavior

Error messages above

**Comment by DNM1008** [comment]
Actually, what I found helpful was to update PowerShell **THE SAME WAY** that you installed it. My mistake was that I downloaded the .msi file from github and them updated it through winget
