### ISSUE TITLE
oops. something went wrong.

### ISSUE THREAD

**Issue by ph0rd** [PowerShell/PSReadLine#3146]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.2.1
OS: Microsoft Windows 10.0.22000
BufferWidth: 197
BufferHeight: 29

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

![Screenshot 2022-01-11 062745](https://user-images.githubusercontent.com/2100410/148961394-4d6da160-76c9-4ffe-8dd7-d953a8db7f4b.jpg)


### Environment data

```console
can't. Severely fubar'd guys. Not cool.
```

### Steps to reproduce

All I did war run the MS installer, and now I'm screwed. I can't get a pwsh at all .

### Expected behavior

I should have just kept running the version I had - because it worked. This is a clear reminder to not try and fix something that isn't broken... It was just so annoying to see the "Please Upgrade" nag every time I launched a pwsh. 

### Actual behavior

Obviously... running the Terminal app would run pwsh and it wouldn't be FUBAR'd aka SWNAFU. : / Very disappointed.

**Comment by ph0rd** [comment]
Just FYI I did this and it didn't help in any way:

run pwsh -noprofile -noninteractive to start pwsh without loading PSReadLine
run Uninstall-Module -Name PSReadLine -RequiredVersion <2.2.0-beta1 or 2.2.0-beta2> -AllowPrerelease to remove the module. Or, you can manually remove that module folder.

**Comment by ph0rd** [comment]
So lame.

**Comment by ph0rd** [comment]
Sorry, but this is really costing me money and as a retired internet guy (employee 35 @ Roku) it's really not something I expected; I've learned a very hard lesson today : don't trust this dev team.
