### ISSUE TITLE
Powershell Exception on startup

### ISSUE THREAD

**Issue by kellycole** [PowerShell/PSReadLine#3147]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

I just upgraded powershell this morning.

### Environment data

```console
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.1
OS: Microsoft Windows 10.0.19044
BufferWidth: 209
BufferHeight: 58

Last 0 Keys
```

### Steps to reproduce

open powershell window

### Expected behavior

No exception

### Actual behavior

The above exception happens

**Comment by kellycole** [comment]
I tried following the first set of instructions above and got into a sign in loop with the devicelogin page. So I tried the second set of instructions and was able to uninstall the 2.2.0-beta1 PSReadline.
