### ISSUE TITLE
Not responding terminal after running version 2.2.0-beta1

### ISSUE THREAD

**Issue by BlagovestMihaylov** [PowerShell/PSReadLine#3153]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![image](https://user-images.githubusercontent.com/74532053/149370862-7fb05bd6-f7d7-4da1-9373-57f4ccfd5f6b.png)

### Environment data

```console
Does not respond
```

### Steps to reproduce

I just ran

Install-module -Name PSReadLine -RequiredVersion 2.2.0-beta1 -AllowPrerelease 

### Expected behavior

Getting listed histoty of commands in terminal

### Actual behavior

Made my terminal not responding 

![image](https://user-images.githubusercontent.com/74532053/149371757-74e51ef9-4859-4909-8e1a-e393ef8aeb61.png)

**Comment by BlagovestMihaylov** [comment]
This issue was fixed in 2.2.0-beta3 version of PSReadLine. You can fix this by upgrading to the latest 2.2.0-beta5 version of PSReadLine. Instructions for doing so:

1. stop all instances of pwsh.
2. from cmd.exe on Windows or bash on Linux, run: pwsh -noprofile -command "Install-Module PSReadLine -AllowPrerelease -Force"
