### ISSUE TITLE
an error has occured

### ISSUE THREAD

**Issue by twangithub** [PowerShell/PSReadLine#3156]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.1.0
PowerShell: 7.2.1
OS: Microsoft Windows 10.0.19042
BufferWidth: 119
BufferHeight: 29

Last 200 Keys

 l d Spacebar - t Spacebar a g i l - r e n d e r - s e r v e r - d e v Spacebar - f Spacebar . / a g i l 4 x p l a t f o r m / r e n d e r s e r v e r / D o c k e r f i l e . d e v t i m e Spacebar . Enter
 UpArrow Enter
 Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 Escape [ ? 1 ; 0 c Escape [ ? 1 ; 0 c Escape [ ? 1 ; 0 c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c Ctrl+c UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 d o k Backspace c k e r Spacebar c p Spacebar C : \ U s e r s \ 8 6 1 3 7 \ P i c t u r e s \ p n g 2 0 0 _ 2 0 0 . p n g Spacebar f 1 3 6 d e 4 4 2 6 1 b : / m n t Enter
 UpArrow UpArrow UpArrow

### Exception

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 29.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.UpdateFromHistory(HistoryMoveCursor moveCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![image](https://user-images.githubusercontent.com/4607600/149438291-18ba0d1d-a071-4a92-ae43-53a3ac37c0de.png)

### Environment data

```console
info contains Exception report
```

### Steps to reproduce

please see the capture

### Expected behavior

Expected  normal

### Actual behavior

please see the capture

**Comment by daxian-dbw** [comment]
@twangithub Did you resize the terminal window before seeing this exception?
