### ISSUE TITLE
Error asked to report the following

### ISSUE THREAD

**Issue by martinsidestud** [PowerShell/PSReadLine#317]
Last 5 Keys:
 Ctrl+v Ctrl+v Ctrl+v Ctrl+v Enter

Exception:
System.UnauthorizedAccessException: Access to the path 'C:\Users\Tom\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadline' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Func`2 fileOpener)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean readingHistoryFile, Boolean fromDifferentSession)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
##    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

PS C:\WINDOWS\system32> Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

**Comment by lzybkr** [comment]
Closing as a dupe of #322
