### ISSUE TITLE
System.ArgumentOutOfRangeException on command "git remote show origin"

### ISSUE THREAD

**Issue by charlpcronje** [PowerShell/PSReadLine#3179]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. 
Parameter name: top
Actual value was -4.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

Is was the first command I ran after I opened a local powershell terminal within VS Code also right after I opened he folder containing the repo

![Code_-_Insiders_oFlt6mmsBH](https://user-images.githubusercontent.com/9626228/150779246-b30f728b-e931-4dd1-bbcf-32f815f139dd.png)

### Environment data

```console
PS Version: 5.1.19041.1320
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 143
BufferHeight: 37
```

### Steps to reproduce

1. I opened VS Code
2. I opened the folder container a private repo that I access a SSH key
3. Opened a new terminal by pressing Ctrl + `
4. I pasted

```shell
git remote show origin
```
5.  Got the exception
6.  When I entered the command again it worked the second time

### Expected behavior

I expected git to show me the remote origin

### Actual behavior

I got an exception

```shell
-----------------------------------------------------------------------
Last 1 Keys:
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. 
Parameter name: top
Actual value was -4.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by charlpcronje** [comment]
O did have a look at the update you are referring to and that was more than a year ago, is it possible that update has been yet been pushed to prodution?

**Comment by charlpcronje** [comment]
I did check that I'm on the newest version 

git version 2.34.1.windows.1

**Comment by daxian-dbw** [comment]
> I did check that I'm on the newest version
> git version 2.34.1.windows.1

PSReadLine is a PowerShell module, not part of `git`. The `2.1.0` version is the latest stable version, but the latest `2.2.0-beta5` is also very stable now, and you can move to it if you want all the latest features and bug fixes.
