### ISSUE TITLE
Random key presses crashes something

### ISSUE THREAD

**Issue by kunalspathak** [PowerShell/PSReadLine#323]
I got this message.

``` command
Last 200 Keys:
 " , s Backspace Backspace m s i e x e c Spacebar Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+v Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow ' Delete Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+LeftArrow ' Delete End " Spacebar - W Tab Tab Tab Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow " Delete Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow LeftArrow RightArrow " Delete Ctrl+RightArrow RightArrow RightArrow ' Delete Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow ' Delete Enter
 UpArrow UpArrow Escape $ n a m e = Ctrl+v Enter
 UpArrow UpArrow Ctrl+LeftArrow UpArrow UpArrow UpArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace $ n a m e Enter
 UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow ' Ctrl+RightArrow LeftArrow LeftArrow ' Enter
 UpArrow UpArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow ( Backspace { Ctrl+RightArrow LeftArrow LeftArrow } Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Escape m s i Spacebar Backspace e x F8 Backspace Backspace Backspace Backspace Backspace ' Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow ' Delete Enter
 UpArrow UpArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow Delete Delete Delete Delete " Enter
 UpArrow Home Delete Delete Delete Delete Delete Delete

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.DeleteCharImpl(Boolean orExit)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

```

**Comment by lzybkr** [comment]
The full command line would be very helpful here - I should have put it in the diagnostic, but was worried I'd get fewer opened bugs if I did that.

**Comment by kunalspathak** [comment]
ah, I closed the prompt. I will keep an eye on it next time I hit it.

**Comment by lzybkr** [comment]
Rendering has been completely rewritten, so I'm assuming this problem is fixed.
