### ISSUE TITLE
 Could not load type 'System.Management.Automation.Subsystem.PredictionResult'

### ISSUE THREAD

**Issue by YuriySamorodov** [PowerShell/PSReadLine#3237]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta2
PowerShell: 7.3.0-preview.2
OS: Microsoft Windows 10.0.18363
BufferWidth: 121
BufferHeight: 9001

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

![image](https://user-images.githubusercontent.com/5260172/158283962-b1ea998c-2cb0-4922-9a21-35d83373ba5e.png)


### Environment data

```console
PSReadLine: 2.2.0-beta2
PowerShell: 7.3.0-preview.2
OS: Microsoft Windows 10.0.18363
BufferWidth: 121
BufferHeight: 9001
```

### Steps to reproduce

Start ```pwsh.exe```

### Expected behavior

No error is expected upon start

### Actual behavior

Cannot even see a prompt. ```Ctrl+C``` will throw the same error again.
Please note the issues happens with PSReadline 2.2.0 beta 2

**Comment by YuriySamorodov** [comment]
Update to ```PSReadline 2.2.2``` has fixed the issue.
