### ISSUE TITLE
Oops, something went wrong 1

### ISSUE THREAD

**Issue by snsyzf** [PowerShell/PSReadLine#3249]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
⨯ ⚡ yzf@DESKTOP-3QOVV3A  C:\Program Files\PowerShell\7                                                                                                                                                                          [18:26]
❯
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.2
OS: Microsoft Windows 10.0.19044
BufferWidth: 237
BufferHeight: 9001

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

Please run the script in the PowerShell session where you ran into the issue, and paste the verbatim output below.
```


### Screenshot

![image](https://user-images.githubusercontent.com/35677762/160378980-fbfa9c2b-2375-4a59-9f06-2a6e906a3699.png)


### Environment data

```console
### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.2
OS: Microsoft Windows 10.0.19044
BufferWidth: 237
BufferHeight: 9001
```

### Steps to reproduce

Open Terminal

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

Please run the script in the PowerShell session where you ran into the issue, and paste the verbatim output below.

### Actual behavior

Oops, something went wrong

**Comment by snsyzf** [comment]
![image](https://user-images.githubusercontent.com/35677762/160379690-64072ad9-f435-49c4-a7bb-aadadeafe5b4.png)
