### ISSUE TITLE
System.Management.Automation.RuntimeException: Unable to find type [PSConsoleUtilities.PSConsoleReadLine].

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#326]
This just started happening today, no idea what has changed in my environment to cause it.

C:\Program Files\JPSoft\TCMD19_x64> help
Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 171 Keys:
 g e t = - a l i Backspace Backspace Backspace Backspace Backspace 0 Backspace - a l i a s Spacebar | ? Spacebar w e h r e -
 Backspace Backspace Backspace Backspace Backspace h e r e - o b j e c t Spacebar { Escape c d Spacebar e Backspace $ n Back
space e n v : l o c a l a p p Tab Enter
 c d Spacebar j p Tab Enter
 l s Enter
 c d Spacebar $ e n v : p r o g r a Tab Enter
 l s Enter
 c d Spacebar j p Tab Enter
 l s Enter
 l s Spacebar t a k Tab Tab Enter
 c : \ p r o g r Tab j p Tab t a k Tab Backspace Backspace Backspace t Tab Tab Tab Enter
 l Backspace UpArrow Home c d Spacebar Delete Enter
 l w d Enter
 l s Spacebar \* . i n i Enter
 h e l p F1

Exception:
System.Management.Automation.RuntimeException: Unable to find type [PSConsoleUtilities.PSConsoleReadLine].
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception excepti
on)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLo
calScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object doll
arUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClassa.<InvokeWithPipe>b__8()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBeha
vior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagate
AllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvoke(Object dollarUnder, Object input, Object[] args)
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass67.<ProcessOneKey>b__65()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass63.<CalloutUsingDefaultConsoleMode>b__62()
   at Microsoft.PowerShell.PSConsoleReadLine.CalloutUsingDefaultConsoleMode[T](Func`1 func)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfN
oAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
##    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

C:\Program Files\JPSoft\TCMD19_x64>

**Comment by rkeithhill** [comment]
Did you happen to upgrade to WMF 5?  The version of PSReadLine that comes with WMF 5 has changed namespace `PSConsoleUtilities` to `Microsoft.PowerShell`.  So if you have any PSReadLine customizations in your profile, you will need to do a search and replace of the former with the latter.  

You might also try running `PowerShell -NoProfile` to see if the problem remains (sans your profile) - just to verify if this is indeed the problem.

**Comment by lzybkr** [comment]
WMF5 does not include PSReadline, so an upgrade to WMF5 would not cause this.

An upgrade to Win10 would, as would pulling the latest and building your own version of PSReadline.

At any rate, as Keith mentions, the namespace has changed, you need to update your custom key handlers.
