### ISSUE TITLE
Get-M365DSCCompiledPermissionList -ResourceNameList + Crtl+Space throws error

### ISSUE THREAD

**Issue by Bryand13** [PowerShell/PSReadLine#3269]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Excepción:
System.ArgumentOutOfRangeException: El valor debe ser mayor que o igual a cero y menor que el tamaño de búfer de consola en dicha dimensión.
Nombre del parámetro: top
Valor actual -33.
   en System.Console.SetCursorPosition(Int32 left, Int32 top)
   en Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   en Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   en Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   en Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   en Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   en Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   en Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

![imagen](https://user-images.githubusercontent.com/50946094/162922151-e9c5bfca-04e0-4ba6-bb3a-e532b805d1f4.png)

### Environment data

```console
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Steps to reproduce

Open powershell 5.1 in windows terminal.
Enter the command Get-M365DSCCompiledPermissionList -ResourceNameList and Crtl+Space
Windows Terminal throws an error

### Expected behavior

See all available option when executing Get-M365DSCCompiledPermissionList -ResourceNameList and Crtl+Space

### Actual behavior

Error exception when executing Get-M365DSCCompiledPermissionList -ResourceNameList and Crtl+Space

**Comment by hberge** [comment]
[EDIT]

This was resolved when I updated to [PSReadline 2.2.2](https://www.powershellgallery.com/packages/PSReadLine/2.2.2)
See #1306
---

I only had this occur in Windows Terminal. It works as expected in Windows Powershell.

I had an exception error first with `G e t - N e t Ctrl+Space`. After doing `clear` in the terminal it would work again, however following that up with `G e t - Ctrl+Space y` resulted in the same exception.

 - Exception report:
```psl
Last 67 Keys:
 g e t - n e t Ctrl+Space c l e a r Enter
 c l e a r Enter
 g e t - Ctrl+Space y Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c l e a r Enter
 g e t - n e t Ctrl+Space Backspace LeftArrow RightArrow LeftArrow Backspace Ctrl+Space Backspace LeftArrow LeftArrow LeftArrow Delete Backspace Backspace Backspace Ctrl+Space y

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -73.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

Windows specifications
```
Edition	Windows 10 Pro
Version	21H2
OS build	19044.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0
```
