### ISSUE TITLE
 The system cannot open the device or file specified. : 'PSReadLineHistoryFile_2966948577' on starting pwsh

### ISSUE THREAD

**Issue by JiriZidek** [PowerShell/PSReadLine#3293]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Exception

System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_2966948577'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![image](https://user-images.githubusercontent.com/8578952/165537839-09264e36-7255-439a-8505-e0a918252971.png)

### Environment data

```console
### Environment
PSReadLine: 2.1.0
PowerShell: 7.2.2
OS: Linux 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

Just write pwsh on bash $ prompt

### Expected behavior

This started to happen showed on 27-APR-2022

### Actual behavior

It showed no errors before.
Now after this error, the PowerShell is crippled a bit...

```
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

ls
iCC.ReactClient.zip  myagent  snap  vsts-agent-linux-x64-2.202.1.tar.gz
PS /home/atlantis>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 7.2.2
OS: Linux 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022
BufferWidth: 120
BufferHeight: 30

Last 0 Keys
```

```

**Comment by daxian-dbw** [comment]
@JiriZidek This will happen when the `/tmp` folder or `/tmp/.dotnet` folder doesn't have write permission for non-root users. Please take a look at [this comment](https://github.com/PowerShell/PSReadLine/issues/1464#issuecomment-631656531) and [the one below it](https://github.com/PowerShell/PSReadLine/issues/1464#issuecomment-631941511) for details, and see if you have the same problem.

**Comment by JiriZidek** [comment]
Helped ! Thx
