### ISSUE TITLE
Exception report requested: Series of >PSIC outputs in VSCode debugger followed by PSReadline exception

### ISSUE THREAD

**Issue by jhoneill** [PowerShell/PSReadLine#3323]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.2.5
PowerShell: 2022.5.1
OS: Microsoft Windows 10.0.22000
BufferWidth: 281
BufferHeight: 42

Last 200 Keys:

 LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Spacebar Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow RightArrow RightArrow RightArrow RightArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Delete Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Delete Enter
 UpArrow Shift+Home Ctrl+x n e w - m RightArrow Backspace p Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Shift+Tab Shift+Home Delete p p q Enter
 p Enter
 c d Spacebar - Enter
 c

### Exception

System.InvalidOperationException: Queue empty.
   at System.Collections.Generic.Queue`1.ThrowForEmptyQueue()
   at System.Collections.Generic.Queue`1.Dequeue()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![image](https://user-images.githubusercontent.com/16209593/169989998-d08a72d1-c0aa-4ef8-81ff-28b3233e0b18.png)

In the screen shot command 551 tried to run 18 lines of code from the VSCode editor window with [F8],    
This was in the wrong directory so the first command failed. 
A later command dropped into the debugger and at the same time a series of "PSIC>"   appeared. When this happens normally the only way to regain control of VSCode is to terminate the PowerShell console but this time the sequence stopped.   
One cd command took me to the previous directory and starting to enter the next caused the exception. 

### Environment data

```console
PS Version: 7.2.3
PS HostName: Visual Studio Code Host
PSReadLine Version: 2.2.5
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 263
BufferHeight: 39
```

### Steps to reproduce

Cannot repro at will, just providing exception in case it helps with other reports 
**Feel free to close the issue is informational, can't repro**

### Expected behavior

No Exception

### Actual behavior

Exception as above

**Comment by andschwa** [comment]
Is the debugger starting up when that breakpoint is hit? It sounds like _maybe_ we're re-entering PSReadLine.

**Comment by jhoneill** [comment]
IIRC the the debugger was set for "interactive session" and would have been have been active waiting for something to hit a breakpoint.
