### ISSUE TITLE
Key stroke issue

### ISSUE THREAD

**Issue by Guyrato** [PowerShell/PSReadLine#3325]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 7.2.4
OS: Microsoft Windows 10.0.22000
BufferWidth: 103
BufferHeight: 25

Last 200 Keys

 Spacebar - - h e l p Enter
 UpArrow UpArrow UpArrow UpArrow Escape Escape Ctrl+c p g _ d u m p Spacebar - - f i l e = d b b a c k 0 5 2 6 . c u s t o m Spacebar - - f o r m a t = c u s t o m Spacebar - - v e r b o s e Spacebar - - h o s t = p o s t o d o o . p o s t g r e s . d a t a b a s e . a z u r e . c o m Spacebar - - p o r t = 5 4 3 2 Spacebar - - u s e r n a m e = o d o o p s q l @ p o s t o d o o Spacebar - - d b n a m e = t o p d e k _ t e s t 2 Spacebar # M a s t e r p s q l $ 9 0 5 0 Enter
 UpArrow DownArrow
```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 25.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.UpdateFromHistory(HistoryMoveCursor moveCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.NextHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

PS C:\Users\RubenChilavert\OneDrive - TOPDEK\Adoo\Database>
```


### Screenshot

![image](https://user-images.githubusercontent.com/95034850/170504654-d561e2b2-d015-488a-ae27-c9839dd27293.png)



### Environment data

```console
PS Version: 7.2.4
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 103
BufferHeight: 45
```

### Steps to reproduce

Ran a pg_dump command session then just leave the machine alone for a while. 

### Expected behavior

Nothing

### Actual behavior

The above exceptions happens

**Comment by daxian-dbw** [comment]
Please try out the latest 2.2.5 version of PSReadLine: https://www.powershellgallery.com/packages/PSReadLine/2.2.5.
Many fixes went into the 2.2.x release that significantly improved the reliability of the module.
