### ISSUE TITLE
Ctrl-V multiple times does not work

### ISSUE THREAD

**Issue by HipHopFishyFish** [PowerShell/PSReadLine#3338]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 p y Enter
 & Space C : / U s e r s / h e c t o / A p p D a t a / L o c a l / P r o g r a m s / P y t h o n / P y t h o n 3 1 0 / p y t h o n . e x e 
Space c : / U s e r s / h e c t o / D o c u m e n t s / P y X a p p s / t o k e n i z e r / t o k e n i s e r . p y Enter
 Ctrl+v Space a r g Enter
 Ctrl+v Enter
 Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Enter
 Ctrl+v Space Ctrl+v Space Ctrl+v Enter
 Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -33.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

![tokeniser py - tokenizer - Visual Studio Code 04_06_2022 17_15_30](https://user-images.githubusercontent.com/104759571/172015462-13d59501-6306-41fa-8d15-a07e37ec2b8e.png)

### Environment data

```console
PS Version: 5.1.19041.1682
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 139
BufferHeight: 13
```

### Steps to reproduce

I was doing Ctrl-V multiple times(I had copied something.) and it came up with the exception

### Expected behavior

I just wanted no exception and I wanted it to keep pasting.

### Actual behavior

It just came up with the exception when I clicked Ctrl-V

**Comment by HipHopFishyFish** [comment]
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR im annoyed
YOUR BOT IS A BOT I HATE THE BOT. HELP ME

**Comment by andyleejordan** [comment]
@MinecraftCoder9-YT as the bot says, you are using `PSReadLine Version: 2.0.0-beta2`. Can you please try exactly what the bot says, which is upgrade to [2.2.3](https://www.powershellgallery.com/packages/PSReadLine/2.2.3) and try to repro the issue?
