### ISSUE TITLE
Unicode Character Error

### ISSUE THREAD

**Issue by EtaCarnis** [PowerShell/PSReadLine#3341]
### Prerequisites

- [x] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 7.2.4
OS: Microsoft Windows 10.0.22000
BufferWidth: 114
BufferHeight: 27

Last 13 Keys

 $ s Spacebar = Spacebar ' ' LeftArrow � � Ctrl+z RightArrow Enter

```

### Exception
```
System.Text.EncoderFallbackException: Unable to translate Unicode character \\uD83C at index 6 to specified code page.
   at System.Text.EncoderExceptionFallbackBuffer.Fallback(Char charUnknown, Int32 index)
   at System.Text.EncoderFallbackBuffer.InternalFallback(ReadOnlySpan`1 chars, Int32& charsConsumed)
   at System.Text.Encoding.GetBytesWithFallback(ReadOnlySpan`1 chars, Int32 originalCharsLength, Span`1 bytes, Int32 originalBytesLength, EncoderNLS encoder)
   at System.Text.Encoding.GetBytesWithFallback(Char* pOriginalChars, Int32 originalCharCount, Byte* pOriginalBytes, Int32 originalByteCount, Int32 charsConsumedSoFar, Int32 bytesWrittenSoFar, EncoderNLS encoder)
   at System.Text.Encoding.GetBytes(Char* pChars, Int32 charCount, Byte* pBytes, Int32 byteCount, EncoderNLS encoder)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass83_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Boolean overwritten)
   at Microsoft.PowerShell.PSConsoleReadLine.IncrementalHistoryWrite()
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean fromDifferentSession, Boolean fromInitialRead)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

![image](https://user-images.githubusercontent.com/79852087/172844180-c95ca89e-909d-4704-aab5-1e22ce0c954d.png)

### Environment data

```console
PS Version: 7.2.4
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 114
BufferHeight: 27
```

### Steps to reproduce

1. I copied the character called _Mahjong Tile Three of Bamboos_: 🀒
2. pasted it in the terminal and did <kbd>Ctrl</kbd>+<kbd>z</kbd> and realized that it displayed the character replacement symbol
3. I attempted to create a variable and assign this value to it via:
```ps1
$s = '�'
```
5. I got this error

### Expected behavior

Expected no bug (aka the same result as doing any other assignment to a variable):
```ps1
PS> $a = 0
PS> $a
0
PS>
```

### Actual behavior

Got this error thrown

**Comment by daxian-dbw** [comment]
Close as duplicate of #2358
