### ISSUE TITLE
PSReadLine TypeLoadException after updating to PS 7.2.4

### ISSUE THREAD

**Issue by jonweaver** [PowerShell/PSReadLine#3348]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.4
OS: Microsoft Windows 10.0.19041
BufferWidth: 120
BufferHeight: 30

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

Exception pops up on load

![image](https://user-images.githubusercontent.com/18248207/174422161-d10dd6d1-0bb0-4cc7-93d9-535c17e5c7a7.png)


### Environment data

```console
Can't run anything from PS 7 this is from other PS 5 x86

PS Version: 5.1.19041.1
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 3000
```

### Steps to reproduce

launch PS 7 

### Expected behavior

No Exception

### Actual behavior

Exception happens on launch

**Comment by jonweaver** [comment]
Thanks, worked great.
