### ISSUE TITLE
Bug report as requested by PS's error: System.ArgumentOutOfRangeException.

### ISSUE THREAD

**Issue by MMeent** [PowerShell/PSReadLine#3354]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.1682
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 104
BufferHeight: 3000
```

### Steps to reproduce

I'm uncertain about this being 100% reproducible, but
- Shortly after a restart
- Use explorer to go to a folder
- "File" -> "Open Windows Powershell"
- in PS, arrow up to start the previously executed command
- In explorer, once again "File" -> "Open Windows Powershell".
- in new PS, arrow-up -> this exception

### Expected behavior

The last history item is shown on the command line.

### Actual behavior

An exception is thrown, in the bundled PS that was provided with my fully-updated installation of Windows Pro.

**Comment by MMeent** [comment]
As mentioned, I've installed all available updates, but the issue persists.

**Comment by daxian-dbw** [comment]
It's not about Windows Updates. It's about updating to use the latest PSReadLine module.
