### ISSUE TITLE
Powershell crashes when path is longer than one line (on screen)

### ISSUE THREAD

**Issue by wilkovanderveen** [PowerShell/PSReadLine#3379]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 167 Keys:
 c d Space C : \ U s e r s \ w i l k o . v a n d e r v e e n \ s o u r c e \ r e p o s \ d e l t a - e s b c o n t r a c t s - c o d e g e n e r a t o r Enter
 g i t Space s t a t u s Enter
 g i t Space p u s h Enter
 UpArrow Space - s Backspace - s e t - u p s t r e a m Space o r i g i n Space g Backspace f e a t u r e / p r o o f - o f - c o n c e p t Enter
 c d Space s Tab Enter
 c d Space D e Tab Tab Tab Tab Tab Enter
 d o

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\wilko.vanderveen\source\repos\delta-esbcontracts-codegenerator\source\Delta.Mulesoft.ContractsGenerator.Cli>
```

### Screenshot

![image](https://user-images.githubusercontent.com/9797033/179162857-e6125d56-6981-4936-a5d3-f158dffbec1e.png)

### Environment data

```console
PS Version: 5.1.19041.1682
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.320 (WinBuild.160101.0800)
BufferWidth: 203
BufferHeight: 3000
```

### Steps to reproduce

* Go to a folder which' name is as longor longer as the width of the powershell window, so that the command prompt is on the next line
* Type any character

* Also occurs when first widening the window and try to execute some commands after widening.

### Expected behavior

The command is being executed

### Actual behavior

Powershell crashes (as mentioned above)

**Comment by wilkovanderveen** [comment]
Powershell is a part of Windows, why do I need to manually install an update to fix this issue?

**Comment by daxian-dbw** [comment]
New versions of PSReadLine are released outside of Windows.
