### ISSUE TITLE
Tried Ctrl+Break via (fn, Shift, altgr combos) randomly, crashed PSReadLine

### ISSUE THREAD

**Issue by rubi-rastko** [PowerShell/PSReadLine#3394]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.6
PowerShell: 2022.7.2
OS: Linux 5.18.11-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jul 12 22:52:35 UTC 2022
BufferWidth: 125
BufferHeight: 26

Last 200 Keys:

 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Enter
 d n f Spacebar s UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 g e m Spacebar s e a r c h Spacebar - r Spacebar r a i l s Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace RightArrow ^ RightArrow RightArrow RightArrow RightArrow RightArrow Enter
 UpArrow DownArrow DownArrow DownArrow DownArrow UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 RightArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 p o d m a n Spacebar s y s t e m Spacebar d f Spacebar - v Enter
 p o d m a n Spacebar e v e n t s Enter
 Enter
 4 5 4 r Ctrl+b B b Ctrl+b Enter
 Ctrl+b Enter
 Ctrl+b Ctrl+b r b b r Escape Delete ~ Escape ; ~ Escape ; ~ Escape ; ~ Escape ;

### Exception

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'left')
Actual value was 523623622.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.CalculateWhereAndWhatToRender(Boolean cursorMovedToInitialPos, RenderData renderData, LineInfoForRendering& lineInfoForRendering)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![image](https://user-images.githubusercontent.com/89523087/182327460-b6a43cd2-0b1b-4329-904f-906eb9ee4737.png)

### Environment data

```console
PS Version: 7.2.5
PS HostName: Visual Studio Code Host
PSReadLine Version: 2.2.6
PSReadLine EditMode: Emacs
OS: Linux ionian 5.18.11-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jul 12 22:52:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
BufferWidth: 98
BufferHeight: 1
```

### Steps to reproduce

Try to Ctrl+C a running task without typing Ctrl+C, but randomly typing various control characters.

Kill the process from another terminal with SIGKILL.

### Expected behavior

Well, didn't expect anything beautiful to happen really.

### Actual behavior

Ooops, something wen't wrong message.
Normal behavior afterwards.

**Comment by StevenBucher98** [comment]
@rubi-rastko I am a little confused by your reproduction steps? are there particular control characters that are causing this exception?

**Comment by rubi-rastko** [comment]
> @rubi-rastko I am a little confused by your reproduction steps? are there particular control characters that are causing this exception?

@StevenBucher98  That should be visible both from the screen shot & the detailed exception console log.
I believe the sigkill from another terminal is a necessary part to reproduce.
