### ISSUE TITLE
Crash/exception report

### ISSUE THREAD

**Issue by cronhan** [PowerShell/PSReadLine#3395]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.2.5
PowerShell: 7.2.5
OS: Microsoft Windows 10.0.19044
BufferWidth: 188
BufferHeight: 50

Last 200 Keys:

 d Spacebar $ E n v : B O O Tab Tab Shift+Tab Tab Tab Tab Shift+Tab \ Tab Tab \ Tab \ Tab Tab Backspace Tab Enter
 d i r Enter
 d u m p b i n Spacebar / d i r e c t i v e s Spacebar / s e c t i o n : . d r e c t v e Spacebar b o o s t _ p r Tab Tab Spacebar > Spacebar C : \ t Tab b o o s t _ O G Backspace Backspace p g o . t x t Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace d l l Enter
 c d Spacebar - Enter
 UpArrow UpArrow UpArrow DownArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Escape c d Spacebar Backspace Backspace Backspace g i t Spacebar - C Spacebar w PageUp PageUp PageUp Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+r w o r k t r e e Spacebar a Ctrl+c

### Exception

System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 58.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.CalculateWhereAndWhatToRender(Boolean cursorMovedToInitialPos, RenderData renderData, LineInfoForRendering& lineInfoForRendering)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.RenderWithPredictionQueryPaused()
   at Microsoft.PowerShell.PSConsoleReadLine.ClearStatusMessage(Boolean render)
   at Microsoft.PowerShell.PSConsoleReadLine.InteractiveHistorySearch(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.ReverseSearchHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![2022-08-04 09_04_37](https://user-images.githubusercontent.com/24264385/182785406-8515a4c3-f395-46e6-bdad-ac950846c228.png)

### Environment data

```console
### Environment
PSReadLine: 2.2.5
PowerShell: 7.2.5
OS: Microsoft Windows 10.0.19044
BufferWidth: 188
BufferHeight: 50
```

### Steps to reproduce

I think I did a reverse search followed by Ctrl+C

### Expected behavior

No exception ;)

### Actual behavior

A report is generated as above

**Comment by daxian-dbw** [comment]
@cronhan Can you please try to repro this issue with the key input history shown in the exception report?
I cannot reproduce the issue by "reverse search followed by Ctrl+C", so will need your help to get a consistent repro.

Also, what edit mode are you using when seeing this exception?
