### ISSUE TITLE
System.IO.IOException: The handle is invalid.

### ISSUE THREAD

**Issue by Alicds** [PowerShell/PSReadLine#340]
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineI
ntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineInt
rinsics)

**Comment by lzybkr** [comment]
Duplicated of #158.
