### ISSUE TITLE
Error with autocomplete script in profile.ps1

### ISSUE THREAD

**Issue by tacbuh** [PowerShell/PSReadLine#3401]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
I added this code in my profile.ps1 (https://dev.to/ofhouse/add-a-bash-like-autocomplete-to-your-powershell-4257) and I get an error message when I use it in Windows Terminal.
I have to enlarge the window to solve the problem.

Exception :
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. : top
Actual value was -25.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics
```

### Screenshot

![image](https://user-images.githubusercontent.com/96725013/183691517-8166d30b-3234-4966-8ea9-e17b729ca6a0.png)

### Environment data

```console
PS Version: 5.1.19041.1682
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1826 (WinBuild.160101.0800)
BufferWidth: 120
BufferWidth: 120
```

### Steps to reproduce

Example :
type `get-` and use Tab
Type `y` to display all possibilities

### Expected behavior

Same error as above

### Actual behavior

Same error as above

**Comment by tacbuh** [comment]
Problem solve after update PSreadline `Install-Module -Name PSReadLine -Force`
Thanks
