### ISSUE TITLE
Ctrl-A, Ctrl-X throws exception when there is nothing to select

### ISSUE THREAD

**Issue by saqneo** [PowerShell/PSReadLine#341]
Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 2 Keys:
 Ctrl+a Ctrl+x

Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at Microsoft.PowerShell.PSConsoleReadLine.Cut(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

**Comment by lzybkr** [comment]
I can't repro, but this seems like something that was probably fixed.
