### ISSUE TITLE
Permission problem when running Powershell as a different user

### ISSUE THREAD

**Issue by jones-g** [PowerShell/PSReadLine#346]
I have Console setup up to run a powershell as a different user. However on a new install of Console 1.16.0.16038 I am getting the error below when I attempt to do anything. Running Powershell directly as this user works as intended.

Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 7 Keys:
 w h o a m i Enter

Exception:
System.UnauthorizedAccessException: Access to the path 'C:\Users\Default\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadline' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Func`2 fileOpener)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean readingHistoryFile, Boolean fromDifferentSession)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

**Comment by jones-g** [comment]
Turns out Windows 10 has PSReadline 1.1 installed which did not work. Using "Install-Module PSReadline -Force" updated to 1.2 and resolved the issue.

**Comment by lzybkr** [comment]
I did make a change to improve the experience.  Are you getting a warning about history not being saved now? Or is history actually being saved properly (so when you open a new instance of PowerShell, the history can be recalled from the previous session.)

**Comment by jones-g** [comment]
History works - Very nice feature! Had not even noticed it but this can really boost my experience!
