### ISSUE TITLE
System.IO.IOException: The parameter is incorrect. at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)

### ISSUE THREAD

**Issue by sldr** [PowerShell/PSReadLine#3483]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
19044
BufferWidth: 120
BufferHeight: 9001

Last 88 Keys

 LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows m k d i r Spacebar \ g i t l a b Enter
 c d Spacebar \ g i t l a b Enter
 c l s Enter
 d i r Enter
 d i r Spacebar - Tab Tab Tab Shift+Tab Tab Tab Tab Tab Tab Tab Tab Tab Spacebar Tab Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Backspace Backspace Backspace Backspace Backspace Backspace Backspace Spacebar Ctrl+Tab Backspace Backspace Spacebar Shift+Tab Shift+Spacebar Backspace Ctrl+Spacebar LeftWindows Enter

```

### Exception
```
System.IO.IOException: The parameter is incorrect.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.MoveCursor(Int32 newCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.SetCursorPosition(Int32 cursor)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

PS C:\gitlab>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 7.2.6
OS: Microsoft Windows 10.0.19044
BufferWidth: 120
BufferHeight: 9001

Last 89 Keys
```
 LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows m k d i r Spacebar \ g i t l a b Enter
 c d Spacebar \ g i t l a b Enter
 c l s Enter
 d i r Enter
 d i r Spacebar - Tab Tab Tab Shift+Tab Tab Tab Tab Tab Tab Tab Tab Tab Spacebar Tab Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Backspace Backspace Backspace Backspace Backspace Backspace Backspace Spacebar Ctrl+Tab Backspace Backspace Spacebar Shift+Tab Shift+Spacebar Backspace Ctrl+Spacebar LeftWindows Enter
 Enter

```

### Exception
```
System.IO.IOException: The parameter is incorrect.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.MoveCursor(Int32 newCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.SetCursorPosition(Int32 cursor)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

PS C:\gitlab>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 7.2.6
OS: Microsoft Windows 10.0.19044
BufferWidth: 120
BufferHeight: 9001

Last 90 Keys
```
 LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows m k d i r Spacebar \ g i t l a b Enter
 c d Spacebar \ g i t l a b Enter
 c l s Enter
 d i r Enter
 d i r Spacebar - Tab Tab Tab Shift+Tab Tab Tab Tab Tab Tab Tab Tab Tab Spacebar Tab Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Backspace Backspace Backspace Backspace Backspace Backspace Backspace Spacebar Ctrl+Tab Backspace Backspace Spacebar Shift+Tab Shift+Spacebar Backspace Ctrl+Spacebar LeftWindows Enter
 Enter
 Enter

```

### Exception
```
System.IO.IOException: The parameter is incorrect.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.MoveCursor(Int32 newCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.SetCursorPosition(Int32 cursor)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

asdfasdf
asdfasdf: The term 'asdfasdf' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\gitlab>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 7.2.6
OS: Microsoft Windows 10.0.19044
BufferWidth: 120
BufferHeight: 9001

Last 92 Keys
```
 LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows m k d i r Spacebar \ g i t l a b Enter
 c d Spacebar \ g i t l a b Enter
 c l s Enter
 d i r Enter
 d i r Spacebar - Tab Tab Tab Shift+Tab Tab Tab Tab Tab Tab Tab Tab Tab Spacebar Tab Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Backspace Backspace Backspace Backspace Backspace Backspace Backspace Spacebar Ctrl+Tab Backspace Backspace Spacebar Shift+Tab Shift+Spacebar Backspace Ctrl+Spacebar LeftWindows Enter
 Enter
 Enter
 Enter
 Enter

```

### Exception
```
System.IO.IOException: The parameter is incorrect.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.CalculateWhereAndWhatToRender(Boolean cursorMovedToInitialPos, RenderData renderData, LineInfoForRendering& lineInfoForRendering)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

PS C:\gitlab>
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.1.0
PowerShell: 7.2.6
OS: Microsoft Windows 10.0.19044
BufferWidth: 120
BufferHeight: 9001

Last 92 Keys
```
 LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows m k d i r Spacebar \ g i t l a b Enter
 c d Spacebar \ g i t l a b Enter
 c l s Enter
 d i r Enter
 d i r Spacebar - Tab Tab Tab Shift+Tab Tab Tab Tab Tab Tab Tab Tab Tab Spacebar Tab Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Backspace Backspace Backspace Backspace Backspace Backspace Backspace Spacebar Ctrl+Tab Backspace Backspace Spacebar Shift+Tab Shift+Spacebar Backspace Ctrl+Spacebar LeftWindows Enter
 Enter
 Enter
 Enter
 Enter

```

### Exception
```
System.IO.IOException: The parameter is incorrect.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.MoveCursor(Int32 newCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.SetCursorPosition(Int32 cursor)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

I was trying to use git.exe when I got the following exceptions and process hang (ok maybe not hang but slow down to point of unusable). I went to task manager and have process dump from running process btw. The screenshot is the top of the window scrolled all the way up. The "mkdir \gitlab" command worked fine and was at the top of the screen but isn't anymore.
![image](https://user-images.githubusercontent.com/9607160/202226558-59f0fee5-8956-4d13-afb0-dfdcc0205221.png)

### Environment data

```console
From exception above:
PSReadLine: 2.1.0
PowerShell: 7.2.6
OS: Microsoft Windows 10.0.19044
BufferWidth: 120
BufferHeight: 9001

From new process running same exe (C:\Program Files\WindowsApps\Microsoft.PowerShell_7.2.6.0_x64__8wekyb3d8bbwe\pwsh.exe):
PS Version: 7.2.6
PS HostName: ConsoleHost
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 9001
```

### Steps to reproduce

Didn't try "exact" steps to reproduce. Contact me if you want the dump file from the running process.

### Expected behavior

PSReadLine not to throw an exception when typing.

### Actual behavior

PSReadLine threw an exception when typing.

**Comment by daxian-dbw** [comment]
Please update to the latest version 2.2.6 of PSReadLine: https://www.powershellgallery.com/packages/PSReadLine/2.2.6
