### ISSUE TITLE
Problem with script when powershell is running in the "noprofile" context

### ISSUE THREAD

**Issue by WithHolm** [PowerShell/PSReadLine#351]
Hi!
Win10 admin here. Great product!
I do, however have an issue:
If you run powershell without a profile (example: "runas /noprofile /user:administrator"), it will run without a profile context (ie no "c:\users\default").
This does create some issues as you dont have access to other peoples profiles and it apparenty checks the document "consolehost_history.txt" reciding in %appdata%.

In some enviorments this does work as "administrator" have full read and write to default, but here you cannot do that. You can change the behaviour of the default profile, however this is not my issue with this error: 
My issue is that if this error pops up, there is no way to "unload" this module as it intercepts all of my commands untill i create a "consolehost_history.txt" and give expicit permissions to the user.
I recognise the importance of being able to load last commands even though you have closed your consolewindow, but is there some way of making this module ask to be unloaded if this where to happen?

(i also know that the default $Env:PSModulePathin win10 is $home\Documents\WindowsPowerShell\Modules. Is there some way of incorprating this as the path instead?)

---

Exception:
System.UnauthorizedAccessException: Access to the path 'C:\Users\Default\AppData\Roaming\Microsoft\Wi
ndows\PowerShell\PSReadline\ConsoleHost_history.txt' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean
useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, Stri
ng msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int3
2 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean c
heckHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize,
Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.AppendText(String path)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Func`2 fileOpe
ner)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 und
oEditIndex, Boolean readingHistoryFile, Boolean fromDifferentSession)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntri
nsics)

**Comment by lzybkr** [comment]
Try version 1.2 which was recently published to the gallery.  The experience should be much nicer, just a warning a couple times at most with a suggestion to set the history path.

If the warning is still annoying and you don't want history saved anyway, you can do something like:

`powershell -noexit -command "Set-PSReadlineOption -HistorySaveStyle SaveNothing"`

**Comment by lzybkr** [comment]
The error should have been fixed by 2269484.
