### ISSUE TITLE
PSReadLine: 2.2.6 Gives ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by air2** [PowerShell/PSReadLine#3515]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
S /usr/bin> l
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.1
OS: Linux 4.14.294-220.533.amzn2.x86_64 #1 SMP Thu Sep 29 01:01:23 UTC 2022
BufferWidth: 0
PS /usr/bin> 
sProcess terminated. The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineFromConsole(Boolean endOnTab, String initialContent, Boolean calledFromPipeline, String& restOfLine, ReadLineResult& result)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLine(Boolean endOnTab, String initialContent, ReadLineResult& result, Boolean calledFromPipeline, Boolean transcribeResult)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineWithTabCompletion(Executor exec)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName, String configurationFilePath)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, Boolean issProvidedExternally)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)Aborted
sh-4.2$
```

### Screenshot

![image](https://user-images.githubusercontent.com/3084096/208129809-7a92a837-0170-4f71-b367-1f703123df85.png)

### Environment data

```console
PS Version: 7.3.1
PS HostName: ConsoleHost
PSReadLine Version: 
PSReadLine EditMode: Emacs
OS: Linux ip-10-24-0-209.us-east-1.compute.internal 4.14.294-220.533.amzn2.x86_64 #1 SMP Thu Sep 29 01:01:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
BufferWidth: 0
BufferHeight: 0
```

### Steps to reproduce

I start pswh then I try to enter a character, boom error.

### Expected behavior

Being able to type commands

### Actual behavior

The above exception happens

**Comment by air2** [comment]
This was a problem in not initializing xtermjs with AWS correctly. Fixed by sending the buffersize message to AWS, so it was an error on my end. Sorry for creating this issue.
