### ISSUE TITLE
Error encountered on pasting a PS script into Windows Terminal

### ISSUE THREAD

**Issue by neilfairall** [PowerShell/PSReadLine#3520]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Space Space Space Space Space Space Space Space $ a n n u a l t o t a l Space + = Space ( $ h i r e s - $ t e r m s ) Enter
 Space Space Space Space } Enter
 Space Space Space Space [ s t r i n g ] $ y e a r + ' Space t o t a l Space h i r e s : Space ' + $ a n n u a l h i r e s Enter
 Space Space Space Space [ s t r i n g ] $ y e a r + ' Space t o t a l Space t e r m s : Space ' + $ a n n u a l t e r m s Enter
 Space Space Space Space [ s t r i n g ] $ y e a r + ' Space n e t Space c h a n g e : Space ' + $ a n n u a l t o t a l Enter
 Space Space Space Space " ` n " Enter
 } Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -23.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.1682
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 163
BufferHeight: 43
```

### Steps to reproduce

You paste the code into the window and it goes boom. Look, the thing asked me to post it here, I don't really know what I am doing but you've got the last few lines of code above. If you're really excited about it, reach out to me and we can talk.

### Expected behavior

Script completes without PSreadline spewing red text and telling me to report an issue

### Actual behavior

The exception occurs, and the script appears to complete successfully anyway.

**Comment by neilfairall** [comment]
That fix worked a treat, thank you!
