### ISSUE TITLE
Issue with Powershell 7.3.1 in Win 11

### ISSUE THREAD

**Issue by tuco80** [PowerShell/PSReadLine#3522]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.1
OS: Microsoft Windows 10.0.19044
BufferWidth: 253
BufferHeight: 8000

Last 1 Keys:

 r

### Exception

System.IO.IOException: The parameter is incorrect.
   at System.ConsolePal.set_CursorVisible(Boolean value)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorVisible(Boolean value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

NO screenshot, but there's really nothing, I can't really do anything, this happens when powershell is loading up

PowerShell 7.3.1
Loading personal and system profiles took 2367ms.
   Microsoft.PowerShell_7.3.1.0_x64__8wekyb3d8bbwe 

(and then when I try to type something, I get the error.)

### Environment data

```console
PSReadLine: 2.2.6
PowerShell: 7.3.1
OS: Microsoft Windows 10.0.19044
BufferWidth: 253
BufferHeight: 8000
```

### Steps to reproduce

Followed instructions to install solarized light

### Expected behavior

powerhsell loads up as it used to with solarized light colors

### Actual behavior

exceptions when I type something

**Comment by StevenBucher98** [comment]
@tuco80 which instructions did you use to install solarized light? and did you face any errors before you installed it?

**Comment by ghost** [comment]
This issue is closed because it has been marked as requiring author feedback but has not had any activity for **7 days**. If you think the issue is still relevant, please reopen and provide your feedback.
