### ISSUE TITLE
PowerShell - Oops, something went wrong - error message

### ISSUE THREAD

**Issue by andypbaker** [PowerShell/PSReadLine#3533]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0
PowerShell: 5.1.22000.1335
OS: Microsoft Windows 10.0.22000
Last 200 Keys

 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 # t r y Tab Tab Tab Tab Tab Tab Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows LeftWindows UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow Escape # t w e a Tab Enter
 PageUp PageUp PageUp PageUp PageUp PageUp PageUp PageUp Escape LeftWindows Alt+v Escape Escape Escape Escape PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown PageDown
```

### Exception
```
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayDown(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

andyp,   DEV-08
01/05/2023 08:40:56
D:\documents
PS>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
```


### Screenshot

![2023-01-05 09_18_27-Greenshot](https://user-images.githubusercontent.com/101548208/210744864-1a783024-689c-46bd-b94c-e024ac148d04.png)


### Environment data

```console
PS Version: 5.1.22000.1335
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 211
BufferHeight: 9001
```

### Steps to reproduce

This is intermittent, but simple Alt-Tabbed to powershell windows and cursored up to retrieve previous commands.

One thing I did not was that recently, with window 11, pressing Alt-Tab leaves Alt activated - this may or may not be a factor.

### Expected behavior

no exception occurred

### Actual behavior

Exception occurred

**Comment by daxian-dbw** [comment]
@andypbaker Thanks for reporting the issue. The PSReadLine version you are using is pretty old. Please upgrade to the latest version 2.2.6 from [PowerShell Gallery](https://www.powershellgallery.com/packages/PSReadLine/2.2.6) and give it a try.
