### ISSUE TITLE
Weird slow powershell behavior and Weirder Exception

### ISSUE THREAD

**Issue by Dlorwisdom** [PowerShell/PSReadLine#354]
Today very suddenly, Powershell began acting up.
It takes forever to start my commands. Its not the scripts that are slow, powershell just sits idle for up to 1 minute before executing any command, which then runs at normal speed.

Last 0 Keys:

Exception:
System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadHistoryFile()
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize(String hostName, Int32 historyCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment]
It's possible this is another symptom of #524 which was fixed.
