### ISSUE TITLE
Last 78 Key.

### ISSUE THREAD

**Issue by thevk70** [PowerShell/PSReadLine#3546]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
PS C:\Users\vishu\Desktop\Assignment C++ Ineuron Course>
 cd "c:\Users\vishu\Desktop\Assignment C++ Ineuron Course"
PS C:\Users\vishu\Desktop\Assignment C++ Ineuron Course> 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 78 Keys:
 c d Space " c : \ U s e r s \ v i s h u \ D e s k t o p \ A s s i g n m e n t Space C + + Space I n e u r o n Space C o u r s e " Enter
 & Space . \ " A s s i g n 2 3 . e x e " Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's 
buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)     
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\vishu\Desktop\Assignment C++ Ineuron Course>
```

### Screenshot

![bug](https://user-images.githubusercontent.com/100605183/213914377-6c834162-470f-4fbd-a01c-c5fbab8b6606.jpg)

### Environment data

```console
PS C:\Users\vishu\Desktop\Assignment C++ Ineuron Course>
 cd "c:\Users\vishu\Desktop\Assignment C++ Ineuron Course"
PS C:\Users\vishu\Desktop\Assignment C++ Ineuron Course> 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 78 Keys:
 c d Space " c : \ U s e r s \ v i s h u \ D e s k t o p \ A s s i g n m e n t Space C + + Space I n e u r o n Space C o u r s e " Enter
 & Space . \ " A s s i g n 2 3 . e x e " Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's 
buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\vishu\Desktop\Assignment C++ Ineuron Course>































   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\vishu\Desktop\Assignment C++ Ineuron Course>
```

### Steps to reproduce

Run this program in c++.

#include <iostream>
#include <cstring>
using namespace std;

int main()
{
    char name[10],name1[10];
    cout<<"Enter your name"<<endl;
    cin.get(name,10);
    cin.get(name1,10);
    cout<<"Name "<<name<<endl;
    cout<<"Name "<<name1<<endl;
    return 0;
}

### Expected behavior

Enter your name
vishu
vishwajeet
Name vishu
name vishwajeet

### Actual behavior

PS C:\Users\vishu\Desktop\Assignment C++ Ineuron Course>
 cd "c:\Users\vishu\Desktop\Assignment C++ Ineuron Course"
PS C:\Users\vishu\Desktop\Assignment C++ Ineuron Course> 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 78 Keys:
 c d Space " c : \ U s e r s \ v i s h u \ D e s k t o p \ A s s i g n m e n t Space C + + Space I n e u r o n Space C o u r s e " Enter
 & Space . \ " A s s i g n 2 3 . e x e " Space Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's 
buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\vishu\Desktop\Assignment C++ Ineuron Course>

**Comment by thevk70** [comment]
Check This Out.
