### ISSUE TITLE
System.TypeLoadException when starting powershell 7.2.9

### ISSUE THREAD

**Issue by bjdiedering** [PowerShell/PSReadLine#3552]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.9
OS: Microsoft Windows 10.0.22000
BufferWidth: 120
BufferHeight: 30

Last 0 Keys


```

### Exception
```
System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult' from assembly 'Microsoft.PowerShell.PSReadLine.Polyfiller, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionInlineView.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Prediction.Reset()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

![image](https://user-images.githubusercontent.com/74918413/214593626-4b13341b-c9e8-491f-8db5-b50f2f1fb1dc.png)


### Environment data

```console
Cannot Execute this powershell because PSReadline wont run because of the error...
```

### Steps to reproduce

When I start Windows Terminal I get the errormessage above. 
One of the prerequisites is reproducing on the newest version, but when I try to install the newest version (on standard powershell because my powershell 7 is broke) I get an error : 
```
PS C:\WINDOWS\system32> Install-Module -Name PSReadLine
Install-Module : The term 'Install-Module' is not recognized as the name of a cmdlet, function, script file, or operabl
e program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Install-Module -Name PSReadLine
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-Module:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Expected behavior

I was expecting to startup Powershell 7 with the Windows Terminal without errors. 

### Actual behavior

This exception happens : System.TypeLoadException: Could not load type 'System.Management.Automation.Subsystem.PredictionResult'

**Comment by bjdiedering** [comment]
How can I install or uninstall a module if the powershell 7 starts up with an error and wont give me a prompt?!

**Comment by bjdiedering** [comment]
nevermind step 1 and 2 worked :) thanx github-actions bot ;)
