### ISSUE TITLE
exception ArgumentOutOfRangeException with setup "Tab to MenuComplete" and "HistorySearchCursorMovesToEnd"

### ISSUE THREAD

**Issue by freetomik** [PowerShell/PSReadLine#3559]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.MenuCompleteImpl(Menu menu, CommandCompletion completions)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.MenuComplete(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![PSReadLine_bug](https://user-images.githubusercontent.com/5520368/216107160-2f820eaa-33b4-44e6-a813-6ac4578b8ee0.gif)

### Environment data

```console
PS Version: 7.3.2
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.19041.320 (WinBuild.160101.0800)
BufferWidth: 202
BufferHeight: 60
```

### Steps to reproduce

1. run `Set-PSReadlineKeyHandler -Chord Tab -Function MenuComplete` to enable menu completion with tab key
2. run `Set-PSReadLineOption -HistorySearchCursorMovesToEnd` to move cursor to the end after history search
3. have folders `strong` and `stronghold` in current empty folder
4. type following keys:
`c d Spacebar s Tab h Tab Backspace h`

### Expected behavior

No exception.

### Actual behavior

The above exception happens.

**Comment by StevenBucher98** [comment]
Thank you so much for the in-depth repro steps! I can reproduce it and marked as a bug
