### ISSUE TITLE
Error with git add command

### ISSUE THREAD

**Issue by Davinder05** [PowerShell/PSReadLine#3636]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 C o r p A c t i o n s O v e r w r i t e T e s t s . j a v a Space Space s r c / t e s t / j a v a / c o m / s p g l o b a l / t e s t s / I m p a c t A
 n a l y s i s D e p e n d e n c y L a b e l s O v e r w r i t e T e s t s . j a v a Space s r c / t e s t / j a v a / c o m / s p g l o b a l / t e s t
 s / I m p a c t A n a l y s i s P r i c e O v e r w r i t e T e s t s . j a v a Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow UpArrow UpArrow UpArrow UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -8.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
```

### Screenshot

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 C o r p A c t i o n s O v e r w r i t e T e s t s . j a v a Space Space s r c / t e s t / j a v a / c o m / s p g l o b a l / t e s t s / I m p a c t A
 n a l y s i s D e p e n d e n c y L a b e l s O v e r w r i t e T e s t s . j a v a Space s r c / t e s t / j a v a / c o m / s p g l o b a l / t e s t
 s / I m p a c t A n a l y s i s P r i c e O v e r w r i t e T e s t s . j a v a Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow UpArrow UpArrow UpArrow UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -8.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)

### Environment data

```console
git version 2.33.0.windows.2
```

### Steps to reproduce

git add

### Expected behavior

git add should be success

### Actual behavior

Exception

**Comment by Davinder05** [comment]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 s C o r p A c t i o n s O v e r w r i t e T e s t s . j a v a Space Space s r c / t e s t / j a v a / c o m / s p g l o b a l / t e s t s / I m p a c t
 A n a l y s i s D e p e n d e n c y L a b e l s O v e r w r i t e T e s t s . j a v a Space s r c / t e s t / j a v a / c o m / s p g l o b a l / t e s
 t s / I m p a c t A n a l y s i s P r i c e O v e r w r i t e T e s t s . j a v a Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow UpArrow UpArrow UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -8.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)        
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
