### ISSUE TITLE
I set my DingDuration to 0, and that causes an exception when calling the System.Console.Beep API

### ISSUE THREAD

**Issue by AndrewGaspar** [PowerShell/PSReadLine#364]
```
SD E:\rs\dv3\minkernel [minkernel]> Set-PSReadlineOption -DingDuration 0
SD E:\rs\dv3\minkernel [minkernel]>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Spacebar . . Backspace Backspace Backspace Backspace Backspace l s Enter
 d c Backspace Backspace Backspace d Backspace l s Spacebar s h i m Enter
 c d Backspace Backspace Backspace Backspace Backspace l s Spacebar t e s t s Enter
 c d Spacebar t e s t Tab Enter
 s d h i s t o r y Enter
 s d v Spacebar / ? Enter
 m i n k e r n e l Enter
 s d h i Backspace Backspace Backspace Backspace e r r Spacebar Ctrl+v Enter
 e r r Spacebar Ctrl+v Enter
 LeftWindows s e t - p r e Backspace Backspace s r e a d o n l i n Backspace Backspace Backspace Backspace Backspace l i
 n e o p Tab Spacebar - d i Tab Tab Spacebar Escape g e t - v e r b Enter
 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace UpArrow UpArrow UpA
rrow Escape s e t - p s r e a d o Backspace l i n e o p Tab Spacebar - d u r Tab Backspace Backspace i n g d u Tab Space
bar - Backspace 0 Enter
 Backspace

Exception:
System.ArgumentOutOfRangeException: Positive number required.
Parameter name: duration
Actual value was 0.
   at System.Console.Beep(Int32 frequency, Int32 duration)
   at Microsoft.PowerShell.PSConsoleReadLine.Microsoft.PowerShell.Internal.IPSConsoleReadLineMockableMethods.Ding()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

![image](https://cloud.githubusercontent.com/assets/2292643/14094682/4cbf6752-f50d-11e5-949d-6da968f0b147.png)

**Comment by lzybkr** [comment]
Nice.  Until I fix this, maybe you'll prefer:

Set-PSReadlineOption -BellStyle None
