### ISSUE TITLE
error in  vs code where no program written is giving output and shows a certain bug

### ISSUE THREAD

**Issue by MaheshVerma12** [PowerShell/PSReadLine#3656]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [x] Search the existing issues, especially the pinned issues.

### Exception report

```console
PS C:\Users\Bageshwory Infosys\Desktop>


Oops, something went wrong.  Please report this bug with the details below.   
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------       
Last 1 Keys:
 &

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------       
PS C:\Users\Bageshwory Infosys\Desktop>  "C:/Users/Bageshwory Infosys/AppData/Local/Programs/Python/Python310/python.exe" "c:/Users/Bageshwory Infosys/Desktop/one.py"
At line:1 char:83
+ ... on/Python310/python.exe"         
"c:/Users/Bageshwory 
Infosys/Desktop/one.py"
+                              ~~~~~~~ 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
Unexpected token 
'"c:/Users/Bageshwory
Infosys/Desktop/one.py"' in
expression or statement.
    + CategoryInfo          : ParserE
   rror: (:) [], ParentContainsError
  RecordException
    + FullyQualifiedErrorId : Unexpec
   tedToken

PS C:\Users\Bageshwory Infosys\Desktop>
```

### Screenshot

no ouput is given with this bug statement and other bugs.

### Environment data

```console
it all works in PowerShell but seems to be a problem in vs code
```

### Steps to reproduce

#list in python
a = [1, 2 ,4 ,5 ,3 ,12 ,7 ]
print(a[3])

# list methods
list.sort()
print(a)

### Expected behavior

it is supposed to give output

### Actual behavior

no output is given with this bug statement and other bugs.

**Comment by MaheshVerma12** [comment]
sorry in the above one list. Sort was my bad but it still shows this bug sometimes even with just basic printing like
a = 5
print(a)

**Comment by daxian-dbw** [comment]
The version of PSReadLine you are using is very old, likely 2.0.0-beta2 or prior. The issue has been fixed in later versions of PSReadLine, so please upgrade to the latest stable version v2.2.6. See the upgrade instructions here: https://github.com/PowerShell/PSReadLine#upgrading
