### ISSUE TITLE
Told to Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.

### ISSUE THREAD

**Issue by VWACRansom** [PowerShell/PSReadLine#3666]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.2.6
PowerShell: 2023.3.3
OS: Microsoft Windows 10.0.19045
BufferWidth: 207
BufferHeight: 12

Last 200 Keys:

 p p p p p p p p p p p Ctrl+c Ctrl+c Enter
 Enter
 p p p p p p p p p p p p p UpArrow Enter
 p p p p p p p p p p p p p p $ T a b l e Spacebar | Spacebar W h e r e - O b j e c t Spacebar { Spacebar $ _ . " R e p o r t s Spacebar T o " Spacebar - e q Spacebar " " Spacebar } Enter
 p p p p p p p p p p p p p p p p $ p r o j e c t . V a l u e Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow . N a m e Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Spacebar | Spacebar C o n v e r t T o - J s o n Enter
 p p $ p r o j e c t Enter
 UpArrow [ $ p r o j e c t . K e y s ] Enter
 p e y s Escape Enter
 Enter
 Enter
 p

### Exception

System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.InternalRegister(Action`1 callback, Object stateForCallback, SynchronizationContext targetSyncContext, ExecutionContext executionContext)
   at System.Threading.CancellationToken.Register(Action`1 callback, Object state, Boolean useSynchronizationContext, Boolean useExecutionContext)
   at System.Threading.CancellationToken.InternalRegisterWithoutEC(Action`1 callback, Object state)
   at System.Threading.CancellationTokenSource.CreateLinkedTokenSource(CancellationToken token1, CancellationToken token2)
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.CancellationContext.EnterScope(Boolean isIdleScope, CancellationToken cancellationToken)
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost.OnPowerShellIdle(CancellationToken idleCancellationToken)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![image](https://user-images.githubusercontent.com/68121441/235511391-9b0e7708-6683-4c42-b246-6acf4835135d.png)

### Environment data

```console
PS Version: 5.1.19041.2673
PS HostName: Visual Studio Code Host
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 207
BufferHeight: 12
```

### Steps to reproduce

Was running a PowerShell script in debug, and made some changes while at a breakpoint.
While typing ".Keys" the ".K" appeared in the code, but the "eys" appeared in the terminal. I hit escape and and enter to clear the Terminal, then finished the "eys" in the code.
It showed an error "Missing property name after reference operator." even with the .Keys there. I tried deleting the ".Keys" but the error was still there. I re-entered it again, but the error was still there.
So, I attempted to save the file. It went into the long waiting loop trying to format the code before saving. I don't remember if I cancelled it or not.
I then stopped the debug session and tried to save the file again. Then the error showed up.
After that, I saved it again and everything went well.

### Expected behavior

When typing in code window, not to jump to terminal window
When modifying the code, detect the error has been addressed.
Format and save the file on first attempt.

### Actual behavior

Jumped to terminal window while typing in code window
Error never went away, even when deleting and redoing proper code.
File formatting and saving failed and this error showed up.

**Comment by daxian-dbw** [comment]
This looks like an issue in the PowerShell VSCode extension. I will transfer this issue to the right repository.
