### ISSUE TITLE
powershell on rhel 8 gives error running on docker without maximized powershell windows on windows

### ISSUE THREAD

**Issue by GjpaRRY** [PowerShell/PSReadLine#3676]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
tryuing to run any commend in docker container after opening interactive session with it using:

nerdctl exec -it 36fd8cdfaa53 /bin/bash


get error after running pwsh

EProcess terminated. The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineFromConsole(Boolean endOnTab, String initialContent, Boolean calledFromPipeline, String& restOfLine, ReadLineResult& result)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLine(Boolean endOnTab, String initialContent, ReadLineResult& result, Boolean calledFromPipeline, Boolean transcribeResult)
   at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineWithTabCompletion(Executor exec)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
   at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
   at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
   at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName, String configurationFilePath)
   at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, Boolean issProvidedExternally)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String[] args, Int32 argc)Aborted
```

### Screenshot

bash-4.4$ pwsh
PowerShell 7.3.4
PS /home/oracle>

### Environment data

```console
bash-4.4$ pwsh -c '$psversiontable'

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP …
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Steps to reproduce

install powershell 7.3.4.1 on container... on oracle enterprise linux... run conatiner connect to it without maximising powershell windows on widnows.  open pwsh ... typoe any commands and get error

### Expected behavior

No exception

### Actual behavior

get error shown above

**Comment by daxian-dbw** [comment]
@GjpaRRY Can you please provide the detailed repro steps? Including which container to install, how 7.3.4 is installed, how pwsh get invoked, and etc., in steps 1, 2, 3, 4, ...
This will help us to reproduce the problem locally for investigation.
