### ISSUE TITLE
UpArrow error

### ISSUE THREAD

**Issue by marshallovski** [PowerShell/PSReadLine#3751]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Last 1 Keys:
 UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```
```


### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.3031
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.320 (WinBuild.160101.0800)
BufferWidth: 76
BufferHeight: 3000
```

### Steps to reproduce

just press "arrow down" button. its happened to me for first time

### Expected behavior

return the previous console value

### Actual behavior

UpArrow error

**Comment by StevenBucher98** [comment]
It looks like you are on a beta version of PSReadLine, can you try updating to the latest stable version, https://www.powershellgallery.com/packages/PSReadLine/2.2.6, by using `Install-Module -Name PSReadLine -RequiredVersion 2.2.6`. Let us know if you still run into the issue after the upgrade.
