### ISSUE TITLE
Barf on expressions in Format-Table

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PSReadLine#376]
I was using the PowerSploit functions.  I pasted the  Find-4648Logons into the console and then did  the following which got a an error directing me to post a bug:

PS> Find-4648Logons $SecurityLog -ov a
PS> $a |sort {$_.times.count} |ft @{
Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 200 Keys:
 e Tab Enter
 UpArrow Spacebar = Backspace - o v Spacebar a Enter
 $ a [ 0 ] Enter
 UpArrow Backspace Backspace Backspace UpArrow Backspace Backspace Backspace . k k Backspace e y s Enter
 UpArrow Backspace Enter
 UpArrow Backspace Backspace Backspace Ctrl+Spacebar Backspace Spacebar } g n Backspace Backspace Backspace Backspace Backspace Backspace g c m n Backspace Spacebar - i n Spacebar $ a Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace m Enter
 UpArrow LeftArrow LeftArrow LeftArrow p u Enter
 $ a Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Backspace Backspace Backspace Backspace Backspace Home $ a = Enter
 UpArrow UpArrow UpArrow Enter
 $ a [ 0 ] Enter
 $ a . k e y s Enter
 UpArrow Spacebar | s o r t Enter
 UpArrow Spacebar - o v Spacebar b Enter
 $ a [ 0 Backspace $ b [ 0 ] ] Enter
 $ a Spacebar | $ a . Backspace Backspace Backspace s o r t Spacebar $ Backspace { $ _ . t i m e s . c o u n t } Spacebar | f t Spacebar { $ _ Backspace Backspace Backspace @ { Ctrl+Spacebar

Exception:
System.ArgumentException: 'start' cannot be less than zero or greater than the length of the buffer
Parameter name: start
   at Microsoft.PowerShell.PSConsoleReadLine.Replace(Int32 start, Int32 length, String replacement)
   at Microsoft.PowerShell.PSConsoleReadLine.DoReplacementForCompletion(CompletionResult completionResult, CommandCompletion completions)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.MenuComplete(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
##    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

C:\WINDOWS\system32> $a |sort {$_.times.count} |ft @{

The bug is easily replicated:
PS> $a = gps
PS> $a |ft @{
Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 200 Keys:
 c o u n t } Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow . Backspace LeftArrow LeftArrow Left
Arrow @ ( RightArrow RightArrow ) Enter
 $ a Enter
 $ a . v a l u e Enter
 LeftArrow UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow @ \* Backspace ( RightArrow RightArrow ) Enter
 $ a | g m Enter
 $ a . v a l u e s Enter
 UpArrow UpArrow UpArrow UpArrow DownArrow UpArrow v Backspace s Enter
 UpArrow . t i m e s . c o u n t Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Spacebar | Spacebar T ^ Shift+Backspace Shift+Backspace % { $ _ . End } Enter
 UpArrow Shift+Spacebar | s o r t Enter
 g h y Enter
 UpArrow Spacebar | ^ Backspace % Spacebar c o m m a n d l i n e Enter
 $ a Spacebar = Spacebar g p s Enter
 $ a Spacebar | s o r t Backspace Backspace Backspace o Backspace Backspace f t Spacebar @ { Tab

Exception:
System.ArgumentException: 'start' cannot be less than zero or greater than the length of the buffer
Parameter name: start
   at Microsoft.PowerShell.PSConsoleReadLine.Replace(Int32 start, Int32 length, String replacement)
   at Microsoft.PowerShell.PSConsoleReadLine.DoReplacementForCompletion(CompletionResult completionResult, CommandCompletion completions)
   at Microsoft.PowerShell.PSConsoleReadLine.Complete(Boolean forward)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
##    at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

C:\WINDOWS\system32> $a |ft @{

**Comment by CJHarmath** [comment]
Just ran into the same by hitting a tab after 
`new-object System.Net.WebClient -Property @{`

```
Exception:
System.ArgumentException: 'start' cannot be less than zero or greater than the length of the buffer
Parameter name: start
   at Microsoft.PowerShell.PSConsoleReadLine.Replace(Int32 start, Int32 length, String replacement, Action`2 instigator, Object instigatorArg)
   at Microsoft.PowerShell.PSConsoleReadLine.DoReplacementForCompletion(CompletionResult completionResult, CommandCompletion completions)
   at Microsoft.PowerShell.PSConsoleReadLine.Complete(Boolean forward)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment]
Dupe of #534.
