### ISSUE TITLE
Why is this coming???????????

### ISSUE THREAD

**Issue by Anilkumar7877** [PowerShell/PSReadLine#3767]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Space " c : \ U s e r s \ L O O K \ D e s k t o p \ C + + e x \ . v s c o d e \ 5 . B i t w i s e Space o p e r a t o r s , F o r Space l o o p s , v a r i a b l e Space s c o p i n g \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space p r o d u c t m i n u s s u m q u e s t i o n . c p p Space - o Space p r o d u c t m i n u s s u m q u e s t i o n Space } Space ; Space i f Space ( $ ? ) Space { Space . \ p r o d u c t m i n u s s u m q u e s t i o n Space } Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)       
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)   
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

N/A

### Environment data

```console
N/A
```

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by StevenBucher98** [comment]
Can you please provide more clear reproduction steps and environment information? We are unable to take any actionable steps from the information you provided.

**Comment by daxian-dbw** [comment]
The report URL https://github.com/lzybkr/PSReadLine/issues/new indicates you are using a very old version of PSReadLine. Please upgrade to the latest 2.2.6 and try again.
