### ISSUE TITLE
Clipboard crash

### ISSUE THREAD

**Issue by MarkHone** [PowerShell/PSReadLine#377]
I guess the below copied and pasted from the console says it all.  I was just trying to copy the command and paste it into a text editor (Notepad++).  Despite this message, the paste operation succeeded.

```
PS H:\aws> Get-DefaultAWSRegion
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 16 Keys:
 c d Spacebar a w s Enter
 d i r Enter
 UpArrow UpArrow UpArrow Shift+Home Ctrl+c

Exception:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at Microsoft.PowerShell.PSConsoleReadLine.Copy(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------


```

**Comment by lzybkr** [comment]
Duplicate of #265
