### ISSUE TITLE
WebDriverException non-specific

### ISSUE THREAD

**Issue by DavidBRatcliff** [PowerShell/PSReadLine#3777]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Exception has occurred: WebDriverException
Message: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
<style>
a:link
{
    font-family:Arial,Helvetica,sans-serif;
    font-size:10pt;
    color:Red;
    }
a:visited
{
    font-family:Arial,Helvetica,sans-serif;
    font-size:10pt;
    color:Red;
    }
td
{
    font-family:Arial,Helvetica,sans-serif;
    padding-left:20px;
    padding-right:20px;
    }
</style>
    <title>Restricted Site</title>
</head>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title> Texas Instruments - Web Filter</title>
	<script src='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/modernizr.js'></script>
	<link href='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/style.css' rel="stylesheet"/>

<script src='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/jquery-1.10.2.js' type="text/javascript"></script>
<script src='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/bootstrap.js' type="text/javascript"></script>
<script src='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/respond.js' type="text/javascript"></script>

<script type="text/javascript">
	function showFAQs() {
		divs = document.getElementsByClassName("FAQs");
		for (i = 0; i < divs.length; i++) {
			display = divs[i].style.display;
			if (display == "block") {
				divs[i].style.display= "none";
			} else {
				divs[i].style.display= "block";
			}
		}
	}
</script>

<style>
	.FAQ { display:none; /* 's' was removed from end of .FAQ to disable style */}
</style>


<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<a href="http:///www.ti.com" class="navbar-brand">
				<!-- <b>Texas Instruments</b>-->
				<img src="/mwg-internal/de5fs23hu73ds/files/default/logo.png" alt="Logo" style="width:193px;height:24px;">
			</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
			</ul>
		</div>
	</div>
</div>

<div class="container body-content">
	<div class="jumbotron">
		<h1> Proceed with caution</h1>
		<br />
		<br />
		<p class="lead">
			<b>
				The Internet site you are trying to access is not categorized by TI's security vendor.
			</b>
			<br />
			<br />
			<i>
				Uncategorized sites have a higher rate of malicious Internet content.
			</i>
		</p>

		<p>
			If you trust this site, click <b>'Yes, continue to site'.</b> Otherwise, close this page and exit.
		</p>
		<br />

		<p>


			
		</p>


		<p style="float:left">
			  
		</p>

		<p style="float:right">
			<b> Please confirm: </b>
			<input type="button" id="activatebutton" value="Yes, continue to site »" onclick="activateSession(&quot;/mwg-internal/de5fs23hu73ds/plugin?target=QuotaPlugin&amp;quotatype=coaching&quot;,&quot;&quot;,&quot;aHR0cDovL2xvY2FsaG9zdDo2MjIyNC9zZXNzaW9u.1691659037.1928815501.wfkUD9nk9z3H8Z7L7Jqov9mnTPdLA9cCVTM4erBhdmE,&quot;); return false;" class="btn btn-primary btn-lg" style="margin-left:5em" />
		</p>

		<br />
		<br />
		<br />
		<br />

		<p>
			<b>URL: </b><font color="red">http://localhost:62224/session</font>
		</p>

		<p>
			<!-- Click <a href="#faqs"><font size="4">here</font></a> for a list of Frequently Asked Questions (FAQs). -->
			For further questions, go to <a href="http://help.ti.com"><font size="4">http://help.ti.com</font></a> and contact the help desk.
		</p>

		<div class="FAQs" id="faqs">
			<br />
			<h1> FAQs </h1>
			<br />
			<p>
				TI's web security vendor, McAfee, utilizes a site categorization engine named TrustedSource. 
				TrustedSource is an Internet reputation system that provides reputation scores for Internet identities, 
				such as IP addresses, URLs, domains, and email/web content. TrustedSource works by analyzing in real-time 
				traffic patterns from email, web and network data flows from McAfee's global set of security appliances 
				and hosted services, as well as those of partners.
			</p>

			<p>
				<ul>
				<font size="4">
					<li><font color="red">Why is XYZ site uncategorized?</font></li>
					
					<p class="answer">
					&emsp; There are numerous reasons that a site might be uncategorized by McAfee. The most frequent reason is that the site is not commonly visited
					by Internet users, or  you may have mis-typed the URL. Alternatively, the site might be very new and McAfee hasn't yet had the chance to assign a category to the site.
					</p>
					
					<br />
					<br />
					
					<li><font color="red">How do I get a site categorized?</font></li>
					
					<div>
					&emsp; To request that a site have a proper category, please visit <a href="https://sitelookup.mcafee.com/"><font size="4">this link</font></a>.
					First select <b>"McAfee Web Gateway v7.x/v6.9.x (resident)"</b> from the drop down menu. Then enter the URL into the freeform field beneath the drop down menu.
					After clicking <b>"Check URL",</b> you will be given the option to suggest categories for the site.
					</div>
					
					<br />
					<br />
					
					<li><font color="red">Do I need to get this site categorized?</font></li>
					&emsp; There is no strict requirement to request that a site be categorized. However, it may benefit you to request that a site be categorized if you frequently visit the 
					site and are continually having to click through this warning page.
				</font>
				</ul>
			</p>
				
		</div>

</div>

<hr />

<footer>
	<p>&copy; 2015 - Texas Instruments</p>
</footer>


</html>

  File "C:\Users\a0233720\Documents\New folder\selenium_test.py", line 12, in <module>
    driver = webdriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
selenium.common.exceptions.WebDriverException: Message: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
<style>
a:link
{
    font-family:Arial,Helvetica,sans-serif;
    font-size:10pt;
    color:Red;
    }
a:visited
{
    font-family:Arial,Helvetica,sans-serif;
    font-size:10pt;
    color:Red;
    }
td
{
    font-family:Arial,Helvetica,sans-serif;
    padding-left:20px;
    padding-right:20px;
    }
</style>
    <title>Restricted Site</title>
</head>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title> Texas Instruments - Web Filter</title>
	<script src='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/modernizr.js'></script>
	<link href='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/style.css' rel="stylesheet"/>

<script src='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/jquery-1.10.2.js' type="text/javascript"></script>
<script src='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/bootstrap.js' type="text/javascript"></script>
<script src='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/respond.js' type="text/javascript"></script>

<script type="text/javascript">
	function showFAQs() {
		divs = document.getElementsByClassName("FAQs");
		for (i = 0; i < divs.length; i++) {
			display = divs[i].style.display;
			if (display == "block") {
				divs[i].style.display= "none";
			} else {
				divs[i].style.display= "block";
			}
		}
	}
</script>

<style>
	.FAQ { display:none; /* 's' was removed from end of .FAQ to disable style */}
</style>


<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<a href="http:///www.ti.com" class="navbar-brand">
				<!-- <b>Texas Instruments</b>-->
				<img src="/mwg-internal/de5fs23hu73ds/files/default/logo.png" alt="Logo" style="width:193px;height:24px;">
			</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
			</ul>
		</div>
	</div>
</div>

<div class="container body-content">
	<div class="jumbotron">
		<h1> Proceed with caution</h1>
		<br />
		<br />
		<p class="lead">
			<b>
				The Internet site you are trying to access is not categorized by TI's security vendor.
			</b>
			<br />
			<br />
			<i>
				Uncategorized sites have a higher rate of malicious Internet content.
			</i>
		</p>

		<p>
			If you trust this site, click <b>'Yes, continue to site'.</b> Otherwise, close this page and exit.
		</p>
		<br />

		<p>


			
		</p>


		<p style="float:left">
			  
		</p>

		<p style="float:right">
			<b> Please confirm: </b>
			<input type="button" id="activatebutton" value="Yes, continue to site »" onclick="activateSession(&quot;/mwg-internal/de5fs23hu73ds/plugin?target=QuotaPlugin&amp;quotatype=coaching&quot;,&quot;&quot;,&quot;aHR0cDovL2xvY2FsaG9zdDo2MjIyNC9zZXNzaW9u.1691659037.1928815501.wfkUD9nk9z3H8Z7L7Jqov9mnTPdLA9cCVTM4erBhdmE,&quot;); return false;" class="btn btn-primary btn-lg" style="margin-left:5em" />
		</p>

		<br />
		<br />
		<br />
		<br />

		<p>
			<b>URL: </b><font color="red">http://localhost:62224/session</font>
		</p>

		<p>
			<!-- Click <a href="#faqs"><font size="4">here</font></a> for a list of Frequently Asked Questions (FAQs). -->
			For further questions, go to <a href="http://help.ti.com"><font size="4">http://help.ti.com</font></a> and contact the help desk.
		</p>

		<div class="FAQs" id="faqs">
			<br />
			<h1> FAQs </h1>
			<br />
			<p>
				TI's web security vendor, McAfee, utilizes a site categorization engine named TrustedSource. 
				TrustedSource is an Internet reputation system that provides reputation scores for Internet identities, 
				such as IP addresses, URLs, domains, and email/web content. TrustedSource works by analyzing in real-time 
				traffic patterns from email, web and network data flows from McAfee's global set of security appliances 
				and hosted services, as well as those of partners.
			</p>

			<p>
				<ul>
				<font size="4">
					<li><font color="red">Why is XYZ site uncategorized?</font></li>
					
					<p class="answer">
					&emsp; There are numerous reasons that a site might be uncategorized by McAfee. The most frequent reason is that the site is not commonly visited
					by Internet users, or  you may have mis-typed the URL. Alternatively, the site might be very new and McAfee hasn't yet had the chance to assign a category to the site.
					</p>
					
					<br />
					<br />
					
					<li><font color="red">How do I get a site categorized?</font></li>
					
					<div>
					&emsp; To request that a site have a proper category, please visit <a href="https://sitelookup.mcafee.com/"><font size="4">this link</font></a>.
					First select <b>"McAfee Web Gateway v7.x/v6.9.x (resident)"</b> from the drop down menu. Then enter the URL into the freeform field beneath the drop down menu.
					After clicking <b>"Check URL",</b> you will be given the option to suggest categories for the site.
					</div>
					
					<br />
					<br />
					
					<li><font color="red">Do I need to get this site categorized?</font></li>
					&emsp; There is no strict requirement to request that a site be categorized. However, it may benefit you to request that a site be categorized if you frequently visit the 
					site and are continually having to click through this warning page.
				</font>
				</ul>
			</p>
				
		</div>

</div>

<hr />

<footer>
	<p>&copy; 2015 - Texas Instruments</p>
</footer>


</html>
```

### Screenshot

>>> driver = webdriver.Chrome(options=options)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\a0233720\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\a0233720\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\a0233720\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\a0233720\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a0233720\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\a0233720\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
<style>
a:link
{
    font-family:Arial,Helvetica,sans-serif;
    font-size:10pt;
    color:Red;
    }
a:visited
{
    font-family:Arial,Helvetica,sans-serif;
    font-size:10pt;
    color:Red;
    }
td
{
    font-family:Arial,Helvetica,sans-serif;
    padding-left:20px;
    padding-right:20px;
    }
</style>
    <title>Restricted Site</title>
</head>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title> Texas Instruments - Web Filter</title>
        <script src='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/modernizr.js'></script>
        <link href='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/style.css' rel="stylesheet"/>

<script src='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/jquery-1.10.2.js' type="text/javascript"></script>
<script src='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/bootstrap.js' type="text/javascript"></script>
<script src='/mwg-internal/de5fs23hu73ds/files/default/Coaching_Page/respond.js' type="text/javascript"></script>

<script type="text/javascript">
        function showFAQs() {
                divs = document.getElementsByClassName("FAQs");
                for (i = 0; i < divs.length; i++) {
                        display = divs[i].style.display;
                        if (display == "block") {
                                divs[i].style.display= "none";
                        } else {
                                divs[i].style.display= "block";
                        }
                }
        }
</script>

<style>
        .FAQ { display:none; /* 's' was removed from end of .FAQ to disable style */}
</style>

<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
                <div class="navbar-header">
                        <a href="http:///www.ti.com" class="navbar-brand">
                                
                                <img src="/mwg-internal/de5fs23hu73ds/files/default/logo.png" alt="Logo" style="width:193px;height:24px;">
                        </a>
                </div>
                <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                        </ul>
                </div>
        </div>
</div>

<div class="container body-content">
        <div class="jumbotron">
                <h1> Proceed with caution</h1>
                <br />
                <br />
                <p class="lead">
                        <b>
                                The Internet site you are trying to access is not categorized by TI's security vendor.
                        </b>
                        <br />
                        <br />
                        <i>
                                Uncategorized sites have a higher rate of malicious Internet content.
                        </i>
                </p>

                <p>
                        If you trust this site, click <b>'Yes, continue to site'.</b> Otherwise, close this page and exit.
                </p>
                <br />

                <p>

                </p>

                <p style="float:left">

                </p>

                <p style="float:right">
                        <b> Please confirm: </b>
                        <input type="button" id="activatebutton" value="Yes, continue to site »" onclick="activateSession(&quot;/mwg-internal/de5fs23hu73ds/plugin?target=QuotaPlugin&amp;quotatype=coaching&quot;,&quot;&quot;,&quot;aHR0cDovL2xvY2FsaG9zdDo2MzQ3NC9zZXNzaW9u.1691662416.672255223.J-OFRgD_sWYPXnxUWmeo4mlBPd2jTFiyLqiVW7HMC-4,&quot;); return false;" class="btn btn-primary btn-lg" style="margin-left:5em" />
                </p>

                <br />
                <br />
                <br />
                <br />

                <p>
                        <b>URL: </b><font color="red">http://localhost:63474/session</font>
                </p>

                <p>
                        
                        For further questions, go to <a href="http://help.ti.com"><font size="4">http://help.ti.com</font></a> and contact the help desk.
                </p>

                <div class="FAQs" id="faqs">
                        <br />
                        <h1> FAQs </h1>
                        <br />
                        <p>
                                TI's web security vendor, McAfee, utilizes a site categorization engine named TrustedSource.
                                TrustedSource is an Internet reputation system that provides reputation scores for Internet identities,
                                such as IP addresses, URLs, domains, and email/web content. TrustedSource works by analyzing in real-time
                                traffic patterns from email, web and network data flows from McAfee's global set of security appliances
                                and hosted services, as well as those of partners.
                        </p>

                        <p>
                                <ul>
                                <font size="4">
                                        <li><font color="red">Why is XYZ site uncategorized?</font></li>

                                        <p class="answer">
                                        &emsp; There are numerous reasons that a site might be uncategorized by McAfee. The most frequent reason is that the site is not commonly visited
                                        by Internet users, or  you may have mis-typed the URL. Alternatively, the site might be very new and McAfee hasn't yet had the chance to assign a category to the site.
                                        </p>

                                        <br />
                                        <br />

                                        <li><font color="red">How do I get a site categorized?</font></li>

                                        <div>
                                        &emsp; To request that a site have a proper category, please visit <a href="https://sitelookup.mcafee.com/"><font size="4">this link</font></a>.
                                        First select <b>"McAfee Web Gateway v7.x/v6.9.x (resident)"</b> from the drop down menu. Then enter the URL into the freeform field beneath the drop down menu.
                                        After clicking <b>"Check URL",</b> you will be given the option to suggest categories for the site.
                                        </div>

                                        <br />
                                        <br />

                                        <li><font color="red">Do I need to get this site categorized?</font></li>
                                        &emsp; There is no strict requirement to request that a site be categorized. However, it may benefit you to request that a site be categorized if you frequently visit the
                                        site and are continually having to click through this warning page.
                                </font>
                                </ul>
                        </p>

                </div>

</div>

<hr />

<footer>
        <p>&copy; 2015 - Texas Instruments</p>
</footer>

</html>

>>>

### Environment data

```console
PS Version: 5.1.19041.3031
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 3000
```

### Steps to reproduce

Cut and Paste working example off internet 
Exception occurs at the webdriver statement.  No difference in output results between MS-edge, Chrome, Firefox browsers

### Expected behavior

expected webpage

### Actual behavior

diverted to error page

**Comment by DavidBRatcliff** [comment]
Error is independent of PSReadLine, as program originally ran without PSReadLine, and it was only added to help diagnose the problem.  Please try again.
