### ISSUE TITLE
Error Message when logging in via Session Manager

### ISSUE THREAD

**Issue by s-mustafa-rashid** [PowerShell/PSReadLine#3789]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0
PowerShell: 5.1.20348.1850
OS: Microsoft Windows 10.0.20348
Last 0 Keys


```

### Exception
```
System.UnauthorizedAccessException: Access to the path 'PSReadLineHistoryFile_1679151030' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNew, MutexSecurity mutexSecurity)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

### Screenshot

N/A

### Environment data

```console
Get-CimInstance : Access denied
At line:6 char:18
+ ...        $p = Get-CimInstance -ClassName Win32_Process -Filter "Process ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041003,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand


PS Version: 5.1.20348.1850
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0
PSReadLine EditMode: Windows
OS: 10.0.20348.1 (WinBuild.160101.0800)
BufferWidth: 210
BufferHeight: 3000
```

### Steps to reproduce

Logged into AWS instance via Session Manager

### Expected behavior

Prompt

### Actual behavior

Error message

**Comment by StevenBucher98** [comment]
Looks like some kind of permission issue with the location of the file. I suggest trying to upgrade to the latest version 2.3.3 however we believe no changes were made since 2.0.0 with the mutex of this file so its likely some kind of permission issue on the machine you are using.
