### ISSUE TITLE
ArgumentOutOfRangeException on arrow up

### ISSUE THREAD

**Issue by dan-mathews** [PowerShell/PSReadLine#3792]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this 
bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less thaParameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)        
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

There's no history in the terminal half in which the error occured since it was new.

<img width="1638" alt="bug" src="https://github.com/PowerShell/PSReadLine/assets/42862651/b9a40ec7-0ff1-4ba1-a010-723a67bb78ec">

### Environment data

```console
PS Version: 5.1.19041.3031
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 49
BufferHeight: 28
```

### Steps to reproduce

I haven't attempted to reproduce I also don't have time, just trying to be a reasonable web citizen by following the exception instructions.

I was working in Visual Studio Code, running a php server in a single terminal at the bottom. I then split my terminal into 2 halves, and pressed arrow up in the new half, which triggered the error.

### Expected behavior

no exception

### Actual behavior

exception

**Comment by dan-mathews** [comment]
I now realise this should have gone in Steps to reproduce, not exception report. Sorry, in a rush here

I was working in Visual Studio Code, running a php server in a single terminal at the bottom. I then split my terminal into 2 halves, and pressed arrow up in the new half, which triggered the error.
