### ISSUE TITLE
PowerShell console requested to submit bug report.

### ISSUE THREAD

**Issue by yotsuda** [PowerShell/PSReadLine#3831]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
PS O1:\総務部> Add-OrchFolderUser 'Automation Users',everyone
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.3.4
PowerShell: 7.3.8
OS: Microsoft Windows 10.0.22621
BufferWidth: 120
BufferHeight: 30

Last 65 Keys:

 c d Spacebar o 1 : RightArrow Enter
 g e t - o r c h u Tab Enter
 g e t - o r c h f Tab Tab Enter
 a d d - o r c h f o Tab Spacebar Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Tab Tab Spacebar Ctrl+Spacebar RightArrow RightArrow LeftArrow RightArrow RightArrow RightArrow RightArrow LeftArrow , Ctrl+Spacebar

### Exception

System.Management.Automation.PSInvalidOperationException: Cannot access properties on a null instance of the type CompletionResult.
   at System.Management.Automation.CompletionResult.get_ListItemText()
   at Microsoft.PowerShell.PSConsoleReadLine.<>c.<CreateCompletionMenu>b__54_0(CompletionResult c)
   at System.Linq.Enumerable.MaxInteger[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Microsoft.PowerShell.PSConsoleReadLine.CreateCompletionMenu(Collection`1 matches)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.MenuComplete(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

<img width="867" alt="image" src="https://github.com/PowerShell/PSReadLine/assets/6428198/fde59af3-266b-414b-9fb9-2c6bc9656263">

### Environment data

```console
PS Version: 7.3.8
PS HostName: ConsoleHost
PSReadLine Version: 2.3.4
PSReadLine EditMode: Windows
OS: 10.0.22621.1848 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

I am developing my own cmdlet with c#.
This has arg completer. when pressing ctrl+space to show the candidates, PS console shows message to request file a bug report.

### Expected behavior

Show the completion candidates.

### Actual behavior

Show the error above.

**Comment by yotsuda** [comment]
sorry, the correct first line is followng.
PS O1:\総務部> Add-OrchFolderUser 'Automation Users',

I mistakenly pasted as
PS O1:\総務部> Add-OrchFolderUser 'Automation Users',everyone
but the last "everyone" is the predicted text and I didn't type it.

**Comment by yotsuda** [comment]
I found ParameterSetName attribute usage was incorrect in my code. I fixed it and the problem gone. I am sorry for bothering you. Thanks.
