### ISSUE TITLE
VS code crash

### ISSUE THREAD

**Issue by kareemahmed30** [PowerShell/PSReadLine#3843]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)   
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

![Screenshot 2023-10-22 185026](https://github.com/PowerShell/PSReadLine/assets/132448699/082e4b9b-266a-401b-96c5-f20d6f95730c)

### Environment data

```console
PS Version: 5.1.19041.3570
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 3000
```

### Steps to reproduce

#include <iostream>
using namespace std;

int main()
{
    int n;
    cout << "Enter a number: ";
    cin >> n;
    for (int i = n; i > 0; i--)
    {
        bool prime = true;  
        for (int j = 2; j < i; j++)
        {
            if (i % j == 0)
                prime = false;
        }
        if (prime)
        {
            cout << i << "\n";
            break;
        }
        
    }
}

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by StevenBucher98** [comment]
@kareemahmed30 you are on an older version of PSReadLine, try upgrading to 2.3.4 by running `Install-Module -Name PSReadLine` and resetting your PowerShell sessions. Let us know if you are still having issues with the latest version.
