### ISSUE TITLE
Argument Out of Range Exception in VS Code Python Terminal

### ISSUE THREAD

**Issue by AllahDalla** [PowerShell/PSReadLine#3846]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 UpArrow Enter
 UpArrow Enter
 & Space C : / U s e r s / D e a n - A n d r e w / A p p D a t a / L o c a l / M i c r o s o f t / W i n d o w s A p p s / p y 
t h o n 3 . 1 0 . e x e Space c : / U s e r s / D e a n - A n d r e w / D e s k t o p / A l s c r i p t s / J - T E C / C u s t o m e r _ R e l a t i o n s _ M a n a g e m e n t / c r m / d a t a b a s e / T A P T e s t . p y Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 UpArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in 
that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.3570
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 127
BufferHeight: 31
```

### Steps to reproduce

Just pressing on the up key to trigger history while in a python terminal

### Expected behavior

N/A

### Actual behavior

N/A

**Comment by daxian-dbw** [comment]
@AllahDalla, This issue was already fixed (see #1306). Please upgrade to the [2.3.4 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.4) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
