### ISSUE TITLE
ArgEx from ViIndicateInsertMode: sometimes Console.CursorSize gives us zero

### ISSUE THREAD

**Issue by jazzdelightsme** [PowerShell/PSReadLine#386]
I'm using PSReadLine on an internal build of Windows, with the "confans" bits, and I got the following exception:

```
Exception:
System.ArgumentOutOfRangeException: The cursor size is invalid. It must be a percentage between 1 and 100.
Parameter name: value
Actual value was 0.
   at System.Console.set_CursorSize(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ViIndicateInsertMode()
   at Microsoft.PowerShell.PSConsoleReadLine.ViReplaceLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ViChord(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

That value is coming from `SetDefaultViBindings()`, which sets it to `_console.CursorSize` (so that's where the 0 came from).

Interestingly, I can't get this to repro for me in a normal PowerShell window--it only happens in a razzle environment. So I suppose some razzle tool is messing with console settings. But apparently it can happen, so we should probably protect against it. Agree? I can whip up a PR. I'll also ping the console people to see if this is expected.

**Comment by jazzdelightsme** [comment]
I believe the console guys have figured out the problem (some stuff could get dropped during a reflow/resize). Not fixed yet, but I'm guessing it will be soon. Based on that, maybe we _don't_ need to do anything to protect against this in PSReadLine.

On the other hand, though, they made a comment in their bug that "it's not wrong for the cursor size to be reported as 0 if the cursor size is actually set to 0 from the registry preference. The v1 console never enforced a minimum size here." So based on that, we probably should anyway.
