### ISSUE TITLE
ArgumentOutOfRangeException on CTRL+A / CTRL+SPACE

### ISSUE THREAD

**Issue by UNIcodeX** [PowerShell/PSReadLine#3860]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
-----------------------------------------------------------------------
Last 9 Keys:
 Ctrl+a Enter
 g i t Space Ctrl+Space Ctrl+Space Ctrl+Space

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -41.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/8235002/eaec333a-59a6-4766-b9bd-94ad5b24cee3)

### Environment data

```console
PS Version: 5.1.19041.1682
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 100
BufferHeight: 37
```

### Steps to reproduce

npm install -g @microsoft/inshellisense

inshellisense bind and selected powershell
restarted powershell
git (CTRL+a)

### Expected behavior

pop up with potential git commands opens up.

### Actual behavior

attached exception occurs.

**Comment by daxian-dbw** [comment]
The version of PSReadLine you were using is very old so the issue was likely fixed in recent versions. Please upgrade to the [2.3.4 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.4) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
