### ISSUE TITLE
Oops, something went wrong. when resizing

### ISSUE THREAD

**Issue by Rom265** [PowerShell/PSReadLine#3866]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.2.6
PowerShell: 7.3.8
OS: Microsoft Windows 10.0.19045
BufferWidth: 77
BufferHeight: 9001

Last 200 Keys:

 t Spacebar { $ _ | . \ u p d a t e - t a g . p s 1 Spacebar - D e l e t e Spacebar q u a l y s A g e n t I n s t a l l , s p l u n k A g e n t I n s t a l l } Home RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Backspace Backspace Backspace Backspace Backspace p r Tab o d Enter
 . \ r e Tab Spacebar d e c 5 e 2 9 0 - e a d 0 - 9 9 a a - 5 1 8 f - 9 6 7 c c 7 e a 9 5 b 9 Enter
 UpArrow Escape . \ r e Tab Spacebar b 6 c 5 e 2 9 1 - 0 2 f 0 - b 7 9 a - 8 4 c d - 7 a 8 e b 9 0 9 f 4 0 d Enter
 UpArrow UpArrow Enter
 UpArrow LeftWindows UpArrow

### Exception

System.IO.IOException: The parameter is incorrect.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.CalculateWhereAndWhatToRender(Boolean cursorMovedToInitialPos, RenderData renderData, LineInfoForRendering& lineInfoForRendering)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.UpdateFromHistory(HistoryMoveCursor moveCursor)
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

N/A

### Environment data

```console
PS Version: 7.3.8
PS HostName: ConsoleHost
PSReadLine Version: 2.2.6
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 157
BufferHeight: 9001
```

### Steps to reproduce

I used the Windows snap feature to resize the window from maximized to half-screen after running some script. Then, I think I hit the up arrow to run the script again, but nothing was showing on the screen; so, I maximized again and saw the "Oops" message.

### Expected behavior

No exception.

### Actual behavior

The above exception happened.

**Comment by daxian-dbw** [comment]
> I used the Windows snap feature to resize the window from maximized to half-screen after running some script. Then, I think I hit the up arrow to run the script again, but nothing was showing on the screen

I guess you went from "maximized" to "window-on-the-right" using <kbd>win+right</kbd>, right? This is a problem of the console host -- nothing is shown in the console after you snapping from "maximized" to "half-screen-on-the-right".

CMD.exe shows the same behavior in the console host. However, Windows terminal works fine, so you may want to switch to Windows Terminal instead. Close as a duplicate of #2037.
