### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by edisonpowell** [PowerShell/PSReadLine#3873]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [x] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0
PowerShell: 5.1.22621.2506
OS: Microsoft Windows 10.0.22621
Last 200 Keys

 i t c h f o r k % 2 0 % 2 8 O r i g i n a l % 2 9 . m p 4 ? e x p i r e s = 1 7 0 0 4 6 9 5 0 2 & l o c = e x t e r n a l & s e s s i o n _ i d = 1 1 b 4 5 7 7 7 8 6 f 9 9 f c 5 1 4 2 7 9 8 d 5 8 7 a e 4 6 5 c 9 5 6 8 e b a 2 1 7 0 0 3 8 2 9 8 2 & s i g n a t u r e = 7 4 a 4 1 4 e b 3 d 1 2 c a 5 f 7 0 4 8 7 3 8 9 a 5 e c 2 0 7 0 b 7 8 2 f 4 5 d c 9 3 e 6 4 2 8 5 1 1 0 a 8 5 5 9 b c d 1 2 9 3 Ctrl+a ,
```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 28.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Replace(Int32 start, Int32 length, String replacement, Action`2 instigator, Object instigatorArg)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

11/19/2023 8:22 PM, i dont have screenshot

### Environment data

```console
PS Version: 5.1.22621.2506
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.0.0
PSReadLine EditMode: Windows
OS: 10.0.22621.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

Ctrl + A and press the wrong button

### Expected behavior

Tried to del something

### Actual behavior

IDK

**Comment by StevenBucher98** [comment]
Looks like you are on an older version of PSReadLine, please update to the latest stable 2.3.4 and see if the bug persists.
