### ISSUE TITLE
Executing powershell script from unc path

### ISSUE THREAD

**Issue by eromanowski** [PowerShell/PSReadLine#388]
Last 0 Keys:
16:52:38Info
Exception:
16:52:38Info
System.IO.IOException: The handle is invalid.
16:52:38Info
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
16:52:38Info
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
16:52:38Info
   at Microsoft.PowerShell.Internal.ConhostConsole.get_CursorLeft()
16:52:38Info
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
16:52:38Info
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by eromanowski** [comment]
Task ID:        ServerTasks-12
Task status:    Executing
Task queued:    Monday, May 16, 2016 5:09 PM
Task started:   Monday, May 16, 2016 5:09 PM
Task duration:  1 minute
Server version: 3.3.12+Branch.master.Sha.0474f72915626d6dd344060fa5d54c919b1a1ebc

```
                | == Running: Deploy ECP Windows App release 0.5.108.0 to Dev ==
```

17:09:52   Verbose  |   Guided failure is not enabled for this task
                    | 
                    |   == Running: Step 1: Uninstall ==
                    |  
                    |     Running: Eric
17:09:52   Verbose  |       Octopus Server version: 3.3.12+Branch.master.Sha.0474f72915626d6dd344060fa5d54c919b1a1ebc
17:09:52   Info     |       Executing script on 'Eric'
17:09:52   Verbose  |       Octopus Deploy: Calamari version 3.3.12+Branch.master.Sha.5c60c9a9a96c3991cf8f8f3c1f28fe131d8648a4
17:09:53   Verbose  |       Name                           Value
17:09:53   Verbose  |       ----                           -----
17:09:53   Verbose  |       PSVersion                      5.1.14328.1000
17:09:53   Verbose  |       PSEdition                      Desktop
17:09:53   Verbose  |       PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
17:09:53   Verbose  |       CLRVersion                     4.0.30319.42000
17:09:53   Verbose  |       BuildVersion                   10.0.14328.1000
17:09:53   Verbose  |       WSManStackVersion              3.0
17:09:53   Verbose  |       PSRemotingProtocolVersion      2.3
17:09:53   Verbose  |       SerializationVersion           1.1.0.1
17:09:53   Info     |       Windows PowerShell
17:09:53   Info     |       Copyright (C) 2016 Microsoft Corporation. All rights reserved.
17:09:54   Info     |       Oops, something went wrong.  Please report this bug with the details below.
17:09:54   Info     |       Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
17:09:54   Info     |       -----------------------------------------------------------------------
17:09:54   Info     |       Last 0 Keys:
17:09:54   Info     |       Exception:
17:09:54   Info     |       System.IO.IOException: The handle is invalid.
17:09:54   Info     |       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
17:09:54   Info     |       at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
17:09:54   Info     |       at Microsoft.PowerShell.Internal.ConhostConsole.get_CursorLeft()
17:09:54   Info     |       at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
17:09:54   Info     |       at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
17:09:54   Info     |       -----------------------------------------------------------------------
                    |
