### ISSUE TITLE
Exception raised when trying to commit with message. 

### ISSUE THREAD

**Issue by vicflucus-lonza** [PowerShell/PSReadLine#3905]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Last 26 Keys:
 g i t Space s t a t u s Enter
 g i t Space c o m m i t Space - m Space "

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

<img width="960" alt="git commit error 18DEC23" src="https://github.com/PowerShell/PSReadLine/assets/151045893/c79589b7-1b36-431b-9e60-658e20bafeb4">

### Environment data

```console
PS Version: 5.1.19041.3693
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 133
BufferHeight: 32
```

### Steps to reproduce

git status
git commit -m "

### Expected behavior

I should be able to type a message to go along with my commit. 

### Actual behavior

Exception raised and I am unable to type a message

**Comment by vicflucus-lonza** [comment]
Resolved with previously posted issue. Thank you
