### ISSUE TITLE
Oops, something went wrong.  Please report this bug with the details below.

### ISSUE THREAD

**Issue by SleepTheGod** [PowerShell/PSReadLine#3938]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
PS C:\Windows\system32>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -22.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Windows\system32>
```

### Screenshot

# The Fix

# Check the installed version of PSReadLine
Get-Module PSReadLine -ListAvailable | Select-Object Name,Version,Path

# Update PSReadLine to the latest version available from PowerShell Gallery
Install-Module -Name PSReadLine -AllowClobber -Force

# Remove the PSReadLine configuration file
Remove-Item (Get-PSReadLineOption).HistorySavePath

# Restart PowerShell to see if the issue is resolved

### Environment data

```console
Current windows 10 pro
```

### Steps to reproduce

na

### Expected behavior

na

### Actual behavior

Just appeared

**Comment by SleepTheGod** [comment]
> This issue was already fixed (see #1306). Please upgrade to the [2.3.4 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.4) from PowerShell Gallery. See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.

Thank you
