### ISSUE TITLE
Powershell died

### ISSUE THREAD

**Issue by refe** [PowerShell/PSReadLine#3952]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0
PowerShell: 5.1.20348.2227
OS: Microsoft Windows 10.0.20348
Last 200 Keys

 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace LeftArrow LeftArrow Spacebar RightArrow RightArrow Backspace Backspace Backspace Enter
 a d d - m a n a g Tab Spacebar ' O R O Spacebar C o r t e x Spacebar A d m i n A c c Spacebar E x c h Spacebar M g m t Spacebar R o l e ' LeftArrow \ A d d - M a i l b o x P e r m i s s i o n Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 s e t - s Backspace d o Tab Escape s e t - Tab Spacebar 8 9 7 0 Enter
 Enter
 Enter
 Enter
 Enter
 UpArrow Backspace Backspace Backspace Backspace 2 2 5 3 0 Enter
 Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace 5 3 7 8 9 Enter
 Enter
 Enter
 Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace 1 5 0 2 3 Enter
 Enter
 Enter
 Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace 1 5 0 1 4 Enter
 Enter
 Enter
 Enter
 Enter

```

### Exception
```
System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Management.Automation.AmsiUtils.AmsiNativeMethods.AmsiCloseSession(IntPtr amsiContext, IntPtr amsiSession)
   at System.Management.Automation.AmsiUtils.CloseSession()
   at System.Management.Automation.Runspaces.PipelineBase..ctor(Runspace runspace, CommandCollection command, Boolean addToHistory, Boolean isNested, ObjectStreamBase inputStream, ObjectStreamBase outputStream, ObjectStreamBase errorStream, PSInformationalBuffers infoBuffers)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
```


### Screenshot

no screenshot ...the buffer was full of this error

### Environment data

```console
PS Version: 5.1.20348.2227
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0
PSReadLine EditMode: Windows
OS: 10.0.20348.1 (WinBuild.160101.0800)
BufferWidth: 122
BufferHeight: 3000
```

### Steps to reproduce

i can't reproduce ...it just happend over the week-end

### Expected behavior

console to remain usable

### Actual behavior

console was not usable

**Comment by daxian-dbw** [comment]
The error stack is in PowerShell, not PSReadLine. PowerShell somehow failed to close the AMSI session. Given that this happens in PowerShell 5.1, you will have to reported with the [Feedback Hub app](https://support.microsoft.com/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332), by choosing "Apps > PowerShell" in the category.
