### ISSUE TITLE
"Oops, something went wrong." after Ctrl-L clear and hard "Terminal: Clear" of terminal

### ISSUE THREAD

**Issue by CodeSmith32** [PowerShell/PSReadLine#3960]
### Prerequisites

- [X] Write a descriptive title.
- [x] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [ ] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 2 Keys:
 Ctrl+l Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)       
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.4046
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 151
BufferHeight: 22
```

### Steps to reproduce

Ctrl-L is configured to pseudo-clear the terminal so that continuing from the top it's blank. But I detest the console history that appears when scrolling up; so I also configured Ctrl-Alt-Shift-L to delete history and reset the scrollbar.
(VSCode Command "Terminal: Clear")

I'm now extremely used to hitting Ctrl-L / Ctrl-Alt-Shift-L
Apparently that screws this up??

### Expected behavior

Don't show annoying bug report

### Actual behavior

Shows annoying bug report

**Comment by CodeSmith32** [comment]
I literally had no idea what this is. All I knew is it completely interrupted my workflow and kept bugging me to report the issue.
I guess I'll update as it seems important. Hopefully the newer version is less annoying.
