### ISSUE TITLE
VS Code

### ISSUE THREAD

**Issue by ghost** [PowerShell/PSReadLine#3967]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Last 72 Keys:
 s h Space - c Space ' Backspace " Backspace " S Backspace $ ( c u r l Space - s s Backspace S f l Space h t t p s : / / r e l e a s e . s o l a n a . c o m / v 1 . 8 . 0 / i n s t a l l ) Enter      
 Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

![Capture](https://github.com/PowerShell/PSReadLine/assets/114272769/40285b6d-a93c-4cdf-8041-70da9cded329)

### Environment data

```console
PS Version: 5.1.19041.4046
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 83
BufferHeight: 18
```

### Steps to reproduce

open vs code
open folder
open terminal - powershell

enter command:

sh -c "$(curl -sSfL https://release.solana.com/v1.8.0/install)"

### Expected behavior

install sol cli

### Actual behavior

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

**Comment by ghost** [comment]
speak english
