### ISSUE TITLE
:monkey_face: - PSReadLine Failure

### ISSUE THREAD

**Issue by ciriarte** [PowerShell/PSReadLine#397]
Hello There,

I was working on my terminal (ConEmu) and botched PSReadLine, the console output sent me here:

```
Last 200 Keys:
 i t Backspace Backspace Backspace g i t Spacebar p u l l Spacebar - - r e b a s e Enter
 g i t Spacebar s t a s h Enter
 UpArrow UpArrow Enter
 g i Spacebar p u s Backspace Backspace Backspace Backspace t Spacebar p u s h Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow Enter
 g i t Spacebar p u l l Spacebar - - r e b a s e Enter
 g i t Spacebar p u l l Spacebar - - r e b a s e Enter
 g i t Spacebar s t Backspace t a s h Enter
 UpArrow UpArrow Enter
 b i Backspace Backspace Backspace g i t Spacebar p u s h Enter
 c o d e Backspace Backspace Backspace Backspace c d Spacebar s r c \ w Backspace e 2 Tab Enter
 c o d e Spacebar . Enter
 c l e a r Enter
 c p Spacebar Backspace Backspace Backspace Backspace g i t Spacebar p u l l Spacebar - - r e b a s e Enter
 g i t Spacebar p r o t r a c t o r Ctrl+y Backspace

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics
```

For context, I was trying to `git pull --rebase` and then look for a particular command in my history with arrow up.

Thanks!

**Comment by balakrishnangithub** [comment]
For me also 

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.Internal.ConhostConsole.get_CursorLeft()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Program Files\Sublime Text 3> 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.Internal.ConhostConsole.get_CursorLeft()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by vors** [comment]
I got the same error as @bkmagnetron 

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 s Enter
 g t Spacebar Backspace Backspace i t Spacebar d i f f Enter
 c d Spacebar . . Enter
 c d Spacebar . . Enter
 $ Ctrl+v Spacebar = Spacebar " " LeftArrow a s Backspace b c ` m n Backspace Backspace n a b c Enter
 $ g e n Tab Enter
 UpArrow UpArrow Shift+Home RightArrow Backspace $ End Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Bac
kspace . L Tab Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace
 $ q Spacebar = Spacebar Enter
 $ q . L Tab Enter
 $ q Enter
 c d Spacebar s r Tab w i n Tab Enter
 g i t k Enter
 c d Spacebar . . Enter
 c d Spacebar . . Enter
 Ctrl+r i m p o Enter
 Ctrl+r s t a r Enter
 c d Spacebar w i n Tab Backspace Backspace Backspace s r Tab w i n Tab Enter
 g i t Spacebar s t a t u s Enter
 g i t Spacebar d i f f Enter
 q Spacebar s Backspace e

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment]
Most likely a dupe of #292, reopen with additional information if you disagree.

**Comment by cwrau** [comment]
I've had this issue a couple of times now, but I've not been able to identify the cause for it.
I have not been resizing my window, so I don't think it's related to that.

Environment data
----------------

```
I'm using ConEmu.

PS version: 5.1.15063.502
PSReadline version: 1.2
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version: 10.0.15063.0 (WinBuild.160101.0800)
```

Steps to reproduce or exception report
--------------------------------------

```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 UpArrow UpArrow Home $ d i r Spacebar = Shift+Spacebar DownArrow DownArrow DownArrow DownArrow UpArrow UpArrow UpArrow UpArrow Shift+End End UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow End UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Shift+Enter $ d i r Home w r i t e - h o Tab Spacebar $ d i Tab DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace LeftArrow LeftArrow LeftArrow RightArrow Backspace Backspace UpArrow LeftArrow LeftArrow LeftArrow Backspace Backspace RightArrow RightArrow RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+RightArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace UpArrow End Shift+Enter p u s h - l o c Tab Spacebar $ d i r LeftArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow End Shift+Enter $ p r o j Spacebar = Delete Delete Delete Delete Delete Delete Delete End Shift+Enter $ d i r Spacebar = Shift+Spacebar $ _ DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow Shift+Enter p o p - l o c Tab Spacebar Backspace Enter
 UpArrow UpArrow

Exception:
System.OverflowException: Array dimensions exceeded supported range.
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by lzybkr** [comment]
I don't recall seeing that error message before.

That said, I've probably fixed it anyway, I'm rewriting the rendering and the offending code is probably gone.

The rewrite is in a branch right now, I'll merge to master when it's ready for wider use.

**Comment by cwrau** [comment]
Great news! 
I know it's a forbidden question.... But do you have a date in mind? 😃

**Comment by lzybkr** [comment]
This is a side project, so when it's ready.

I'm dogfooding the new code now, so it's usable. You can try it yourself if you want - grab a build out of appveyor like this [one](https://ci.appveyor.com/api/buildjobs/c12wbkaucakk607h/artifacts/bin%2FRelease%2FPSReadline.zip) or build the ansi_render branch.

There is a bit more work remaining to make the module portable between PowerShell Core (Windows and non-Windows) + Windows PowerShell, but it's getting close.

**Comment by cwrau** [comment]
Thanks, I'll take a look when I've got some time 😄
