### ISSUE TITLE
histfile exception on Ubuntu

### ISSUE THREAD

**Issue by zp-zpanda** [PowerShell/PSReadLine#3988]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
### Environment
PSReadLine: 2.3.4
PowerShell: 7.4.1
OS: Ubuntu 22.04.3 LTS
BufferWidth: 133
BufferHeight: 33

Last 0 Keys:



### Exception

System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_1763915222'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

N/A

### Environment data

```console
PSReadLine: 2.3.4
PowerShell: 7.4.1
OS: Ubuntu 22.04.3 LTS
BufferWidth: 133
BufferHeight: 33
```

### Steps to reproduce

I'm unsure

### Expected behavior

No exception

### Actual behavior

Exception happens

**Comment by zp-zpanda** [comment]
Turns out I accidentally set the fs to readonly :(
