### ISSUE TITLE
Last 8 Keys:  & Space C : / U s 

### ISSUE THREAD

**Issue by parthtrap03** [PowerShell/PSReadLine#3991]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Last 8 Keys:
 & Space C : / U s e

Exception:
System.ArgumentOutOfRangeException: The 
value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value) 
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object a   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, D   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

![2024-04-09 (1)](https://github.com/PowerShell/PSReadLine/assets/108417312/d2ea1539-4764-444f-9ace-48c4def84019)

### Environment data

```console
s
```

### Steps to reproduce

ss

### Expected behavior

s

### Actual behavior

s

**Comment by daxian-dbw** [comment]
The "reporting issue" URL shown in your exception report indicates that you were using a very old version of PSReadLine, likely 2.0.0-beta2 or prior. The issue has been fixed in later versions. Please upgrade to the latest v2.3.5 version and try again.

![image](https://github.com/PowerShell/PSReadLine/assets/127450/dc75db49-588f-4a72-88df-1aeac4f11882)
