### ISSUE TITLE
error in toggle panel

### ISSUE THREAD

**Issue by RahulEdumanag** [PowerShell/PSReadLine#3999]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 UpArrow UpArrow Enter
 g i Space r Backspace Backspace r Space Backspace Backspace t Space a d d Space . Enter
 g i t Space c o m m m i t Space - m Space " " LeftArrow u p d a t e Space i m a g e s Enter
 g i UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Enter
 g i t Space p u s h Space Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 g i t Space a d d Space . Enter
 g i t Space s t a t u s Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow Ctrl+a Backspace UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow UpArrow DownArrow UpArrow UpArrow UpArrow Ctrl+z Ctrl+y Ctrl+y Ctrl+y Ctrl+z Ctrl+z Ctrl+z Ctrl+z UpArrow Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+y Ctrl+y Ctrl+y UpArrow UpArrow UpArrow Ctrl+y Ctrl+y Ctrl+z

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -967.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)        
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\xampp\htdocs\Edumanag-Projects\RestaurantMenuBookingSystem>
```

### Screenshot

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 UpArrow UpArrow Enter
 g i Space r Backspace Backspace r Space Backspace Backspace t Space a d d Space . Enter
 g i t Space c o m m m i t Space - m Space " " LeftArrow u p d a t e Space i m a g e s Enter
 g i UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Enter
 g i t Space p u s h Space Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 g i t Space a d d Space . Enter
 g i t Space s t a t u s Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow Ctrl+a Backspace UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow UpArrow DownArrow UpArrow UpArrow UpArrow Ctrl+z Ctrl+y Ctrl+y Ctrl+y Ctrl+z Ctrl+z Ctrl+z Ctrl+z UpArrow Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+y Ctrl+y Ctrl+y UpArrow UpArrow UpArrow Ctrl+y Ctrl+y Ctrl+z

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -967.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)        
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\xampp\htdocs\Edumanag-Projects\RestaurantMenuBookingSystem>

### Environment data

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 UpArrow UpArrow Enter
 g i Space r Backspace Backspace r Space Backspace Backspace t Space a d d Space . Enter
 g i t Space c o m m m i t Space - m Space " " LeftArrow u p d a t e Space i m a g e s Enter
 g i UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Enter
 g i t Space p u s h Space Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 g i t Space a d d Space . Enter
 g i t Space s t a t u s Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow Ctrl+a Backspace UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow UpArrow DownArrow UpArrow UpArrow UpArrow Ctrl+z Ctrl+y Ctrl+y Ctrl+y Ctrl+z Ctrl+z Ctrl+z Ctrl+z UpArrow Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+y Ctrl+y Ctrl+y UpArrow UpArrow UpArrow Ctrl+y Ctrl+y Ctrl+z

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -967.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)        
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\xampp\htdocs\Edumanag-Projects\RestaurantMenuBookingSystem>
```

### Steps to reproduce

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 UpArrow UpArrow Enter
 g i Space r Backspace Backspace r Space Backspace Backspace t Space a d d Space . Enter
 g i t Space c o m m m i t Space - m Space " " LeftArrow u p d a t e Space i m a g e s Enter
 g i UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Enter
 g i t Space p u s h Space Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 g i t Space a d d Space . Enter
 g i t Space s t a t u s Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow Ctrl+a Backspace UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow UpArrow DownArrow UpArrow UpArrow UpArrow Ctrl+z Ctrl+y Ctrl+y Ctrl+y Ctrl+z Ctrl+z Ctrl+z Ctrl+z UpArrow Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+y Ctrl+y Ctrl+y UpArrow UpArrow UpArrow Ctrl+y Ctrl+y Ctrl+z

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -967.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)        
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\xampp\htdocs\Edumanag-Projects\RestaurantMenuBookingSystem>

### Expected behavior

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 UpArrow UpArrow Enter
 g i Space r Backspace Backspace r Space Backspace Backspace t Space a d d Space . Enter
 g i t Space c o m m m i t Space - m Space " " LeftArrow u p d a t e Space i m a g e s Enter
 g i UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Enter
 g i t Space p u s h Space Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 g i t Space a d d Space . Enter
 g i t Space s t a t u s Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow Ctrl+a Backspace UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow UpArrow DownArrow UpArrow UpArrow UpArrow Ctrl+z Ctrl+y Ctrl+y Ctrl+y Ctrl+z Ctrl+z Ctrl+z Ctrl+z UpArrow Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+y Ctrl+y Ctrl+y UpArrow UpArrow UpArrow Ctrl+y Ctrl+y Ctrl+z

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -967.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)        
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\xampp\htdocs\Edumanag-Projects\RestaurantMenuBookingSystem>

### Actual behavior

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 UpArrow UpArrow Enter
 g i Space r Backspace Backspace r Space Backspace Backspace t Space a d d Space . Enter
 g i t Space c o m m m i t Space - m Space " " LeftArrow u p d a t e Space i m a g e s Enter
 g i UpArrow Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Enter
 g i t Space p u s h Space Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 g i t Space a d d Space . Enter
 g i t Space s t a t u s Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow Ctrl+a Backspace UpArrow Enter
 UpArrow UpArrow Enter
 UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow UpArrow DownArrow UpArrow UpArrow UpArrow Ctrl+z Ctrl+y Ctrl+y Ctrl+y Ctrl+z Ctrl+z Ctrl+z Ctrl+z UpArrow Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+z Ctrl+y Ctrl+y Ctrl+y UpArrow UpArrow UpArrow Ctrl+y Ctrl+y Ctrl+z

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -967.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)        
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\xampp\htdocs\Edumanag-Projects\RestaurantMenuBookingSystem>

**Comment by RahulEdumanag** [comment]
error
