### ISSUE TITLE
UpArrow

### ISSUE THREAD

**Issue by pungpond78** [PowerShell/PSReadLine#4008]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

![image](https://github.com/PowerShell/PSReadLine/assets/88936863/1f5c1e27-dc2d-4f8f-851f-09275c65e2b4)

### Environment data

```console
กดดกเก
```

### Steps to reproduce

![image](https://github.com/PowerShell/PSReadLine/assets/88936863/ee085909-e117-4085-81a1-7ab37abeebef)

### Expected behavior

 
![image](https://github.com/PowerShell/PSReadLine/assets/88936863/8d8db748-06ce-4122-91ef-2a6db22abece)

### Actual behavior

![image](https://github.com/PowerShell/PSReadLine/assets/88936863/332f8bfb-f8dc-4927-9011-29ed8bd443a7)

**Comment by daxian-dbw** [comment]
This issue was already fixed (see #1306). Please upgrade to the [2.3.5 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.5) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
