### ISSUE TITLE
Exception:  System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by jatinnayak47** [PowerShell/PSReadLine#4028]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
PS C:\Users\KIIT\Documents\VS CODE\GitDemo\local_repo> git commit -m 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 115 Keys:
 Ctrl+t Backspace Backspace c d Space l o c a l _ r e 
p o Enter
 g t i Space Backspace Backspace Backspace i t Space s t a t u s Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace g t i Space Backspace Backspace Backspace i t Space s t a t u s Enter
 g t i Space Backspace Backspace Backspace i t Space s Backspace a d d Space i n d e x . h t m l Enter      
 g t Backspace i t Space s t a t u s Enter
 g i t Space c o m m i t Space - m Space '

Exception:
System.ArgumentOutOfRangeException: The value must be 
greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)       
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 
   dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics 
   engineIntrinsics)
```

### Screenshot

![bug_details](https://github.com/PowerShell/PSReadLine/assets/101475040/97c98775-fbd4-4574-9bc6-3b619b4e061a)

### Environment data

```console
PS Version: 5.1.19041.4291
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 3000
```

### Steps to reproduce

A description of how to trigger issue :-
I encounted the issue while commiting , using this cmd :-  git commit -m ""

### Expected behavior

After typing -m when i press the double quotation , it should allow me type the comment about new changes between double quotation.

### Actual behavior

After typing -m  while commiting ,when i press the double quotation , it should allow me type the comment about new changes between double quotation, but when i press the button the command is automatically completed, and was not allowing me to comment about new changes.

**Comment by jatinnayak47** [comment]
Resolve this issue please.
