### ISSUE TITLE
Windows 10 Start menu not open

### ISSUE THREAD

**Issue by patelnishant1** [PowerShell/PSReadLine#403]
Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 200 Keys:
 l o p m e n t M o d e Spacebar - R e g i s t e r Spacebar " $ ( $ _ . I n s t a l l L o c a t i o n ) \ A p p X M a n i f e s t . x m l " } Enter
 Ctrl+v Enter
 Backspace Backspace Backspace Backspace Ctrl+v G e t - A p p X P a c k a g e Spacebar - A l l U s e r s Spacebar | Spacebar F o r e a c h Spacebar { A d d - A p p x P a c k a g e Spacebar - D i s a b l e D e v e l o p m e n t M o d e Spacebar - R e g i s t e r Spacebar " $ ( $ _ . I n s t a l l L o c a t i o n ) \ A p p X M a n i f e s t . x m l " } Enter

Exception:
System.UnauthorizedAccessException: Access to the path 'C:\Users\Dipu\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadline' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Microsoft.PowerShell.PSConsoleReadLine.WriteHistoryRange(Int32 start, Int32 end, Func`2 fileOpener)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean readingHistoryFile, Boolean fromDifferentSession)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()

**Comment by lzybkr** [comment]
I think this is fixed in v1.2 with this change: 22694843e9852bf6b31942ef009b6b2eeaa3c8c1

You can check your version: `(gmo psreadline).Version.ToString()`

If you are running 1.2, feel free to reactivate.
