### ISSUE TITLE
System.ArgumentOutOfRangeException thrown

### ISSUE THREAD

**Issue by webframp** [PowerShell/PSReadLine#404]
I was helpfully told to report these details here. Only sanitized the domain name where needed.

> Oops, something went wrong.  Please report this bug with the details below.
> Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

<details>

```
-----------------------------------------------------------------------
Last 200 Keys:
 y - t e s t ' Enter
 e n d Spacebar Enter
 Ctrl+c Ctrl+c Ctrl+c g i t Spacebar c l o n e Spacebar h t t p s ; / / g i t h u b . c o m / e d e l i g h t / c h e f - s o l o - s e a
r c h . g i t Enter
 r m Spacebar - f r Spacebar c h e f - s o l o Tab o Backspace - Tab Enter
 c d Spacebar Backspace Backspace Backspace Backspace Backspace . / d o w n l Tab c h e f d Tab Enter
 Ctrl+j n Backspace Backspace LeftWindows p u n g Spacebar Ctrl+a Ctrl+k u i Backspace Backspace Backspace p i n g Spacebar u s w e b 1 2
5 Backspace 6 Enter
 Ctrl+r s s h Spacebar u s Ctrl+c s s h Spacebar u s e Backspace s o m e s e r v e r . d o m a i n . o r g Ctrl+a Ctrl+e Enter
 Escape Ctrl+p Ctrl+p Ctrl+a Ctrl+k Shift+Tab Ctrl+LeftWindows Ctrl+l

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -12.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

</details>

**Comment by lzybkr** [comment]
The stack trace is different, but #503 is very likely the same thing. At any rate, the code has been rewritten significantly and likely is fixed.
