### ISSUE TITLE
"The numeric constant 0x10000000000000000 is not valid" when calling `ValidateAndAcceptLine`

### ISSUE THREAD

**Issue by MatejKafka** [PowerShell/PSReadLine#4064]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
The numeric constant 0x10000000000000000 is not valid.
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.yaml
Thank you!

### Environment
PSReadLine: 2.3.5+2cc85806c561a9395751a96a818e8ff1592d19f7
PowerShell: 7.5.0-preview.2
OS: Microsoft Windows 10.0.19045
BufferWidth: 208
BufferHeight: 48

Last 2 Keys:

 Ctrl+v Enter

### Exception

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at Microsoft.PowerShell.PSConsoleReadLine.ConvertOffsetToPoint(Int32 offset)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.ValidateAndAcceptLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

N/A

### Environment data

```console
PS Version: 7.5.0-preview.2
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.3.5
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 208
BufferHeight: 48
```

### Steps to reproduce

1) Run `pwsh -noprofile`.
2) Invoke `Set-PSReadLineKeyHandler -Key Enter -Function ValidateAndAcceptLine`.
3) Type `$n = 0x10000000000000000` and press Enter (triggering `ValidateAndAcceptLine`).

### Expected behavior

Either the command is accepted and it throws a runtime error, or `PSReadline` refuses to accept the input and adds a new line.

### Actual behavior

The above exception is raised.

**Comment by daxian-dbw** [comment]
This is a parsing error in PowerShell. PR submitted to fix the issue in PowerShell: https://github.com/PowerShell/PowerShell/pull/24024
