### ISSUE TITLE
Visual Code reporting this error after most recent update

### ISSUE THREAD

**Issue by tonyg57** [PowerShell/PSReadLine#4093]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 11 Keys:
 & Space C : / U s e r s /

Exception:
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

N/A

### Environment data

```console
PS Version: 5.1.19041.4648
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 3000
```

### Steps to reproduce

Third error I've noticed.  Seems to occur the first time I launch Visual Code

### Expected behavior

No exception.

### Actual behavior

The exception above occurs.  Closing and re-opening Visual Code, the exception does not re-appear.

**Comment by tonyg57** [comment]
Not sure why PowerShell is coming up in Visual Code.  I don't do anything in PowerShell, just Python. Upgraded to V2.3.5 of PSReadLine as suggested but was warned it was from an untrusted repository.
