### ISSUE TITLE
show error while run the code 

### ISSUE THREAD

**Issue by Prajjwal18-web** [PowerShell/PSReadLine#4101]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 137 Keys:
 c d Space " c : \ U s e r s \ a s u s \ O n e D r i v e \ D o c u m e n t s \ c Space f i l e s \ " Space ; Space i f Space ( $ ? ) Space { Space g c c Space r e m o v e _ d u p l i c a t e . c Space - o Space r e m o v e _ d u p l i c a t e Space } Space ; Space i f Space ( $ ? ) Space { Space . \ r e m o v e _ d u p l i c a t e Space } Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

PS C:\Users\asus\OneDrive\Documents\c files>
c
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 137 Keys:
 c d Space " c : \ U s e r s \ a s u s \ O n e D r i v e \ D o c u m e n t s \ c Space f i l e s \ " Space ; Space i f Space ( $ ? ) Space { Space g c c Space r e m o v e _ d u p l i c a t e . c Space - o Space r e m o v e _ d u p l i c a t e Space } Space ; Space i f Space ( $ ? ) Space { Space . \ r e m o v e _ d u p l i c a t e Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\asus\OneDrive\Documents\c files> cd "c:\Users\asus\OneDrive\Documents\c files\" ; if ($?) { gcc remove_duplicate.c -o remove_duplicate } ; if ($?) { .\remove_duplicate }
enter the string
e
w
e
entered string is: e
w
e♣
PS C:\Users\asus\OneDrive\Documents\c files>

### Environment data

```console
PS Version: 5.1.19041.4648
PS HostName: ConsoleHost  
PSReadLine Version:       
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 121
BufferHeight: 36
```

### Steps to reproduce

#include<stdio.h>
#include<string.h>
#include<stdlib.h>
int main(){
    char st[5],st1[5],st2[5];
    int i,j;
    printf("enter the string\n");
    for(i=0;i<5;i++)
    {
        scanf("%c",&st[i]);
    }
    printf("entered string is: ");
    for(j=0;j<5;j++)
    {
        printf("%c",st[j]);
    }
    return 0;
}

### Expected behavior

input and output will be 5

### Actual behavior

input and output are only 3

**Comment by Prajjwal18-web** [comment]
please fix this error

**Comment by Prajjwal18-web** [comment]
This bug is occur again

**Comment by Prajjwal18-web** [comment]
please tell me how to fix it
