### ISSUE TITLE
Issue While running code

### ISSUE THREAD

**Issue by Beshlr** [PowerShell/PSReadLine#4104]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

![image](https://github.com/user-attachments/assets/499c6229-b695-438d-9b9b-b7f8db8624eb)

### Environment data

```console
PS Version: 5.1.19041.4648                                                                                              PS HostName: ConsoleHost                                                                                                PSReadLine Version: 2.0.0-beta2                                                                                         PSReadLine EditMode: Windows                                                                                            OS: 10.0.19041.1 (WinBuild.160101.0800)                                                                                 BufferWidth: 120                                                                                                        BufferHeight: 3000
```

### Steps to reproduce

i don't know

### Expected behavior

i don't know

### Actual behavior

i don't know

**Comment by daxian-dbw** [comment]
The GitHub URL shown in your screenshot indicates you are using a very old version of PSReadLine (2.0.0-beta2 or prior). Please upgrade to the v2.3.6 of PSReadLine module and give it another try. The issue should be fixed in newer versions.
