### ISSUE TITLE
System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_652624388'

### ISSUE THREAD

**Issue by sjp363** [PowerShell/PSReadLine#4109]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
System.IO.IOException: The system cannot open the device or file specified. : 'PSReadLineHistoryFile_652624388'
   at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken, Nullable`1 lastRunStatus)
```

### Screenshot

![image](https://github.com/user-attachments/assets/641d3fc8-79e2-47ff-8d94-eb2c51f8e35e)

### Environment data

```console
PSReadLine: 2.3.4
PowerShell: 7.4.1
OS: Ubuntu 22.04.4 LTS
BufferWidth: 120
BufferHeight: 30

Last 0 Keys:
```

### Steps to reproduce

started pwsh from command prompt, ubuntu on hyper-v

### Expected behavior

start powershell

### Actual behavior

crashed immediately after pwsh command

**Comment by sjp363** [comment]
never mind linux inodes 100% used.  freed up disk space. lol sorry.
