### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by SiyaNagar** [PowerShell/PSReadLine#4115]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
c
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 104 Keys:
 c d Space " c : \ U s e r s \ v i s h a l Space n a g a r \ D e s k t o p \ c Space l a n g u a g e \ " Space ; Space i 
f Space ( $ ? ) Space { Space g c c Space h e l l o . c Space - o Space h e l l o Space } Space ; Space i f Space ( $ ? ) Space { Space . \ h e l l o Space } Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\vishal nagar\Desktop\c language> cd "c:\Users\vishal nagar\Desktop\c language\" ; if ($?) { gcc hello.c -o hello } ; if ($?) { .\hello }
Hello world
PS C:\Users\vishal nagar\Desktop\c language> cd "c:\Users\vishal nagar\Desktop\c language\" ; if ($?) { gcc checkPrimeOrNot.c -o checkPrimeOrNot } ; if ($?) { .\checkPrimeOrNot }
```

### Screenshot

c
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 104 Keys:
 c d Space " c : \ U s e r s \ v i s h a l Space n a g a r \ D e s k t o p \ c Space l a n g u a g e \ " Space ; Space i 
f Space ( $ ? ) Space { Space g c c Space h e l l o . c Space - o Space h e l l o Space } Space ; Space i f Space ( $ ? ) Space { Space . \ h e l l o Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\vishal nagar\Desktop\c language> cd "c:\Users\vishal nagar\Desktop\c language\" ; if ($?) { gcc hello.c -o hello } ; if ($?) { .\hello }
Hello world
PS C:\Users\vishal nagar\Desktop\c language> cd "c:\Users\vishal nagar\Desktop\c language\" ; if ($?) { gcc checkPrimeOrNot.c -o checkPrimeOrNot } ; if ($?) { .\checkPrimeOrNot }

### Environment data

```console
c
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 104 Keys:
 c d Space " c : \ U s e r s \ v i s h a l Space n a g a r \ D e s k t o p \ c Space l a n g u a g e \ " Space ; Space i 
f Space ( $ ? ) Space { Space g c c Space h e l l o . c Space - o Space h e l l o Space } Space ; Space i f Space ( $ ? ) Space { Space . \ h e l l o Space } Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\vishal nagar\Desktop\c language> cd "c:\Users\vishal nagar\Desktop\c language\" ; if ($?) { gcc hello.c -o hello } ; if ($?) { .\hello }
Hello world
PS C:\Users\vishal nagar\Desktop\c language> cd "c:\Users\vishal nagar\Desktop\c language\" ; if ($?) { gcc checkPrimeOrNot.c -o checkPrimeOrNot } ; if ($?) { .\checkPrimeOrNot }
```

### Steps to reproduce

c
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 104 Keys:
 c d Space " c : \ U s e r s \ v i s h a l Space n a g a r \ D e s k t o p \ c Space l a n g u a g e \ " Space ; Space i 
f Space ( $ ? ) Space { Space g c c Space h e l l o . c Space - o Space h e l l o Space } Space ; Space i f Space ( $ ? ) Space { Space . \ h e l l o Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\vishal nagar\Desktop\c language> cd "c:\Users\vishal nagar\Desktop\c language\" ; if ($?) { gcc hello.c -o hello } ; if ($?) { .\hello }
Hello world
PS C:\Users\vishal nagar\Desktop\c language> cd "c:\Users\vishal nagar\Desktop\c language\" ; if ($?) { gcc checkPrimeOrNot.c -o checkPrimeOrNot } ; if ($?) { .\checkPrimeOrNot }

### Expected behavior

c
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 104 Keys:
 c d Space " c : \ U s e r s \ v i s h a l Space n a g a r \ D e s k t o p \ c Space l a n g u a g e \ " Space ; Space i 
f Space ( $ ? ) Space { Space g c c Space h e l l o . c Space - o Space h e l l o Space } Space ; Space i f Space ( $ ? ) Space { Space . \ h e l l o Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\vishal nagar\Desktop\c language> cd "c:\Users\vishal nagar\Desktop\c language\" ; if ($?) { gcc hello.c -o hello } ; if ($?) { .\hello }
Hello world
PS C:\Users\vishal nagar\Desktop\c language> cd "c:\Users\vishal nagar\Desktop\c language\" ; if ($?) { gcc checkPrimeOrNot.c -o checkPrimeOrNot } ; if ($?) { .\checkPrimeOrNot }

### Actual behavior

c
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 104 Keys:
 c d Space " c : \ U s e r s \ v i s h a l Space n a g a r \ D e s k t o p \ c Space l a n g u a g e \ " Space ; Space i 
f Space ( $ ? ) Space { Space g c c Space h e l l o . c Space - o Space h e l l o Space } Space ; Space i f Space ( $ ? ) Space { Space . \ h e l l o Space } Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\vishal nagar\Desktop\c language> cd "c:\Users\vishal nagar\Desktop\c language\" ; if ($?) { gcc hello.c -o hello } ; if ($?) { .\hello }
Hello world
PS C:\Users\vishal nagar\Desktop\c language> cd "c:\Users\vishal nagar\Desktop\c language\" ; if ($?) { gcc checkPrimeOrNot.c -o checkPrimeOrNot } ; if ($?) { .\checkPrimeOrNot }

**Comment by SiyaNagar** [comment]
c
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 104 Keys:
 c d Space " c : \ U s e r s \ v i s h a l Space n a g a r \ D e s k t o p \ c Space l a n g u a g e \ " Space ; Space i 
f Space ( $ ? ) Space { Space g c c Space h e l l o . c Space - o Space h e l l o Space } Space ; Space i f Space ( $ ? ) Space { Space . \ h e l l o Space } Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\vishal nagar\Desktop\c language> cd "c:\Users\vishal nagar\Desktop\c language\" ; if ($?) { gcc hello.c -o hello } ; if ($?) { .\hello }
Hello world
PS C:\Users\vishal nagar\Desktop\c language> cd "c:\Users\vishal nagar\Desktop\c language\" ; if ($?) { gcc checkPrimeOrNot.c -o checkPrimeOrNot } ; if ($?) { .\checkPrimeOrNot }
