### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by DipayanSantra** [PowerShell/PSReadLine#4125]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Last 99 Keys:
 c d Space " c : \ U s e r s \ u s e r \ D e s k t o p \ c h a p 6 . c \ " Space ; Space i f Space ( $ ? ) Space { Space g c c Space 0 6 _ s w a p . c Space - o Space 0 6 _ s w a p Space } Space ; Space i f Space ( $ ? ) Space { Space . \ 0 6 _ s w a p Space } Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

![Screenshot (118)](https://github.com/user-attachments/assets/06b87a21-87e9-40f0-a2e7-c4bcb3708ff7)

### Environment data

```console
PSVersion                      5.1.19041.4780
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.4780
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Steps to reproduce

just solve it

### Expected behavior

nothing

### Actual behavior

dont know

**Comment by DipayanSantra** [comment]
please fix it
