### ISSUE TITLE
cpp error in terminal

### ISSUE THREAD

**Issue by Sarfraz-1112** [PowerShell/PSReadLine#4136]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 93 Keys:
 c d Space " c : \ U s e r s \ I n t e l \ D o w n l o a d s \ C + + Space P r o g r a m m i n g \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space n e w . c p p Space - o Space n e w Space } Space ; Space i f Space ( $ ? ) Space { Space .
```

### Screenshot

![error](https://github.com/user-attachments/assets/6674161d-373f-4971-8d15-6e6b59d7897a)

### Environment data

```console
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 93 Keys:
 c d Space " c : \ U s e r s \ I n t e l \ D o w n l o a d s \ C + + Space P r o g r a m m i n g \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space n e w . c p p Space - o Space n e w Space } Space ; Space i f Space ( $ ? ) Space { Space .
```

### Steps to reproduce

cd 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 93 Keys:
 c d Space " c : \ U s e r s \ I n t e l \ D o w n l o a d s \ C + + Space P r o g r a m m i n g \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space n e w . c p p Space - o Space n e w Space } Space ; Space i f Space ( $ ? ) Space { Space .

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's 
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics) 

### Expected behavior

cd 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 93 Keys:
 c d Space " c : \ U s e r s \ I n t e l \ D o w n l o a d s \ C + + Space P r o g r a m m i n g \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space n e w . c p p Space - o Space n e w Space } Space ; Space i f Space ( $ ? ) Space { Space .

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's 
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics) 

### Actual behavior

cd 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 93 Keys:
 c d Space " c : \ U s e r s \ I n t e l \ D o w n l o a d s \ C + + Space P r o g r a m m i n g \ " Space ; Space i f Space ( $ ? ) Space { Space g + + Space n e w . c p p Space - o Space n e w Space } Space ; Space i f Space ( $ ? ) Space { Space .

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's 
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by Sarfraz-1112** [comment]
Please Solve this error
