### ISSUE TITLE
Last 3 Keys:  & Space C

### ISSUE THREAD

**Issue by tanayhsh** [PowerShell/PSReadLine#4158]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object 
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

![image](https://github.com/user-attachments/assets/48055bde-1fbc-4447-b09b-41fcb811ce7c)

### Environment data

```console
PS Version: 5.1.19041.4780
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 140
BufferHeight: 10
```

### Steps to reproduce

print("Welcome to my quiz!")

playing = input("Do you want to play? ")

if playing != "yes":
    quit()

### Expected behavior

No exception

### Actual behavior

The above happens

**Comment by tanayhsh** [comment]
[image: image.png]

PSReadLine Version 2.3.5 is not loading.
