### ISSUE TITLE
Visual Studio code bug

### ISSUE THREAD

**Issue by DerieJulez** [PowerShell/PSReadLine#4231]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

![Screenshot (2)](https://github.com/user-attachments/assets/da5ff473-cf99-4a63-ab6b-15f32460c433)

### Environment data

```console
PS Version: 5.1.19041.1
PS HostName: ConsoleHost
PSReadLine Version: 2.0.0-beta2
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 163
BufferHeight: 20
```

### Steps to reproduce

Just when i run the code on the console or sometimes if I rerun the code

### Expected behavior

Just run the code on the console without the error

### Actual behavior

Before I run my code on the console

**Comment by DerieJulez** [comment]
Please help me fix this

**Comment by daxian-dbw** [comment]
You are using a very old version of PSReadLine module (2.0.0-beta2). The issue has been fixed in newer versions, so please upgrade to the latest version v2.3.6 (`Install-Module PSReadLine -RequiredVersion 2.3.6 -Repository PSGallery`) and you will be good.
