### ISSUE TITLE
Crazy Bug after running code

### ISSUE THREAD

**Issue by Bright-jasi** [PowerShell/PSReadLine#4240]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
-----------------------------------------------------------------------
Last 200 Keys:
 m e - E v o l u t i o n / n a m e _ e v o l u t i o n . p y " Enter
 Enter
 & Space " C : / U s e r s / B r i g h t Space J a s i / a n a c o n d a 3 / p y t h o n . e x e " Space " c : / U s e r s / B r i g h t Space J a s i / N a m e s / N a m e - E v o l u t i o n / n a m e _ e v o l u t i o n . p y " Enter
 c l s Enter
 g i t Space a d d . Backspace Space . Enter
 c l s Enter
 c l s Enter
 c l e a r Enter
 c l s Enter
 c l e a r Enter
 Enter
 Backspace c l e a r Enter
 c l e a r Enter
 c l s Enter
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

### Screenshot

No images

### Environment data

```console
windows
```

### Steps to reproduce

I dont know

### Expected behavior

no

### Actual behavior

no idea

**Comment by daxian-dbw** [comment]
@Bright-jasi, you may be using a very old version of PSReadLine (2.0.0-beta2 or prior), and it's likely that the issue was fixed in a newer version.
Please upgrade to the [2.3.5 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.5) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
