### ISSUE TITLE
exception issue

### ISSUE THREAD

**Issue by architgore050** [PowerShell/PSReadLine#4280]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
Oops, something went wrong. Please report this bug with the details below.
Report on GitHub: https://github.com/Izybkr/PSReadLine/issues/new
Last 4 Keys:
& Space C:
Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
at System.Console.SetCursorPosition (Int32 left, Int32 top)
at Microsoft.PowerShell.Internal.Virtual Terminal.set_CursorLeft(Int32 value)
at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender (RenderData renderData, String defaultcolor)
at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
at Microsoft.PowerShell.PSConsoleReadLine. SelfInsert (Nullable 1 key, Object arg)
at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKey Info key, Dictionary 2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

N/A

### Environment data

```console
Im a new programmer. I don't know what this data is that it is asking me for here
```

### Steps to reproduce

I don't know what the issue is, it just happens every time I run any code of any sort

### Expected behavior

everything works as normal and the code gives the output

### Actual behavior

the code still gives the output and everything is running completely fine, or maybe I just haven't run into any issue yet. But otherwise the issue still shows up, but otherwise I haven't noticed it affecting anything in the functioning.

**Comment by daxian-dbw** [comment]
@architgore050, you were using a pretty old version of PSReadLine (2.0.0-beta2 or prior), and it's likely that the issue was fixed in a newer version.
Please upgrade to the [2.3.6 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.6) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
