### ISSUE TITLE
Please  help to fix this error problem.

### ISSUE THREAD

**Issue by airinkhanam01** [PowerShell/PSReadLine#4309]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
---------------------------------
Last 3 Keys:
 & Space C

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.  
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### Screenshot

![Capture](https://github.com/user-attachments/assets/75ebf1d2-be5e-4241-87f0-a66c3bc1beed)
![Capture](https://github.com/user-attachments/assets/85f7bb4d-d525-418f-8475-e33523acf7d6)

### Environment data

```console
..
```

### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

.

**Comment by daxian-dbw** [comment]
@airinkhanam01 You are using a very old version of PSReadLine (v2.0.0-beta2 or prior). This issue was already fixed (see #1306). Please upgrade to the [2.3.5 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.3.5) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
