### ISSUE TITLE
powershell -executionpolicy bypass

### ISSUE THREAD

**Issue by geechy** [PowerShell/PSReadLine#440]
PS C:\WINDOWS\system32> powershell -executionpolicy bypass
Windows PowerShell 
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

Oops, something went wrong.  Please report this bug with the details below.
## Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new

Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by marcusm** [comment]
I am also receiving this error. Anything I can do to help diagnose?

**Comment by lzybkr** [comment]
Most likely a dupe of #158, reopen with additional information if you disagree.
