### ISSUE TITLE
"ESC k j w" in vi mode throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by ThatGeoGuy** [PowerShell/PSReadLine#456]
I pressed some random keys and got the following error message. 

I am using vi-mode, but I don't think I've done any specific customization to PSReadline to prompt any weird behaviour. I can provide more information if needed. If I understand correctly, this may have something to do with issue #221. 

```
-----------------------------------------------------------------------
Last 4 Keys:
 Ctrl+[ k j w

Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Text.StringBuilder.get_Chars(Int32 index)
   at Microsoft.PowerShell.PSConsoleReadLine.ConvertOffsetToCoordinates(Int32 offset)
   at Microsoft.PowerShell.PSConsoleReadLine.ViNextWord(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by srdubya** [comment]
A pull request fixing this has been submitted.
