### ISSUE TITLE
System.ArgumentException: Destination array was not long enough. "n p m Backspace Backspace Backspace"

### ISSUE THREAD

**Issue by aaronbloom** [PowerShell/PSReadLine#461]
Typed 'npm', then rapidly pressed backspace many times, using Powershell with posh-git, Windows 10.

Powershell version:

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10240  17146
```

Problem:

```
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

C:\example [master ≡ +1 ~2 -0 !]> n
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 6 Keys:
 n p m Backspace Backspace Backspace

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
C:\example [master ≡ +1 ~2 -0 !]
```

**Comment by lzybkr** [comment]
I'll have an official prerelease build out next week if you want to verify this is fixed, otherwise you can grab a build out of appveyor [here](https://ci.appveyor.com/project/lzybkr/psreadline).
