### ISSUE TITLE
Powershell fails to start after installation.  

### ISSUE THREAD

**Issue by NilsJS** [PowerShell/PSReadLine#488]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.Internal.ConhostConsole.get_CursorLeft()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by NilsJS** [comment]
GNU Emacs 24.2.1 (i386-mingw-nt6.2.9200) of 2012-08-29 on MARVIN

**Comment by NilsJS** [comment]
This was probably a conflict with PSReadline 

After commenting out the following lines from my Proershell profile it works fine:

import-module PSReadline
Set-PSReadlineOption -EditMode Emacs

**Comment by lzybkr** [comment]
Yeah, PSReadline probably doesn't work in emacs - PSReadline doesn't support redirected input.
