### ISSUE TITLE
I drag the git shell and I see the terminal completely blank(Windows 10)

### ISSUE THREAD

**Issue by reach2jeyan** [PowerShell/PSReadLine#499]
PFB the logs

```
Last 200 Keys:
 c k Spacebar f e a t u r e " Enter
 g i t Spacebar p u s h Enter
 g i t Spacebar a d d Spacebar f e a t u r e s / s t e p _ d e f i n i t i o n s / t e s t _ s t e p s . r b Enter
 g i t Spacebar c m m Backspace Backspace o m m i t Spacebar 0 Backspace - m Spacebar " s Backspace a d e d Backspace Backspace d e d Spacebar c o d e , Spacebar t Backspace Backspace Backspace Spacebar f o r Spacebar c l i c k Spacebar a n d Spacebar d e f Backspace Backspace Backspace n e w Backspace Backspace Backspace d e s i r e d Spacebar c a p i Backspace a b i l i t i e s Spacebar f r Spacebar c h Backspace Backspace Backspace Backspace r Spacebar Backspace Backspace o r Spacebar c h r m e Backspace Backspace o m e " Enter
 g i t Spacebar p u s h Enter
 LeftArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was 85.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.ConhostConsole.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.PlaceCursor(Int32 x, Int32& y)
   at Microsoft.PowerShell.PSConsoleReadLine.SetCursorPosition(Int32 cursor)
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

**Comment by lzybkr** [comment]
The stack trace is different, but #503 is very likely the same thing. At any rate, the code has been rewritten significantly and likely is fixed.
