### ISSUE TITLE
ArgumentNullException setting the clipboard

### ISSUE THREAD

**Issue by BanterBoy** [PowerShell/PSReadLine#509]
```
PS C:\>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow Dow
nArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow Dow
nArrow DownArrow DownArrow RightArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow DownArrow Do
wnArrow DownArrow DownArrow DownArrow Enter
 UpArrow DownArrow DownArrow DownArrow DownArrow UpArrow UpArrow UpArrow DownArrow Enter
 UpArrow UpArrow UpArrow UpArrow Spacebar - d Tab Tab Tab Backspace Backspace i n Tab Spacebar d Tab Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow L
eftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow L
eftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace 9 0 Enter
 c l s Enter
 Ctrl+a Ctrl+x

Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at Microsoft.PowerShell.PSConsoleReadLine.Cut(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment]
The clipboard code has been rewritten so we'll call this fixed - at least it doesn't repro with the latest bits.
