### ISSUE TITLE
Tab Cycling -- Froze up, got this error.

### ISSUE THREAD

**Issue by BinaryInk** [PowerShell/PSReadLine#531]
Environment data
----------------

PS version: 5.1.15063.138
PSReadline version: 1.2
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version: 10.0.15063.0 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 38 Keys:
 I m p o r t - M o d u l e Spacebar Tab Tab Tab Tab Tab Tab Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+LeftArrow Backspace Backs
pace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Ctrl+Backspace
Ctrl+Backspace Ctrl+Delete

Exception:
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collectio
n.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Microsoft.PowerShell.PSConsoleReadLine.Kill(Int32 start, Int32 length, Boolean prepend)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by lzybkr** [comment]
Closing as no repro - that stack isn't possible, `PSConsoleReadLine.Kill` can't be bound directly to a key, and anything called from `ProcessOneKey` must be bindable.

If you have a solid repro, feel free to reopen.
