### ISSUE TITLE
Crash in tab completion for hashtables in 6.0Beta

### ISSUE THREAD

**Issue by jpsnover** [PowerShell/PSReadLine#534]
```
PS D:\PowerShell\6.0.0-beta1> gps |select -Property @{Name="test";
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 g p s Spacebar ? Shift+Backspace & Enter
 d i r Enter
 g p s Spacebar | s e l e c t Spacebar - p Tab Spacebar Tab Tab Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Tab Tab Tab Tab Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Tab Tab Tab Tab Tab Tab Tab Tab Tab Enter
 UpArrow , n Tab , @ { Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab n a m e = Tab Tab Tab Tab Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace @ { Tab = " t e s t Backspace Backspace Backspace Backspace Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Tab Backspace Backspace Backspace Backspace = Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspace = " t e s t " ; e Backspace Tab

Exception:
System.ArgumentException: 'start' cannot be less than zero or greater than the length of the buffer
Parameter name: start
   at Microsoft.PowerShell.PSConsoleReadLine.Replace(Int32 start, Int32 length, String replacement, Action`2 instigator, Object instigatorArg)
   at Microsoft.PowerShell.PSConsoleReadLine.DoReplacementForCompletion(CompletionResult completionResult, CommandCompletion completions)
   at Microsoft.PowerShell.PSConsoleReadLine.Complete(Boolean forward)
   at Microsoft.PowerShell.PSConsoleReadLine.TabCompleteNext(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------



PS D:\PowerShell\6.0.0-beta1> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
BuildVersion                   3.0.0.0
CLRVersion
GitCommitId                    v6.0.0-beta.1
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by lzybkr** [comment]
Simple repro:
```
gps | format-table -Property @{Name="aa";<TAB>
```

This will repro in Windows PowerShell as well, and with 2.0.
