### ISSUE TITLE
ArgumentOutOfRangeException after pasting 5000 lines

### ISSUE THREAD

**Issue by the-ress** [PowerShell/PSReadLine#535]
Environment data
----------------
PS version: 5.1.15063.168
PSReadline version: 1.2
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version: 10.0.15063.0 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------
1. Paste ~5000 lines
2. Press Enter
3. Press Up
4. Press Down

Result:
--------------------------------------
```
Last 4 Keys:
 Ctrl+v Enter
 UpArrow DownArrow

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -2000.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.NextHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

(I've looked through a few similar issues reported here, but I found none with this stack trace.)

**Comment by lzybkr** [comment]
The stack trace is different, but #503 is very likely the same thing. At any rate, the code has been rewritten significantly and likely is fixed.
