### ISSUE TITLE
ExternalException (0x800401D0): Requested Clipboard operation did not succeed

### ISSUE THREAD

**Issue by Celmor** [PowerShell/PSReadLine#546]
### Environment data
```powershell
PS version: 5.1.15063.483
PSReadline version: 1.2
os: 10.0.15063.0 (WinBuild.160101.0800)
PS file version: 10.0.15063.0 (WinBuild.160101.0800)
```
-----------------------------------------------------------------------
### Exception
```
Last 65 Keys:
 Ctrl+r - e Ctrl+LeftArrow Ctrl+LeftArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+RightArrow Ctrl+LeftArrow LeftArrow RightArrow LeftArrow RightArrow LeftArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Shift+RightArrow Ctrl+c

Exception:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at Microsoft.PowerShell.PSConsoleReadLine.Copy(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```
-----------------------------------------------------------------------

### Description
Was selecting and copying an env-variable via keyboard to paste it into a new powershell window to check its value (Exception appeared as I was middle-mouse clicking the powershell window to open a new instance iirc).

[Screenshot](https://puu.sh/wLMeD/c6e74adde0.png) (was unable to attach it directly to the Issue, got "Something went really wrong, and we can’t process that file.")

**Comment by lzybkr** [comment]
Probably the same as #265.
