### ISSUE TITLE
lzybkr/PSReadLine/issues/new

### ISSUE THREAD

**Issue by Zhanra** [PowerShell/PSReadLine#553]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 123 Keys:
 c d Escape k : Enter
 c d Spacebar e Tab Tab Enter
 l s Spacebar * F8 F8 F8 F8 F8 . d o c ? , Backspace Spacebar * . x l s ? Enter
 UpArrow Spacebar - r Tab Spacebar ~ Backspace ~ Backspace | Spacebar s e l e c t Backspace Backspace Backspace Backspac
e Backspace o r t - o Tab Spacebar l a s t w Tab Spacebar - d e Tab Spacebar \ Backspace | Spacebar s e l e c t - o Tab
Spacebar - f Tab Spacebar 1 0 Enter
 l s Enter
 l s Spacebar m Tab Enter
 UpArrow UpArrow UpArrow Home Ctrl+RightArrow Ctrl+RightArrow LeftArrow LeftArrow LeftArrow , Enter
 UpArrow Shift+Home Ctrl+c

Exception:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at Microsoft.PowerShell.PSConsoleReadLine.Copy(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignor
eIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------Steps to reproduce or exception report
![powershell copy error](https://user-images.githubusercontent.com/30932190/29697550-5fa7974e-8982-11e7-9952-838e71a321bf.png)

--------------------------------------

**Comment by lzybkr** [comment]
Probably the same as #265.
