### ISSUE TITLE
Exception after Escape in vi mode

### ISSUE THREAD

**Issue by lzybkr** [PowerShell/PSReadLine#571]
In trying to reproduce #539, I hit the following exception.

Environment data
----------------
```
PS version: 5.1.16299.19
PSReadline version: 2.0
os: 10.0.16299.15 (WinBuild.160101.0800)
PS file version: 10.0.16299.15 (WinBuild.160101.0800)
```

Steps to reproduce or exception report
--------------------------------------
```
#28 PS> powershell -nop
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\PSReadLine\PSReadLine> Set-PSReadlineOption -EditMode vi
PS C:\PSReadLine\PSReadLine> Set-PSReadlineKeyHandler -Chord 'j,k' -Function NextLine -ViMode Command
PS C:\PSReadLine\PSReadLine> Set-PSReadlineKeyHandler -Chord 'j,k' -Function NextLine -ViMode Command
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 105 Keys:
 s e t - p s r e Tab Tab o Backspace Space - e d Tab Space v i Enter
 s e t - p s r e Tab Space - c h Tab Space ' , j k Backspace Backspace Backspace j , k ' Space - f u Tab Space O Tab Tab Backspace Backspace Space N e x t L Tab Space - v i Tab Space C o Tab Enter
 a Space b Escape k Alt+r Escape Escape Alt+r 0 D Escape i a Space b Escape j k Alt+r Escape 0 C UpArrow Alt+f Alt+f Alt+f Alt+f Alt+f Escape

Exception:
System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.GetRange(Int32 index, Int32 count)
   at Microsoft.PowerShell.PSConsoleReadLine.EndEditGroup(Action`2 instigator, Object instigatorArg)
   at Microsoft.PowerShell.PSConsoleReadLine.GroupUndoHelper.EndGroup()
   at Microsoft.PowerShell.PSConsoleReadLine.ViCommandMode(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by srdubya** [comment]
Submitted a pull request with a fix.  Note:  I added a test case, but I could never get the case to fail with a unit test, even though I could readily replicate the failure at the command line.  TDD failed me in this case.
