### ISSUE TITLE
parameter is incorecct

### ISSUE THREAD

**Issue by buchokoy** [PowerShell/PSReadLine#574]
PS C:\WINDOWS\system32> n
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 60 Keys:
 o p e n f i l Tab Spacebar / q Backspace q u e r Tab t Backspace Backspace Backspace Backspace u e r t Backspace y Spacebar / Spacebar R S V Backspace Backspace Backspace Backspace s Spacebar R S V P Backspace Backspace Backspace B C S V R R E P 0 2 Enter
 Ctrl+x n

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by lzybkr** [comment]
Dupe of #292.
