### ISSUE TITLE
PSReadline crashes PowerShell when PSReadline is installed but not auto-imported when calling 'powershell -noprofile'

### ISSUE THREAD

**Issue by bergmeister** [PowerShell/PSReadLine#643]
Environment data
----------------

```
PSReadline version: 1.2
os: 6.3.9600.16384 (winblue_rtm.130821-1623)
PS file version: 10.0.14409.1005 (rs1_srvoob.161208-1155)
> $PSVersionTable

Name                           Value                                                                                                            
----                           -----                                                                                                            
PSVersion                      5.1.14409.1012                                                                                                   
PSEdition                      Desktop                                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                          
BuildVersion                   10.0.14409.1012                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                  
WSManStackVersion              3.0                                                                                                              
PSRemotingProtocolVersion      2.3                                                                                                              
SerializationVersion           1.1.0.1   
```

Steps to reproduce or exception report
--------------------------------------

On a WinServer 2012 R2 machine, PSReadline 1.2 is installed but does not get auto-loaded in the ISE.
I tried to do a `powershell -noprofile` and then PSReadline completely crashed PowerShell and it ended up in a hanging state:
````powershell
PS >  powershell -noprofile
Windows PowerShell 
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS > 
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.Internal.ConhostConsole.get_CursorLeft()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
````

**Comment by lzybkr** [comment]
This particular exception is just saying that `stdin` is redirected, `2.0.0-beta1` should handle this situation more gracefully.

If this is just in the ISE - then I think the hang is expected - it doesn't support an interactive console process, see this list:

```
#2 PS>$psUnsupportedConsoleApplications
wmic
wmic.exe
cmd
cmd.exe
diskpart
diskpart.exe
edit.com
netsh
netsh.exe
nslookup
nslookup.exe
powershell
powershell.exe
```

**Comment by bergmeister** [comment]
Ok. The reason why it only happened in the ISE was because PSReadLine already gets auto-discovered/loaded in powershell.exe
I would need to check what happened if I changed the auto-loading preference but if you say that the pre-releases handle it already better then that's OK.
