### ISSUE TITLE
Destination array was not long enough.Check destIndex and length, and the array's lower bounds.

### ISSUE THREAD

**Issue by puviyarasan** [PowerShell/PSReadLine#650]
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 7 Keys:
 Enter
 c d Backspace Backspace Backspace d

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

Environment data
----------------
PS version: 5.1.16299.251
PSReadline version: 1.2
os: 10.0.16299.15 (WinBuild.160101.0800)
PS file version: 10.0.16299.15 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------
I just created a new tab using ConEmu and moved it to a new window, I cannot repro it again, still reporting it just in case, the call stack helps.

**Comment by lzybkr** [comment]
This is a duplicate and has been reported many times, e.g. #481.
This is fixed in [2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta1).
