### ISSUE TITLE
System.PlatformNotSupportedException while running under tmux in iTerm2 on MacOS

### ISSUE THREAD

**Issue by bgshacklett** [PowerShell/PSReadLine#654]
Environment data
----------------

PS version: 6.0.2
PSReadline version: 2.0.0-beta1
os: Darwin BrianShlettsMBP.attlocal.net 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
PS file version:
PS /Users/brianshacklett/.vim>

Steps to reproduce or exception report
--------------------------------------

```
PS /Users/brianshacklett/.vim>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 77 Keys:
 t m u x Space - - v e r s i o n Enter
 UpArrow Ctrl+c UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace V Enter
 Ctrl+c Ctrl+b % Backspace Ctrl+b % Backspace Ctrl+b 5 Backspace Ctrl+b Backspace Backspace j Backspace g i t Space s t a t u s Enter
 v i m Space . g i t m o d u l e s Enter
 Enter
 Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l Ctrl+l

Exception:
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by petegooch** [comment]
Ditto.

PS version: 6.1.0
PSReadline version: 2.0.0-beta3
os: Linux pitrlaptop 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PS file version: 
<nothing here?>

**Comment by SteveL-MSFT** [comment]
Not reproing for me on Mojave and PSCore 6.1 or PSCore 6.2-preview.1 with PSReadLine 2.0.0-beta2.  

```
tmux
pwsh
vim
```

all works

**Comment by lzybkr** [comment]
The TERM setting might be important for this issue.

**Comment by bgshacklett** [comment]
I'll update my config and test as soon as I have a moment.

**Comment by DarkRTA** [comment]
I am also getting this issue upon pressing ctrl-l twice.

For reference my `$TERM` environment variable was set to `xterm-256color`. This only seems to happen when i press ctrl-l and the terminal was cleared recently.

## Enviroment Data
```
PS version: 6.1.1
PSReadline version: 2.0.0-beta3
os: Linux [hostname removed] 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PS file version:  6.1.1.0 
```

## Steps to reproduce

Last 2 Keys:
```
 Ctrl+l Ctrl+l
```

Exception:
```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by SteveL-MSFT** [comment]
This was repro'ing for me with beta.3, but using the latest built from master doesn't repro.

**Comment by lzybkr** [comment]
#790 must have fixed this, so I'll go ahead and close this issue.
