### ISSUE TITLE
Powershell crashes microsoft/powershell docker container

### ISSUE THREAD

**Issue by mikedbrook** [PowerShell/PSReadLine#670]
Running Docker Edge on MAC OSX 10.12.6
From within iterm2 pulled microsoft/powershell:latest container.
spin up the container ok and can docker exec into the container ok

run push in container to start powershell and receive the following output:

```
root@3d90889506e0:/# pwsh
PowerShell v6.0.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS />
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.DivideByZeroException: Attempted to divide by zero.
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```
### Steps to reproduce

docker pull microsoft/powershell
docker run --name=mypowershell -itd microsoft/powershell:latest
docker exec -it mypowershell /bin/bash

type pwsh at prompt

**Comment by mikedbrook** [comment]
I have also tried to run the same container on a windows machine running docker with limited sucess.  I have had an operational container and the above error under windows so this seems to be intermittent

**Comment by oivindoh** [comment]
Appears to still be a thing in 6.1; I'm seeing the same issue in

```
FROM microsoft/dotnet:2.1.0-rc1-aspnetcore-runtime-stretch-slim
RUN groupadd -g 999 appuser; useradd -r -u 999 -g appuser appuser

RUN apt-get update -y; \
    apt-get install wget curl gnupg apt-transport-https nano procps ca-certificates -y; \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -; \
    sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/microsoft.list'; \
    apt-get update; \
    apt-get install -y powershell; \
USER appuser
ENTRYPOINT [ "pwsh" ]
CMD [ "-File", "initScript.ps1" ]
```

The initScript.ps1 just unpacks some files before starting a dotnet application.

If I exec -ti into the container I'll get this error sometimes (just after starting pwsh, without entering anything):

```
$ pwsh
PowerShell v6.1.0-preview.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /app>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:


Exception:
System.DivideByZeroException: Attempted to divide by zero.
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

And then if I kill the container and start the exact same image again, everything might work smoothly with no error except `Error reading or writing history file '/home/appuser/.local/share/powershell/PSReadLine/ConsoleHost_history.txt': Access to the path '/home/appuser/.local/share/powershell/PSReadLine' is denied.` (which doesn't really concern us). Next restart things might still be fine, maybe the one after that as well, and then suddenly a failure. All running the exact same container with the exact same data in it.

**Comment by ghost** [comment]
In Docker compose environment, the problem occurs only when using the `exec` subcommand:
```
docker exec -it cli pwsh
# OR
docker exec -it cli bash
pwsh
```

But when using `attach` subcommand, the error does not seems to occur.
```
docker attach cli
pwsh
```

Regards,
Souvik

Reference: #705

**Comment by hifall** [comment]
This issue happens quite consistently on Ubuntu 16.04/Powershell 6.x, using @mikedbrook's repro in the original post.

Looks like a high-P issue to me.

**Comment by daxian-dbw** [comment]
Does this issue still reproduce to anyone with the latest powershell container images?
I tried `mcr.microsoft.com/powershell` and `mcr.microsoft.com/powershell:lts-ubuntu-16.04` with the @mikedbrook's repro steps, and did not observe the crash. PSReadLine works fine for me in both images.

**Comment by daxian-dbw** [comment]
Reopen this one as there are reports on a similar crash here: https://github.com/PowerShell/PowerShell/issues/11815

**Comment by DavidKittleSEL** [comment]
Any update on this? If I just start a container on our linux kubernetes cluster with the image tag mcr.microsoft.com/powershell:7.0.1 it crashes every couple of minutes with:
```
=PS /> 0
Oops, something went wrong. Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0
PowerShell: 7.0.1
OS: Linux 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020
Last 1 Keys

0

### Exception

System.DivideByZeroException: Attempted to divide by zero.
at Microsoft.PowerShell.PSConsoleReadLine.PhysicalLineCount(Int32 columns, Boolean isFirstLogicalLine, Int32& lenLastPhysicalLine)
at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
at Microsoft.PowerShell.PSConsoleReadLine.Render()
at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)

PS /> PS /> ;Process terminated. The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
at System.Environment.FailFast(System.String, System.Exception)
at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was -1.
at System.Console.SetCursorPosition(Int32 left, Int32 top)
at System.Console.set_CursorLeft(Int32 value)
at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineFromConsole(Boolean endOnTab, String initialContent, Boolean calledFromPipeline, String& restOfLine, ReadLineResult& result)
at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLine(Boolean endOnTab, String initialContent, ReadLineResult& result, Boolean calledFromPipeline, Boolean transcribeResult)
at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineWithTabCompletion(Executor exec)
at Microsoft.PowerShell.ConsoleHost.InputLoop.Run(Boolean inputLoopIsNested)
at Microsoft.PowerShell.ConsoleHost.InputLoop.RunNewInputLoop(ConsoleHost parent, Boolean isNested)
at Microsoft.PowerShell.ConsoleHost.EnterNestedPrompt()
at Microsoft.PowerShell.ConsoleHost.DoRunspaceLoop(String initialCommand, Boolean skipProfiles, Collection`1 initialCommandArgs, Boolean staMode, String configurationName)
at Microsoft.PowerShell.ConsoleHost.Run(CommandLineParameterParser cpp, Boolean isPrestartWarned)
at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, String[] args)
at Microsoft.PowerShell.ConsoleShell.Start(InitialSessionState initialSessionState, String bannerText, String helpText, String[] args)
at Microsoft.PowerShell.ConsoleShell.Start(String bannerText, String helpText, String[] args)
at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc)
```

**Comment by 123dev** [comment]
> 
> 
> Does this issue still reproduce to anyone with the latest powershell container images?
> I tried `mcr.microsoft.com/powershell` and `mcr.microsoft.com/powershell:lts-ubuntu-16.04` with the @mikedbrook's repro steps, and did not observe the crash. PSReadLine works fine for me in both images.

Yes, and it's so frustrating, is there any solution in sight?
Even a workaround?

Thanks

**Comment by zkhcohen** [comment]
+1 - Same symptoms using Docker Desktop and the PS container as a dev. container in VSCode:

PS /> PS /> ls@~~@@@@���

Oops, something went wrong. Please report this bug with the details below.

Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new

### Environment

PSReadLine: 2.0.0
PowerShell: 7.0.0
OS: Linux 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020
Last 200 Keys

```
@ @ @ @ @ @ @ @ @ Ctrl+b � � � � � � � � � Ctrl+r � Backspace @ @ � � � � � Backspace @ @ M Ctrl+c � � � Backspace @ @ � � � � � Backspace @ @ 0 f Ctrl+t ~ � Backspace @ @ � � � Ctrl+r � Backspace @ @ 2 ~ � � � Backspace @ @ � � � � � Backspace @ @ p � � Backspace � Backspace @ @ � � � Ctrl+r � Backspace @ @ 2 ~ � � @ @ @ @ @ @ @ @ � Backspace @ @ � p Ctrl+m @ @ @ @ @ � � O ~ � Backspace @ @ � ] � � � Backspace @ @ � � � T � Backspace @ @ � � � T � Backspace @ @ Ctrl+a @ @ @ @ @ @ @ � � � � � Backspace @ @ @ @ @ @ @ @ @ @ q � � Backspace � Backspace @ @ � � � Ctrl+r � Backspace @ @ � � � Backspace � Backspace @ @
```

### Exception

```
System.DivideByZeroException: Attempted to divide by zero.
at Microsoft.PowerShell.PSConsoleReadLine.PhysicalLineCount(Int32 columns, Boolean isFirstLogicalLine, Int32& lenLastPhysicalLine)
at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
at Microsoft.PowerShell.PSConsoleReadLine.CancelLine(Nullable`1 key, Object arg)
at Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by JohnLBevan** [comment]
The issue seems to be with these lines: https://github.com/PowerShell/PSReadLine/blob/fd1265e385cb4b7b860d8f1452da1ceb347e123e/PSReadLine/Render.cs#L489-L498 i.e. as BufferWidth is zero.

Below's some additional info (sadly copy-paste is not possible from the Docker for Desktop logs panel, where this info's available).

```
### Environment 
PSReadLine: 2.1.0 
PowerShell: 7.1.1 
OS: Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 
BufferWidth: 0 
BufferHeight: 0 
Last 1 Keys 
```
<?>
```
### Exception 
System.DivideByZeroException: Attempted to divide by zero. 
at Microsoft.PowerShell.PSConsoleReadLine.PhysicalLineCount(Int32 columns, Boolean isFirstLogicalLine, Int32& lenLastPhysicalLine) 
at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor) 
at Microsoft.PowerShell.PSConsoleReadLine.ForceRender() 
at Microsoft.PowerShell.PSConsoleReadLine.Render() at Microsoft.PowerShell.PSConsoleReadLine.Insert(Chat c) 
at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable'l key, Object arg) 
at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary'2 dispatchTable, Boolean ignoreIfNoAction, Object arg) 
at Microsoft.PowerShell.PSConsoleReadLine.InputLoop() 
at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, Enginelntrinsics engineIntrinsics, CancellationToken cancellationToken) 

PS /tmp> PS /tmp> 4Process terminated. The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top') 
Actual value was -1. 
at System.Environment. FailFast(System. String, System.Exception) 
at Microsoft. PowerShell.UnmanagedPSEntry. Start(System. String[], Int32) 
at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[]) System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top') Actual value was -1. 
at System. Console.SetCursorPosition(Int32 left, Int32 top) 
at System. Console. set_CursorLeft(Int32 value) 
at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLineFromConsole(Boolean endOnTab, String initialContent, Boolean calledFromPipeline, String& restOfLine, ReadLineResult& result) in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs:line 1796 
at Microsoft.PowerShell.ConsoleHostUserInterface.ReadLine(Boolean endOnTab, String initialContent, ReadLineResult& result, Boolean calledFromPipeline, Boolean transcribeResult) in /PowerShell/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs:line 1431 

```

**Comment by mmgil** [comment]
this error is disturbing me to generate powershell automations in linux environments

**Comment by ipg-informatik** [comment]
We have the same issue.

**Comment by daxian-dbw** [comment]
My investigation shows that the `DivideByZeroException` exception is caused by having the container detached.
When running `docker run -itd` to start the powershell container, since the container is detached, `System.Console.BufferWidth` and `System.Console.BufferHeight` are both 0, meaning the console windows doesn't exist, and it's actually a broken state. That leads to the `DivideByZeroException`.

I don't think there is anything to fix in PSReadLine. As a workaround, if you need to start the container in a detached mode, then instead of using the default CMD, which is really just for interactive attached usage, just explicitly specify a command to prevent things from shutting down, such as
```console
docker run --name=mypowershell -itd mcr.microsoft.com/powershell:latest pwsh -c "[console]::ReadKey()"
```
Then, you can run `docker exec -it mypowershell /bin/bash` or `docker exec -it mypowershell pwsh`

-------------------

For the "Remote - Container" extension in VSCode, now the extension automatically adds a `docker-compose.yml` file to override the default CMD of a container image. The overriding command is just a loop, to prevents the container from shutting down.
```yml
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
```
So I think you don't need to do anything extra, and it will just work. If the overriding command is not automatically added, then try adding it by yourself.
