### ISSUE TITLE
Powershell crashes after random keypresses

### ISSUE THREAD

**Issue by MuharremOkutan** [PowerShell/PSReadLine#672]
Exception
-----------
Exception:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at Microsoft.PowerShell.PSConsoleReadLine.Copy(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

Environment data
----------------
Windows 10

PS Version:
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  2125

Steps to reproduce or exception report
--------------------------------------
Last 45 Keys:
 i p c o n f i g Spacebar / a l l Enter
 p i n g Spacebar 1 0 . 1 7 8 . 2 . 2 5 Enter
 UpArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Shift+LeftArrow Ctrl+c

**Comment by lzybkr** [comment]
Thanks for the report. This is fixed in [2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta1).
