### ISSUE TITLE
System.IO.IOException: The parameter is incorrect.

### ISSUE THREAD

**Issue by iankronquist** [PowerShell/PSReadLine#681]
Environment data
----------------
PS version: 5.1.17134.1
PSReadline version: 1.2
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 10.0.17134.1 (WinBuild.160101.0800)

                               
Steps to reproduce or exception report
--------------------------------------
```
D:\2\os\src\shellcommon\inetcore>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 d Spacebar / s k u Backspace i p t e s t c o d e Enter
 Enter
 Enter
 b i n Enter
 Enter
 Enter
 c d Spacebar D : \ 2 \ o s \ s r c \ s h e l l c o m m o n \ i n e t c o r e Enter
 b u i l d Enter
 LeftWindows v Spacebar t o Tab d e p Tab c o Backspace Tab Enter
 UpArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Tab Tab Backspace Tab Tab Tab Enter
 UpArrow Home RightArrow Backspace l s Enter
 UpArrow Tab Enter
 UpArrow Tab Home RightArrow RightArrow Backspace Backspace Backspace v Enter
 g s Enter
 g d Backspace Backspace Backspace c p Spacebar ~ / d _ _ Tab Tab Tab Tab Spacebar Enter
 LeftWindows UpArrow . . \ . . \ o n Tab Tab i n Tab l i Tab s Tab Tab Tab Tab Tab Tab t o o Tab Backspace Backspace Backspace Backspace Backspace E Tab Enter
 PageUp

Exception:
System.IO.IOException: The parameter is incorrect.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```
gs and gd are function's I've defined in my powershell profile which run git status and git diff respectively.

I was working with Razzle, Microsoft's internal Windows Build system, and then running powershell when this happened. I have no idea what happened or how to reproduce it but I am dutifully submitting a bug report in hopes that it helps!

**Comment by lzybkr** [comment]
Thanks. This most likely happened after resizing and is probably fixed in [2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta1).

As an aside - you should try <kbd>Ctrl+Spacebar</kbd>, you may find yourself hitting <kbd>Tab</kbd> and <kbd>Backspace</kbd> much less.
