### ISSUE TITLE
Running as system using PSEXEC - System.IO.IOException: The handle is invalid.

### ISSUE THREAD

**Issue by whentimeslows** [PowerShell/PSReadLine#685]
When running Powershell as SYSTEM account using psexec.exe, we get errors complaining about the handle being invalid.

PS C:\WINDOWS\system32>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.Internal.ConhostConsole.get_CursorLeft()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIn
trinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntr
insics)
-----------------------------------------------------------------------

Environment data
----------------
PSReadline version: 1.2
os: 6.1.7601.17514 (win7sp1_rtm.101119-1850)

Steps to reproduce or exception report
--------------------------------------
1. Open CMD as administrator
2. Type "<folder>\psexec.exe -s -e cmd.exe" and hit enter
3. Type "Powershell.exe" and hit enter

**Comment by daxian-dbw** [comment]
I just tried the repro steps and start `pwsh` with the 2.2.2 version of PSReadLine instead, and no exception was thrown. I presume this was fixed at some point, so closing this one.
