### ISSUE TITLE
Issue when using Register-ObjectEvent to bind to a Process.Exited event

### ISSUE THREAD

**Issue by sammie-p** [PowerShell/PSReadLine#690]
I am trying to write a script that will start TightVNC service on a remote machine, launch the TightVNC viewer to connect to that machine, and stop the service on that machine when the Viewer exits.

## Function Definition:

```
function Start-TightVNC {
    param([Parameter(Position=0, Mandatory=$true, ValueFromPipeline=$true)][string]$ComputerName,
        [int]$Port,
        [switch]$Fullscreen,
        [switch]$ViewOnly,
        [switch]$FitToWindow,
        [switch]$NoRemoteCursor
    )
    Write-Host "Starting TightVNC Server on $ComputerName"
    $startupjob = Invoke-Command -ComputerName $ComputerName -ScriptBlock { Start-Service "tvnserver"; Start-Sleep 2 } -AsJob

    $spw = Read-Host -AsSecureString -Prompt "Provide a TightVNC password: "
    $BSTR = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($spw)
    $pw = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto($BSTR)
    
    #resolve tvnv path
    if(Test-Path "$env:ProgramFiles\TightVNC\tvnviewer.exe") {
        $tv="$env:ProgramFiles\TightVNC\tvnviewer.exe"
    } elseif (test-path "${env:ProgramFiles(x86)}\TightVNC\tvnviewer.exe") {
        $tv = "${env:ProgramFiles(x86)}\TightVNC\tvnviewer.exe"
    } else {
        Write-Error "TightVNC viewer cannot be found on this machine."
        throw "TightVNC viewer cannot be found on this machine."
    }

    #converting to encoded password (ref TightVNC source code on SourceForge)
    [byte[]]$bytes = [System.Text.Encoding]::UTF8.GetBytes($pw)
    [byte[]]$epw = [byte[]](,0*8)
    #pad password with nulls
    for ($i = 0; $i -lt 8; $i++) {
		if ($i -lt $bytes.Length) {
			$epw[$i] = $bytes[$i];
		} else {	
			break
		}
    }
    $des = [System.Security.Cryptography.DES]::Create()
    $des.Padding = [System.Security.Cryptography.PaddingMode]::None
    $des.Mode = [System.Security.Cryptography.CipherMode]::ECB
    $enc = $des.CreateEncryptor([byte[]]@(232,74,214,96,196,114,26,224),$null) #inverse of key VNC uses because VNC uses an inverted DES algo
    $epw = $enc.TransformFinalBlock($epw,0,$epw.Length) #bytes of the 'encoded' 8 character password
    $enc.Dispose()
    $des.Dispose()


    $args=@("-host=`"$ComputerName`"")
    [string]$options="[connection]`r`nhost=$ComputerName`r`npassword=$([string]::Join('',($epw | % { $_.ToString("x2")})))`r`n" #encoded password saved to connection file
    if($Port) {
        $args[0]="-host=`"$ComputerName::$Port`""
        $options+="port=$Port`r`n"
    }
    $options+="[options]`r`n"
    if($Fullscreen) {
        $options+="fullscreen=1`r`n"
    }
    if($ViewOnly) {
        $options+="viewonly=1`r`n"
    }
    if($FitToWindow) {
        $options+="fitwindow=1`r`n"
    }
    if($NoRemoteCursor) {
        $options+="noremotecursor=1`r`n"
    }
    $tg = [Guid]::NewGuid()
    sc -Value "$options" -Path $env:temp\$tg.vnc -Force
    $args+="-optionsfile=`"$env:temp\$tg.vnc`""
    $startupjob | Wait-Job | Remove-Job #waiting for startup to complete
    $proc = Start-Process -FilePath $tv -ArgumentList $args -PassThru
    $proc.EnableRaisingEvents=$true;
    $proc.WaitForExit(2000) | Out-Null #we wait for TVNCV to run a bit and open the connection file
    Remove-Item $env:temp\$tg.vnc #delete the connection file with the stored password.

    #2018-05-25 We want to shut down the remote computer's TVNC service after disconnection.
    Register-ObjectEvent -InputObject $proc -EventName Exited -MaxTriggerCount 1 -SourceIdentifier $proc.Exited -MessageData $ComputerName -Action {
        $ComputerName=$event.MessageData
        Write-Host "TightVNC Viewer exited. Stopping the TightVNC Server on $ComputerName."
        Invoke-Command -ComputerName $ComputerName -ScriptBlock { Stop-Service "tvnserver"; Set-Service "tvnserver" -StartupType Manual }
    } | Out-Null
}
```

## Command line

`Start-TightVNC -ComputerName pax-ws-rec1 -ViewOnly -FitToWindow`

## Exception (repeating continuously)
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 m e . " Enter
 Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar Spacebar I n v o k e - C o m m a n d Spacebar - C o m p u t e r N a m e Spacebar $ C o m p u t e r N a m e Spacebar - S c r i p t B l o c k Spacebar { Spacebar S t o p - S e r v i c e Spacebar " t v n s e r v e r " ; Spacebar S e t - S e r v i c e Spacebar " t v n s e r v e r " Spacebar - S t a r t u p T y p e Spacebar M a n u a l Spacebar } Enter
 Spacebar Spacebar Spacebar Spacebar } Spacebar | Spacebar O u t - N u l l Enter
 } Enter
 s t a r t - t i g h Tab Spacebar - Tab Spacebar p a x - w s - r e c 1 Spacebar - v i Tab Spacebar - f i t Tab Enter


Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```
## Environment Data
PS version: 5.1.16299.431
PSReadline version: 1.2
os: 10.0.16299.15 (WinBuild.160101.0800)
PS file version: 10.0.16299.15 (WinBuild.160101.0800)

**Comment by daxian-dbw** [comment]
@sammie-p Can you please try on the latest 2.2.2 version of PSReadLine and see if this still reproduces?
