### ISSUE TITLE
calling powershell script from Typescript

### ISSUE THREAD

**Issue by nivechandra** [PowerShell/PSReadLine#696]
Get NetworkSettings
NPS>  Process 15304 started

NPS>  Command invoke started
NPS>  i:\Preasto\checklist\server\powershellscripts\Get-NetworkSettings.ps1 -ComputerName <computerNae>-user <user> -pass <pswd>
NPS>  Command invoke finished

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:

Exception:
System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at Microsoft.PowerShell.Internal.ConhostConsole.get_CursorLeft()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment]
I'm guessing this is with v1.2? Redirected input can cause this error, it's not supported.

You can try [2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta1) and see if the error goes away.

**Comment by daxian-dbw** [comment]
Please try out the 2.0.0-rc1 from PowerShell Gallery.
