### ISSUE TITLE
Error while in Terminal of VSCode

### ISSUE THREAD

**Issue by nissan** [PowerShell/PSReadLine#701]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
-----------------------------------------------------------------------
Last 49 Keys:
 l s Enter
 d o t n e t Spacebar r u n Enter
 l s Enter
 c d Spacebar C l i Tab Enter
 y a r n Spacebar a d d Spacebar r e a c t s t r a p Enter
 UpArrow Enter
 UpArrow DownArrow

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.NextHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by lzybkr** [comment]
This is a duplicate and has been reported many times, e.g. #481.
This is fixed in [2.0.0-beta1](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta1).
