### ISSUE TITLE
e+Backspace throws ArgumentException

### ISSUE THREAD

**Issue by markfortma** [PowerShell/PSReadLine#706]
Environment data
----------------

PS version: 5.1.17134.81
PSReadline version: 1.2
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 10.0.17134.1 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------
Type 'e' then 'Backspace'

```PS C:\> e
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------------------
Last 2 Keys:
 e Backspace

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------------------
```

**Comment by lzybkr** [comment]
This is a duplicate and has been reported many times, e.g. #481.
This is fixed in [2.0.0-beta2](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta2).
