### ISSUE TITLE
Array length exception when copying from console

### ISSUE THREAD

**Issue by andyvanosdale** [PowerShell/PSReadLine#733]
Exception thrown when copying to the clipboard (not the same exception as !265).

Environment data
----------------
PS version: 5.1.17134.165
PSReadline version: 1.2
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 10.0.17134.1 (WinBuild.160101.0800)

Steps to reproduce or exception report
-----------------------------------------------------------------------
Last 200 Keys:
 c r e t - a l l - b i n d i n g Enter
 k c Spacebar g e t Spacebar r o l e Enter
 k c Spacebar g e t Spacebar r o l Spacebar e p Backspace Backspace Backspace e Spacebar p o d = a l Backspace Backspace Backspace - a l l Spacebar " Backspace - o = y a m l Enter
 UpArrow DownArrow k c Spacebar a p p l y Spacebar - f Spacebar 8
Backspace k 8 s / g i t l a b - r u n n e r - r b a c k . y m l Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Enter
 UpArrow Enter
 d e Backspace Backspace k c Spacebar d e l e t e Spacebar r o l e b i n d i n g Spacebar g i t l a b - r u n n e r Enter
 UpArrow Backspace Backspace Backspace n e r LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 UpArrow UpArrow UpArrow Enter
 UpArrow Enter
 k

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean
reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

**Comment by lzybkr** [comment]
This is a duplicate and has been reported many times, e.g. #481.
This is fixed in [2.0.0-beta2](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta2).
