### ISSUE TITLE
I found this bug when I install new laravel project

### ISSUE THREAD

**Issue by harishpatel143** [PowerShell/PSReadLine#734]
PS D:\Laravel Projects> composer create-project --prefer-dist laravel/laravel admin_panel
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 89 Keys:
 c o m p o s e r Spacebar c r e a t e - p r o j e c t Spacebar - - p r e f e r - d i s t Spacebar l a r a v e l / l a r a v e l Spacebar b l o g Backspace Backspace Backspace Backspace q i u c k Backspace Backspace Backspace Backspace u i c k _ a d m i n _ p a n e l Ctrl+Shift+LeftArrow Ctrl+c

Exception:
System.Runtime.InteropServices.ExternalException (0x800401D0): Requested Clipboard operation did not succeed.
   at System.Windows.Forms.Clipboard.ThrowIfFailed(Int32 hr)
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at Microsoft.PowerShell.PSConsoleReadLine.Copy(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.CopyOrCancelLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment]
Thanks for the report, I think this can't happen anymore with [2.0.0-beta2](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta2).
