### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zhaowei19920524** [PowerShell/PSReadLine#743]
PS F:\OneDrive\Documents\McMaster University\2018\python lesson\PythonCodesLesson2> a
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 18 Keys:
 a s e d s Backspace Backspace f d g h Backspace Backspace Backspace Backspace Backspace Backspace Backspace

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.BackwardDeleteChar(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS F:\OneDrive\Documents\McM
 lesson\PythonCodesLesson2>

**Comment by lzybkr** [comment]
This is a duplicate and has been reported many times, e.g. #481.
This is fixed in [2.0.0-beta2](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta2).
