### ISSUE TITLE
Exception in static ctor creating history mutex

### ISSUE THREAD

**Issue by piddeman75** [PowerShell/PSReadLine#746]
Environment data
----------------

Steps to reproduce or exception report
```
Last 0 Keys:


Exception:
System.UnauthorizedAccessException: Access to the path 'PSReadlineHistoryFile_46696421' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Threading.Mutex.MutexTryCodeHelper.MutexTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.Mutex.CreateMutexWithGuaranteedCleanup(Boolean initiallyOwned, String name, Boolean& createdNew, SECURITY_ATTRIBUTES secAttrs)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name, Boolean& createdNew, MutexSecurity mutexSecurity)
   at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIntrinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```
[problem.txt](https://github.com/lzybkr/PSReadLine/files/2297034/problem.txt)

**Comment by daxian-dbw** [comment]
#1061 and #1602 were made to improve how PSReadLine uses mutex for history file. Also, it's been a long time that I don't see new issues reporting about `UnauthorizedAccessException` regarding the mutex. So I think the issue was resolved. Please upgrade to the [2.1.0 version of PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.1.0) from PowerShell Gallery.
See the [upgrading section](https://github.com/PowerShell/PSReadLine#upgrading) for instructions. Please let us know if you run into the same issue with the latest version.
