### ISSUE TITLE
"Oops, something went wrong.  Please report this bug with the details below." when pressing "Up"

### ISSUE THREAD

**Issue by xobs** [PowerShell/PSReadLine#761]
Environment data
----------------

<!-- provide the output of the following:
```powershell
PS version: 5.1.17134.228
PSReadline version: 1.2
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 10.0.17134.1 (WinBuild.160101.0800)
-->

Steps to reproduce or exception report
--------------------------------------

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 - c Enter
 UpArrow Backspace Backspace Enter
 RightArrow UpArrow Spacebar B e a c o n B l e : S Spacebar ' v e n d o r . q t i . b l u e t o o t h @ 1 . 0 - i b s _ h a n d l e r : S ' Enter
 UpArrow Spacebar v e n d o r . q t i . b l u e t o o t h @ 1 . 0 - i b s _ h a n d l e r : Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace B l u e t o o t h L e S c a n n e r : S Spacebar B l u e t o o t h A d a p t e r : S Spacebar Enter
 UpArrow Ctrl+c Ctrl+c UpArrow Escape h i s t o r y Enter
 ! 3 8 Enter
 UpArrow UpArrow UpArrow

Exception:
System.OverflowException: Array dimensions exceeded supported range.
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.PreviousHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------

I was told by Powershell to report this issue to this URL.

I was using "adb logcat", and Powershell would print the above message every time I tried to scroll back to a history item.  The command in question is:

adb logcat LocSvc_ApiV02:S wpa_supplicant:S LocSvc_libulp:S ThermalEngine:S LocSvc_HIDL_IzatOsNpGlue:S LocSvc_HIDL_OsNpGlue_jni:S LocSvc_api_v02:S AnalyticsTrackWrapper:S ChimeraUtils:S zygote64:S zygote64:S ctxmgr:S LocSvc_HIDL_IzatProvider:S LocSvc_HIDL_IzatProvider_jni:S LocSvc_GnssInterface:S IzatSvc_ComboNetworkProvider:S chatty:S WificondControl:S NetworkPolicy:S NativeCrypto:S ProviderInstaller:S  BeaconBle:S 'vendor.qti.bluetooth@1.0-ibs_handler:S' BluetoothLeScanner:S BluetoothAdapter:S

Eventually the problem went away, however the error message said to file a bug here, so that's what I'm doing.

**Comment by lzybkr** [comment]
Which version of PSReadLine are you using? If this is 1.2, I think I'll just close this as the rendering has been rewritten starting with 2.0.0-beta1.

**Comment by xobs** [comment]
It's 1.2.  Sorry, it looks like the output from the command got placed into a comment.

Since it's 1.2 I'll close this issue.
