### ISSUE TITLE
Up Arrow In Integrated Terminal After F8 Code Run Causes System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by rossmeyer1** [PowerShell/PSReadLine#764]
Environment data
----------------

PS version: 6.1.0
PSReadline version: 2.0.0-beta3
os: Darwin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
PS file version: n/a

Steps to reproduce or exception report
--------------------------------------
Last 3 Keys:
```
 ` UpArrow DownArrow
```

Exception:
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -23.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.HistoryRecall(Int32 direction)
   at Microsoft.PowerShell.PSConsoleReadLine.NextHistory(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------

Run large chunk of code with F8 in VSCode.
Go to the integrated terminal.
Press the up arrow.

**Comment by SeeminglyScience** [comment]
@GHRoss Could you try manually adding the same snippet to history outside of VSCode and see if it does the same thing?

```powershell
[Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory($text)
```

I think this is due to `System.Console`'s cursor API's only being aware of the viewport for Unix-like.

**Comment by rossmeyer1** [comment]
> @GHRoss Could you try manually adding the same snippet to history outside of VSCode and see if it does the same thing?
> 
> ```powershell
> [Microsoft.PowerShell.PSConsoleReadLine]::AddToHistory($text)
> ```
> 
> I think this is due to `System.Console`'s cursor API's only being aware of the viewport for Unix-like.

So you'd want me to put it in a here string and assign it to $text?

**Comment by SeeminglyScience** [comment]
@GHRoss Yes that's right.  Outside of VSCode, assign to `$text` a here string containing the code you invoked with <kbd>F8</kbd> when that error occurred.  Then invoke that method and try pressing <kbd>UpArrow</kbd> again.
