### ISSUE TITLE
When tab completing 400+ AD computers using get-adcomputer

### ISSUE THREAD

**Issue by Donovoi** [PowerShell/PSReadLine#765]
Environment data
----------------

PS version: 5.1.17758.1
PSReadline version: 2.0.0-beta2
os: 10.0.17758.1 (WinBuild.160101.0800)
PS file version: 10.0.17758.1 (WinBuild.160101.0800)
Steps to reproduce or exception report
--------------------------------------
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 i Tab n e Enter
 g e t - p s r e a d l i n e Tab Tab Space - Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Enter
 e x i t Enter
 i m p o r t - m o d Tab Space p s r e Tab Enter
 s e t - p s r e a d Tab Tab Tab Tab Space - Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace Backspace e d Tab Space Tab Enter
 g e t - p r o Tab c Tab Space - Tab Tab Tab n a Tab Space Tab Tab s e r Tab Enter
 g e t 0 Backspace - a d Tab Tab Tab c o m p Tab Space - Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Tab Backspace - Tab f i l Tab Space Tab Tab y Backspace Backspace Tab Tab y

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1746.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.EnsureMenuAndInputIsVisible(IConsole console, Int32 tooltipLineCount)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\WINDOWS\system32> Get-ADComputer -Filter

**Comment by Morilli** [comment]
Got a rather similar error today. I just opened the console, pressed up and got a ``System.ArgumentOutOfRangeException``, telling me the actual value was -1. Happened on the current version of Windows 10 Pro 1809.

**Comment by lzybkr** [comment]
Closed via #783.
