### ISSUE TITLE
System.OutOfMemoryException: Array dimensions exceeded supported range. 

### ISSUE THREAD

**Issue by jkotalik** [PowerShell/PSReadLine#778]
Environment data
----------------
```
Exception:
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at Microsoft.PowerShell.PSConsoleReadLine.<MaybeReadHistoryFile>b__66_0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.<>c__DisplayClass65_0.<WriteHistoryRange>b__0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.MaybeAddToHistory(String result, List`1 edits, Int32 undoEditIndex, Boolean readingHistoryFile, Boolean fromDifferentSession)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

Can't get the output due to OOM
-->

Steps to reproduce or exception report
--------------------------------------
Over time, Powershell on my desktop started failing to accept text input. Currently, I can reproduce by simply opening Powershell and typing ls.

**Comment by lzybkr** [comment]
I'm guessing this is PSReadLine 1.2?

There was a race condition that has been fixed. You'll probably need to delete your history file, or at least edit it make it smaller.

**Comment by jkotalik** [comment]
Yep, that worked.
