### ISSUE TITLE
Tab Expansion/Completion Detonates After Some Time

### ISSUE THREAD

**Issue by nteague22** [PowerShell/PSReadLine#791]
Environment data
----------------
PS version: 5.1.14409.1012
PSReadline version: 2.0.0-beta3
os: 6.1.7601.17514 (win7sp1_rtm.101119-1850)
PS file version: 10.0.14409.1005 (rs1_srvoob.161208-1155)

Steps to reproduce or exception report
--------------------------------------

Use powershell window (regular user or as Administrator)  Window v buffer is set to a huge amount (approx 5500).  When you get enough data to scroll through the page (directory recursive searches, etc.) and then attempt to double tab to activate expansion -- the below emits everytime, until you kill terminal or run clear to wipe the active buffer

This was supplied output:

-----------------------------------------------------------------------
Last 200 Keys:
```
 i l t e r Space p a c k a g e s . c o n f i g LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Lef
tArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Lef
tArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow - p a t h Space LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Space RightArrow RightArrow
 RightArrow RightArrow RightArrow Delete End Enter
 UpArrow Space | Space s l s Space ' s y s t e m ' Enter
 UpArrow Escape s v n Space b l a m e Space . \ m v c t e s t s \ p a c k Tab Enter
 ` m s b u i l d Space d x e n g Tab / Backspace . s l n Space / r e s t o e r Space / Backspace Backspace Backspace Backspace r e Space / m Enter
 n u n i Tab Tab Tab Tab Backspace Backspace Backspace Backspace Backspace . \ p a c k a Tab n u Tab Tab
```

Exception:
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was 300.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.Menu.DrawMenu(Menu previousMenu, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.PossibleCompletionsImpl(CommandCompletion completions, Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.CompleteImpl(Boolean menuSelect)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------

**Comment by lzybkr** [comment]
This is fixed in https://github.com/lzybkr/PSReadLine/pull/783

You can grab a build from AppVeyor until I get the next beta out.

**Comment by daxian-dbw** [comment]
Closed as fixed.
