### ISSUE TITLE
copy to Administrator

### ISSUE THREAD

**Issue by MisakaMikoto19090** [PowerShell/PSReadLine#816]
Detail:

```Shell
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -100.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

Enviroment data:

```Shell
PS version: 5.1.17763.134
PSReadline version: 2.0.0-beta2
os: 10.0.17763.1 (WinBuild.160101.0800)
PS file version: 10.0.17763.1 (WinBuild.160101.0800)
```
Trigger:

copy from a common txt file and to an Administrator Powershell, but it didn`t trgger again after i opened a new poweshell(admin or common user)

**Comment by lzybkr** [comment]
Could this be a duplicate of #663?

**Comment by Ash258** [comment]
I am experiencing something similar. CTRL+V does not work, but Right click work as exepected

Happening on elevated and unelevated prompt.

![Proof](https://i.imgur.com/wqjQlp7.png)

```
PS version: 6.1.1
PSReadline version: 1.2
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 6.1.1
```

**Comment by MisakaMikoto19090** [comment]
@lzybkr Sorry,went on a business trip.After checking out #663. I believe it is a similiar problem with diferent parameters . Thank you ,I will close this issue.
