### ISSUE TITLE
Tab autocomplete dropped to a [DBG] prompt, then asked me to follow this link.

### ISSUE THREAD

**Issue by BeRangel** [PowerShell/PSReadLine#820]
Environment data
----------------
PS version: 5.1.17134.228
PSReadline version: 1.2
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 10.0.17134.1 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------
I hit the Tab key to autocomplete the name of a folder on my root C:\. Instead of autocomplete, it switched the prompt to [DBG].

When I typed exit, it threw an exception and asked me to report the following;
```
PS C:\Windows\system32> cd \RarAt line:35 char:1
+ {
+ ~
[DBG]: PS C:\Windows\system32>> ^C
[DBG]: PS C:\Windows\system32>> exit

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace UpArrow Backspace Backspace Backspace Backspace Backspace Backspace [ 0 ] Enter
 UpArrow UpArrow UpArrow [ 0 ] Enter
 S t o p - P Tab Tab Spacebar $ r c s Tab [ 0 ] . I Tab Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Enter
 $ r c s v Tab . C o u Tab Enter
 UpArrow UpArrow UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow Delete 1 Enter
 UpArrow Ctrl+LeftArrow LeftArrow LeftArrow LeftArrow Delete 0 Enter
 G e t - S E r Tab g e t - s e r v i c e Spacebar r a r e c y t e Enter
 e x i t Enter
 Backspace Backspace Backspace Backspace Backspace Backspace Backspace g e t - s e r v i c e Spacebar r a r e c y t e Enter
 S Backspace Backspace S t a r t - S e r Tab Spacebar R a r e C y t e Enter
 UpArrow UpArrow Enter
 UpArrow Enter
 UpArrow Enter
 c d Spacebar \ R a r Tab Ctrl+c e x i t Enter


Exception:
System.ArgumentException: length is too big
Parameter name: length
   at Microsoft.PowerShell.PSConsoleReadLine.Replace(Int32 start, Int32 length, String replacement, Action`2 instigator, Object instigatorArg)
   at Microsoft.PowerShell.PSConsoleReadLine.DoReplacementForCompletion(CompletionResult completionResult, CommandCompletion completions)
   at Microsoft.PowerShell.PSConsoleReadLine.Complete(Boolean forward)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
```

**Comment by daxian-dbw** [comment]
We had lots of fixes to improve the stability of PSReadLine and this issue looks like one that was fixed in the latest version of PSReadLine. Please upgrade to the latest PSReadLine version v2.3.1-beta1 and give it a try (see instructions [here](https://github.com/PowerShell/PSReadLine#upgrading)). Feel free to open a new issue if you continue to run into this.
