### ISSUE TITLE
Azure service alert

### ISSUE THREAD

**Issue by haroon-yunus** [PowerShell/PSReadLine#853]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by haroon-yunus** [comment]
```
          "maxLength": 12,
             "metadata": {
                 "description": "Short name for the Action group."
             }
         },
         "emailAddress": {
             "type": "haroon_yunus@hotmail.com",
             "metadata": {
                 "description": "Email address."
             }
         },
         "activityLogAlertName": {
             "type": "AE1611Alert",
             "defaultValue": "serviceHealthAlert",
             "minLength": 1,
             "metadata": {
                 "description": "Name for the Activity log alert."
             }
         }
     },
     "resources": [
         {
             "type": "Microsoft.Insights/actionGroups",
             "apiVersion": "2017-04-01",
             "name": "[parameters('actionGroupName')]",
             "location": "Global",
             "properties": {
                 "groupShortName": "[parameters('actionGroupShortName')]",
                 "enabled": true,
                 "smsReceivers": [],
                 "emailReceivers": [
                     {
                         "name": "emailReceiver",
                         "emailAddress": "[parameters('emailAddress')]"
                     }
                 ],
                 "webhookReceivers": []
             }
         },
         {
             "type": "Microsoft.Insights/activityLogAlerts",
             "apiVersion": "2017-04-01",
             "name": "[parameters('activityLogAlertName')]",
             "location": "Global",
             "dependsOn": [
                 "[parameters('actionGroupName')]"
             ],
             "properties": {
                 "enabled": true,
                 "scopes": [
                     "[subscription().id]"
                 ],
                 "condition": {
                     "allOf": [
                         {
                             "field": "Category",
                             "equals": "ServiceHealth"
                         }
                     ]
                 },
                 "actions": {
                     "actionGroups": [
                         {
                             "actionGroupId": "[resourceId('Microsoft.Insights/actionGroups', parameters('actionGroupName'))]"
                         }
                     ]
                 }
             }
         }
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
```
 Space Space Space Space Space " a c t i o n G r o u p I d " : Space " [ r e s o u r c e I d ( ' M i c r o s o f t . I n s i g h t s / a c t i o n G r o u ps ' , Space p a r a m e t e r s ( ' a c t i o n G r o u p N a m e ' ) ) ] " Enter
 Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space } Enter
 Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space ] Enter
 Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space Space } Enter
 Space Space Space Space Space Space Space Space Space Space Space Space } Enter
 Space Space Space Space Space Space Space Space } Enter
 Space Space Space Space ] Enter
 }
```

Exception:
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -73.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------

**Comment by haroon-yunus** [comment]
I have  tried  to use the JSON  command
https://github.com/Azure/azure-quickstart-templates/tree/master/monitor-servicehealth-alert

Its comming up with an error
Its works fine when i deploy to azure but need the command
Please advise.
