### ISSUE TITLE
Endless exception loop in VScode with PowerShell Preview 2.0.1 extension

### ISSUE THREAD

**Issue by sba923** [PowerShell/PSReadLine#889]
## Environment data
(captured from another VScode context where the endless loop does _not_ occur)
````
PSReadline version: 2.0.0-beta4
os: 10.0.17134.1 (WinBuild.160101.0800)
PS file version: 6.2.0
````

## Steps to reproduce or exception report

I don't know how, but in one of my VScode "folders" (on a network UNC path, FWIW) with PowerShell code I've reached a situation where even launching VScode without performing any action (the active file has to be a .ps1 file) causes the TERMINAL pane to enter an endless loop with:

````
PS>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
### Environment
PSReadLine: 2.0.0-beta3
PowerShell: 2.0.1
OS: Microsoft Windows 10.0.17134
Last 0 Keys
```

```

### Exception
```
System.Management.Automation.Runspaces.InvalidRunspaceStateException: Cannot invoke the pipeline because the runspace is not in the Opened state. Current state of the runspace is 'Closing'.
   at System.Management.Automation.Runspaces.RunspaceBase.AddToRunningPipelineList(PipelineBase pipeline)
   at System.Management.Automation.Runspaces.RunspaceBase.DoConcurrentCheckAndAddToRunningPipelines(PipelineBase pipeline, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(IEnumerable input, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
````

(please note that I don't have any `beta3` PSRL anywhere on the system, only `beta4`).

This makes it basically impossible to use VScode to develop PowerShell code in that folder.

**Comment by ghvanderweg** [comment]
I get this same exception loop in VS Code from time to time, haven't been able to reliably reproduce the issue. Usually restarting the PowerShell sessions fixes it.

### Environment
PSReadLine: 2.0.0-beta4
PowerShell: 2.0.2
OS: Microsoft Windows 10.0.18898

### Exception
```
System.Management.Automation.Runspaces.InvalidRunspaceStateException: Cannot invoke the pipeline because the runspace is not in the Opened state. Current state of the runspace is 'Closing'.
   at System.Management.Automation.Runspaces.RunspaceBase.AddToRunningPipelineList(PipelineBase pipeline)
   at System.Management.Automation.Runspaces.RunspaceBase.DoConcurrentCheckAndAddToRunningPipelines(PipelineBase pipeline, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(IEnumerable input, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by msftrncs** [comment]
I think it is entirely a coincidence that PSReadLine reports an error here, and that it really has to do with something that the VS Code Extension is doing, because it uses the PowerShell session behind the scenes, PowerShell just happens to be waiting in PSReadLine's ReadKey method at the time it crashes.

It could be that PSReadLine just needs to ignore this exception when it occurs.

**Comment by daxian-dbw** [comment]
The root cause of this exception is the PowerShell VSCode extension. It indicated a bug in the Runspace management in PowerShell editor service (PSES) -- PSReadLine attempts to use the default Runspace that's owned by PSES while the Runspace is not available for code execution.

There has been a lot improvements in PSES related to PSReadLine support in the past year, so it's very likely that the reported issue was fixed. Given that, I'm closing this issue. Feel free to open a new issue if you run into something else.
