### ISSUE TITLE
100,000 lines returns this error Win32

### ISSUE THREAD

**Issue by coffeemade** [PowerShell/PSReadLine#907]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------
Customer has over 100,000 mailboxes and we get a count so I run $a = get-mailbox -resultsize unlimited and I get this error. 

I then follow up with $a.count, but so my question is there a limit to the amount it can put or a better way?

**Comment by lzybkr** [comment]
Not a PSReadLine issue.

**Comment by PaulRNewell** [comment]
Izybkr, 
PowerShell actually tells us to come here to open a new issue: 

https://github.com/lzybkr/PSReadLine/issues/new
Exception:
System.IO.IOException: Illegal operation attempted on a registry key that has been marked for deletion.

   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.GetValueNames()
   at System.Management.Automation.Utils.GetGroupPolicySetting(String groupPolicyBase, String settingName, RegistryKey[] preferenceOrder)
   at System.Management.Automation.ScriptBlock.ScriptBlockLoggingExplicitlyDisabled()
   at System.Management.Automation.ScriptBlock.LogScriptBlockCreation(ScriptBlock scriptBlock, Boolean force)
   at System.Management.Automation.ScriptBlock.LogScriptBlockStart(ScriptBlock scriptBlock, Guid runspaceId)
   at System.Management.Automation.DlrScriptCommandProcessor.DoBegin()
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
   at System.Management.Automation.Runspaces.LocalPipeline.StartPipelineExecution()
   at System.Management.Automation.Runspaces.PipelineBase.CoreInvoke(IEnumerable input, Boolean syncCall)
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadKey()
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by lzybkr** [comment]
I see. Based on that stack, this seems like a more general PowerShell issue that could affect any running script, not just PSReadLine.
