### ISSUE TITLE
"Oops, something went wrong

### ISSUE THREAD

**Issue by jroggeman** [PowerShell/PSReadLine#908]
Got a general error message + stack trace with instructions to report it. Doesn't appear to be the same exception as any other bugs with the same title I see (feel free to close if I missed one).

```powershell
C:\Users\jorogg\Code\kubernetes-util\azureml-infra\src\Telemetry\JoelFakeApp
  echo $env:SYSTEM_HOSTTYPE
C:\Users\jorogg\Code\kubernetes-util\azureml-infra\src\Telemetry\JoelFakeApp
λ
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 187 Keys:
 c d Spacebar k Backspace c o Tab c Backspace Enter
 c d Spacebar k u Tab Enter
 d i r Enter
 c d Backspace Backspace Backspace c d Spacebar a z u Tab Enter
 c d Spacebar s r Tab Enter
 c d Spacebar t l Tab Enter
 c d Spacebar t e Tab Enter
 d i r Enter
 c d Spacebar j o Tab Enter
 Ctrl+r m s f t k u b Enter
 . . \ . . \ . . \ . . \ v e n t Backspace v 2 \ s c r Tab t Backspace a c t Tab . p s Tab Enter
 UpArrow UpArrow Enter
 e c h o Spacebar $ e n v Enter
 c a t Spacebar Backspace Backspace Backspace Backspace Backspace e c h o Spacebar % S Y S T E M _ H O S T T Y P E % Enter
 UpArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow End Backspace Home RightArrow Ctrl+RightArrow RightArrow Backspace $ e n v : Enter
 LeftWindows f

Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
C:\Users\jorogg\Code\kubernetes-util\azureml-infra\src\Telemetry\JoelFakeAppineIntrinsics engineIntrinsics)
```

Environment data
----------------

PS version: 5.1.17763.316
PSReadline version: 1.2
os: 10.0.17763.1 (WinBuild.160101.0800)
PS file version: 10.0.17763.1 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------
See above

**Comment by lzybkr** [comment]
This was reported frequently, e.g. #481 and is likely fixed in 2.0.
