### ISSUE TITLE
Powershell stuck when I open a new Console

### ISSUE THREAD

**Issue by woshihyf234** [PowerShell/PSReadLine#921]
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

Loading personal and system profiles took 598ms.
PS C:\windows\system32>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 0 Keys:

Exception:
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at Microsoft.PowerShell.PSConsoleReadLine.<ReadHistoryFile>b__67_0()
   at Microsoft.PowerShell.PSConsoleReadLine.WithHistoryFileMutexDo(Int32 timeout, Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.DelayedOneTimeInitialize()
   at Microsoft.PowerShell.PSConsoleReadLine.Initialize(Runspace runspace, EngineIntrinsics engineIn
trinsics)
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntr
insics)
-----------------------------------------------------------------------

Sometimes I open a new Console this issue will happening. After open I can't type in any character and what's more, I notice the memory cost will increasing crazily and after reach to 90%, this error message will shown up.

**Comment by lzybkr** [comment]
I'm guessing you have PSReadLine 1.2 and your history file is huge. Assuming this is the case, there was a race condition in PSReadLine that caused this and deleting the file (or just editing it) should fix the problem.

**Comment by SteveL-MSFT** [comment]
@woshihyf234 can you try PSReadLine 2.0.0-beta4 or the recommended fix by Jason?
