### ISSUE TITLE
PS ReadLine 

### ISSUE THREAD

**Issue by dccozine** [PowerShell/PSReadLine#923]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by dccozine** [comment]
-----------------------------------------------------------------------
Last 200 Keys:
```
 n g s t o r a g e a c c o u n t " Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace d a t a s c i e n c e RightArrow Insert PageUp End Insert Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace UpArrow UpArrow DownArrow Enter
 $ s t o r a g e A c c o u n t N a m e Space = Space " m y e x i s t i n g s t o r a g e a c c o u n t " Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace d a t a s c i e n c e Insert RightArrow PageUp UpArrow Enter
 $ s t o r a g e A c c o u n t N a m e Space = Space " d a t a s c i e n c e RightArrow Insert PageUp
```

Exception:
```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayUp(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------

**Comment by dccozine** [comment]
Error returned when using PS Azure:\> $storageAccountName = "
