### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by rasiar** [PowerShell/PSReadLine#929]
----------------

Last 91 Keys:
 p y t h o n Space - u Space " c : \ U s e r s \ R A S I A R \ D e s k t o p \ P y t h o n Space P r o j e c t s \ M y Space F i r s t Space P r o g r a m \ t e m p C o d e R u n n e r F i l e . p y " Enter

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
--------------------------------------

**Comment by SteveL-MSFT** [comment]
@rasiar can you confirm what version you are using?
