### ISSUE TITLE
Error received in PowerShell

### ISSUE THREAD

**Issue by milescw** [PowerShell/PSReadLine#932]
Environment data
----------------
PS version: 5.1.17763.503
PSReadline version: 2.0.0-beta2
os: 10.0.17763.1 (WinBuild.160101.0800)
PS file version: 10.0.17763.1 (WinBuild.160101.0800)

Steps to reproduce or exception report
--------------------------------------
All I did was start to type docker run -v and as soon as I pressed the letter "d" this error came up.
$d
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 152 Keys:
 c d Space C : \ U s e r s \ C h a r l e s \ D o c u m e n t s \ T r a i n i n g \ U d a c i t y \ N a n o d e g r e e \ B l o c k c h a i n - D e v e l o p e r \ T e r m 2 \ P r o j e c t s \ u d b c d - b l o c k c h a i n - c a p s t o n e Enter
 p w d Enter
 f u n c t i o n Space p r o m p t Space { " $ " } Enter
 p w d Enter
 d o

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
$cker run

**Comment by daxian-dbw** [comment]
This one is a easy repro, it's because the `prompt` function was changed to produce a string that is shorter than the error prompt `> `.
