### ISSUE TITLE
Powershell shows ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by ggaryu** [PowerShell/PSReadLine#950]
Opened PowerShell and tried to paste a short string and got this message. The string was pasted successfully after the message, as shown below.

PS C:\git\CoreScienceDataStaging\datasources\Teams\resources\infiles>
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 3 Keys:
 ` ` Ctrl+v

Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\git\CoreScienceDataStaging\datasources\Teams\resources\infiles> fst.exe -f Moments.intent.matching.infile

Environment data
----------------
PS version: 5.1.18362.145
PSReadline version: 2.0.0-beta2
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 10.0.18362.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 9001

Steps to reproduce or exception report
--------------------------------------

**Comment by AArnott** [comment]
Environment data
----------------
```
PS version: 6.2.1
PSReadline version: 2.0.0-beta3
os: Linux DESKTOP-T9OG488 4.4.0-18362-Microsoft #1-Microsoft Mon Mar 18 12:02:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
PS file version: 6.2.1.0
BufferWidth: 120
BufferHeight: 30
```

Steps to reproduce or exception report
--------------------------------------

In an Ubuntu 18 (Windows subsystem for Linux) window, type `pwsh` to launch powershell. 
**BEFORE** pwsh's prompt appears, start typing the next command. It repros fairly reliably. See output below. Notice how I started typing `./init.ps1` and my command got split across multiple lines, followed by pwsh complaining: (I added backslashes in front of triple-tick marks that pwsh itself emitted so that github wouldn't interpret them)

```
andrew@DESKTOP-T9OG488:~/git/vs-streamjsonrpc$ ls
CONTRIBUTING.md  README.md        azure-pipelines.yml  global.json  init.ps1      src    version.json
LICENSE          azure-pipelines  doc                  init.cmd     nuget.config  tools
andrew@DESKTOP-T9OG488:~/git/vs-streamjsonrpc$ pwsh
PowerShell 6.2.1
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

./
inPS /home/andrew/git/vs-streamjsonrpc> it.ps1

Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 4 Keys:
\```
 . / i n
\```

Exception:
\```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: left
Actual value was -2.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.Internal.VirtualTerminal.set_CursorLeft(Int32 value)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Render()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
\```
-----------------------------------------------------------------------
PS /home/andrew/git/vs-streamjsonrpc> ./init.ps1                                                                                                   ^[OA
INFO: Creating the nuget plugin directory (i.e. /home/andrew/.nuget/plugins).
Downloading from https://github.com/Microsoft/artifacts-credprovider/releases/latest/download/Microsoft.NuGet.CredentialProvider.tar.gz
INFO: credential provider netcore plugin extracted to /home/andrew/.nuget/
```

**Comment by jlouros** [comment]
Same for me.
Happens on Windows Terminal 0.3.2171.0 but works fine on pwsh shell

## Environment data
```
PS version: 6.2.2                                                                                                                                                               PSReadline version: 2.0.0-beta3
os: 10.0.18362.1 (WinBuild.160101.0800)
PS file version: 6.2.2.0
BufferWidth: 176
BufferHeight: 41
```

## Exception

Last 200 Keys:
```
 Space Space Space Space Space Space = Space @ ( " $ . C o n n e c t i o n S t r i n g s . m a s t e r W r i t e " , Space " $ . C o n n e c t i o n S t r i n g s . w r i t e " ) Enter
 Ctrl+Enter Space Space Space Space Space Space Space Space Space Space Space Space i s p a r t a l Space Space Space Space Space Space Space = Space $ t r u e Enter
 Ctrl+Enter Space Space Space Space Space Space Space Space Space Space Space Space r e p l a c e p a t t e r n Space = Space " s e r v e r \ = ( [ \ s \ w \ { \ } \ - , ] + ) ; " Enter
 Ctrl+Enter Space Space Space Space Space Space Space Space } Enter
 Ctrl+Enter Space Space Space Space ) $ Backspace Backspace Backspace Backspace Backspace Backspace Backspace Backspace c l e a r Enter

```

Exception:
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -164.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLineImpl(Boolean validate)
   at Microsoft.PowerShell.PSConsoleReadLine.AcceptLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
