### ISSUE TITLE
Exception after maximizing PowerShell Window

### ISSUE THREAD

**Issue by DavidEPatrick** [PowerShell/PSReadLine#963]
-----------------------------------------------------------------------
Last 200 Keys:
```
 Space - - s u b n e t - p r e f i x Space 1 0 . 0 . 1 . 0 / 2 4 Enter
 UpArrow UpArrow UpArrow UpArrow UpArrow UpArrow Backspace Enter
 UpArrow UpArrow DownArrow UpArrow DownArrow Ctrl+v - - r e s o u r c e - g r o u p Space m y R e s o u r c e G r o u p Space Ctrl+v - - n a m e Space m y V n e t Space
 - - a d d r e s s - p r e f i x Space 1 0 . 0 . 0 . 0 / 1 6 Space Space - - s u b n e t - n a m e Space m y S u b n e t F r o n t E n d Space Space - - s u b n e t - p
 r e f i x Space 1 0 . 0 . 1 . 0 / 2 4 Enter
 h e l p Space s u b s c r i p t i o n Enter
 PageDown
```

Exception:
```
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.ConsolePal.SetWindowPosition(Int32 left, Int32 top)
   at System.Console.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.Internal.VirtualTerminal.SetWindowPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ScrollDisplayDown(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```
-----------------------------------------------------------------------
Azure:/

**Comment by daxian-dbw** [comment]
> System.PlatformNotSupportedException: Operation is not supported on this platform.

What platform did you use when running into this issue?
