### ISSUE TITLE
VS code error for Windows Powershell

### ISSUE THREAD

**Issue by thewongwaae** [PowerShell/PSReadLine#992]
Environment data
----------------

Steps to reproduce or exception report
--------------------------------------

**Comment by thewongwaae** [comment]
Last 200 Keys:
 t h o n - 2 0 1 9 . 6 . 2 4 2 2 1 \ p y t h o n F i l e s \ p t v s d _ l a u n c h e r . p y ' Space ' - - d e f a u l t ' Space ' - - n o d e b u g ' Space ' - - c l i e n t ' Space ' - - h o s t ' Space ' l o c a l h o s t ' Space ' - - p o r t ' Space ' 5 2 8 7 4 ' Space ' d : \ P e r s o n a l \ H o n g Y o u \ P r o g r a m m i n g \ H u m a n Space F a c e Space D e t e c t i o n \ h u m a n F a c e D e t e c t i o n . p y ' Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)

**Comment by thewongwaae** [comment]
This is the error it gave me when I tried to compile this code:

`
import cv2, time
import numpy as np

img = cv2,imread('')
face_csc = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

faces = face_csc.detectMultiScale(gray,1.1.4)

for(x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)

cv2.imshow('img',img)
cv2.waitKey(0)
`

**Comment by billchenchina** [comment]
Same bug happened. I opened my vscode in half-window size(Windows 10) and the bug occurred. Resizing the window helps
