### ISSUE TITLE
Unable to paste from clipboard with Shift+Insert

### ISSUE THREAD

**Issue by spajak** [PowerShell/PSReadLine#995]
When I try to paste from clipboard using defined keys I get:
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 1 Keys:
 Shift+Insert

Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Microsoft.PowerShell.PSConsoleReadLine.ExecuteOnSTAThread(Action action)
   at Microsoft.PowerShell.PSConsoleReadLine.Paste(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

I have this setting in my profile:
```
Set-PSReadLineKeyHandler -Key Shift+Insert -Function Paste
```

Shift+Ctrl+V works.
I've tried to upgrade the module a few times but it always ends with only version `1.2` in the modules directory.

```
PS version: 6.2.0
PSReadline version: 1.2
os: 10.0.17763.1 (WinBuild.160101.0800)
PS file version: 6.2.0.0
BufferWidth: 120
BufferHeight: 9999
```

**Comment by lzybkr** [comment]
The error is expected and fixed in PSReadLine 2.0. PowerShell 6.2.0 comes with PSReadLine 2.0.

I'm guessing your PSModulePath is set incorrectly.

**Comment by spajak** [comment]
Yes. But why I cannot install `2.0`? I did everything as in the README. It just installs `1.2` every time.

```
$env:PSModulePath:

D:\Home\Documents\PowerShell\Modules;C:\Program Files\PowerShell\Modules;c:\program files\powershell\6\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
```

**Comment by lzybkr** [comment]
The `README` is outdated, maybe @SteveL-MSFT or @daxian-dbw can get it updated.

I think you need to run:

```powershell
Install-Module PSReadLine -AllowPrerelease -Force
````

If `Install-Module` does not have the `-AllowPrerelease` parameter, then you need to update `PowerShellGet` first.

**Comment by spajak** [comment]
Thanks, that was this
